### ISSUE TITLE
[Crash] DragonAPI - Invalid UUID during Patreon load?

### ISSUE THREAD

**Issue by Sadumon** [ReikaKalseki/Reika_Mods_Issues#1033]
Can provide more of the log, but it looks like a UUID is invalid that it is trying to pull from your Patreon list for DragonAPI?  Happens during startup with version 15a -- was working fine earlier in the day.

Time: 7/7/16 9:53 PM
Description: Initializing game

java.lang.IllegalArgumentException: Invalid UUID string: affe50759da749c1952dc0e69d906699
    at java.util.UUID.fromString(UUID.java:194)
    at Reika.DragonAPI.Auxiliary.Trackers.PatreonController.addPatron(PatreonController.java:115)
    at Reika.DragonAPI.Auxiliary.Trackers.PatreonController.addPatrons(PatreonController.java:61)
    at Reika.DragonAPI.Auxiliary.Trackers.PatreonController.registerMod(PatreonController.java:51)
    at Reika.DragonAPI.DragonAPIInit.load(DragonAPIInit.java:499)

**Comment by hadn69** [comment]
I'm also having this error. I'll attach my crash log for those interested.
[crash-2016-07-08_01.52.17-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/353376/crash-2016-07-08_01.52.17-server.txt)

**Comment by Sadumon** [comment]
Looks like a new entry in your Patreon list is missing the dashes in the UUID:

agowa338:affe50759da749c1952dc0e69d906699:1 //Klaus Frank

http://server.techjargaming.com/Reika/Donator/patreon_Reika.txt

**Comment by Shadows-of-Fire** [comment]
Blocking that URL allows the server to start.

**Comment by ReikaKalseki** [comment]
Fixed.
