### ISSUE TITLE
[Crash] Immersive Engineering & RotaryCraft FlyWheels

### ISSUE THREAD

**Issue by Enterpriser1995** [ReikaKalseki/Reika_Mods_Issues#1034]
[11:29:42] [Client thread/INFO]: net.minecraft.client.gui.GuiIngameMenu
[11:29:43] [Netty Client IO #0/INFO]: Restoring client configs.
[11:29:43] [Netty Client IO #0/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[11:29:43] [Netty Client IO #0/INFO]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler

So, after placing an Iron FlyWheel that's what I get, and the world stops working, with the flywheel rotating and everything else not working at all.

Also, when i hit the Terminate button, I get this:

Exception in thread "Immersive Engineering Registry Iteratoration Thread" 
So I wonder what to do there.

**Comment by Enterpriser1995** [comment]
[11:51:33] [Immersive Engineering Registry Iteratoration Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[11:51:33] [Immersive Engineering Registry Iteratoration Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.ArrayList.rangeCheck(Unknown Source)
[11:51:33] [Immersive Engineering Registry Iteratoration Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.ArrayList.get(Unknown Source)
[11:51:33] [Immersive Engineering Registry Iteratoration Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
[11:51:33] [Immersive Engineering Registry Iteratoration Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler.getRecycleCalculation(ArcRecyclingThreadHandler.java:192)
[11:51:33] [Immersive Engineering Registry Iteratoration Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler$RegistryIterationThread.run(ArcRecyclingThreadHandler.java:147) got this one too.

**Comment by ReikaKalseki** [comment]
#820, #769, #734
