### ISSUE TITLE
Display screens "error reading book"

### ISSUE THREAD

**Issue by Amelia0010** [ReikaKalseki/Reika_Mods_Issues#1055]
Hello, i'm trying to use the display screens to show a message, however, when i write a book, sign it, and then right click on the display screen, it says "error reading book" in the chat. i've got a coil in the display, so i don't know what i'm doing wrong.

**Comment by nichlas0010** [comment]
Just to clarify, i am also powering the screen

**Comment by ReikaKalseki** [comment]
Does it print anything else? What is the content of the book? (Has book encoding changed since 1.6?)

**Comment by Amelia0010** [comment]
I right click with the book, and it just says (in the chat) "error reading book". I've tried with a variety of books, ranging from an entire page, to literally just "awsd"

**Comment by Amelia0010** [comment]
[Gif](http://imgur.com/a/Bohzy)

**Comment by ReikaKalseki** [comment]
What does it say in your console?

**Comment by Amelia0010** [comment]
http://pastebin.com/YQfvGCWz
thats everything from when i clicked

**Comment by ReikaKalseki** [comment]
So they did change book encoding:

2016-07-20 23:48:14 [INFO] [STDERR] java.lang.ClassCastException: net.minecraft.nbt.NBTTagString cannot be cast to net.minecraft.nbt.NBTTagList
2016-07-20 23:48:14 [INFO] [STDERR]     at Reika.RotaryCraft.Base.BlockBasicMultiTE.func_71903_a(BlockBasicMultiTE.java:436)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:371)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1390)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1868)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.client.main.Main.main(SourceFile:101)
2016-07-20 23:48:14 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-07-20 23:48:14 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-07-20 23:48:14 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-07-20 23:48:14 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:483)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2016-07-20 23:48:14 [INFO] [STDERR]     at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by Amelia0010** [comment]
So it's not just me being inept, that's nice to know. Thanks for tye help anyways :D

**Comment by Palaract** [comment]
Is there any way to fix this? Because i have the same issue and i need the screen for my Build Project

**Comment by ReikaKalseki** [comment]
It works for me. Either you have a mod changing the way books are encoded or you are using the wrong item.

![](http://i.imgur.com/zqVALjG.png)
