### ISSUE TITLE
crash when right-clicking the game of life block

### ISSUE THREAD

**Issue by shadoxxhd** [ReikaKalseki/Reika_Mods_Issues#1056]
I placed the block from the NEI inventory, right-clicked it 2 times and then crashed:

```
java.lang.NullPointerException: Ticking memory connection
    at Reika.ChromatiCraft.Block.Dimension.Structure.GOL.BlockGOLController$GOLController.reset(BlockGOLController.java:129)
    at Reika.ChromatiCraft.Block.Dimension.Structure.GOL.BlockGOLController$GOLController.access$100(BlockGOLController.java:89)
    at Reika.ChromatiCraft.Block.Dimension.Structure.GOL.BlockGOLController.activate(BlockGOLController.java:61)
    at Reika.ChromatiCraft.Block.Dimension.Structure.GOL.BlockGOLController.func_149727_a(BlockGOLController.java:54)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

full crash report: http://pastebin.com/txSzhzEH

**Comment by ReikaKalseki** [comment]
You are not supposed to spawn technical blocks.

**Comment by shadoxxhd** [comment]
could you add a tag to them to indicate that?

**Comment by Aivech** [comment]
There is a way to hide items from NEI. 
If this isn't documented anywhere, Gendustry has "hidden from NEI" as an option for its custom bees [made with JSON files], maybe a glance at bdew's code could help.

**Comment by ReikaKalseki** [comment]
Done.
