### ISSUE TITLE
Console spam on private pack..

### ISSUE THREAD

**Issue by RedCz** [ReikaKalseki/Reika_Mods_Issues#1088]
I get this often, once I start exploring different dimensions. Nothing ever crashes from this specific issue, just wondering if it's been seen, or if you have any ideas. One thing that has saolved it is using MCEdit to purge unused chunks, but it comes back once I explore again.

[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reflector.callBoolean(Reflector.java:391)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.SpawnerAnimals.func_77190_a(SpawnerAnimals.java:318)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:178)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at WorldServerOF.func_72835_b(WorldServerOF.java:234)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at fastcraft.at.a(F:978)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at fastcraft.H.aq(F:36)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.ChromatiCraft.Block.BlockCrystalPylon.isSideSolid(BlockCrystalPylon.java:168)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.block.Block.canCreatureSpawn(Block.java:1533)
[17:28:40] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     ... 15 more

**Comment by ReikaKalseki** [comment]
I do not think this is my doing.

**Comment by RedCz** [comment]
I didn't think so either, with fastcraft being mentioned, and my own pack thrown together. I just wanted to make sure.

I'll hunt it down if it becomes too much of a problem for me.

**Comment by RedCz** [comment]
For reference, or curiosity's sake, here's a giant log:
https://www.dropbox.com/s/heac20gq46ol3qh/fml-client-latest.log?dl=0

Again, I'm sure it's a mix of stuff I've done, but the data is here in case something comes out of it.
