### ISSUE TITLE
console spam when entering a world

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#1105]
I added the mods DragonAPI RotaryCraft ReactorCraft ElectriCraft ChromatiCraft (newest versions) and Galacticcraft (+planets,+core) to the FTB Infinity modpack (1.5.0) and disabled the mods AOBD BiomesOPlenty BiblioWoods(BoP addon) and ChickenChunks. I also changed the potion id`s from Witchery.
The game starts and everything is fine but when you enter a world you get this error spammed in the console.
 i tried my best to fix this but im not very skilled in java so i couldnt manage to fix it.
 i dont know if this is an error of Galacticcraft or any of Reikas mods so im posting it on both sites.

This is whats spammed into my console (on both server and client)

java.lang.NullPointerException
[20:19:42] [Client thread/ERROR] [FML]: Index: 33 Listeners:
[20:19:42] [Client thread/ERROR] [FML]: 0: HIGHEST
[20:19:42] [Client thread/ERROR] [FML]: 1: ASM: Reika.ChromatiCraft.ChromaClientEventController@68754f27 reachBoostHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 2: ASM: powercrystals.minefactoryreloaded.block.transport.BlockRedNetCable@2521bc84 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 3: HIGH
[20:19:42] [Client thread/ERROR] [FML]: 4: ASM: cofh.thermaldynamics.item.ItemServo@4b376541 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 5: ASM: cofh.thermaldynamics.item.ItemFilter@32e89d49 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 6: ASM: cofh.thermaldynamics.item.ItemCover@7f2645e8 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 7: ASM: cofh.thermaldynamics.item.ItemRetriever@746cc1f8 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 8: ASM: cofh.thermaldynamics.item.ItemRelay@7ddc796 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 9: NORMAL
[20:19:42] [Client thread/ERROR] [FML]: 10: ASM: thaumcraft.client.lib.RenderEventHandler@6814dfba blockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 11: ASM: thaumcraft.common.blocks.BlockTube@220d4409 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 12: ASM: jds.bibliocraft.HighlightHandler@12b6a7be DrawBlockHighlightEvent(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 13: ASM: jds.bibliocraft.EventBlockMarkerHighlight@619058d4 DrawBlockHighlightEvent(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 14: ASM: buildcraft.core.render.BlockHighlightHandler@4fe3dd7b handleBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 15: ASM: Reika.ChromatiCraft.ChromaClientEventController@68754f27 drawExcavatorHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 16: ASM: Reika.ChromatiCraft.ChromaClientEventController@68754f27 drawPlacerHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 17: ASM: Reika.ChromatiCraft.ChromaClientEventController@68754f27 drawBuilderFrame(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 18: ASM: io.endertech.client.handler.DrawBlockHighlightEventHandler@2a19528 onDrawBlockHighlightEvent(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 19: ASM: openmods.block.BlockSelectionHandler@6d7c0806 onHighlightDraw(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 20: ASM: codechicken.microblock.handler.MicroblockEventHandler$@4b53cb9e drawBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 21: ASM: com.rwtema.extrautils.EventHandlerClient@78d95a5c SonarRender(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 22: ASM: com.rwtema.extrautils.EventHandlerClient@78d95a5c BuildersWandRender(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 23: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@64892a4d renderAdditionalBlockBounds(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 24: ASM: INSTANCE onDrawBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 25: ASM: codechicken.enderstorage.common.BlockEnderStorage@3bb6c956 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 26: ASM: cofh.thermaldynamics.duct.BlockDuct@211599d8 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 27: ASM: cofh.thermaldynamics.duct.BlockDuct@45509304 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 28: ASM: cofh.thermaldynamics.duct.BlockDuct@35b5c141 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 29: ASM: cofh.thermaldynamics.duct.BlockDuct@727476ed onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 30: ASM: codechicken.translocator.BlockTranslocator@7a093437 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 31: ASM: codechicken.translocator.BlockCraftingGrid@3679f6fb onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 32: ASM: codechicken.multipart.handler.MultipartEventHandler$@a346e84 drawBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 33: ASM: com.emoniph.witchery.brewing.potions.WitcheryPotions$ClientEventHooks@62d78e1d onDrawBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 34: LOWEST
[20:19:42] [Client thread/ERROR] [FML]: 35: ASM: Reika.ChromatiCraft.ChromaClientEventController@68754f27 stopPylonBoxHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reflector.callBoolean(Reflector.java:222)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1632)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1330)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:19:42] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[20:19:42] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@45b78f61:

and if i place anything from the deco Tab from Chromaticraft the game crashes with this error 

java.lang.NullPointerException
    at net.minecraft.entity.EntityLivingBase.func_70660_b(EntityLivingBase.java:627) ~[sv.class:?]
    at com.emoniph.witchery.common.GenericEvents.onPlayerInteract(GenericEvents.java:922) ~[GenericEvents.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1606_GenericEvents_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1446) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:19:42] [Client thread/ERROR] [FML]: Index: 47 Listeners:
[20:19:42] [Client thread/ERROR] [FML]: 0: HIGHEST
[20:19:42] [Client thread/ERROR] [FML]: 1: ASM: Reika.RotaryCraft.RotaryEventManager@1d50fcca buildWorktables(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 2: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@1d5186fc vanillaSeedPlanting(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 3: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@1d5186fc waterPadCreation(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 4: NORMAL
[20:19:42] [Client thread/ERROR] [FML]: 5: ASM: binnie.botany.Botany@5739b75e onShearFlower(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 6: ASM: binnie.botany.Botany@5739b75e onFertiliseSoil(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 7: ASM: vazkii.botania.common.block.string.BlockRedStringInterceptor@42c93365 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 8: ASM: vazkii.botania.common.item.material.ItemManaResource@48ae3179 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 9: ASM: vazkii.botania.common.item.relic.ItemLokiRing@42c145c6 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 10: ASM: vazkii.botania.common.item.rod.ItemExchangeRod@5a247eea onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 11: ASM: binnie.core.item.ModuleItems@3271da9e onUseFieldKit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 12: ASM: binnie.extratrees.carpentry.BlockCarpentry@d896bc5 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 13: ASM: mods.railcraft.common.carts.MinecartHooks@5c094cc5 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 14: ASM: team.chisel.item.chisel.ChiselController@705489a4 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 15: ASM: FLM_ItemWrench@3a4cae49 leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 16: ASM: com.xcompwiz.mystcraft.core.MystcraftEventHandler@dfc9f98 bottleFix(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 17: ASM: Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher@12b744de sendInteractToClient(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 18: ASM: Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher@12b744de addGuideGUI(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 19: ASM: Reika.ChromatiCraft.ChromaticEventManager@460b37ae onUseSacrificeOrb(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 20: ASM: com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler@450ed3e3 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 21: ASM: minetweaker.mc1710.ForgeEventHandler@289bc581 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 22: ASM: ftb.lib.mod.FTBLibEventHandler@2cfe92c0 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 23: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@651fbdd4 onPlayerClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 24: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@1d5186fc applyVinesToGrate(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 25: ASM: com.InfinityRaider.AgriCraft.handler.PlayerInteractEventHandler@1d5186fc denyBonemeal(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 26: ASM: appeng.parts.PartPlacement@4ced222d playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 27: ASM: vazkii.botania.common.core.handler.SpawnerChangingHandler@3ccbf26a onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 28: ASM: vazkii.botania.client.core.handler.MultiblockRenderHandler@322de2ce onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 29: ASM: com.carpentersblocks.util.handler.EventHandler@702cac63 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 30: ASM: twilightforest.TFEventListener@2b76338c rightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 31: ASM: com.rwtema.extrautils.EventHandlerServer@41c056ba angelBlockDestroy(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 32: ASM: thaumic.tinkerer.common.core.handler.kami.KamiDimensionHandler@417715e0 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 33: ASM: Reika.ChromatiCraft.Auxiliary.AbilityHelper@1fbbd74d analyzeBees(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 34: ASM: Reika.ChromatiCraft.Auxiliary.AbilityHelper@1fbbd74d saveUsedStack(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 35: ASM: Reika.ChromatiCraft.Auxiliary.AbilityHelper@1fbbd74d analyzeGenes(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 36: ASM: Reika.ChromatiCraft.Auxiliary.AbilityHelper@1fbbd74d clickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 37: ASM: com.enderio.core.common.handlers.RightClickCropHandler@6495178b handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 38: ASM: logisticspipes.LogisticsEventListener@27aa8db0 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 39: ASM: mcjty.rftools.ForgeEventHandlers@2d664559 onPlayerInterractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 40: ASM: mcjty.rftools.ForgeEventHandlers@2d664559 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 41: ASM: stevesaddons.naming.EventHandler@5e5e6331 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 42: ASM: com.jaquadro.minecraft.storagedrawers.core.ForgeEventHandler@6b469f36 playerInteracts(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 43: ASM: flaxbeard.thaumicexploration.event.TXEventHandler@306a9361 handleItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 44: ASM: appeng.fmp.FMPEvent@4fbca510 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 45: ASM: com.emoniph.witchery.item.ItemPoppet$PoppetEventHooks@62c6577c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 46: ASM: com.emoniph.witchery.infusion.Infusion$EventHooks@39fb89f7 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 47: ASM: com.emoniph.witchery.common.GenericEvents@cc5e8ce onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 48: ASM: com.emoniph.witchery.brewing.DispersalTriggered$EventHooks@7fbed8f4 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 49: LOW
[20:19:42] [Client thread/ERROR] [FML]: 50: ASM: codechicken.multipart.minecraft.EventHandler@6940cbd3 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[20:19:42] [Client thread/ERROR] [FML]: 51: LOWEST
[20:19:42] [Client thread/ERROR] [FML]: 52: ASM: [] guardArea(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V

and im sorry for my bad english.

**Comment by LukaPix** [comment]
i managed to fix both errors by removing witchery.

**Comment by ReikaKalseki** [comment]
WTF...?
