### ISSUE TITLE
Rotary/Reactor requires Chromatic

### ISSUE THREAD

**Issue by ZorbaHerbalist** [ReikaKalseki/Reika_Mods_Issues#1130]
Is that right?

```
UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCH FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
UCH Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
UCH DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16a.jar) 
UCE RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V16a.jar) 
UCE ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V16a.jar) 
UCE ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V16a.jar) 
```

[01:31:22] [Client thread/ERROR]: The following problems were captured during this phase
[01:31:22] [Client thread/ERROR]: Caught exception from RotaryCraft
java.lang.NoClassDefFoundError: Reika/ChromatiCraft/ChromatiCraft
    at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_101]
    at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_101]
    at java.lang.Class.privateGetPublicFields(Unknown Source) ~[?:1.8.0_101]
    at java.lang.Class.getFields(Unknown Source) ~[?:1.8.0_101]

**Comment by ReikaKalseki** [comment]
Redownload it.
