### ISSUE TITLE
This issue involves a small modpack. This has relationships to a missing dependent mod, i'm not sure what one

### ISSUE THREAD

**Issue by Stryder914** [ReikaKalseki/Reika_Mods_Issues#1159]
[13:50:14] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:50:14] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:50:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[13:50:14] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[13:50:14] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass1(Native Method)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.AccessController.doPrivileged(Native Method)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName0(Native Method)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName(Class.java:344)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 23 more
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 25 more
[13:50:14] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\User\AppData\Roaming.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_25]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
    at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 23 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 23 more
Exception in thread "main" [13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass1(Native Method)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.AccessController.doPrivileged(Native Method)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName0(Native Method)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName(Class.java:344)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 23 more
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[13:50:14] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 25 more

**Comment by HellFirePvP** [comment]
1) **DO NOT** copy paste stacktraces into the your message! Use pastebin or related for that!

2) This seems like a forge installation error at first sight. Not sure though. I can't see any connection to reika's mods?

[FML]: An error occurred trying to configure the minecraft home at C:\Users\User\AppData\Roaming.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
