### ISSUE TITLE
Crash with tinker's construct interaction (on Wanderlust Reloaded)

### ISSUE THREAD

**Issue by maximumsomething** [ReikaKalseki/Reika_Mods_Issues#1172]
This pack is Wanderlust Reloaded with a few mods added and removed. I'm trying to add RoC and ReC. After resolving crashes with potion ids and updating Forestry, I got this crash. See http://pastebin.com/gPNy7Axh 

The error:

```
Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
You cannot get the cast for a null or non-recipe!
at Reika.DragonAPI.ModInteract.RecipeHandlers.SmelteryRecipeHandler.getRecipeCast(SmelteryRecipeHandler.java:206)
at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesCrystallizer.addPostLoadRecipes(RecipesCrystallizer.java:165)
at Reika.RotaryCraft.RotaryRecipes.addPostLoadRecipes(RotaryRecipes.java:170)
at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:616)
```

**Comment by ReikaKalseki** [comment]
Someone added a recipe to the TiC casting table casting a fluid to null. This is not present in my pack which means it is either a TiC addon or a MT script or similar. Either way, it is a fairly clear thing NOT to do.

**Comment by maximumsomething** [comment]
Is there a way to fix this? Disabling TiC integration would be fine.

**Comment by ReikaKalseki** [comment]
You need to find the at-fault mod.
