### ISSUE TITLE
Casting table not breakable and throws error on crafting

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1180]
Hi,
when i place a casting table, i cannot break it outside of creative mode or using a ars magica dig spell. Even explosives or a mining laser wont work. The funny thing is, if i start a new singleplayer world, it seems to work, at least the breaking of an cheated-in table. I have had this issue on my old server (with another save) as well.

Also, when i try to craft something, i get the following error :

[fml-client-latest.zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/557592/fml-client-latest.zip)

`[06:42:35] [Client thread/INFO] [inventorytweaks/]: Reika.ChromatiCraft.GUI.Tile.Inventory.GuiCastingTable
[06:42:35] [Client thread/INFO] [inventorytweaks/]: Reika.ChromatiCraft.Container.ContainerCastingTable
[06:42:46] [Client thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Casting Table @ DIM0: -335, 77, 794 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.DragonAPI.Libraries.ReikaPlayerAPI.getDeathPersistentNBT(ReikaPlayerAPI.java:293)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.Registry.ChromaResearchManager.getNBT(ChromaResearchManager.java:367)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.Registry.ChromaResearchManager.getNBTRecipes(ChromaResearchManager.java:416)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.Registry.ChromaResearchManager.getPlayerRecipes(ChromaResearchManager.java:406)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.Registry.ChromaResearchManager.playerHasUsedRecipe(ChromaResearchManager.java:391)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.Registry.ChromaResearchManager.givePlayerRecipe(ChromaResearchManager.java:395)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.onCrafted(CastingRecipe.java:203)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:266)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:151)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.world.World.func_72939_s(World.java:1939)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.main.Main.main(SourceFile:148)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:498)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[06:42:46] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[06:42:46] [Client thread/INFO] [FML/]: DRAGONAPI: 
[06:42:47] [Client thread/INFO] [inventorytweaks/]: net.minecraft.client.gui.GuiChat
[06:43:04] [Client thread/INFO] [inventorytweaks/]: net.minecraft.client.gui.inventory.GuiInventory
[06:43:04] [Client thread/INFO] [inventorytweaks/]: net.minecraft.inventory.ContainerPlayer`

If more information is needed, please ask for it and i will try do provide it. I can also do some specific testing if needed.

**Comment by ReikaKalseki** [comment]
It has a null placer. Delete it.

**Comment by Savallator** [comment]
It happens with every new table i try to plant, no difference if i build them normally or cheat them in via creative mode.

**Comment by Savallator** [comment]
I already figured that the placer is not set correctly
However, it does so every time in that world, for every table I placed. I can not find any errors related to the placing, but I guess it might be a Cross-mod interaction.
If the table is placed, will it check for a null player?
If so, then the problem might actually be saving the player and not retrieving it.
If that is not the case, I have no idea which other mod would cause a null player to be returned.
I do have some extensive, content changing mods installed like gregtech, thaumcraft and ars magica, maybe one of them is at fault here.

**Comment by ReikaKalseki** [comment]
This happens _consistently_?

**Comment by Savallator** [comment]
Yes, with every new table I place

**Comment by ReikaKalseki** [comment]
Are you playing in offline mode?

**Comment by Savallator** [comment]
I and every player on the server is using a legal account,
But I am not sure if the server is accidently set to offline mode. I will check as soon as I get home in about an hour

**Comment by Savallator** [comment]
Ok. So the server is in offline mode for some reason, although i dont know why. I cannot switch it without greater problems, as it seems like all players would loose their inventory.
Also, since this day, i get a chromaticraft related crash whenever i click an item in NEI:
[crash-2016-10-31_04.22.36-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/561055/crash-2016-10-31_04.22.36-client.txt)

`java.lang.ExceptionInInitializerError
    at Reika.ChromatiCraft.ModInterface.NEI.FabricatorHandler.loadCraftingRecipes(FabricatorHandler.java:122)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
    at Reika.ChromatiCraft.ModInterface.NEI.FabricatorHandler.loadCraftingRecipes(FabricatorHandler.java:109)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258)
    at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166)
    at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365)
    at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
You cannot key a null itemstack!
    at Reika.DragonAPI.Instantiable.Data.KeyedItemStack.<init>(KeyedItemStack.java:41)
    at Reika.ChromatiCraft.Auxiliary.RecipeManagers.FabricationRecipes.addRecipe(FabricationRecipes.java:194)
    at Reika.ChromatiCraft.Auxiliary.RecipeManagers.FabricationRecipes.<init>(FabricationRecipes.java:161)
    at Reika.ChromatiCraft.Auxiliary.RecipeManagers.FabricationRecipes.<clinit>(FabricationRecipes.java:38)
    ... 23 more`

**Comment by ReikaKalseki** [comment]
> So the server is in offline mode for some reason

There is your problem. Fix it.

**Comment by Savallator** [comment]
Okay, switching to online mode fixed it. Maybe, for a future release, add a warning somewhere about this?
The other problem however persists, i will make a new Issue for that

**Comment by ReikaKalseki** [comment]
> Okay, switching to online mode fixed it. Maybe, for a future release, add a warning somewhere about this?

If I do anything it will be making CC not work at all in offline mode, or at least an update-checker-style "this will not work".

**Comment by Savallator** [comment]
That's exactly what i meant.

**Comment by Aivech** [comment]
> If I do anything it will be making CC not work at all in offline mode, or at least an update-checker-style "this will not work".

It already doesn't work at all in offline mode. It just needs to be more obvious 😁
