### ISSUE TITLE
Ritual Table crashing: "java.lang.NullPointerException on update: null"

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1215]
The Ritual Table is not working, it does not grant the Ritual nor does it grant the "Personal Enhancement" Progress. It spins me ariund and so on, but the completion does not work. World and Player are in Online Mode.

`[23:50:13] [Client thread/INFO]: [CHAT] Tile Entity Ritual Table @ DIM0: -343, 92, 794 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[23:50:13] [Client thread/INFO]: [CHAT] [Reika.ChromatiCraft.Registry.Chromabilities.setToPlayer(Chromabilities.java:531), Reika.ChromatiCraft.Registry.Chromabilities.give(Chromabilities.java:501), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.giveAbility(TileEntityRitualTable.java:249), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.onRitualTick(TileEntityRitualTable.java:175), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.updateEntity(TileEntityRitualTable.java:90), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[23:50:13] [Client thread/INFO]: [CHAT] 
[23:50:13] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Ritual Table @ DIM0: -343, 92, 794 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Registry.Chromabilities.setToPlayer(Chromabilities.java:531)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Registry.Chromabilities.give(Chromabilities.java:501)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.giveAbility(TileEntityRitualTable.java:249)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.onRitualTick(TileEntityRitualTable.java:175)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.updateEntity(TileEntityRitualTable.java:90)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:50:13] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:50:13] [Client thread/INFO] [FML]: DRAGONAPI: `

I am not quite sure how that can happen. From the github, that is the relevant code:

`	private static void setToPlayer(EntityPlayer ep, boolean set, Ability a, boolean force) {
		NBTTagCompound nbt = ep.getEntityData();
		NBTTagCompound abilities = nbt.getCompoundTag(NBT_TAG);
		if (abilities == null) {
			**abilities = new NBTTagCompound();**
		}
		if (force || set || abilities.hasKey(a.getID()))
			abilities.setBoolean(a.getID(), set);
		nbt.setTag(NBT_TAG, abilities);
		if (ep instanceof EntityPlayerMP)
			ReikaPlayerAPI.syncCustomData((EntityPlayerMP)ep);
	}`

it seems that a Null ability might be passed down. Is it possible that
`Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.giveAbility(TileEntityRitualTable.java:249)`
is somehow called twice, so it is null for the second call?

**Comment by Savallator** [comment]
Ok, on a second try, it does grant the Ability, but it still crashes

**Comment by ReikaKalseki** [comment]
Break and replace it.
