### ISSUE TITLE
Server keeps crashing 

### ISSUE THREAD

**Issue by notchriss** [ReikaKalseki/Reika_Mods_Issues#1281]
java.lang.NullPointerException: Exception in server tick loop

at TEnergyReceiver$$PassThrough$class.canConnectEnergy(Unknown Source)
at TileMultipart_cmp$$1.canConnectEnergy(Unknown Source)
at Reika.ElectriCraft.Network.RF.RFNetwork$EnergyInteraction.getTotalInsertible(RFNetwork.java:280)

http://pastebin.com/VFSdtMqd

**Comment by ReikaKalseki** [comment]
This is on multipart's end.
