### ISSUE TITLE
Column Decrementer NPE on world load

### ISSUE THREAD

**Issue by elifoster** [ReikaKalseki/Reika_Mods_Issues#1298]
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/12/17 12:41 PM
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at Reika.ExpandedRedstone.TileEntities.TileEntityColumnDecrementer.getEmission(TileEntityColumnDecrementer.java:45)
	at Reika.ExpandedRedstone.TileEntities.TileEntityColumnDecrementer.getEmission(TileEntityColumnDecrementer.java:45)
	at Reika.ExpandedRedstone.Base.BlockRedstoneBase.func_149709_b(BlockRedstoneBase.java:145)
	at net.minecraft.world.World.func_72878_l(World.java:3424)
	at net.minecraft.world.World.func_94572_D(World.java:3438)
	at net.minecraft.block.BlockRedstoneWire.func_150175_a(BlockRedstoneWire.java:91)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:74)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147441_b(World.java:680)
	at Reika.ExpandedRedstone.Base.BlockRedstoneBase.func_149695_a(BlockRedstoneBase.java:157)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:650)
	at Reika.DragonAPI.Libraries.World.ReikaWorldHelper.causeAdjacentUpdates(ReikaWorldHelper.java:1380)
	at Reika.ExpandedRedstone.Base.TileRedstoneBase.update(TileRedstoneBase.java:253)
	at Reika.ExpandedRedstone.Base.TileRedstoneBase.onFirstTick(TileRedstoneBase.java:45)
	at Reika.DragonAPI.Base.TileEntityBase.updateTileEntity(TileEntityBase.java:612)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:489)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.ExpandedRedstone.TileEntities.TileEntityColumnDecrementer.getEmission(TileEntityColumnDecrementer.java:45)
	at Reika.ExpandedRedstone.TileEntities.TileEntityColumnDecrementer.getEmission(TileEntityColumnDecrementer.java:45)
	at Reika.ExpandedRedstone.Base.BlockRedstoneBase.func_149709_b(BlockRedstoneBase.java:145)
	at net.minecraft.world.World.func_72878_l(World.java:3424)
	at net.minecraft.world.World.func_94572_D(World.java:3438)
	at net.minecraft.block.BlockRedstoneWire.func_150175_a(BlockRedstoneWire.java:91)
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:74)
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:318)
	at net.minecraft.world.World.func_147460_e(World.java:697)

-- Block being updated --
Details:
	Source block type: ID #816 (tile.Fullblock // Reika.ExpandedRedstone.ItemBlocks.BlockRedstoneMachine)
	Block type: ID #55 (tile.redstoneDust // net.minecraft.block.BlockRedstoneWire)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (-179,6,1752), Chunk: (at 13,0,8 in -12,109; contains blocks -192,0,1744 to -177,255,1759), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
Stacktrace:
	at net.minecraft.world.World.func_147441_b(World.java:680)
	at Reika.ExpandedRedstone.Base.BlockRedstoneBase.func_149695_a(BlockRedstoneBase.java:157)
	at net.minecraft.world.World.func_147460_e(World.java:697)

-- Block being updated --
Details:
	Source block type: ID #816 (tile.Fullblock // Reika.ExpandedRedstone.ItemBlocks.BlockRedstoneMachine)
	Block type: ID #816 (tile.Fullblock // Reika.ExpandedRedstone.ItemBlocks.BlockRedstoneMachine)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (-179,5,1753), Chunk: (at 13,0,9 in -12,109; contains blocks -192,0,1744 to -177,255,1759), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
Stacktrace:
	at net.minecraft.world.World.func_147459_d(World.java:650)
	at Reika.DragonAPI.Libraries.World.ReikaWorldHelper.causeAdjacentUpdates(ReikaWorldHelper.java:1380)
	at Reika.ExpandedRedstone.Base.TileRedstoneBase.update(TileRedstoneBase.java:253)
	at Reika.ExpandedRedstone.Base.TileRedstoneBase.onFirstTick(TileRedstoneBase.java:45)
	at Reika.DragonAPI.Base.TileEntityBase.updateTileEntity(TileEntityBase.java:612)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:489)
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
	Name: ExpRedstoneColumn Decrementer // Reika.ExpandedRedstone.TileEntities.TileEntityColumnDecrementer
	Block type: ID #816 (tile.Fullblock // Reika.ExpandedRedstone.ItemBlocks.BlockRedstoneMachine)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-179,6,1753), Chunk: (at 13,0,9 in -12,109; contains blocks -192,0,1744 to -177,255,1759), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
	Actual block type: ID #816 (tile.Fullblock // Reika.ExpandedRedstone.ItemBlocks.BlockRedstoneMachine)
	Actual block data value: 8 / 0x8 / 0b1000
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: witchery
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2944291165375603701
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-204,4,1730), Chunk: (at 4,0,2 in -13,108; contains blocks -208,0,1728 to -193,255,1743), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
	Level time: 626595 game time, 82630 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 44620 (now: false), thunder time: 13594 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.12.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 574744144 bytes (548 MB) / 1002962944 bytes (956 MB) up to 1002962944 bytes (956 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.27} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.27.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHIJAAAA	StartingInventory{1.7.10.r01} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r01.jar) 
	UCHIJAAAA	StatusEffectHUD{1.26} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.26.jar) 
	UCHIJAAAA	DC1{3.4.2.19} [KingCore] ([1.7.2+] KingCore v3.4.2.19.jar) 
	UCHIJAAAA	Glow{1.1.0.3} [Glow] ([1.7.10M] Glow v1.1.0.3.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-328.jar) 
	UCHIJAAAA	IC2{2.2.811-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.811-experimental.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-399.jar) 
	UCHIJAAAA	CustomOreGen{1.2.21} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.21.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.4-114.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	ExpandedRedstone{1.0} [Expanded Redstone] (ExpandedRedstone 1.7.10 V16b.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	Steamcraft{0.29.2} [Flaxbeard's Steam Power] (FSP-1.7.10-0.29.2.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	NEIDumpBooster{1.0} [NEIDumpBooster] (NEI Dump Booster.jar) 
	UCHIJAAAA	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	oredictdumper{1.1.1} [OreDictDumper] (OreDictDumper-1.7.10-1.1.1.jar) 
	UCHIJAAAA	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	witcherypatch{1.0.0} [WitcheryPatch] (WitcheryPatch-1.7.10-1.0.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.3-328
	ThermalFoundation: -[1.7.10]1.2.4-114
	ThermalExpansion: -[1.7.10]4.1.2-240
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

[Relevant line](https://github.com/ReikaKalseki/ExpandedRedstone/blob/22d3321d8b39655934995206739dc510c7910012/TileEntities/TileEntityColumnDecrementer.java#L45)

**Comment by ReikaKalseki** [comment]
Fixed.
