### ISSUE TITLE
Chromaticraft V16d ConcurrentModificationException and pylons not working until visited

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1299]
Chromaticraft/DragonAPI/ReikaOtherMods Version 16d.

Spent some time figuring out a way to reliably reproduce this, got it hitting every time with only Reika's mods, thaumcraft, some thaumcraft addons, NEI, and railcraft installed.

I can reproduce this by connecting to pylons that are outside of the player loaded range, loading up the single player game, trying to craft something.  It does not reproduce if I visit each of my connected pylons first, but until they are visited this will happen about 50% of the time when crafting a recipe that uses lumen energy.  Interestingly the times that it does not crash then the colors that I did not visit will not work until they are visited (to within the player loaded distance) then continue to work without issue until the game is restarted.  Attempted a variety of things to fix it around testing chunkloaders at the pylons, at the pylons and mostly along the repeater paths to no avail, it seems that I have to either visit the pylons or at least visit the path of repeaters along the whole distance.  I've yet been unable to verify that every repeater has gotten chunkloaded so that may be the issue, but everything I've read about this implies that no chunkloading of anything should be necessary, and indeed thus far chunkloading has not resolved the issue.

From looking over the file https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Magic/Network/CrystalNetworker.java it appears that the class field of tiles is mutated while iteration is happening.  At the crash happened on https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Magic/Network/CrystalNetworker.java#L608 then the only lines that could cause that are either https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Magic/Network/CrystalNetworker.java#L612 (`te.canConduct()`) or https://github.com/ReikaKalseki/ChromatiCraft/blob/master/Magic/Network/CrystalNetworker.java#L613 (`te.isConductingElement(e)`) and both of those call in to the `CrystalSource` interface, which ends up branching into a variety of other classes, and this is assuming that this whole thing is not multi-threaded (which if it is then it is sorely missing some synchronization primitives).  The `TileEntityCache` from DragonAPI also does nothing to ensure that concurrent access cannot happen (changing a collection while it is being iterated), for example its keyset returns a immutable view to the main data source but does not copy it nor set any flag to ensure that changes cannot be made while the iteration is in progress.  I stopped researching here however, it is not my code.  ^.^

Stacktrace:
```java
Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/14/17 8:23 PM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.getAllSourcesFor(CrystalNetworker.java:608)
	at Reika.ChromatiCraft.Magic.Network.PylonFinder.anyConnectedSources(PylonFinder.java:151)
	at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:136)
	at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:125)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:261)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:248)
	at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:83)
	at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:94)
	at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergyDifference(CrystalReceiverBase.java:101)
	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:258)
	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:151)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.getAllSourcesFor(CrystalNetworker.java:608)
	at Reika.ChromatiCraft.Magic.Network.PylonFinder.anyConnectedSources(PylonFinder.java:151)
	at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:136)
	at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:125)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:261)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:248)
	at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:83)
	at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:94)
	at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergyDifference(CrystalReceiverBase.java:101)
	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:258)
	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:151)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
	Name: CCchroma.table // Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable
	Block type: ID #2005 (tile.ChromaticTile // Reika.ChromatiCraft.Base.BlockChromaTile)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (21,70,316), Chunk: (at 5,4,12 in 1,19; contains blocks 16,0,304 to 31,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #2005 (tile.ChromaticTile // Reika.ChromatiCraft.Base.BlockChromaTile)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
```

**Comment by ReikaKalseki** [comment]
#1100, #1290
