### ISSUE TITLE
Chromaticraft:  Lost player progression data + Sound Thread issues and workaround(?)

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1302]
While playing on the main server had this crash while popping a chest in the chroma-dimension:
```java
---- Minecraft Crash Report ----
// Oops.

Time: 1/16/17 3:43 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 7
        at extrabiomes.items.ItemNewSapling.func_77667_c(ItemNewSapling.java:33)
        at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
        at net.minecraft.entity.item.EntityItem.func_70005_c_(EntityItem.java:405)
        at mcp.mobius.mobiuscore.monitors.MonitoredEntityList.getName(MonitoredEntityList.java:50)
        at mcp.mobius.mobiuscore.monitors.MonitoredEntityList.addCount(MonitoredEntityList.java:16)
        at mcp.mobius.mobiuscore.monitors.MonitoredList.add(MonitoredList.java:16)
        at net.minecraft.world.World.func_72838_d(World.java:1337)
        at Reika.DragonAPI.Libraries.Registry.ReikaItemHelper.dropInventory(ReikaItemHelper.java:322)
        at Reika.ChromatiCraft.Block.Worldgen.BlockLootChest.func_149749_a(BlockLootChest.java:108)
        at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
        at net.minecraft.world.World.func_147465_d(World.java:451)
        at Reika.DragonAPI.Auxiliary.ProgressiveRecursiveBreaker$ProgressiveBreaker.dropBlock(ProgressiveRecursiveBreaker.java:302)
        at Reika.DragonAPI.Auxiliary.ProgressiveRecursiveBreaker$ProgressiveBreaker.tick(ProgressiveRecursiveBreaker.java:194)
        at Reika.DragonAPI.Auxiliary.ProgressiveRecursiveBreaker$ProgressiveBreaker.access$400(ProgressiveRecursiveBreaker.java:65)
        at Reika.DragonAPI.Auxiliary.ProgressiveRecursiveBreaker.tick(ProgressiveRecursiveBreaker.java:410)
        at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.worldTick(TickRegistry.java:78)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_574_TickRegistry_worldTick_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```
This is obviously an extrabiomes crash and has been fixed in their >1.7 MC version, however the issue here is that when the server reloaded then all player progression data was entirely wiped.  Abilities gone, progression gone, still had the book with all the fragments in it however none were accessible with an invalid mark on all but the beginning 2-3 of them.  On the server reload I noticed this:
```java
[15:58:17] [Server thread/INFO] [FML/]: CHROMATICRAFT: Restoring progression for OvermindDL1 from cache, as it had more progression than they did!
[15:58:17] [Server thread/WARN] [FML/]: ****************************************
[15:58:17] [Server thread/WARN] [FML/]: * ChromatiCraft: Player OvermindDL1 just lost some of their progression!
[15:58:17] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionCacher.updateProgressCache(ProgressionCacher.java:119)
[15:58:17] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.setPlayerStage(ProgressionManager.java:629)
[15:58:17] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.setPlayerStage(ProgressionManager.java:559)
[15:58:17] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.stepPlayerTo(ProgressionManager.java:488)
[15:58:17] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.access$000(ProgressionManager.java:72)
[15:58:17] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager$ProgressStage.stepPlayerTo(ProgressionManager.java:165)...
[15:58:17] [Server thread/WARN] [FML/]: ****************************************
```
However this was not just 'some' progression lost, but 'all' progression lost, this was a substantial set back considering everything was unlocked but the monument (I was busy collecting the dimension cores when this happened).  I've still not able to get it all back as thus far there is only one ender dragon and only ever found one desert burrow in over 10kx10k explored, and as cheating is entirely blocked on this server...

**Comment by AshIndigo** [comment]
This has been happening on the server I play on too, the only solution I have is using /chromaprog to restore it myself whenever it happens. Also #1113

**Comment by OvermindDL1** [comment]
Unsure if this is related to #1113, this was in the chroma dimension and happened due to a server crash instead of exiting the dimension.  Also as a note I did get the books for reika's mods again (chromaticraft, roterycraft, etc... etc...), but no other mods (I started this server with *9* books, only got Reika's back, so it seems specific to this set or perhaps DragonAPI?).

**Comment by OvermindDL1** [comment]
And I had none of iChun's mods. And I'm pretty sure the NBT was well below 32k as I'm not storing anything that should have a lot of NBT data (I have a few bags, but they are full of mostly generic stuff that have no attached NBT data), and the only book on me was Chromaticrafts (also, wtf is chromaticrafts book storing string data on its NBT instead of encoding tightly?).

Also I found the reason the music lags on load, along with a fix, but it is a hack and I'm unsure it should be used, but it is working for me (I should probably stop editing bytecode of the class files in the jar's and instead actually make PR's, bleh, I really hate java, even its bytecode is more fun to use...).

**Comment by AshIndigo** [comment]
(I want that fix now, the lag is annoying) My current theory is that the data is interrupted when saving, I.E Timing out, crashing, server sky striked. But its a weak one and that doesnt explain why the progression cache wouldnt restore it.

**Comment by OvermindDL1** [comment]
> I want that fix now, the lag is annoying

For note, I do not know about the streaming thread crashing that was reported elsewhere, I never experienced that.  The reason it was slow on my computer (and likely others) is that minecraft decodes ogg's very slowly, and it was having to decode the entire ogg files (not streaming it, why it was not streaming by design when above a certain size, no clue...) on every-single-load, and considering those music files are so *huge* compared to minecraft's that can also cause the issue for me, though only measures in a second or 5 compared to Chromaticraft's 10+ seconds.  My hack is just to force paulscode to keep it in memory via a little cache in a global variable (first load slow, then fine).  Re-encoding the ogg's to wav's might also fix it if you want something less hacky (update the filecache file too).  The way playing such huge files 'should' be done is probably via javax's AudioSystem as it can actually stream from disk instead of loading the entire decoded file into memory (I think you can also send the individual frames of audio via Paulscode too if wanted, but that'd be a lot more code), but DragonAPI is built to work with MC's SoundSystem (Paulscode) instead of anything else, but it really should add a new streaming handler built using javax's AudioSystem (is that available on OpenJDK?  Unsure...).

As for the progression, probably Reika's mods store data elsewhere than on the player and 'that' file got killed somehow.  It is probably writing to the file directly I'd wager, instead of to a new temp file then atomically rename it on to the existing one, that would ensure a coherent file at all times with the worst case being out of date by one save cycle (and you could even keep the, say, last 3 copies as backups too, auto-restoring on load failure), though I've not looked into how DragonAPI saves such player specific data so take this part with a grain of salt.  ^.^

**Comment by ReikaKalseki** [comment]
>  The way playing such huge files 'should' be done is probably via javax's AudioSystem as it can actually stream from disk

How does one do this?

**Comment by Barhandar** [comment]
I am losing all progression about half the time my instance crashes, thanks FTBU for backups. Coincidentally, overlapping half the crashes are caused by Chromaticraft itself.

Can progress data please be a little less volatile? And can the cache actually _work as it should_ and restore progression if the main storage gets corrupt? Right now it not only fails to load from cache, but _wipes the cache too_.

**Comment by ReikaKalseki** [comment]
I actually implemented a new backup system yesterday; v19 will be its test.

**Comment by OvermindDL1** [comment]
The docs are at:  https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioSystem.html

Can see the second answer at this for a detailed usage with error checking:  https://stackoverflow.com/questions/41331288/java-how-to-play-an-audio-file-like-wav-and-mp3-from-a-file

**Comment by ReikaKalseki** [comment]
Everything I find, including on your pages, gives nonfunctional code - it can only read WAV files, which would be several hundred megabytes *each*. And all the tutorials for reading OGG or MP3 actually do not work - they just throw exceptions. Worse, basically everyone mentions ultimately resorting to third-party libraries - most often paulscode! - which are not an option here.

Also, none of that code offers programmatic modulation, such as volume control.

**Comment by OvermindDL1** [comment]
> Everything I find, including on your pages, gives nonfunctional code - it can only read WAV files, which would be several hundred megabytes each. And all the tutorials for reading OGG or MP3 actually do not work - they just throw exceptions. Worse, basically everyone mentions ultimately resorting to third-party libraries - most often paulscode! - which are not an option here.

You have to decode ogg/mp3 files into a wave format as that is all that audio systems understand, I usually did that as one bulk step during loading (on another thread of course) of the file itself then passed the waveform piecemeal to the audio system.  A better way would be to load and decode the file in parts on another thread and pass it to the audio handling thread as it decodes.  It will always decode faster than it plays so that is never an issue and with this you can start playing music instantly without neither a game freeze nor physical delay of more than a few milliseconds at all.  I can give good C code that I've used for years on doing it as it is not too hard to translate to java (and for mp3/ogg you still need a third-party decoder, which pauls code includes I think?).

You do the programmatic modulation of volume, pitch, etc... to the waveform that is output after the decoding step.  Remember that a waveform is just a discrete set of (traditionally) shorts (16-bit integer) that represent from 0/silence to 0DB (max representable volume) for a set of waveforms of the range that you want (traditionally 48khz nowadays, so you have 48k 'samples' of those 16-bit shorts).

Now adjusting volume is just adjusting the amplitude of these values, which is trivially done by multiplying to a float scaler each of the short samples, which you can do 'as' you pass it to the audio card (this is what pauls or java's audio system does when you set the volume for example).

To adjust pitch there are two ways, you can either take the cheap cop-out and raise or lower the sample rate (passing more or less packed shorts at a time), but that also adjusts the speed that it plays at (like speeding up or slowing down an audio cassette or record... I may have dated myself a bit...), which is what Minecraft/paulscode does, which is entirely wrong (my first job was digital audio sampling and manipulation near 3 decades ago, thus the way minecraft does it really bugs the ever living tar out of me).  The proper way to do it is to Fourier Transform it (a relatively simple math equation that transforms a set of discrete points along a sinusoidal wave into a wave equation, this is how mp3 compresses for example, the quality of the mp3 is the number of integral steps you process it via a fourier transform to get a better quality waveform equation), then apply a scaler to the resultant equation, then convert it back to a waveform, which is pretty trivial to do quickly on modern hardware (it used to be popular to do it on a dedicated DSP chip on an audio card for games way back in the day of 100mhz systems, but nowadays it is trivial to do it on CPU and thus about every audio system in existence does just that nowadays as it is fast and works everywhere).

Now of course any decent audio system will do the above for you, but it is not at all hard to do it yourself.  I can give you the C code I use to do it if it is not already in paulscode or so, or just go the minecraft way and time adjust it too as it is the cheap cop-out.  ^.^

But doing it yourself means that you can dump out a perfect waveform of any way that you want straight to the audio system, nice and easy after writing the math.  :-)

Regardless, you will need a third-party library (though isn't it already in paulscode?!) to decode ogg/mp3 files as doing that manually is.... non-trivial by any definition.

**Comment by ReikaKalseki** [comment]
Using paulscode is liable to trigger the problem, as I have no idea where the problem lies. And using another external library is impossible; I am not adding extra random dependencies.

**Comment by ReikaKalseki** [comment]
I looked at this again and got no further. Additionally, some testing indicates that each file is more than 100MB of data as raw PCM; the files may just be so large that parsing them (a necessary all-at-once (ie unthreadable) operation, given the encoded format) is the primary cause.

**Comment by OvermindDL1** [comment]
Just decode it to raw data in another thread when the previous song starts, holding a couple extra hundred megs of ram is no biggie.  You could decode it piecemeal as well instead of all at once (ogg supports that fine) then feed the piecemeal bits to it, this would be the proper thing to do, but no clue about pauls code's code to do it, I use native api's.  ^.^;

**Comment by ReikaKalseki** [comment]
> holding a couple extra hundred megs of ram is no biggie.

I strongly disagree, given the fact that most packs already require 4-5GB of allocated RAM, and where 100MB is easily equivalent to another mod or several.

> You could decode it piecemeal as well instead of all at once (ogg supports that fine) then feed the piecemeal bits to it

paulscode cannot do this.

> I use native api's.

There *are* no native APIs for OGG.

**Comment by OvermindDL1** [comment]
> I strongly disagree, given the fact that most packs already require 4-5GB of allocated RAM, and where 100MB is easily equivalent to another mod or several.

The issue is if the memory is fragmented or not.  Most mods require that much memory because they are highly fragmented due to poor coding.  A single allocated 100 meg block for a sound is trivial and will not introduce strain at all.

And by native API's I mean just calling into the ogg library straight, it comes with pauls code after all, so just bypass pauls code and use it directly. :-)

**Comment by ReikaKalseki** [comment]
> The issue is if the memory is fragmented or not. Most mods require that much memory because they are highly fragmented due to poor coding. A single allocated 100 meg block for a sound is trivial and will not introduce strain at all.

Given that Java completely abstracts away memory management, I rather doubt both parts of this.

> And by native API's I mean just calling into the ogg library straight, it comes with pauls code after all, so just bypass pauls code and use it directly. :-)

How?

**Comment by OvermindDL1** [comment]
> Given that Java completely abstracts away memory management, I rather doubt both parts of this.

That abstraction is what causes this.  ;-)

Allocations in the older GC generation are nicely packed but the younger (and often smaller) generations get fragmented like crazy, when the music is allocated it will take up a chunk of this, but probably not enough room among the fragmentation so it will allocate a new 100 meg or so chunk (just allocate 2 chunks of a size large enough to hold the decompressed data and you are good, just swap between them).

But still, details unneeded, just know that larger allocations are better in Java than small ones (especially if you pool small memory from a single large allocation).

> How?

I don't have MC here at work, what is the ogg library included with paulscode?  I can grab the docs for you then.

**Comment by ReikaKalseki** [comment]
> what is the ogg library included with paulscode?

JOrbis/JCraft.

**Comment by OvermindDL1** [comment]
Ah, that looks pretty easy actually.

Website:  http://www.jcraft.com/jorbis/

Tutorial:  http://www.jcraft.com/jorbis/tutorial/Tutorial.html (just replace the http getters with file system operations).

Looks entirely safe to process the decompression on another thread than pass the result to the audio thread to play once it is complete as well (or send packets of the information over time as well via messages between threads or a synchronized data block).

Or just do what the tutorial does and decompress the ogg file and pass the resultant tiny parts to the audio player in pieces (streaming mode essentially, so it streams from the file system, decoding on the fly, to the audio system, no excess memory use then either, but it requires more setup).

**Comment by ReikaKalseki** [comment]
> Ah, that looks pretty easy actually.

I already saw that page. I have no interest in including 1000 lines of code I do not understand to perform a function I do not fully understand in order to fix a problem of unknown cause.
