### ISSUE TITLE
Chromaticraft: Client-side error while infusing player

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1304]
About 50% of the time while infusing a player this error happens once it is complete.  The infusion does complete properly, however the view of the player remains in third-person with the GUI disabled, have to press F1 and F5 to correct it when this happens.

```java
[17:08:05] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Ritual Table @ DIM0: 21, 70, 340 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Registry.Chromabilities.setToPlayer(Chromabilities.java:531)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Registry.Chromabilities.give(Chromabilities.java:501)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.giveAbility(TileEntityRitualTable.java:249)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.onRitualTick(TileEntityRitualTable.java:175)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityRitualTable.updateEntity(TileEntityRitualTable.java:90)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:08:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by ReikaKalseki** [comment]
Looking at the code, this should be impossible; it is possible that it was fixed since the last release.
