### ISSUE TITLE
Chromaticraft Crash on Dedicated Server Load

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1310]
Running DragonAPI v16d, Chromaticraft v16d, and SGCraft v1.13.0, I get this crash listed at the bottom of this post only on a dedicated server (client works fine).  Searched in prior issues in github and unable to locate an issue about this missing callback.

In essence, this is the important part of the crash report:
```java
Could not inject interface dan200/computercraft/api/peripheral/IPeripheral;
Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift does not implement the following required methods:
        equals (Ldan200/computercraft/api/peripheral/IPeripheral;)Z
```
On TileEntityRift.  Indeed checking at SGCraft https://github.com/gcewing/SGCraft/blob/mc1.7/BUILDING.txt#L19 it is built with ComputerCraft's API v1.65, and if we extract that jar file and acquire the class file of `dan20/computercraft/api/peripheral/IPeripheral.class` and decompile it then we see:
```java
package dan200.computercraft.api.peripheral;

import dan200.computercraft.api.lua.ILuaContext;
import dan200.computercraft.api.lua.LuaException;
import dan200.computercraft.api.peripheral.IComputerAccess;

public interface IPeripheral {
   public String getType();

   public String[] getMethodNames();

   public Object[] callMethod(IComputerAccess var1, ILuaContext var2, int var3, Object[] var4) throws LuaException, InterruptedException;

   public void attach(IComputerAccess var1);

   public void detach(IComputerAccess var1);

   public boolean equals(IPeripheral var1);
}
```
Meaning that TileEntityRift should indeed implement an method of `public boolean equals(IPeripheral var1);`, however if we look at https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Transport/TileEntityRift.java then we plainly see there is no equals method on that file, however there is one on one of its parents parents parents back in DragonAPI here: https://github.com/ReikaKalseki/DragonAPI/blob/2ae08f9f94c2291ecd3735644b14d61d3c271dec/Base/TileEntityBase.java#L638
```java
	@Override
	public final boolean equals(Object o) {/*
		if (o != this && this.isSameTile(o)) {
			DragonAPICore.log("TileEntities would be equal functionally but not in identity!"); //debug code
			Thread.dumpStack();
		}*/
		return super.equals(o);
	}
```

This injection test is done by Chromaticraft by calling into DragonAPI that ends up at https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/ASM/InterfaceInjector.java#L101 that then ends up calling https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/Libraries/Java/ReikaASMHelper.java#L879 that then calls https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/Libraries/Java/ReikaASMHelper.java#L139 to do the actual test  to see if `equals (Ldan200/computercraft/api/peripheral/IPeripheral;)Z` == `equals (LObject;)Z`, which it does by parsing out the method signature via calling https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/Libraries/Java/ReikaASMHelper.java#L627 by more string munging(?!) then calling https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/Libraries/Java/ReikaASMHelper.java#L159 on the returned string to get the class of the string (via more string munging) and pushing that all into an args list that it then tries to compare to the methods on the class via https://github.com/ReikaKalseki/DragonAPI/blob/530f105290ce9338e2822f8b58f01f1f02bb79b9/Libraries/Java/ReikaASMHelper.java#L151 by:
```java
				if (Arrays.equals(m.getParameterTypes(), params)) {
					return true;
				}
```
However, the classes of 'Object' and of `dan200.computercraft.api.peripheral.IPeripheral` are not going to identity match.  It looks like the above three lines should be implemented more like this (pseudo-code, maybe real code, I don't have the API's in front of me...):
```java
				if(m.getParameterTypes().length == params.length) {
					boolean noMatch = false;
					for (int i=params.length; i<params.length; ++i) {
						Class klassLeft = m.getParameterTypes()[i];
						Class klassRight = params[i];
						if(klassRight != klassLeft && !klassRight.isAssignableFrom(klassLeft)) {
							noMatch = true;
							break;
						}
					}
					if(noMatch == false) return true;
				}
```
Or something like that.

However in this case if anything calls the `IPeripheral.equals` call then it will not show equality on the same IPeripherals to make sure identical IPeripherals are not loaded on a computer, thus the correct thing in this case might be to actually implement the `public boolean equals(IPeripheral var1);` method on `TileEntityRift` properly or the IPeripheral API is not being properly fulfilled.

What is interesting is why it is not happening on the client on load as well...  Hmm...

```java
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift
        at Reika.ChromatiCraft.Registry.ChromaTiles.<clinit>(ChromaTiles.java:140)
        at Reika.ChromatiCraft.Registry.ChromaItems.getNumberMetadatas(ChromaItems.java:350)
        at Reika.DragonAPI.Libraries.ReikaRegistryHelper.registerItem(ReikaRegistryHelper.java:129)
        at Reika.DragonAPI.Libraries.ReikaRegistryHelper.instantiateAndRegisterItems(ReikaRegistryHelper.java:120)
        at Reika.ChromatiCraft.ChromatiCraft.setupClassFiles(ChromatiCraft.java:744)
        at Reika.ChromatiCraft.ChromatiCraft.preload(ChromatiCraft.java:352)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: Reika.ChromatiCraft.TileEntity.Transport.TileEntityRift
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 37 more
Caused by: Reika.DragonAPI.ASM.InterfaceInjector$ImproperImplementationException: Error ASMing Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift:
Could not inject interface dan200/computercraft/api/peripheral/IPeripheral;
Reika/ChromatiCraft/TileEntity/Transport/TileEntityRift does not implement the following required methods:
        equals (Ldan200/computercraft/api/peripheral/IPeripheral;)Z

In all likelihood, the interface has changed and its implementation requires correction.
The following methods were found on the class:
        <init> ()V
        getTile ()LReika/ChromatiCraft/Registry/ChromaTiles;
        updateEntity (Lnet/minecraft/world/World;IIII)V
        teleport (Lnet/minecraft/entity/Entity;)V
        shouldTeleport (Lnet/minecraft/entity/Entity;)Z
        onFirstTick (Lnet/minecraft/world/World;III)V
        setDirection (Lnet/minecraftforge/common/util/ForgeDirection;)V
        getSingleDirection ()Lnet/minecraftforge/common/util/ForgeDirection;
        canDrop (Lnet/minecraft/entity/player/EntityPlayer;)Z
        passThrough ()V
        getRedstoneLevel (Lnet/minecraftforge/common/util/ForgeDirection;)I
        animateWithTick (Lnet/minecraft/world/World;III)V
        createRandomLinkID ()V
        assignLinkID (LReika/ChromatiCraft/Base/TileEntity/LinkedTile;)V
        onLinkTo (Lnet/minecraft/world/World;IIILReika/ChromatiCraft/Base/TileEntity/LinkedTile;)V
        onReset ()V
        onResetOther (LReika/ChromatiCraft/Base/TileEntity/LinkedTile;)V
        getColor ()I
        getRandomColor ()I
        canLinkTo (Lnet/minecraft/world/World;III)Z
        getOther ()LReika/ChromatiCraft/TileEntity/Transport/TileEntityRift;
        getBlockFrom (Lnet/minecraftforge/common/util/ForgeDirection;)LReika/DragonAPI/Instantiable/Data/Immutable/WorldLocation;
        getAdjacentTargetTile (Lnet/minecraftforge/common/util/ForgeDirection;)Lnet/minecraft/tileentity/TileEntity;
        getSingleDirTile ()Lnet/minecraft/tileentity/TileEntity;
        getBlockIDFrom (Lnet/minecraftforge/common/util/ForgeDirection;)Lnet/minecraft/block/Block;
        getBlockMetadataFrom (Lnet/minecraftforge/common/util/ForgeDirection;)I
        getTileEntityFrom (Lnet/minecraftforge/common/util/ForgeDirection;)Lnet/minecraft/tileentity/TileEntity;
        writeSyncTag (Lnet/minecraft/nbt/NBTTagCompound;)V
        readSyncTag (Lnet/minecraft/nbt/NBTTagCompound;)V
        isConnectable (Lnet/minecraftforge/common/util/ForgeDirection;)Z
        canInputFrom (Lnet/minecraftforge/common/util/ForgeDirection;)Z
        canOutputTo (Lnet/minecraftforge/common/util/ForgeDirection;)Z
        setSuction (Lthaumcraft/api/aspects/Aspect;I)V
        getSuctionType (Lnet/minecraftforge/common/util/ForgeDirection;)Lthaumcraft/api/aspects/Aspect;
        getSuctionAmount (Lnet/minecraftforge/common/util/ForgeDirection;)I
        takeEssentia (Lthaumcraft/api/aspects/Aspect;ILnet/minecraftforge/common/util/ForgeDirection;)I
        addEssentia (Lthaumcraft/api/aspects/Aspect;ILnet/minecraftforge/common/util/ForgeDirection;)I
        getEssentiaType (Lnet/minecraftforge/common/util/ForgeDirection;)Lthaumcraft/api/aspects/Aspect;
        getEssentiaAmount (Lnet/minecraftforge/common/util/ForgeDirection;)I
        getMinimumSuction ()I
        renderExtendedTube ()Z
        receiveEnergy (Lnet/minecraftforge/common/util/ForgeDirection;IZ)I
        extractEnergy (Lnet/minecraftforge/common/util/ForgeDirection;IZ)I
        canConnectEnergy (Lnet/minecraftforge/common/util/ForgeDirection;)Z
        getEnergyStored (Lnet/minecraftforge/common/util/ForgeDirection;)I
        getMaxEnergyStored (Lnet/minecraftforge/common/util/ForgeDirection;)I
        fill (Lnet/minecraftforge/common/util/ForgeDirection;Lnet/minecraftforge/fluids/FluidStack;Z)I
        drain (Lnet/minecraftforge/common/util/ForgeDirection;Lnet/minecraftforge/fluids/FluidStack;Z)Lnet/minecraftforge/fluids/FluidStack;

        drain (Lnet/minecraftforge/common/util/ForgeDirection;IZ)Lnet/minecraftforge/fluids/FluidStack;
        canFill (Lnet/minecraftforge/common/util/ForgeDirection;Lnet/minecraftforge/fluids/Fluid;)Z
        canDrain (Lnet/minecraftforge/common/util/ForgeDirection;Lnet/minecraftforge/fluids/Fluid;)Z
        getTankInfo (Lnet/minecraftforge/common/util/ForgeDirection;)[Lnet/minecraftforge/fluids/FluidTankInfo;
        func_70302_i_ ()I
        func_70301_a (I)Lnet/minecraft/item/ItemStack;
        func_70298_a (II)Lnet/minecraft/item/ItemStack;
        func_70304_b (I)Lnet/minecraft/item/ItemStack;
        func_70299_a (ILnet/minecraft/item/ItemStack;)V
        func_145825_b ()Ljava/lang/String;
        func_145818_k_ ()Z
        func_70297_j_ ()I
        func_70300_a (Lnet/minecraft/entity/player/EntityPlayer;)Z
        func_70295_k_ ()V
        func_70305_f ()V
        func_94041_b (ILnet/minecraft/item/ItemStack;)Z
        func_94128_d (I)[I
        func_102007_a (ILnet/minecraft/item/ItemStack;I)Z
        func_102008_b (ILnet/minecraft/item/ItemStack;I)Z
        getAspects ()Lthaumcraft/api/aspects/AspectList;
        setAspects (Lthaumcraft/api/aspects/AspectList;)V
        doesContainerAccept (Lthaumcraft/api/aspects/Aspect;)Z
        addToContainer (Lthaumcraft/api/aspects/Aspect;I)I
        takeFromContainer (Lthaumcraft/api/aspects/Aspect;I)Z
        takeFromContainer (Lthaumcraft/api/aspects/AspectList;)Z
        doesContainerContainAmount (Lthaumcraft/api/aspects/Aspect;I)Z
        doesContainerContain (Lthaumcraft/api/aspects/AspectList;)Z
        containerContains (Lthaumcraft/api/aspects/Aspect;)I
        getType ()Ljava/lang/String;
        getMethodNames ()[Ljava/lang/String;
        callMethod (Ldan200/computercraft/api/peripheral/IComputerAccess;Ldan200/computercraft/api/lua/ILuaContext;I[Ljava/lang/Object;)[Ljava/lang/Object;
        attach (Ldan200/computercraft/api/peripheral/IComputerAccess;)V
        detach (Ldan200/computercraft/api/peripheral/IComputerAccess;)V
        onConnect (Lli/cil/oc/api/network/Node;)V
        getOtherNode (LReika/ChromatiCraft/TileEntity/Transport/TileEntityRift;I)Lli/cil/oc/api/network/Node;
        onInvalidateOrUnload (Lnet/minecraft/world/World;IIIZ)V
        breakBlock ()V
        getChunksToLoad ()Ljava/util/Collection;
        getCurrentMana ()I
        isGhost ()Z
        isFull ()Z
        recieveMana (I)V
        canRecieveManaFromBursts ()Z
        sidedNode (Lnet/minecraftforge/common/util/ForgeDirection;)Lli/cil/oc/api/network/Node;
        canConnect (Lnet/minecraftforge/common/util/ForgeDirection;)Z

        at Reika.DragonAPI.ASM.InterfaceInjector.tryInjectInterface(InterfaceInjector.java:109)
        at Reika.DragonAPI.ASM.InterfaceInjector.tryInjectInterfaces(InterfaceInjector.java:96)
        at Reika.DragonAPI.ASM.InterfaceInjector.transform(InterfaceInjector.java:59)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 39 more
```

**Comment by ReikaKalseki** [comment]
Fixed.
