### ISSUE TITLE
java.lang.IllegalStateException: How did a non-source tile (null) get put in the network here

### ISSUE THREAD

**Issue by OvermindDL1** [ReikaKalseki/Reika_Mods_Issues#1315]
Chromaticraft v16d, DragonAPI v16d, [yadda yadda usual bug report fillout that is identical to my others].

Got a new crash while trying to craft at the alter, no previous issues found about the error based on a Github Search, and this one is a bit more unique (as per the title).  Server crashed entirely but reloaded.  Alter works again other than the pylon network not pulling power from the pylons until I go out to them again...

```java
Time: 1/21/17 6:48 PM
Description: Ticking block entity

java.lang.IllegalStateException: How did a non-source tile (null) get put in the network here (6, 84, 331 in DIM0)?
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.getSourceAt(PylonFinder.java:381)
        at Reika.ChromatiCraft.Magic.Network.CrystalPath.<init>(CrystalPath.java:36)
        at Reika.ChromatiCraft.Magic.Network.CrystalFlow.<init>(CrystalFlow.java:31)
        at Reika.ChromatiCraft.Magic.Network.CrystalFlow.<init>(CrystalFlow.java:38)
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:135)
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:125)
        at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:261)
        at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:248)
        at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:83)
        at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:94)
        at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergyDifference(CrystalReceiverBase.java:101)
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:258)
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:151)
        at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.getSourceAt(PylonFinder.java:381)
        at Reika.ChromatiCraft.Magic.Network.CrystalPath.<init>(CrystalPath.java:36)
        at Reika.ChromatiCraft.Magic.Network.CrystalFlow.<init>(CrystalFlow.java:31)
        at Reika.ChromatiCraft.Magic.Network.CrystalFlow.<init>(CrystalFlow.java:38)
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:135)
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:125)
        at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:261)
        at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:248)
        at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:83)
        at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:94)
        at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergyDifference(CrystalReceiverBase.java:101)
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:258)
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:151)
        at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:490)
        at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
        Name: CCchroma.table // Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable
        Block type: ID #2005 (tile.ChromaticTile // Reika.ChromatiCraft.Base.BlockChromaTile)
        Block data value: 3 / 0x3 / 0b0011
        Block location: World: (21,70,316), Chunk: (at 5,4,12 in 1,19; contains blocks 16,0,304 to 31,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Actual block type: ID #2005 (tile.ChromaticTile // Reika.ChromatiCraft.Base.BlockChromaTile)
        Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
```

**Comment by OvermindDL1** [comment]
For note, at the given coordinates there is air, a large amount of air, however there 'used' to be a Lumen Tree there about 5 hours ago (and I've done alter recipes since then), had to destroy it because of an unrelated accident (since re-built in another location).  The tree battery was broken by hand since we could not figure out how to pick it up (right click with wand and all did nothing).

**Comment by ReikaKalseki** [comment]
Does this happen with any reliability?

**Comment by OvermindDL1** [comment]
> Does this happen with any reliability?

Nope, has only happened once.  I'm guessing just a bad cache that got rebuilt cleanly after the server was restarted due to the crash?  The part that confuses/interests me is how it did not happen in the 5 hours between that tree blowing up and the many times I'd used pylon energy in the alter until that one time that it did crash, maybe it was a specific colour that was used?

**Comment by OvermindDL1** [comment]
Also, how are you supposed to be able to pick up the tree battery block that is together with 3 glass?  It has no harvest entry in forge, right clicking with a variety of things starting with the wand did not work.  In the end I just ate the cost and crafted another and broke it by hand (whacking it with the wand left-click until it broke, I was hoping there might have been something there after exhausting everything else I could think of).

**Comment by Builderb0y** [comment]
Need silk touch I think.

**Comment by ReikaKalseki** [comment]
> Nope, has only happened once. I'm guessing just a bad cache

In that case, there is little if anything I can do about it.

**Comment by OvermindDL1** [comment]
> In that case, there is little if anything I can do about it.

Still indicates a bug, which could be caught so it does not happen again by checking the state and rebuilding it or just clearing that one entry or so...

**Comment by ReikaKalseki** [comment]
As far as I can tell, the issue is where a block gets removed and the TileEntity does not - or vice versa. Or where a block is replaced without changing the TileEntity there. In all cases, there is nothing I can do to prevent this.

**Comment by OvermindDL1** [comment]
It was broken by hand, is there any way the tile entity can not clear itself from the cache when that happens?  Is there not a janitor sweep over the cache to ensure coherency over time?

**Comment by ReikaKalseki** [comment]
No, the cache assumes that block-tile relationships work properly, and iterating over it as verification would be extremely bad for performance.

> It was broken by hand, is there any way the tile entity can not clear itself from the cache when that happens?

I have seen cases of it, generally where either MC just breaks or another fake block type is involved.
