### ISSUE TITLE
minecraft crash

### ISSUE THREAD

**Issue by wlich** [ReikaKalseki/Reika_Mods_Issues#1372]
my minecraft crash when I play minecraft with Chromaticraft and fastcraft mod

**Comment by Duckfan77** [comment]
And that is a completely useless piece of information, as we have no idea what went wrong.. Please post the crash log in something like [gist](https://gist.github.com). http://vazkii.us/br101/

**Comment by ReikaKalseki** [comment]
See #1366.

**Comment by wlich** [comment]
with AOA
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 02.03.17 18:01
Description: Initializing game

Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly:
CONFLICT: Biome IDs: net.nevermine.dimension.precasia.biome.BiomeGenPrecasiaDesert@974efc @ ID 102 (BiomeGenPrecasiaDesert & BiomeGenCrystalPlains)
Check your IDs and change them if possible.
This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..
	at Reika.DragonAPI.Auxiliary.Trackers.BiomeCollisionTracker.onConflict(BiomeCollisionTracker.java:75)
	at Reika.DragonAPI.Auxiliary.Trackers.BiomeCollisionTracker.addBiomeID(BiomeCollisionTracker.java:46)
	at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager$Biomes.create(ChromaDimensionManager.java:106)
	at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager$Biomes.access$200(ChromaDimensionManager.java:68)
	at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager.initialize(ChromaDimensionManager.java:239)
	at Reika.ChromatiCraft.ChromatiCraft.load(ChromatiCraft.java:433)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.DragonAPI.Auxiliary.Trackers.BiomeCollisionTracker.onConflict(BiomeCollisionTracker.java:75)
	at Reika.DragonAPI.Auxiliary.Trackers.BiomeCollisionTracker.addBiomeID(BiomeCollisionTracker.java:46)
	at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager$Biomes.create(ChromaDimensionManager.java:106)
	at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager$Biomes.access$200(ChromaDimensionManager.java:68)
	at Reika.ChromatiCraft.World.Dimension.ChromaDimensionManager.initialize(ChromaDimensionManager.java:239)
	at Reika.ChromatiCraft.ChromatiCraft.load(ChromatiCraft.java:433)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 179626632 bytes (171 MB) / 448598016 bytes (427 MB) up to 926154752 bytes (883 MB)
	JVM Flags: 5 total; -Xmx896M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHI	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHI	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHI	nevermine{2.5} [AdventOfAscension] (AoA-Snapshot 2 (2.5).jar) 
	UCHI	chancecubes{1.7.10-2.3.2.126} [Chance Cubes] (ChanceCubes-1.7.10-2.3.2.126.jar) 
	UCHI	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar) 
	UCHE	ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V16d.jar) 
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6470M GL version 4.2.11399 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by redelman** [comment]
RTFM? You have biome ID conflicts. As the log says, this is NOT a bug and you just look foolish now.

**Comment by wlich** [comment]
and no AOA
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 02.03.17 18:13
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferByte.<init>(Unknown Source)
	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
	at java.awt.image.Raster.createWritableRaster(Unknown Source)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
	at javax.imageio.ImageReader.getDestination(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:136)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:97)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:172)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.onGameLoaded(DragonAPIEventWatcher.java:155)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_28_DragonAPIEventWatcher_onGameLoaded_GameFinishedLoadingEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.clientTick(TickRegistry.java:69)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_173_TickRegistry_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.awt.image.DataBufferByte.<init>(Unknown Source)
	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
	at java.awt.image.Raster.createWritableRaster(Unknown Source)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
	at javax.imageio.ImageReader.getDestination(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/blocks.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:172)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.onGameLoaded(DragonAPIEventWatcher.java:155)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_28_DragonAPIEventWatcher_onGameLoaded_GameFinishedLoadingEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.clientTick(TickRegistry.java:69)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_173_TickRegistry_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 16278136 bytes (15 MB) / 926154752 bytes (883 MB) up to 926154752 bytes (883 MB)
	JVM Flags: 5 total; -Xmx896M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar) 
	UCHIJA	ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V16d.jar) 
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6470M GL version 4.2.11399 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ReikaKalseki** [comment]
Word of advice: Frowny-face reactions to being told to read, interpersed with user-error 'bug' reports, with logs directly pasted directly into the comments, make you look like an idiot.

**Comment by Aivech** [comment]
1. Allocate more memory.
2. Change either Advent of Ascension or ChromatiCraft's biome ID's so that they don't conflict.
