### ISSUE TITLE
Crashed on Cauldron

### ISSUE THREAD

**Issue by TehporP** [ReikaKalseki/Reika_Mods_Issues#139]
Forge verison 1408

here is the log

[09:25:52] [main/INFO]: DRAGONAPI: Patching class net.minecraft.block.BlockFire
[09:25:52] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [cauldron-server.jar:KCauldron-1.7.10-1408.95]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [cauldron-server.jar:KCauldron-1.7.10-1408.95]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockFire
    at net.minecraft.block.Block.func_149671_p(Block.java:214) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1590) ~[MinecraftServer.class:?]
    ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockFire
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
    at net.minecraft.block.Block.func_149671_p(Block.java:214) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1590) ~[MinecraftServer.class:?]
    ... 12 more
Caused by: Reika.DragonAPI.Exception.ASMException$NoSuchASMMethodInstructionException: Error ASMing method func_149674_a (Lnet/minecraft/world/World;IIILjava/util/Random;)V:
Could not find an instruction for a method call to func_147465_d (IIILnet/minecraft/block/Block;II)Z:

```
at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getNthMethodCall(ReikaASMHelper.java:415) ~[DragonAPI%201.7.10%20V7b.jar:?]
at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getFirstMethodCall(ReikaASMHelper.java:399) ~[DragonAPI%201.7.10%20V7b.jar:?]
at Reika.DragonAPI.ASM.DragonAPIClassTransfomer$ClassPatch.apply(DragonAPIClassTransfomer.java:686) ~[DragonAPI%201.7.10%20V7b.jar:?]
at Reika.DragonAPI.ASM.DragonAPIClassTransfomer$ClassPatch.access$100(DragonAPIClassTransfomer.java:48) ~[DragonAPI%201.7.10%20V7b.jar:?]
at Reika.DragonAPI.ASM.DragonAPIClassTransfomer.transform(DragonAPIClassTransfomer.java:837) ~[DragonAPI%201.7.10%20V7b.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
at net.minecraft.block.Block.func_149671_p(Block.java:214) ~[aji.class:?]
at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1590) ~[MinecraftServer.class:?]
... 12 more
```

**Comment by 1Matthias** [comment]
Cauldron is not supported.

**Comment by TomeWyrm** [comment]
Update kCauldron. They patched it on their end.

**Comment by webbster64** [comment]
got the same problem, so looks like i have to remove all of ReikaKalseki's mods considering im going choose thermos over DragonAPI RotaryCraft ReactorCraft ElectriCraft GeoStrata, i want to give my players a stable and fun server running at 20-19tps over a server with 5 extra mods thats running at 5tps
