### ISSUE TITLE
client crash: NPE in DragonAPI getDefaultPitch

### ISSUE THREAD

**Issue by keturn** [ReikaKalseki/Reika_Mods_Issues#1399]
DragonAPI 1.7.10 V16d.

Can't reproduce this one on command, presumably it's triggered by something in the area at the time though I don't know what, but I have seven client crash logs with this in it now.

```
	at Reika.DragonAPI.Instantiable.Event.Client.SoundPitchEvent.getDefaultPitch(SoundPitchEvent.java:38)
	at Reika.DragonAPI.Instantiable.Event.Client.SoundPitchEvent.<init>(SoundPitchEvent.java:32)
	at Reika.DragonAPI.Instantiable.Event.Client.SoundPitchEvent.fire(SoundPitchEvent.java:42)
```

Full crash report at https://gist.github.com/keturn/de9b3bf4da3ad789b9568c8875787371

**Comment by ReikaKalseki** [comment]
#1389
