### ISSUE TITLE
Crash when using a bed.

### ISSUE THREAD

**Issue by webmilio** [ReikaKalseki/Reika_Mods_Issues#1436]
I have several other mods installed on my server but the crash log doesn't seem to specify any other mods.

[12:54:59] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Reika/CritterPet/Interfaces/TamedMob
	at Reika.DragonAPI.ASM.DragonAPIClassTransformer.allowMobSleeping(DragonAPIClassTransformer.java:51) ~[DragonAPI%201.7.10%20V17a.jar:?]
	at net.minecraft.entity.player.EntityPlayer.func_71018_a(EntityPlayer.java:1373) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71018_a(EntityPlayerMP.java:557) ~[mw.class:?]
	at net.minecraft.block.BlockBed.func_149727_a(SourceFile:100) ~[ajh.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: Reika.CritterPet.Interfaces.TamedMob
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 15 more
Caused by: java.lang.NullPointerException

**Comment by ReikaKalseki** [comment]
Why is that in CritterPet...

**Comment by ReikaKalseki** [comment]
Oh, wrong interface.
