### ISSUE TITLE
Bezier Crystals in PVP cause client crash

### ISSUE THREAD

**Issue by kenish25** [ReikaKalseki/Reika_Mods_Issues#1476]
Me and my friend's clients crash when we hit each other with Bezier Crystals. The server remains fine, just the clients crash. We are on version 17c.

relevant part of the crash log:
`[13/6/2017 18:46:17 PM] java.lang.NullPointerException
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack$1.func_82704_a(ItemSplineAttack.java:57) ~[ItemSplineAttack$1.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.world.chunk.Chunk.func_76588_a(Chunk.java:964) ~[apx.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.world.World.func_94576_a(World.java:3203) ~[ahb.class:?]
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack.getAttackableEntities(ItemSplineAttack.java:138) ~[ItemSplineAttack.class:?]
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack.func_77659_a(ItemSplineAttack.java:77) ~[ItemSplineAttack.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377) ~[bje.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475) ~[bao.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) ~[bao.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[13/6/2017 18:46:17 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
[13/6/2017 18:46:17 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
[13/6/2017 18:46:17 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
[13/6/2017 18:46:17 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
[13/6/2017 18:46:17 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[13/6/2017 18:46:17 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[13/6/2017 18:46:17 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[13/6/2017 18:46:17 PM] // I feel sad now :(
[13/6/2017 18:46:17 PM] 
[13/6/2017 18:46:17 PM] Time: 6/13/17 6:46 PM
[13/6/2017 18:46:17 PM] Description: Unexpected error
[13/6/2017 18:46:17 PM] 
[13/6/2017 18:46:17 PM] java.lang.NullPointerException: Unexpected error
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack$1.func_82704_a(ItemSplineAttack.java:57)
[13/6/2017 18:46:17 PM] 	at net.minecraft.world.chunk.Chunk.func_76588_a(Chunk.java:964)
[13/6/2017 18:46:17 PM] 	at net.minecraft.world.World.func_94576_a(World.java:3203)
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack.getAttackableEntities(ItemSplineAttack.java:138)
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack.func_77659_a(ItemSplineAttack.java:77)
[13/6/2017 18:46:17 PM] 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[13/6/2017 18:46:17 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13/6/2017 18:46:17 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13/6/2017 18:46:17 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13/6/2017 18:46:17 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[13/6/2017 18:46:17 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13/6/2017 18:46:17 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13/6/2017 18:46:17 PM] 
[13/6/2017 18:46:17 PM] 
[13/6/2017 18:46:17 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[13/6/2017 18:46:17 PM] ---------------------------------------------------------------------------------------
[13/6/2017 18:46:17 PM] 
[13/6/2017 18:46:17 PM] -- Head --
[13/6/2017 18:46:17 PM] Stacktrace:
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack$1.func_82704_a(ItemSplineAttack.java:57)
[13/6/2017 18:46:17 PM] 	at net.minecraft.world.chunk.Chunk.func_76588_a(Chunk.java:964)
[13/6/2017 18:46:17 PM] 	at net.minecraft.world.World.func_94576_a(World.java:3203)
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack.getAttackableEntities(ItemSplineAttack.java:138)
[13/6/2017 18:46:17 PM] 	at Reika.ChromatiCraft.Items.Tools.ItemSplineAttack.func_77659_a(ItemSplineAttack.java:77)
[13/6/2017 18:46:17 PM] 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
[13/6/2017 18:46:17 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)`

**Comment by ReikaKalseki** [comment]
Fixed.
