### ISSUE TITLE
Crash when attempting to launch the game with a non english language.

### ISSUE THREAD

**Issue by PJB3005** [ReikaKalseki/Reika_Mods_Issues#1501]
This is the crash I got when trying to load the game when my language was set to `fr_FR`. I should note that switching the language mid game seems to work fine except for missing translations. Setting the language back to `en_US` in `options.txt` worked to fix it.

https://gist.github.com/PJB3005/bc458c2dd1f451b395cb4211e61dc987

Important bit is probably this:

```
Caused by: java.lang.RuntimeException: Could not load XML at Resources/fr_FR/machines.xml relative to Reika.RotaryCraft.RotaryCraft
	at Reika.DragonAPI.Instantiable.IO.XMLInterface.<init>(XMLInterface.java:70)
	at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.<clinit>(RotaryDescriptions.java:99)
	... 37 more
Caused by: java.lang.RuntimeException: XML file at Resources/fr_FR/machines.xml relative to Reika.RotaryCraft.RotaryCraft not found!
	at Reika.DragonAPI.Instantiable.IO.XMLInterface.<init>(XMLInterface.java:65)
	... 38 more
```

**Comment by ReikaKalseki** [comment]
So the actual problem is that the system cannot handle partly localized handbook data - in particular having categories.xml and not others - and that happens to be the case with French - and *only* French. I will remove the French categories.xml until the whole set is provided by anyone who wishes to do so.

**Comment by ReikaKalseki** [comment]
The source of the categories.xml was this:

https://github.com/ReikaKalseki/RotaryCraft/pull/28
