### ISSUE TITLE
DragonAPI not registering commands on server

### ISSUE THREAD

**Issue by NanoHeart** [ReikaKalseki/Reika_Mods_Issues#1514]
java.lang.RuntimeException: Could not find DragonAPI commands!
	at Reika.DragonAPI.DragonAPIInit.registerCommands(DragonAPIInit.java:630) ~[DragonAPIInit.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_111]
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717) ~[?:1.8.0_111]
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419) ~[?:1.8.0_111]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_111]
	at sun.misc.IOUtils.readFully(IOUtils.java:65) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getBytes(JarFile.java:425) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getManifest(JarFile.java:180) ~[?:1.8.0_111]
	at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:375) ~[guava-17.0.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:327) ~[guava-17.0.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:315) ~[guava-17.0.jar:?]
	at com.google.common.reflect.ClassPath.from(ClassPath.java:92) ~[guava-17.0.jar:?]
	at Reika.DragonAPI.Libraries.Java.ReikaJavaLibrary.getAllClassesFromPackage(ReikaJavaLibrary.java:881) ~[ReikaJavaLibrary.class:?]
	at Reika.DragonAPI.DragonAPIInit.registerCommands(DragonAPIInit.java:616) ~[DragonAPIInit.class:?]
	... 30 more
[15:39:54] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
java.lang.RuntimeException: Could not find DragonAPI commands!
	at Reika.DragonAPI.DragonAPIInit.registerCommands(DragonAPIInit.java:630) ~[DragonAPIInit.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_111]
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717) ~[?:1.8.0_111]
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419) ~[?:1.8.0_111]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_111]
	at sun.misc.IOUtils.readFully(IOUtils.java:65) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getBytes(JarFile.java:425) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getManifest(JarFile.java:180) ~[?:1.8.0_111]
	at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:375) ~[guava-17.0.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:327) ~[guava-17.0.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:315) ~[guava-17.0.jar:?]
	at com.google.common.reflect.ClassPath.from(ClassPath.java:92) ~[guava-17.0.jar:?]
	at Reika.DragonAPI.Libraries.Java.ReikaJavaLibrary.getAllClassesFromPackage(ReikaJavaLibrary.java:881) ~[ReikaJavaLibrary.class:?]
	at Reika.DragonAPI.DragonAPIInit.registerCommands(DragonAPIInit.java:616) ~[DragonAPIInit.class:?]
	... 30 more
[15:39:54] [Server thread/ERROR] [RotaryCraft]: Skipping event FMLModIdMappingEvent and marking errored mod RotaryCraft since required dependency DragonAPI has errored
[15:39:54] [Server thread/ERROR] [ElectriCraft]: Skipping event FMLModIdMappingEvent and marking errored mod ElectriCraft since required dependency DragonAPI has errored
[15:39:54] [Server thread/ERROR] [ReactorCraft]: Skipping event FMLModIdMappingEvent and marking errored mod ReactorCraft since required dependency DragonAPI has errored
[15:39:54] [Server thread/INFO] [FML]: Applying holder lookups
[15:39:54] [Server thread/INFO] [FML]: Holder lookups applied
[15:39:54] [Server thread/ERROR] [RotaryCraft]: Skipping event FMLServerStoppedEvent and marking errored mod RotaryCraft since required dependency DragonAPI has errored
[15:39:54] [Server thread/ERROR] [ElectriCraft]: Skipping event FMLServerStoppedEvent and marking errored mod ElectriCraft since required dependency DragonAPI has errored
[15:39:54] [pool-4-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to /home/11905/userdata/custom-minecraft/./world/enderio/dimensionalTransceiver.json
[15:39:54] [Server thread/ERROR] [ReactorCraft]: Skipping event FMLServerStoppedEvent and marking errored mod ReactorCraft since required dependency DragonAPI has errored
[15:39:54] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:39:54] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
>

**Comment by ReikaKalseki** [comment]
> Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_111]
at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_111]
at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717) ~[?:1.8.0_111]
at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419) ~[?:1.8.0_111]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_111]
at sun.misc.IOUtils.readFully(IOUtils.java:65) ~[?:1.8.0_111]
at java.util.jar.JarFile.getBytes(JarFile.java:425) ~[?:1.8.0_111]
at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193) ~[?:1.8.0_111]
at java.util.jar.JarFile.getManifest(JarFile.java:180) ~[?:1.8.0_111]
at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:375) ~[guava-17.0.jar:?]
at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:327) ~[guava-17.0.jar:?]
at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:315) ~[guava-17.0.jar:?]
at com.google.common.reflect.ClassPath.from(ClassPath.java:92) ~[guava-17.0.jar:?]
at Reika.DragonAPI.Libraries.Java.ReikaJavaLibrary.getAllClassesFromPackage(ReikaJavaLibrary.java:881) ~[ReikaJavaLibrary.class:?]

Redownload the mods, and if that does not fix it, you have something wrong with your JVM.
