### ISSUE TITLE
[DragonAPI] CustomRecipeList does not support oredict entries

### ISSUE THREAD

**Issue by DaFuqs** [ReikaKalseki/Reika_Mods_Issues#1552]
I've added quite a lot of custom recipes via the LUA custom recipe handlers for rotarycraft. The custom recipes do not seem to support oredict, however.

Using item names works:

```
{			
	type = "stargate_naquadah"
	input = "SGCraft:naquadahOre"
	output = "RotaryCraft:rotarycraft_customextracts:0*3"
}
```

using oredict names, however does not work and an error is thrown:

```
{
	type = "tf_dustiron"	
	input = "ore:dustIron"
	output = "ThermalFoundation:material:0"
}
```

```
ROTARYCRAFT ERROR: Could not load custom recipe 'tf_dustiron' for GRINDER
java.lang.IllegalArgumentException: No such item 'ore:dustIron'
at Reika.DragonAPI.Instantiable.IO.CustomRecipeList.parseItemString(CustomRecipeList.java:208)
at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.addCustomRecipe(RecipesGrinder.java:408)
at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipeHandler.loadCustomRecipeFiles(RecipeHandler.java:234)
at Reika.RotaryCraft.RotaryRecipes.addPostLoadRecipes(RotaryRecipes.java:199)
at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:619)
```

**Comment by ReikaKalseki** [comment]
I [explicitly coded OreDict support](https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/IO/CustomRecipeList.java#L146), and used it in the examples back when I posted it. However, not all *machines* support the OreDict directly, and instead require direct item to item conversion. The grinder is one of them.
