### ISSUE TITLE
MeteorCraft Crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1562]
There seems to be an issue with MeteorCraft when spawning a new meteor; following its fall, the game will crash with the following message:

```
[21/8/2017 05:08:03 AM] [Server thread/ERROR]: Encountered an unexpected exception
[21/8/2017 05:08:03 AM] net.minecraft.util.ReportedException: Ticking entity
[21/8/2017 05:08:03 AM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[21/8/2017 05:08:03 AM] Caused by: java.lang.NoSuchMethodError: Reika.DragonAPI.Libraries.World.ReikaWorldHelper.getMaterial(Lnet/minecraft/world/World;III)Lnet/minecraft/block/material/Material;
[21/8/2017 05:08:03 AM] 	at Reika.MeteorCraft.MeteorGenerator.canStopMeteor(MeteorGenerator.java:308) ~[MeteorGenerator.class:?]
[21/8/2017 05:08:03 AM] 	at Reika.MeteorCraft.Entity.EntityMeteor.func_70071_h_(EntityMeteor.java:133) ~[EntityMeteor.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
[21/8/2017 05:08:03 AM] 	at WorldServerOF.func_72870_g(WorldServerOF.java:347) ~[WorldServerOF.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
[21/8/2017 05:08:03 AM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
[21/8/2017 05:08:03 AM] 	... 4 more
```

This doesn't happen every time; I had to type "/meteor" several times before it happened to me, but according to the [bug report](https://github.com/reteo/Survival-Industry/issues/122#issuecomment-323644417) for "Survival Industry," at least one player is getting this with the first meteor fall.

My full log can be found at: http://paste.atlauncher.com/view/d7003258
The other player's log is at: http://paste.atlauncher.com/view/af5e3e99

**Comment by ReikaKalseki** [comment]
This is another issue caused by v18b's update. There is no code change necessary, so the next release will automatically fix it.

**Comment by ghost** [comment]
Okay, thanks for the update.  Are we talking a new 18 sub-release, or you planning the release for 19?

**Comment by ReikaKalseki** [comment]
I just released v18b for MeteorCraft.

**Comment by ghost** [comment]
Ah, gotcha.  Last night, I looked to see 18a still there, so I assumed it wasn't released yet. :-/
