### ISSUE TITLE
Error with lumen Alveary booster on thunderstorm

### ISSUE THREAD

**Issue by Savallator** [ReikaKalseki/Reika_Mods_Issues#1627]
Hi,
i have built an lumen alveary booster, and while i have after considerable testing still no idea if or how it is working (it is consuming lumen, and speeding up the bee, and also adjusting the climate sometimes, but only about half the time, even though lumen supply is plentyful), it throws an error into the chat when a thunderstorm is ocurring. That is reproducable.
I am using Forestry 4.2.16.64 and binnies mods 2.0.21.
Error:

```
[04:56:26] [Client thread/INFO]: DRAGONAPI: 
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException
[04:56:26] [Client thread/INFO]: [CHAT] Tile Entity Lumen Alveary Booster @ DIM0: 531, 65, 1556 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[04:56:26] [Client thread/INFO]: [CHAT] [Reika.ChromatiCraft.ModInterface.Bees.SpecialAlleles$FlowerProviderCrystal.areConditionalsAvailable(SpecialAlleles.java:466), Reika.ChromatiCraft.ModInterface.Bees.SpecialAlleles$FlowerProviderCrystal.affectProducts(SpecialAlleles.java:422), forestry.apiculture.genetics.Bee.produceStacks(Bee.java:531), Reika.DragonAPI.ModInteract.Bees.ReikaBeeHelper.runProductionCycle(ReikaBeeHelper.java:273), Reika.ChromatiCraft.ModInterface.Bees.TileEntityLumenAlveary$LightningProductionEffect.tick(TileEntityLumenAlveary.java:940), Reika.ChromatiCraft.ModInterface.Bees.TileEntityLumenAlveary.updateEntity(TileEntityLumenAlveary.java:242), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:498), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:483), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[04:56:26] [Client thread/INFO]: [CHAT] 
[04:56:26] [Client thread/ERROR]: DRAGONAPI ERROR: Tile Entity Lumen Alveary Booster @ DIM0: 531, 65, 1556 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.ModInterface.Bees.SpecialAlleles$FlowerProviderCrystal.areConditionalsAvailable(SpecialAlleles.java:466)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.ModInterface.Bees.SpecialAlleles$FlowerProviderCrystal.affectProducts(SpecialAlleles.java:422)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at forestry.apiculture.genetics.Bee.produceStacks(Bee.java:531)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.ModInteract.Bees.ReikaBeeHelper.runProductionCycle(ReikaBeeHelper.java:273)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.ModInterface.Bees.TileEntityLumenAlveary$LightningProductionEffect.tick(TileEntityLumenAlveary.java:940)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.ModInterface.Bees.TileEntityLumenAlveary.updateEntity(TileEntityLumenAlveary.java:242)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:498)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[04:56:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Also i noticed another error in the log related to Fluid anchors, but that might be Another mods fault. The Anchors seem to work fine, but it is extremely spamming the logs.

`[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException: cofh.thermaldynamics.duct.fluid.TileFluidDuct cannot be cast to Reika.ChromatiCraft.TileEntity.Transport.TileEntityFluidRelay
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Transport.TileEntityFluidRelay.sendFluidParticles(TileEntityFluidRelay.java:187)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.ChromatiPackets.handleData(ChromatiPackets.java:861)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper$PacketObj.handleClient(ReikaPacketHelper.java:1670)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:155)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:145)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[04:43:00] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

The full log is over 20mb, so i could not put it at pastebin,  but i can upload it somewhere else if needed.

**Comment by ReikaKalseki** [comment]
Are the bees kitrino?

**Comment by Savallator** [comment]
No, Tahara, as i am desperately trying to get Purification powder and that worked nowhere else. I set the correct Biome with a Biome painter and tried everything i could think of, but they made specialties only in the lumen boosted alveary, and even there quite slow because they work only half of the time.

**Comment by ReikaKalseki** [comment]
Apparently alvearies do not properly store their owner, hence the NPEs above. I also fixed the climate matching intermittence.

**Comment by Savallator** [comment]
Nice!
