### ISSUE TITLE
MystCraft reflection Exception

### ISSUE THREAD

**Issue by clubpetey** [ReikaKalseki/Reika_Mods_Issues#164]
Forge 1408
MystCraft 0.11.5.0
RotC/DragonAPI: v7

```
[19:00:06] [Client thread/INFO]: DRAGONAPI: Reflective exception for reading Mystcraft! Was the class loaded?
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Reika.DragonAPI.Exception.ModReflectionException: DragonAPI had an error reading Mystcraft:
Could not find a field for decay
Please notify Reika as soon as possible, and include your version of Mystcraft
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler.getBlockInstance(MystCraftHandler.java:70)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler.<init>(MystCraftHandler.java:38)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler.<clinit>(MystCraftHandler.java:24)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName0(Native Method)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.forName(Class.java:344)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.Libraries.Java.ReikaJavaLibrary.initClass(ReikaJavaLibrary.java:232)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.DragonAPIInit.initHandler(DragonAPIInit.java:658)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.DragonAPIInit.registerHandler(DragonAPIInit.java:636)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.DragonAPIInit.registerHandler(DragonAPIInit.java:628)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.DragonAPIInit.loadHandlers(DragonAPIInit.java:609)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.DragonAPIInit.postload(DragonAPIInit.java:392)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:483)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:483)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:483)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.Loader.initializeMods(Loader.java:717)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:483)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:00:06] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:00:06] [Client thread/INFO]: DRAGONAPI: Loading handler class Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler for mod Mystcraft 0.11.5.00.
```

**Comment by ReikaKalseki** [comment]
Already fixed for v8.
