### ISSUE TITLE
ExpandedRedstone v19 crashes the game while loading.

### ISSUE THREAD

**Issue by RealityAnomaly** [ReikaKalseki/Reika_Mods_Issues#1663]
When ExpandedRedstone is removed the game will load successfully.
Seems to be an issue with a CodeChickenCore interface?

# Client

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 11/11/17 10:26
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/MultiPartRegistry$IPartFactory2
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/multipart/MultiPartRegistry$IPartFactory2
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.multipart.MultiPartRegistry$IPartFactory2
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 191315688 bytes (182 MB) / 470568960 bytes (448 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UC	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UC	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UC	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UC	asielib{0.4.8} [asielib] (AsieLib-1.7.10-0.4.8.jar) 
	UC	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UC	BioLock{2.2.pr1} [BioLock] (BioLock-v2.2.pr1-1.7.10.jar) 
	UC	CCLights2{0.4.3} [CCLights 2] (CCLights2-1.7.10-0.4.3.jar) 
	UC	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UC	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	DragonAPI{v19b} [DragonAPI] (DragonAPI 1.7.10 V19b.jar) 
	UC	ChromatiCraft{v19b} [ChromatiCraft] (ChromatiCraft 1.7.10 V19b.jar) 
	UC	computronics{1.6.5} [Computronics] (Computronics-1.7.10-1.6.5.jar) 
	UC	RotaryCraft{v19b} [RotaryCraft] (RotaryCraft 1.7.10 V19b.jar) 
	UC	ElectriCraft{v19b} [ElectriCraft] (ElectriCraft 1.7.10 V19b.jar) 
	UE	ExpandedRedstone{v19a} [ExpandedRedstone] (ExpandedRedstone 1.7.10 V19a.jar) 
	UC	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UC	GeoStrata{v19a} [GeoStrata] (GeoStrata 1.7.10 V19a.jar) 
	UC	IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
	UC	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
	UC	ImmibisPeripherals{59.0.3} [Immibis's Peripherals] (immibis-peripherals-59.0.3.jar) 
	UC	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UC	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UC	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UC	openfm{0.1.0.40} [OpenFM] (OpenFM-1.7.10-0.1.0-40.jar) 
	UC	OpenMods{0.9.1} [OpenMods] (openmodslib-1.7.10-0.9.1.jar) 
	UC	OpenPeripheralCore{1.3} [OpenPeripheralCore] (openperipheral-1.7.10-AIO-7.jar) 
	UC	OpenPeripheral{0.5.1} [OpenPeripheralAddons] (openperipheral-1.7.10-AIO-7.jar) 
	UC	OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (openperipheral-1.7.10-AIO-7.jar) 
	UC	ReactorCraft{v19b} [ReactorCraft] (ReactorCraft 1.7.10 V19b.jar) 
	UC	TickProfiler{1.0} [TickProfiler] (TickProfiler-1.7.10.jenkins.37.jar) 
	UC	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UC	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 387.92
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Barhandar** [comment]
Not seeing this error with CodeChickenCore-1.7.10-1.0.7.47-universal, CodeChickenLib-1.7.10-1.1.3.138-universal, and ForgeMultipart-1.7.10-1.2.0.345-universal. My FMP version is significantly higher than yours, maybe try updating that (or forcing auto-redownload by removing the file from mods/1.7.10)?

**Comment by ReikaKalseki** [comment]
There is a bug here; it should not be attempting to load this without ProjectRed installed.

**Comment by RealityAnomaly** [comment]
Confirming; Removing and re-downloading the latest version of FMP does not fix the crash.

**Comment by ReikaKalseki** [comment]
That makes no sense, but the above issue is fixed.
