### ISSUE TITLE
[Reactorcraft] Journeymap can't get color of block

### ISSUE THREAD

**Issue by iExalt** [ReikaKalseki/Reika_Mods_Issues#1744]
Line in log: [Client thread/WARN] [journeymap/]: Error getting block color from mod. Plese report this exception to the mod author of ReactorCraft:reactorcraft_block_line: java.lang.NullPointerException
	at Reika.ReactorCraft.Blocks.BlockReactorTile.func_149691_a(BlockReactorTile.java:210)
	at journeymap.client.forge.helper.impl.ColorHelper_1_7_10.getDirectIcon(ColorHelper_1_7_10.java:206)
	at journeymap.client.forge.helper.impl.ColorHelper_1_7_10.getTextureColor(ColorHelper_1_7_10.java:119)

**Comment by ReikaKalseki** [comment]
...What am I supposed to do to fix this?

**Comment by iExalt** [comment]
I haven't the slightest clue. Trying to ping someone over at Journeymap for more info

**Comment by iExalt** [comment]
Can't get an answer from Journeymap. Oh well, can't say we didn't try
