### ISSUE TITLE
[ChC v19c] Mysterious error message in logs related to villager structure

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1792]
I don't know what the symptoms of this are as my world is currently very broken in that items picked up disappear instead of entering the inventory, while analyzing logs I came upon this error message related to villager structures which may be of interest to you:

```
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.Exception: Stack trace
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.dumpStack(Unknown Source)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:781)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:470)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:82)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.safeLoadChunk(AgeController.java:351)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.expandChunkProfile(AgeController.java:341)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.updateProfiledInstability(AgeController.java:319)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.getInstabilityScore(AgeController.java:294)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.instability.InstabilityController.validate(InstabilityController.java:81)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.instability.InstabilityController.tick(InstabilityController.java:135)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.tickBlocksAndAmbiance(AgeController.java:584)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.WorldProviderMyst.canDoLightning(WorldProviderMyst.java:312)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:323)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.at.a(F:978)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.H.aq(F:36)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.InstantiationException: Reika.ChromatiCraft.World.VillagersFailChromatiCraft$WoodenChromaStructure
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143032_b(SourceFile:81)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.structure.StructureStart.func_143020_a(StructureStart.java:104)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143035_a(SourceFile:69)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:267)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:30)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.symbol.symbols.SymbolVillages$TerrainAlteration.alterTerrain(SymbolVillages.java:55)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.modifyTerrain(AgeController.java:553)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.REPLACED_provideChunk(ChunkProviderMyst.java:95)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at farseek.util.Reflection$MethodValue$.apply$extension(Reflection.scala:59)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at farseek.core.ReplacedMethod.apply(MethodReplacer.scala:105)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at farseek.world.gen.ChunkGeneratorExtensions$.provideChunk(ChunkGeneratorExtensions.scala:16)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at farseek.world.gen.ChunkGeneratorExtensions.provideChunk(ChunkGeneratorExtensions.scala)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_73154_d(ChunkProviderMyst.java)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.expandChunkProfile(AgeController.java:342)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.updateProfiledInstability(AgeController.java:319)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.getInstabilityScore(AgeController.java:294)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.instability.InstabilityController.validate(InstabilityController.java:81)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.instability.InstabilityController.tick(InstabilityController.java:135)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.AgeController.tickBlocksAndAmbiance(AgeController.java:584)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.xcompwiz.mystcraft.world.WorldProviderMyst.canDoLightning(WorldProviderMyst.java:312)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:323)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.at.a(F:978)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.H.aq(F:36)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoSuchMethodException: Reika.ChromatiCraft.World.VillagersFailChromatiCraft$WoodenChromaStructure.<init>()
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[22:06:47] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 38 more
```

Apparently some function tries to invoke a non-existent constructor on the VillagersFailChromatiCraft$WoodenChromaStructure

**Comment by ReikaKalseki** [comment]
I thought I fixed this; apparently not. Though it *is* an error, and would break things if my building had a villager assigned to it, the error is currently harmless and affects nothing.
