### ISSUE TITLE
crash adding gregtech to the modpack

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#1797]
hi, 
i get this crash report https://pastebin.com/9KH1ads4.

there is a error in the log 
[20:22:04] [Client thread/ERROR] [ReactorCraft]: Skipping event FMLPostInitializationEvent and marking errored mod ReactorCraft since required dependency RotaryCraft has errored

**Comment by CanisArtorus** [comment]
Error not present in GT6.07.08 + RoC v19c.

@marco6971 please check if your pack still gets the error after today's GregTech update.

Actual error from the pasted log:
java.lang.ClassCastException: Reika.DragonAPI.Libraries.Registry.ReikaOreHelper cannot be cast to Reika.DragonAPI.ModRegistry.ModOreList
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.addOreRecipes(RecipesGrinder.java:388)
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.addPostLoadRecipes(RecipesGrinder.java:282)
    at Reika.RotaryCraft.RotaryRecipes.addPostLoadRecipes(RotaryRecipes.java:201)
    at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:619)
...

which is [RecipesGrinder:388]
if (recipes.containsKey(is)) {
ModOreList mod = (ModOreList)ExtractorModOres.getOreFromExtract(recipes.get(is).output);

best match from [ExtractorModOres:171]
else if (ItemRegistry.EXTRACTS.matchItem(is)) {
return ReikaOreHelper.oreList[is.getItemDamage()%ReikaOreHelper.oreList.length];

which implies a block in the ModOreList was already contained in the oredict of a ReikaOreHelper (vanilla ore)... 

Patch/solution:  change RecipesGrinder:388 to accept the OreType interface, and thus any of the classes which implement it.

**Comment by ReikaKalseki** [comment]
Fixed.
