### ISSUE TITLE
Chromaticraft and Orespawn compatibility.

### ISSUE THREAD

**Issue by EverSoul** [ReikaKalseki/Reika_Mods_Issues#1805]
When I make a world with orespawn and chromaticraft, the game gives me null pointer exception that crashes my game. I have tested orespawn with over 500 mods and it wasn't having this issue until I added Chromaticraft. I have no idea what is causing this!!

Here's the error!
---- Minecraft Crash Report ----
// Don't do that.

Time: 4/4/18 9:44 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
at Reika.ChromatiCraft.World.IWG.DungeonGenerator.tryGenerate(DungeonGenerator.java:275)
at Reika.ChromatiCraft.World.IWG.DungeonGenerator.generate(DungeonGenerator.java:216)
at Reika.DragonAPI.Auxiliary.WorldGenInterceptionRegistry.interceptIWG(WorldGenInterceptionRegistry.java:114)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
at Reika.DragonAPI.Auxiliary.WorldGenInterceptionRegistry.interceptChunkPopulation(WorldGenInterceptionRegistry.java:104)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at net.minecraft.world.World.func_72964_e(World.java:419)
at net.minecraft.world.World.func_147439_a(World.java:345)
at net.minecraft.world.World.func_147437_c(World.java:365)
at net.minecraft.world.World.func_147474_b(World.java:329)
at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
at net.minecraft.world.World.(World.java:260)
at net.minecraft.world.WorldServer.(WorldServer.java:97)
at net.minecraft.world.WorldServerMulti.(WorldServerMulti.java:14)
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Stacktrace:
at Reika.ChromatiCraft.World.IWG.DungeonGenerator.tryGenerate(DungeonGenerator.java:275)
at Reika.ChromatiCraft.World.IWG.DungeonGenerator.generate(DungeonGenerator.java:216)
at Reika.DragonAPI.Auxiliary.WorldGenInterceptionRegistry.interceptIWG(WorldGenInterceptionRegistry.java:114)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
at Reika.DragonAPI.Auxiliary.WorldGenInterceptionRegistry.interceptChunkPopulation(WorldGenInterceptionRegistry.java:104)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
Found chunk: true
Location: World: (-71,64,-80), Chunk: (at 9,4,0 in -5,-5; contains blocks -80,0,-80 to -65,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
at net.minecraft.world.World.func_147439_a(World.java:345)
at net.minecraft.world.World.func_147437_c(World.java:365)
at net.minecraft.world.World.func_147474_b(World.java:329)
at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)

-- Affected level --
Details:
Level name: test
All players: 0 total; []
Chunk stats: ServerChunkCache: 42 Drop: 0
Level seed: -1687724445315775301
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 0 game time, 0 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
at net.minecraft.world.World.(World.java:260)
at net.minecraft.world.WorldServer.(WorldServer.java:97)
at net.minecraft.world.WorldServerMulti.(WorldServerMulti.java:14)
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_151, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 9277095040 bytes (8847 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms10240m -Xmx10240m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 15, allocated: 29, tallocated: 77
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 26 mods loaded, 26 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar)
UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar)
UCHIJAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar)
UCHIJAA	{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
UCHIJAA	mobdropcrops{1.7.2a} [Pam's Mob Drop Crops] ((Azip)Pam's Mob Drop Crops 1.7.10a.zip)
UCHIJAA	DragonAPI{v19c} [DragonAPI] (DragonAPI+1.7.10+V19c.jar)
UCHIJAA	ChromatiCraft{v19c} [ChromatiCraft] (ChromatiCraft+1.7.10+V19c.jar)
UCHIJAA	RotaryCraft{v19c} [RotaryCraft] (RotaryCraft+1.7.10+V19c.jar)
UCHIJAA	ElectriCraft{v19b} [ElectriCraft] (ElectriCraft+1.7.10+V19b.jar)
UCHIJAA	ExpandedRedstone{v19a} [Expanded Redstone] (ExpandedRedstone+1.7.10+V19a.jar)
UCHIJAA	GeoStrata{v19a} [GeoStrata] (GeoStrata+1.7.10+V19a.jar)
UCHIJAA	MeteorCraft{v19a} [MeteorCraft] (MeteorCraft+1.7.10+V19a.jar)
UCHIJAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.jar)
UCHIJAA	ReactorCraft{v19c} [ReactorCraft] (ReactorCraft+1.7.10+V19c (1).jar)
UCHIJAA	UsefulTNT{v19a} [Useful TNT] (UsefulTNT+1.7.10+V19a.jar)
UCHIJAA	VoidMonster{v19c} [Void Monster] (VoidMonster+1.7.10+V19c.jar)
UCHIJAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)
UCHIJAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
UCHIJAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar)
UCHIJAA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar)
UCHIJAA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar)
UCHIJAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar)
UCHIJAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar)
UCHIJAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar)
UCHIJAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar)
GL info: ERROR RuntimeException: No OpenGL context found in the current thread.
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 0 / 8; []
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ReikaKalseki** [comment]
#1593
