### ISSUE TITLE
Odd Interaction with Advanced Rocketry Causing Crashes

### ISSUE THREAD

**Issue by Temmie19** [ReikaKalseki/Reika_Mods_Issues#1818]
I recently added Advanced Rocketry to Wattage and going onto a planet causes the server I've been running to crash consistently. This only happens when the one player on aforementioned planet joins and at no other time does this happen.

https://gist.github.com/Temmie19/f690096dd9f819730f8f159b5fb04c87

It seems like DragonAPI is having a hard time interacting with AR's custom generation, which is why I brought it here. If I am incorrect in thinking this is on DragonAPI's side, please let me know.

Also Reika you're cute <3

**Comment by ReikaKalseki** [comment]
The error you have is a crash due to MystCraft dimension registration, not DragonAPI *or* Advanced Rocketry:

    [16:22:32] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
    [16:22:32] [Server thread/ERROR] [FML/]: Caught exception from Mystcraft
    java.lang.IllegalArgumentException: Failed to register dimension for id 6, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118) ~[DimensionManager.class:?]
	at com.xcompwiz.mystcraft.Mystcraft.registerDimensions(Mystcraft.java:431) ~[Mystcraft.class:?]
	at com.xcompwiz.mystcraft.Mystcraft.serverStart(Mystcraft.java:381) ~[Mystcraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]

It looks like a Dimension ID conflict.
