### ISSUE TITLE
Galacticraft Asteroid Dimension Crashing When Loading Rotarycraft

### ISSUE THREAD

**Issue by MechanizedIT** [ReikaKalseki/Reika_Mods_Issues#1838]
Dragon API and Galacticraft seem to be continually trying to load the same chunk in the Asteroid Dimension (-30).

The output window shows this repeatedly when trying to load a new worl
****************************************
--
21:29:44 | FML | Server thread | warn | * There is an attempt to load a chunk (-3,12) in dimension -30 that is already being loaded. This will cause weird chunk breakages.
21:29:44 | FML | Server thread | warn | *  at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154)
21:29:44 | FML | Server thread | warn | *  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
21:29:44 | FML | Server thread | warn | *  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
21:29:44 | FML | Server thread | warn | *  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
21:29:44 | FML | Server thread | warn | *  at net.minecraft.world.World.func_72964_e(World.java:419)
21:29:44 | FML | Server thread | warn | *  at net.minecraft.world.World.func_147439_a(World.java:345)...
21:29:44 | FML | Server thread | warn | ****************************************

The Crash Report shows this repeatedly:

Description: Exception getting block type in world

java.lang.StackOverflowError: Exception getting block type in world
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:178)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at Reika.DragonAPI.Instantiable.Event.SetBlockEvent.getBlock(SetBlockEvent.java:44)
	at Reika.DragonAPI.Instantiable.Event.SetBlockEvent$Pre.<init>(SetBlockEvent.java:65)
	at Reika.DragonAPI.Instantiable.Event.SetBlockEvent$Pre.fire(SetBlockEvent.java:74)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java)
	at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.generateSkylightMap(ChunkProviderAsteroids.java:842)
	at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.func_73154_d(ChunkProviderAsteroids.java:538)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)

and this:

-- Chunk to be generated --
Details:
	Location: -17,-13
	Position hash: -51539607569
	Generator: RandomLevelSource

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-269,200,-195), Chunk: (at 3,12,13 in -17,-13; contains blocks -272,0,-208 to -257,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)

-- Chunk to be generated --
Details:
	Location: -17,-13
	Position hash: -51539607569
	Generator: RandomLevelSource

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-269,200,-195), Chunk: (at 3,12,13 in -17,-13; contains blocks -272,0,-208 to -257,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)

**Comment by ReikaKalseki** [comment]
Probably fixed.
