### ISSUE TITLE
ChromatiCraft seemingly doesn't save my progression at all [v20a]

### ISSUE THREAD

**Issue by Mikki-m8** [ReikaKalseki/Reika_Mods_Issues#1852]
Not sure what's going on but I can keep earning the same progression over and over again. If I stand in a Rainbow Forest, I'll get the little notification every 20 seconds or so. Every time I break the leaves of a dye tree or look a crystal I'll get the notification too. 

`[17:29:21] [Server thread/INFO] [FML/]: CHROMATICRAFT: Restoring progression for Mikki__ from cache, as it had more progression than they did!
[17:29:21] [Server thread/WARN] [FML/]: ****************************************
[17:29:21] [Server thread/WARN] [FML/]: * ChromatiCraft: Player Mikki__ just lost some of their progression!
[17:29:21] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionCacher.updateProgressCache(ProgressionCacher.java:130)
[17:29:21] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.setPlayerStage(ProgressionManager.java:706)
[17:29:21] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.setPlayerStage(ProgressionManager.java:633)
[17:29:21] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.stepPlayerTo(ProgressionManager.java:562)
[17:29:21] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager.access$000(ProgressionManager.java:86)
[17:29:21] [Server thread/WARN] [FML/]: *  at Reika.ChromatiCraft.Auxiliary.ProgressionManager$ProgressStage.stepPlayerTo(ProgressionManager.java:194)...
[17:29:21] [Server thread/WARN] [FML/]: ****************************************`

**Comment by ReikaKalseki** [comment]
Someone else reported this a long time ago; I think the problem was some File I/O problem.

**Comment by Mikki-m8** [comment]
I have no idea what the correlation is but we've figured out it's some interaction with the latest Advent of Ascension versions. It doesn't seem to happen to versions before AoA Tslat-1.0.2. 

Not sure which side the bug is on, but it's been reported to the AoA dev as well.

**Comment by ReikaKalseki** [comment]
Maybe your player data is not saving properly. As for exactly *why*...I do not know, though my first suspicion is it being overloaded (ie too much data). Does AoA write lots of data to the player's NBT (eg RPG-style skills, perhaps)?

**Comment by Mikki-m8** [comment]
It does store stuff in the player NBT file, but it's not an excessive amount by any means.

I've looked at player.dat on two different AoA versions, and I noticed that pre-1.0.2 versions store the AoA data in PlayerPersisted, and post-1.0.2 saves it in both PlayerPersisted and ForgeData > PlayerPersisted. 

I am pretty sure AoA is overwriting the entire ForgeData > PlayerPersisted folder every time, at least that's my guess. Apparently not a problem on your end. I think.

**Comment by ReikaKalseki** [comment]
Update me if that turns out to not be true.

**Comment by pingp0nzi** [comment]
the problem's with AoA; it also causes problems with witchery, spice of life and blood magic. all three mods need to write in ForgeData > PlayerPersisted and AoA overwrites the whole thing

**Comment by ReikaKalseki** [comment]
Who is/are the developer(s) of AoA? Can they be pinged here?

**Comment by pingp0nzi** [comment]
i think the main dev is @Tslat

**Comment by Mikki-m8** [comment]
@Tslat

Afaik it's been reported on the AoA Discord as well.

**Comment by Tslat** [comment]
Can confirm, looking into it.

**Comment by ReikaKalseki** [comment]
This is still being reported.

**Comment by Tslat** [comment]
Can confirm

AoA no longer supports 1.7.10, it's a dead version

This can be rectified by downgrading AoA a few versions - though I don't have exact confirmation on which newest version can be used safely

**Comment by brandyyn** [comment]
For anyone finding this thread later on, the bug has been fixed in a fork, so now you can use chromaticraft and AoA together.
https://www.curseforge.com/minecraft/mc-mods/bbrains-umfixes/files/5092506
