### ISSUE TITLE
Mystcraft integration needs review

### ISSUE THREAD

**Issue by keybounce** [ReikaKalseki/Reika_Mods_Issues#19]
This was in the logs today:

[16:33:51] [Client thread/INFO] [FML]: DRAGONAPI: Loading handler for mod Mystcraft
[16:33:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchFieldException: block_decay
[16:33:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.getDeclaredField(Class.java:1953)
[16:33:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler.getBlockInstance(MystCraftHandler.java:59)
[16:33:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler.<init>(MystCraftHandler.java:37)
[16:33:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.ModInteract.ItemHandlers.MystCraftHandler.<clinit>(MystCraftHandler.java:23)
[16:33:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName0(Native Method)

Dragon API 6f
Mystcraft 0.11.5.0

**Comment by Kolatra** [comment]
Does this actually cause any issues in-game?

**Comment by keybounce** [comment]
I don't know.
I don't know what the mystcraft integration is supposed to do.

**Comment by Kolatra** [comment]
It's just blacklisting Reika's fluids from being pages in Mystcraft, so that people can't skip the tech-tree with it. Is it causing any actual lag or anything?

**Comment by ReikaKalseki** [comment]
I thought I fixed this long ago. Are you sure you are using the latest MystCraft and RC?

**Comment by keybounce** [comment]
keybounceMBP:BiomeTweaker michael$ ls ../../mods/Rota*
 6436 ../../mods/RotaryCraft 1.7.10 V6f.jar
keybounceMBP:BiomeTweaker michael$ ls ../../mods/Myst*
 92 ../../mods/MystNEI-Plugin-1.7.10-02.01.00.00.jar
keybounceMBP:BiomeTweaker michael$ ls ../../mods/myst*
2080 ../../mods/mystcraft-1.7.10-0.11.5.00.jar*           56 ../../mods/mystcraft-panels-1.7.10-0.0.0.10.jar*
keybounceMBP:BiomeTweaker michael$ ls ../../mods/Dra*
1528 ../../mods/DragonAPI 1.7.10 V6f.jar
keybounceMBP:BiomeTweaker michael$ 


6f for dragonAPI and rotarycraft
11.5 for mystcraft.

**Comment by keybounce** [comment]
also: 
keybounceMBP:BiomeTweaker michael$ grep decay ../../logs/fml-client-latest.log 
[16:33:51] [Client thread/INFO] [STDERR/DragonAPI]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchFieldException: block_decay
[16:41:22] [Client thread/DEBUG] [NEI-Mystcraft-Plugin/]: Adding decay types to NEI view
[16:41:25] [Client thread/DEBUG] [NEI-Mystcraft-Plugin/]: Removing decay types from NEI view
[16:41:25] [Client thread/DEBUG] [NEI-Mystcraft-Plugin/]: Adding decay types to NEI view
keybounceMBP:BiomeTweaker michael$

**Comment by ReikaKalseki** [comment]
I will look into this.

**Comment by keybounce** [comment]
Hmm ... skip the tech tree with mystcraft liquids? I did not think of that.

This "real-time" on a website is nice.

**Comment by ReikaKalseki** [comment]
This has nothing to do with liquids; this is the decay and instability handling erroring. Can you provide me a link to the MystCraft file you are using?

**Comment by keybounce** [comment]
http://xcompwiz.com/2015/04/18/mystcraft-0-11-5/

**Comment by ReikaKalseki** [comment]
OK, the problem is that he keeps changing his API back and forth. >_<

Fixed and hopefully more stable.
