### ISSUE TITLE
Crash when opening research in Thaumonomicon

### ISSUE THREAD

**Issue by coyotesfrontier** [ReikaKalseki/Reika_Mods_Issues#1913]
Only happens to actual research pages, such as the bedrock goggles of revealing, and not tabs.
Crash Report:
https://pastebin.com/fUxGgBHd

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Garr890354839** [comment]
Fixed?! FIXED?! Funny.


Time: 11/15/18 9:15 PM
Description: Rendering screen

Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
You cannot query an XML data set before reading it from disk!
	at Reika.DragonAPI.Instantiable.IO.XMLInterface.getValueAtNode(XMLInterface.java:162)
	at Reika.DragonAPI.ModInteract.DeepInteract.ReikaThaumHelper$XMLPage.getTranslatedText(ReikaThaumHelper.java:635)
	at thaumcraft.client.gui.GuiResearchRecipe.drawPage(GuiResearchRecipe.java:352)
	at thaumcraft.client.gui.GuiResearchRecipe.genResearchBackground(GuiResearchRecipe.java:281)
	at thaumcraft.client.gui.GuiResearchRecipe.func_73863_a(GuiResearchRecipe.java:236)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**V21c** DragonAPI crash log. If it was fixed, then I would not expect the exact same crashlog.

**Comment by ReikaKalseki** [comment]
I assume I need to explain the concept of releasing an update to you?

Than again, given all your other comments on this site - to me and others - I doubt that is a worthwhile use of my time. You are neither reasonable nor rational enough to justify it.
