### ISSUE TITLE
RC Crash when right clicking machines with Tinker's Tools

### ISSUE THREAD

**Issue by Keepsedge** [ReikaKalseki/Reika_Mods_Issues#1936]
So It's documented to be fixed in v18 however I'm using v21, and I'm still getting crashed when right clicking machines with a Tinker's pickaxe in hand.

Related Mods:
Tinker's Construct
Iguana Tinker Tweaks
RotaryCraft
DragonAPI

It may be worth noting that I keep several Tools next to each other in my hot bar. Typically:
Long Sword, Pickaxe, Spade, Hatchet, Crescent Hammer In that order. Because Tinker's Tools have a right click functionality that will place blocks that are next to the held tool in hand, It's possible that this is part of the problem. (The long sword does not cause crashes that I have noticed, as it has a different right click effect). 

----------------------------------------------------------------------------------------------------------------
Stack Trace:
Time: 9/3/18 1:26 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@590a4706
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by ReikaKalseki** [comment]
#1423, #652, #590, #855, #161, #1358, #1474, #1488, #1565, #1871
