### ISSUE TITLE
[ChC] Crash when looking at elemental caps research in thaumonomicon

### ISSUE THREAD

**Issue by kutschkem** [ReikaKalseki/Reika_Mods_Issues#1946]
I had just researched elemental caps, when I tried to look at it in the thaumonomicon, the game crashed with this crash log:

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 9/10/18 9:15 PM
Description: Rendering screen

Reika.DragonAPI.Exception.MisuseException: DragonAPI or one of its subclasses or methods was used incorrectly!
The current error was caused by the following:
You cannot query an XML data set before reading it from disk!
	at Reika.DragonAPI.Instantiable.IO.XMLInterface.getValueAtNode(XMLInterface.java:162)
	at Reika.DragonAPI.ModInteract.DeepInteract.ReikaThaumHelper$XMLPage.getTranslatedText(ReikaThaumHelper.java:635)
	at thaumcraft.client.gui.GuiResearchRecipe.drawPage(GuiResearchRecipe.java:352)
	at thaumcraft.client.gui.GuiResearchRecipe.genResearchBackground(GuiResearchRecipe.java:281)
	at thaumcraft.client.gui.GuiResearchRecipe.func_73863_a(GuiResearchRecipe.java:236)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.DragonAPI.Instantiable.IO.XMLInterface.getValueAtNode(XMLInterface.java:162)
	at Reika.DragonAPI.ModInteract.DeepInteract.ReikaThaumHelper$XMLPage.getTranslatedText(ReikaThaumHelper.java:635)
	at thaumcraft.client.gui.GuiResearchRecipe.drawPage(GuiResearchRecipe.java:352)
	at thaumcraft.client.gui.GuiResearchRecipe.genResearchBackground(GuiResearchRecipe.java:281)
	at thaumcraft.client.gui.GuiResearchRecipe.func_73863_a(GuiResearchRecipe.java:236)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchRecipe
	Mouse location: Scaled: (249, 125). Absolute: (999, 578)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['kutschkeM'/557, l='MpServer', x=437.97, y=80.62, z=235.23]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 04 - ATG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (54,64,-4), Chunk: (at 6,4,12 in 3,-1; contains blocks 48,0,-16 to 63,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 20085734 game time, 26870047 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntityItemFrame['Item Frame'/512, l='MpServer', x=428.06, y=80.50, z=239.50], EntityItemFrame['Item Frame'/513, l='MpServer', x=428.06, y=80.50, z=238.50], EntitySquid['Squid'/1071379, l='MpServer', x=397.50, y=58.09, z=240.50], EntityManaBurst['Mana Burst'/5729362, l='MpServer', x=495.50, y=68.78, z=293.27], EntityManaBurst['Mana Burst'/5729105, l='MpServer', x=479.50, y=70.30, z=290.50], EntityWitchCat['Raven'/13, l='MpServer', x=482.69, y=81.00, z=192.22], EntityItem['item.item.egg'/1052959, l='MpServer', x=430.94, y=74.13, z=279.91], EntityZombie['Zombie'/1028893, l='MpServer', x=449.50, y=26.00, z=195.50], EntityZombie['Zombie'/169240, l='MpServer', x=453.47, y=68.00, z=258.91], EntityCorporeaSpark['Corporea Spark'/543, l='MpServer', x=471.50, y=77.50, z=248.50], EntitySquid['Squid'/1071375, l='MpServer', x=395.50, y=58.00, z=242.47], EntityCorporeaSpark['Corporea Spark'/544, l='MpServer', x=472.50, y=77.50, z=252.50], EntityGolemBase['Stone Golem'/545, l='MpServer', x=472.28, y=76.00, z=248.78], EntityCorporeaSpark['Corporea Spark'/546, l='MpServer', x=472.50, y=77.50, z=243.50], EntityCorporeaSpark['Corporea Spark'/547, l='MpServer', x=471.50, y=77.50, z=243.50], EntityCorporeaSpark['Corporea Spark'/548, l='MpServer', x=466.50, y=77.50, z=243.50], EntityCorporeaSpark['Corporea Spark'/549, l='MpServer', x=476.50, y=78.75, z=247.50], EntityCorporeaSpark['Corporea Spark'/550, l='MpServer', x=473.50, y=77.50, z=243.50], EntityCorporeaSpark['Corporea Spark'/551, l='MpServer', x=474.50, y=77.50, z=243.50], EntityZombie['Bouncy'/552, l='MpServer', x=478.50, y=76.00, z=246.50], EntityClientPlayerMP['kutschkeM'/557, l='MpServer', x=437.97, y=80.62, z=235.23], EntityMooshroom['Mooshroom'/566, l='MpServer', x=443.53, y=81.00, z=244.52], EntitySpider['Spider'/1117482, l='MpServer', x=481.66, y=71.00, z=294.72], EntityMooshroom['Mooshroom'/577, l='MpServer', x=443.53, y=80.50, z=243.22], EntityItemFrame['Item Frame'/578, l='MpServer', x=428.06, y=80.50, z=240.50], EntityCow['Cow'/584, l='MpServer', x=429.31, y=75.00, z=262.75], EntitySpark['Spark'/585, l='MpServer', x=482.50, y=75.50, z=268.50], EntityBat['Bat'/543044, l='MpServer', x=456.59, y=56.10, z=238.09], EntitySkeleton['Skeleton'/5711899, l='MpServer', x=366.50, y=78.00, z=255.50], EntityZombie['Zombie'/1094208, l='MpServer', x=498.50, y=44.00, z=231.50], EntitySkeleton['Skeleton'/5711878, l='MpServer', x=412.31, y=18.00, z=311.31], EntityManaBurst['Mana Burst'/5728515, l='MpServer', x=483.91, y=66.42, z=284.02], EntitySkeleton['Skeleton'/1094213, l='MpServer', x=498.50, y=44.00, z=232.50], EntityGolemBase['Straw Golem'/600, l='MpServer', x=454.91, y=76.00, z=282.22], EntityPig['Pig'/602, l='MpServer', x=401.47, y=79.00, z=244.47], EntityCreeper['Creeper'/1094218, l='MpServer', x=509.50, y=70.00, z=311.50], EntitySkeleton['Skeleton'/1036884, l='MpServer', x=427.50, y=18.00, z=266.50], EntityManaBurst['Mana Burst'/5729804, l='MpServer', x=485.50, y=68.70, z=290.50], EntityZombie['Zombie'/994896, l='MpServer', x=419.50, y=45.00, z=244.50], EntitySpark['Spark'/615, l='MpServer', x=479.50, y=74.50, z=273.50], EntityChicken['Chicken'/616, l='MpServer', x=431.53, y=74.00, z=281.88], EntityChicken['Chicken'/617, l='MpServer', x=430.88, y=74.00, z=278.88], EntitySpark['Spark'/634, l='MpServer', x=485.50, y=74.50, z=273.50], EntityItem['item.item.egg'/923506, l='MpServer', x=430.54, y=74.02, z=282.20], EntitySpider['Spider'/817289, l='MpServer', x=474.00, y=58.00, z=240.00], EntityCreeper['Creeper'/913800, l='MpServer', x=489.50, y=49.00, z=248.50], EntityCreeper['Creeper'/1051288, l='MpServer', x=512.50, y=73.00, z=314.50], EntitySpark['Spark'/649, l='MpServer', x=479.50, y=73.31, z=290.50], EntitySquid['Squid'/1072287, l='MpServer', x=395.50, y=59.00, z=234.50], EntityBat['Bat'/5712071, l='MpServer', x=406.57, y=32.75, z=264.22], EntitySkeleton['Skeleton'/1028763, l='MpServer', x=471.50, y=35.00, z=221.50], EntitySpider['Spider'/1124743, l='MpServer', x=395.50, y=77.00, z=231.50], EntitySkeleton['Skeleton'/834192, l='MpServer', x=499.50, y=43.00, z=312.50], EntitySkeleton['Skeleton'/1110668, l='MpServer', x=501.50, y=90.00, z=224.50], EntityBat['Bat'/5712074, l='MpServer', x=447.65, y=14.44, z=275.43], EntityVillager['Villager'/414, l='MpServer', x=513.28, y=83.00, z=213.69], EntityCow['Cow'/671, l='MpServer', x=513.50, y=74.00, z=268.72], EntityVillager['Villager'/415, l='MpServer', x=515.38, y=83.00, z=211.31], EntityVillager['Villager'/416, l='MpServer', x=513.38, y=83.00, z=211.50], EntityBat['Bat'/913837, l='MpServer', x=462.90, y=49.42, z=219.64], EntityVillager['Villager'/417, l='MpServer', x=516.69, y=83.00, z=213.69], EntityBat['Bat'/913836, l='MpServer', x=466.26, y=48.87, z=218.28], EntityVillager['Villager'/418, l='MpServer', x=514.16, y=83.00, z=213.69], EntitySpark['Spark'/675, l='MpServer', x=488.50, y=71.50, z=296.50], EntityVillager['Villager'/419, l='MpServer', x=514.94, y=83.00, z=212.88], EntityBat['Bat'/913838, l='MpServer', x=447.51, y=51.72, z=214.20], EntityVillager['Villager'/420, l='MpServer', x=516.69, y=83.00, z=212.31], EntitySpark['Spark'/677, l='MpServer', x=489.50, y=71.50, z=299.50], EntityVillager['Villager'/421, l='MpServer', x=516.69, y=83.00, z=211.31], EntitySpark['Spark'/678, l='MpServer', x=482.50, y=71.50, z=299.50], EntityVillager['Villager'/422, l='MpServer', x=512.47, y=83.00, z=213.22], EntityBat['Bat'/913835, l='MpServer', x=445.25, y=51.10, z=221.09], EntityVillager['Villager'/423, l='MpServer', x=515.84, y=83.00, z=213.69], EntityBat['Bat'/913834, l='MpServer', x=457.63, y=49.24, z=220.94], EntitySpark['Spark'/680, l='MpServer', x=484.50, y=71.50, z=299.50], EntityVillager['Villager'/424, l='MpServer', x=515.91, y=83.00, z=212.25], EntityDemon['Demon'/425, l='MpServer', x=497.94, y=84.00, z=219.09], EntitySpark['Spark'/682, l='MpServer', x=485.50, y=73.31, z=290.50], EntityCreeper['Creeper'/1011109, l='MpServer', x=502.50, y=44.00, z=273.50], EntityCreeper['Creeper'/1011107, l='MpServer', x=488.50, y=47.00, z=257.50], EntitySquid['Squid'/1072290, l='MpServer', x=390.50, y=58.00, z=238.50], EntitySquid['Squid'/1072291, l='MpServer', x=397.28, y=59.00, z=238.47], EntityBat['Bat'/913848, l='MpServer', x=435.72, y=28.99, z=226.85], EntityBat['Bat'/913840, l='MpServer', x=461.49, y=49.54, z=221.51], EntitySquid['Squid'/913856, l='MpServer', x=392.97, y=58.88, z=236.50], EntityItemFrame['Item Frame'/207, l='MpServer', x=482.94, y=78.50, z=188.50], EntityItemFrame['Item Frame'/208, l='MpServer', x=484.06, y=78.50, z=188.50], EntityCreeper['Creeper'/1130483, l='MpServer', x=419.50, y=32.00, z=309.50], EntityCreeper['Creeper'/1130482, l='MpServer', x=417.50, y=32.00, z=309.50], EntityManaBurst['Mana Burst'/5728944, l='MpServer', x=483.50, y=66.50, z=278.47], EntitySkeleton['Skeleton'/1130479, l='MpServer', x=508.50, y=46.00, z=284.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1347511480 bytes (1285 MB) / 3370352640 bytes (3214 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 50925, allocated: 0, tallocated: 16
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	ExtendedPotions{1.2} [Extended Potions] (ExtendedPotions-MC1.7.10-1.2.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	AccidentallyCircumstantialEvents{1.12.11} [Accidentally Circumstantial Events] (accidentallycircumstantialevents-1.12.11.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	AetherAspects{Alpha 1.7.10-1.2} [Aether Aspects] (AetherAspects-1.7.10-1.2.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (AM2-1.4.0.009-Dev.jar) 
	UCHIJAAAA	AM2PlantFix{1.0} [Ars Magica 2 Plant Fix] (AM2PlantFix-1.0.jar) 
	UCHIJAAAA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHIJAAAA	arcanearteries{5} [Arcane Arteries] (ArcaneArteries0.7.2.jar) 
	UCHIJAAAA	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
	UCHIJAAAA	aura{unspecified} [Aura Cascade] (AuraCascade-557.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJAAAA	Mystcraft{0.12.3.04} [Mystcraft] (mystcraft-1.7.10-0.12.3.04.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	DragonAPI{v21c} [DragonAPI] (DragonAPI 1.7.10 V21c.jar) 
	UCHIJAAAA	ChromatiCraft{v21b} [ChromatiCraft] (ChromatiCraft 1.7.10 V21b.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.13.jar) 
	UCHIJAAAA	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-3.1a.jar) 
	UCHIJAAAA	farseek{2.0.1} [Farseek] (Farseek-1.7.10-2.0.1.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCHIJAAAA	fovcontrol{1.7.10-1.2.1} [FovControl] (FovControl-1.7.10-1.2.1.jar) 
	UCHIJAAAA	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCHIJAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAA	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
	UCHIJAAAA	ImLookingAtBlood{1.1} [I'm Looking At Blood] (ImLookingAtBlood-1.7.2-1.1a.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	launchgui{1.7.10-2.0-18} [LaunchGUI] (LaunchGui-1.7.10-2.0-18-client.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UCHIJAAAA	ODL{1.7.10-1} [Ore Dictionary Log] (ODL-1.7.10-1.0.jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	Quadrum{1.2.0} [Quadrum] (Quadrum-1.7.10-1.2.0.B13-universal.jar) 
	UCHIJAAAA	realtimeclock{1.7.10-0.1} [Real Time Clock] (RealTimeClock-1.7.10-0.2.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAAAA	Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-35.jar) 
	UCHIJAAAA	squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAAAA	streams{0.3.3} [Streams] (Streams-1.7.10-0.3.3.jar) 
	UCHIJAAAA	TCBotaniaExoflame{1.0} [TCBotaniaExoflame] (TCBotaniaExoflame-1.7.10-1.4.jar) 
	UCHIJAAAA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJAAAA	yampst{1.3.5} [YAMPST] (Yampst-Simply Magic-1.0.0.jar) 
	UCHIJAAAA	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@44683483) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@9518516) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.4-329
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7800 Series GL version 4.5.13506 Compatibility Profile Context 23.20.15002.11, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (4)
```

**Comment by ReikaKalseki** [comment]
#1941 #1913
