### ISSUE TITLE
IndexOutOfBoundsException: Index: 382, Size: 383 [Chromaticraft] [Singleplayer]

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#1962]
[crash-2018-09-15_17.45.17-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/2386106/crash-2018-09-15_17.45.17-client.txt)

Happened recently after my new fabricators where placed.

**Comment by lAimBotl** [comment]
not sure how related this is, but I got this in chat:


"[18:15:22] [Client thread/INFO]: [CHAT] 
[18:15:22] [Client thread/ERROR]: DRAGONAPI ERROR: Tile Entity Crystal Repeater @ DIM0: -232, 76, -1336 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_147438_o(World.java:2526)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.Data.Immutable.WorldLocation.getTileEntity(WorldLocation.java:123)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.Data.Immutable.WorldLocation.getTileEntity(WorldLocation.java:118)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Magic.Network.TargetData.<init>(TargetData.java:33)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Auxiliary.ChromaAux.getBeamColorMixes(ChromaAux.java:364)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Auxiliary.ChromaFX.drawLeyLineParticles(ChromaFX.java:228)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.Base.TileEntity.CrystalTransmitterBase.updateEntity(CrystalTransmitterBase.java:69)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.Networking.TileEntityCrystalRepeater.updateEntity(TileEntityCrystalRepeater.java:91)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:496)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:15:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)"

**Comment by OvermindDL1** [comment]
```java
java.lang.IndexOutOfBoundsException: Index: 382, Size: 383
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at net.minecraft.world.World.func_147438_o(World.java:2524)
        at Reika.DragonAPI.Instantiable.Data.Immutable.WorldLocation.getTileEntity(WorldLocation.java:123)
```
What the ever-living-heck?  How does the world TE list change mid-iteration...
```java
...
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Especially when it is running on the main thread.  What is touching TE's at all on side-threads.  Someone somewhere is calling a world function (even `world.getTileEntity` can mutate the tile list for example) from another thread, which is bad bad bad...  Good luck finding the culprit though...  I'm not even sure who would write world-accessing-anything on non-main threads...  o.O

(MC is *very* not thread safe in almost all of its data...)

**Comment by ReikaKalseki** [comment]
This is not my doing.
