### ISSUE TITLE
"Invalid casting recipe was going to be added" on game startup

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#1976]
"Contact Reika immediately!"
Im running 
  Forge 10.13.4.1614
  DragonAPI and Chromaticraft V21b
  Jre1.8.0_181 with start Parameter -XX:+UseG1GC
  and a Ton of other Mods that are listet in my Log !

The last time it worked before this crash occured i was changing many configuration files of all mods in the pack, but i don't have a history of what i changed from when it didn't occur..

Full Log: [https://1drv.ms/t/s!An8Z2izmI8NLgpY3hwg0tiEGoHVTaw](https://1drv.ms/t/s!An8Z2izmI8NLgpY3hwg0tiEGoHVTaw)

```
> Include the following information:
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.validate(CastingRecipe.java:385)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.addRecipe(RecipesCastingTable.java:887)
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.RecipesCastingTable.addPostLoadRecipes(RecipesCastingTable.java:839)
> 	at Reika.ChromatiCraft.ChromaRecipes.addPostLoadRecipes(ChromaRecipes.java:102)
> 	at Reika.ChromatiCraft.ChromatiCraft.postload(ChromatiCraft.java:707)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
> 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
> 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
> 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
> 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> Caused by: java.lang.IllegalArgumentException: Null-item output
> 	at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.validate(CastingRecipe.java:369)
> 	... 48 more
```

**Comment by ReikaKalseki** [comment]
#1923
