### ISSUE TITLE
DragonAPI Immediately crashes my server (v21c) (Solved) [Fastcraft Crashes With DragonAPI]

### ISSUE THREAD

**Issue by rhys19** [ReikaKalseki/Reika_Mods_Issues#2003]
So i wanted to install Reactorcraft but when i installed DragonAPI right after it crashes my server.

any idea why? i don't have ThaumicInfusion

here is the crash log:
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
[12:43:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[12:43:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[12:43:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[12:43:10] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[12:43:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_191, running on Windows Server 2016:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_191
[12:43:11] [main/INFO] [FML]: [AppEng] Core Init
[12:43:11] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/ERROR] [FML]: Coremod DepLoader: Unable to class load the plugin xreliquary.common.asm.DepLoader
java.lang.ClassNotFoundException: xreliquary.common.asm.DepLoader
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
        at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
[12:43:12] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:43:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:43:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:43:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:43:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:43:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [Aroma1997Core]: Finished data injection.
[12:43:14] [main/INFO] [Aroma1997Core]: Finished data injection.
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [IC2-core]: Loaded library EJML-core-0.26.jar.
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:15] [main/INFO] [FML]: Java Version: [8, 0, 191]
[12:43:15] [main/INFO] [FML]: Heap memory allocation: 8192000000
[12:43:15] [main/INFO] [FML]: 9 Java arguments present: [-XX:+CMSIncrementalPacing, -XX:ParallelGCThreads=2, -Xmx8192M, -Xms8192M, -XX:MaxHeapFreeRatio=10, -XX:PermSize=256m, -XX:+UseParNewGC, -XX:MinHeapFreeRatio=5, -XX:+CMSClassUnloadingEnabled]
[12:43:16] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: null: Registered 113 ASM handlers, of which 113 are enabled.
[12:43:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[12:43:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[12:43:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[12:43:16] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[12:43:16] [main/INFO] [malisiscore]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[12:43:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[12:43:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[12:43:16] [main/INFO] [FML]: DRAGONAPI: OPTIFINE not detected.
[12:43:16] [main/INFO] [FML]: DRAGONAPI: LITELOADER not detected.
[12:43:16] [main/INFO] [FML]: DRAGONAPI: FASTCRAFT not detected.
[12:43:16] [main/INFO] [FML]: DRAGONAPI: VIVE not detected.
[12:43:16] [main/INFO] [FML]: DRAGONAPI: COLOREDLIGHTS not detected.
[12:43:16] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Running patcher MOBTARGETEVENT [net.minecraft.world.World/ahb]
[12:43:16] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied MOBTARGETEVENT [net.minecraft.world.World/ahb] ASM handler!
[12:43:16] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Running patcher SETBLOCKLIGHT [net.minecraft.world.World/ahb]
A problem occurred running the Server launcher.[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.reflect.Method.invoke(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.getDeclaredMethods0(Native Method)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.getMethod0(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.getMethod(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   ... 6 more
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.ClassLoader.loadClass(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.ClassLoader.loadClass(Unknown Source)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   ... 13 more
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: Reika.DragonAPI.Exception.ASMException$NoSuchASMMethodInstructionException: Error ASMing method func_147465_d (IIILnet/minecraft/block/Block;II)Z in net/minecraft/world/World:
Could not find an instruction for a method call to net/minecraft/world/World's func_147451_t (III)Z:
Found method calls:
    INVOKEVIRTUAL net/minecraft/world/World.func_72964_e (II)Lnet/minecraft/world/chunk/Chunk; * Owner match
    INVOKEVIRTUAL net/minecraft/world/chunk/Chunk.func_150810_a (III)Lnet/minecraft/block/Block;
    INVOKESTATIC net/minecraftforge/common/util/BlockSnapshot.getBlockSnapshot (Lnet/minecraft/world/World;IIII)Lnet/minecraftforge/common/util/BlockSnapshot;
    INVOKEVIRTUAL java/util/ArrayList.add (Ljava/lang/Object;)Z
    INVOKEVIRTUAL net/minecraft/world/chunk/Chunk.func_150807_a (IIILnet/minecraft/block/Block;I)Z
    INVOKEVIRTUAL java/util/ArrayList.remove (Ljava/lang/Object;)Z
    INVOKEVIRTUAL net/minecraft/profiler/Profiler.func_76320_a (Ljava/lang/String;)V
    INVOKESTATIC fastcraft/Hooks.d (Lnet/minecraft/world/World;III)Z
    INVOKEVIRTUAL net/minecraft/profiler/Profiler.func_76319_b ()V
    INVOKEVIRTUAL net/minecraft/world/World.markAndNotifyBlock (IIILnet/minecraft/world/chunk/Chunk;Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;I)V * Owner match

[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getNthMethodCall(ReikaASMHelper.java:610)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getFirstMethodCall(ReikaASMHelper.java:594)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reika.DragonAPI.ASM.Patchers.SetBlockLight.apply(SetBlockLight.java:39)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reika.DragonAPI.ASM.Patchers.Patcher.apply(Patcher.java:60)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reika.DragonAPI.ASM.DragonAPIClassTransformer.transform(DragonAPIClassTransformer.java:100)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[12:43:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   ... 15 more
Server process finished
Press any key to continue . . .
```

**Comment by rhys19** [comment]
Also note it didn't create a crash report txt file nor do i have xreliquary installed

**Comment by rhys19** [comment]
although when i take out DragonAPI temporairly it works until rotatory craft Crashes and says Required Mods: DragonAPI

I put DragonAPI back in boom immediate crash

that may give you guys some more options to test.
if i need to test anything on my end let me know ;)

**Comment by rhys19** [comment]
it kinda looks like CoFH 

```
[13:22:39] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:77)
```
i'l try removing thermal expansion,etc

**Comment by rhys19** [comment]
welp that didn't work ;(

**Comment by rhys19** [comment]
DragonAPI is conflicting with something because when i take out all mods except for dragon api it works

**Comment by rhys19** [comment]
it's fastcraft!

**Comment by rhys19** [comment]
my server works now!!! :D i solved my own problem yay

**Comment by OvermindDL1** [comment]
> it kinda looks like CoFH

That line wasn't in your above log.  Either way that shouldn't be it.

> Also note it didn't create a crash report txt file nor do i have xreliquary installed

I don't think DragonAPI should be one of those detected things so this is actually surprising...

What is your complete mod list?  Something seems to be trying to depend on reliquary that shouldn't be (and dragonapi might be fulfilling enough of 'some' api that it thinks it is there)...

> it's fastcraft!

Oh hey, this is still surprising!  fastcraft should not be depending on *any* mod!  o.O

Not DragonAPI's issue then, and I'd say this should be reported to fastcraft, but I'm unsure what it's doing to cause this or if it is still even being updated...  ^.^;

**Comment by OvermindDL1** [comment]
As an interesting tidbit, the xreliquary error and fastcraft comes up a lot, some people think it's because of railcraft or chisel2 but not certain...

**Comment by rhys19** [comment]
hmm yeah i removed fastcraft and i booted faster but then it said a whole bunch of other errors popped up. it got a little further but then it crashed again.

**Comment by rhys19** [comment]
that modlist might be a little difficult xD i uhh install a little too many mods sometimes.

**Comment by rhys19** [comment]
o.o wait i might've fixed it.

**Comment by OvermindDL1** [comment]
> o.o wait i might've fixed it.

Ooo?  What was it?

**Comment by rhys19** [comment]
> Ooo? What was it?



i removed these mods:
```
AgriCraft-1.7.10-1.4.0-beta-2-1.7.10.jar
witchery-1.7.10-0.24.1.jar
binnie-mods-2.0-pre14.jar
AOBD-2.8.1.jar
forestry_1.7.10-3.6.6.24.jar
fastcraft-1.21.jar
gendustry-1.5.2.107-mc1.7.10.jar
magicbees-1.7.10-2.3.5.jar
```
then it finally decided to work

**Comment by OvermindDL1** [comment]
Never heard of AOBD.  I know gendustry, magicbees, binnie-mods, and forestry have occasional random/weird issues.  Never seen issues with agricraft or witchery...

**Comment by rhys19** [comment]
AOBD is Another One Bites the Dust https://minecraft.curseforge.com/projects/another-one-bites-the-dust

**Comment by rhys19** [comment]
yeah. i kinda likes Agricraft it helps the plants grow ;) but if it crashes then i guess it's worth it for my rf power ;)

because i like nuclear craft ;) it's realistic better then IC2,or Big Reactors.

**Comment by ReikaKalseki** [comment]
Update FastCraft.
