### ISSUE TITLE
Broken Structure Bypass

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#2012]
Just tried the Bypass Structure thing, and game crash. Not sure if a one-time thing, or not, but here is the essential bits:

Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at Reika.ChromatiCraft.World.Dimension.Structure.MusicPuzzleGenerator.openStructure(MusicPuzzleGenerator.java:143)
	at Reika.ChromatiCraft.Base.DimensionStructureGenerator.forceOpen(DimensionStructureGenerator.java:259)
	at Reika.ChromatiCraft.Block.Dimension.Structure.BlockStructureDataStorage$TileEntityStructurePassword.checkPassword(BlockStructureDataStorage.java:227)
	at Reika.ChromatiCraft.Block.Dimension.Structure.BlockStructureDataStorage$TileEntityStructurePassword.onRightClick(BlockStructureDataStorage.java:136)
	at Reika.ChromatiCraft.Block.Dimension.Structure.BlockStructureDataStorage.func_149727_a(BlockStructureDataStorage.java:84)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Before you ask, yes, I was in a dimensional puzzle, the music one for Kuro.
Also, is there a way of exiting Proxima without taking a fatal hit?

**Comment by voidsong-dragonfly** [comment]
Continue going the same way you went in.

**Comment by ReikaKalseki** [comment]
This is another case of a structure's blocks persisting after the structure data has been deleted, due to an incomplete reset.

**Comment by Garr890354839** [comment]
> This is another case of a structure's blocks persisting after the structure data has been deleted, due to an incomplete reset.

but I only just entered it, never having unloaded the world

**Comment by Garr890354839** [comment]
> Continue going the same way you went in.

That just takes me back into Proxima.
