### ISSUE TITLE
Exception thrown with Draconium Flakes and Draconium ore not valid in Extractor

### ISSUE THREAD

**Issue by clubpetey** [ReikaKalseki/Reika_Mods_Issues#202]
MC 1.7.10
Forge 1388
RotC: 7f

I tried to process Draconium Ore (from Draconic Evolution) in the Extractor.  NEI shows an Extractor recipe for the ore, but you cannot actually place the ore in the extractor.  Previously this type of error was due to AOBD interfering with RotaryCraft, however, RotaryCraft is disabled in the AOBD config.

Next I tried to give my self a stack of Draconium Flakes using NEI.  Clicking on the flakes in NEI caused the following exception

```
java.lang.IndexOutOfBoundsException: Index: 8, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:604) ~[?:1.7.0_25]
        at java.util.ArrayList.get(ArrayList.java:382) ~[?:1.7.0_25]
        at java.util.Collections$UnmodifiableList.get(Collections.java:1211) ~[?:1.7.0_25]
        at Reika.RotaryCraft.ModInterface.ItemCustomModOre.getExtractType(ItemCustomModOre.java:99) ~[ItemCustomModOre.class:?]
        at Reika.RotaryCraft.ModInterface.ItemCustomModOre.getOreType(ItemCustomModOre.java:94) ~[ItemCustomModOre.class:?]
        at Reika.RotaryCraft.ModInterface.ItemCustomModOre.func_77653_i(ItemCustomModOre.java:80) ~[ItemCustomModOre.class:?]
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
        at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
        at codechicken.nei.NEIServerUtils.givePlayerItem(NEIServerUtils.java:189) ~[NEIServerUtils.class:?]
        at codechicken.nei.NEISPH.handleGiveItem(NEISPH.java:134) ~[NEISPH.class:?]
        at codechicken.nei.NEISPH.handlePacket(NEISPH.java:33) ~[NEISPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:117) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) ~[PacketCustom$CustomInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) ~[PacketCustom$CustomInboundHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Help is always appreciated.

**Comment by TomeWyrm** [comment]
Disable Another One Bites The Dust's Rotarycraft integration in the config (there's more than one place, get them all).

**Comment by ReikaKalseki** [comment]
27-plicate and other mod's end.

**Comment by clubpetey** [comment]
All referenced to RotaryCraft are already disabled in the AOBD config, also, I looked for referenced to Draconic Evolution in AOBD, but there are none. 

Still cannot add Draconium Ore to extractor, all other ores seem to work fine.

**Comment by TomeWyrm** [comment]
Then use the RotaryCraft_CustomExtracts.cfg to add Draconium to the extractor, and try again.
