### ISSUE TITLE
crash from CC village structures in superflat

### ISSUE THREAD

**Issue by Garr890354839** [ReikaKalseki/Reika_Mods_Issues#2022]
java.lang.NullPointerException: Exception getting block type in world
	at Reika.ChromatiCraft.Auxiliary.ChromaAux.generateLootChest(ChromaAux.java:593)
	at Reika.ChromatiCraft.World.VillagersFailChromatiCraft$ChromaVillagePiece.generateLootChestFixed(VillagersFailChromatiCraft.java:85)
	at Reika.ChromatiCraft.World.VillagersFailChromatiCraft$WoodenChromaStructure.generate(VillagersFailChromatiCraft.java:786)
	at Reika.DragonAPI.Instantiable.Worldgen.VillageBuilding$VillagePiece.func_74875_a(VillageBuilding.java:148)
... 16 more ... 
	at Reika.DragonAPI.Instantiable.Worldgen.VillageBuilding$VillagePiece.tryPlaceBlock(VillageBuilding.java:202)
	at Reika.DragonAPI.Instantiable.Worldgen.VillageBuilding$VillagePiece.placeBlockAtFixedPosition(VillageBuilding.java:222)
	at Reika.DragonAPI.Instantiable.Worldgen.VillageBuilding$VillagePiece.placeBlockAtFixedPosition(VillageBuilding.java:218)
	at Reika.DragonAPI.Instantiable.Worldgen.VillageBuilding$VillagePiece.placeBlockAtFixedPosition(VillageBuilding.java:226)
	at Reika.ChromatiCraft.World.VillagersFailChromatiCraft$WoodenChromaStructure.generate(VillagersFailChromatiCraft.java:388)
	at Reika.DragonAPI.Instantiable.Worldgen.VillageBuilding$VillagePiece.func_74875_a(VillageBuilding.java:148)
... 21 more

Full details can be found here: https://pastebin.com/VnjpXkgs

Maybe consider removing the Village Replenisher, or completely rewrite the Villager AI?

**Comment by ReikaKalseki** [comment]
The Village Replenisher has nothing to do with any of this.

Additionally, this is an old issue that is not really fixable.

**Comment by ReikaKalseki** [comment]
Fixed.
