### ISSUE TITLE
DragonAPI 22b crashes with Applied Energistics rv3 beta 6 the client

### ISSUE THREAD

**Issue by zetti68** [ReikaKalseki/Reika_Mods_Issues#2023]
Hello Reika,
I opened the GUI of AE pattern terminal and put an item into a slot. The client crashes with a StackOverflowError in a multiplayer game after this action. The server did not crash.

The old version of DragonAPI (21c) was working without problems with same version of applied energistics.

java.lang.StackOverflowError: Rendering screen
	at appeng.container.implementations.ContainerPatternTerm.isSlotEnabled(ContainerPatternTerm.java:338)
	at appeng.container.slot.SlotPatternTerm.isEnabled(SlotPatternTerm.java:78)
	at appeng.container.slot.SlotPatternTerm.func_75211_c(SlotPatternTerm.java:59)
	at Reika.DragonAPI.Instantiable.Event.SlotEvent$AddToSlotEvent.fire(SlotEvent.java:51)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java)
	at appeng.container.slot.AppEngSlot.clearStack(AppEngSlot.java:70)
	at appeng.container.slot.SlotPatternTerm.func_75211_c(SlotPatternTerm.java:63)
	at Reika.DragonAPI.Instantiable.Event.SlotEvent$AddToSlotEvent.fire(SlotEvent.java:51)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java)
	at appeng.container.slot.AppEngSlot.clearStack(AppEngSlot.java:70)
	at appeng.container.slot.SlotPatternTerm.func_75211_c(SlotPatternTerm.java:63)
	at Reika.DragonAPI.Instantiable.Event.SlotEvent$AddToSlotEvent.fire(SlotEvent.java:51)
...

**Comment by ReikaKalseki** [comment]
Fixed.
