### ISSUE TITLE
AutoCrafting unit crashes AE

### ISSUE THREAD

**Issue by Optimoos** [ReikaKalseki/Reika_Mods_Issues#203]
When I connect an autocrafting unit to AE, the inventory of the AE system disappears from terminals, essentially taking the system offline. It requires a server restart to recover. RotaryCraft V7F, AE2 R2 stable 10. Also Extra Cells and AE2 Stuff. Other AutoCrafting unit issues with AE are marked as fixed, as this is still occurring I'm under the impression that it's a new/different issue. Furthermore, if I try to work around the issue by placing an ME interface on top of the AutoCrafting unit, when the unit pulls ingredients from the interface it is doing so in such a way that the interface ingredients do not get replenished. The following output appears on the server console:

[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException: Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader$ActionSource cannot be cast to appeng.api.networking.security.MachineSource
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.me.storage.NetworkInventoryHandler.testPermission(NetworkInventoryHandler.java:155)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.me.storage.NetworkInventoryHandler.extractItems(NetworkInventoryHandler.java:210)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.api.storage.MEMonitorHandler.extractItems(MEMonitorHandler.java:149)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader.removeItem(MESystemReader.java:125)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.getAvailableIngredients(TileEntityAutoCrafter.java:448)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.tryCrafting(TileEntityAutoCrafter.java:422)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.attemptSlotCrafting(TileEntityAutoCrafter.java:365)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.triggerCraftingCycle(TileEntityAutoCrafter.java:321)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.PacketHandlerCore.handleData(PacketHandlerCore.java:571)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper$PacketObj.handleServer(ReikaPacketHelper.java:1599)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:152)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:139)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[01:26:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[01:28:36] [Server thread/INFO] [FML]: Tile Entity AutoCrafting Unit @ DIM0: -420, 77, 704 is throwing class java.lang.ClassCastException on update: Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader$ActionSource cannot be cast to appeng.api.networking.security.MachineSource
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException: Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader$ActionSource cannot be cast to appeng.api.networking.security.MachineSource
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.me.storage.NetworkInventoryHandler.testPermission(NetworkInventoryHandler.java:155)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.me.storage.NetworkInventoryHandler.injectItems(NetworkInventoryHandler.java:95)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.api.storage.MEMonitorHandler.injectItems(MEMonitorHandler.java:86)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader.addItem(MESystemReader.java:151)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.injectItems(TileEntityAutoCrafter.java:270)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.updateEntity(TileEntityAutoCrafter.java:243)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:428)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[01:28:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by TomeWyrm** [comment]
Reika is working on v8, so some (or all... I really don't feel like digging through the issue log right this moment) of the issues that are fixed are not currently available to the public.

I believe this is one of the more recently reported AE issues, and has been fixed. But you won't be able to see it until v8 releases.

**Comment by Optimoos** [comment]
Thanks for the information, I'll wait for v8 to see how things are.

**Comment by ReikaKalseki** [comment]
Try AE rv2 b8. Does it work? If so, AE just changed its API incompatibly.

**Comment by Optimoos** [comment]
Works fine with AE2 RV2 build 8.

Edit to add: However I went back to build 10 in the single player world I did this test in and it's working fine. It's possible the problem exists on my server somehow?

Edit 2: Copied the world locally and the issue happens. Going back to RV2 build 8 doesn't help with that world. Is this world just broken? Any ideas whether or not I might be able to fix it?

**Comment by ReikaKalseki** [comment]
I have no idea.

**Comment by Optimoos** [comment]
So, I got around the issue by attaching the autocrafting unit to a subnetwork supplied by an interface and storage bus. This pulls and resupplies the inventory fine, and AE doesn't crash when using the autocrafting unit.

At this point I figured it must be something else on my AE network causing an interaction and crash. I hunted through everything, and was able to reproduce the crash once I attached the security terminal to the network, so I think that's the culprit. Hope that helps.

**Comment by ReikaKalseki** [comment]
Closed until reproduced.

**Comment by Optimoos** [comment]
Here are the simplest steps I can follow to reproduce this issue.

Clean install, using nothing more than:
- Forge 1492
- DragonAPI v7f
- RotaryCraft v7f
- AE2 R2 stable 10
- CodeChickenCore 1.0.7.47
- NEI 1.0.5.111
- No config changes

Doing the following will cause the issue.
1. Create a new world, creative mode, superflat.
2. Place a creative energy cell, drive, 64k storage unit in the drive, attach a fluix cable, attach an ME crafting terminal to the cable along with a security terminal.
3. Give yourself a few stacks of HSLA steel and some autocrafting patterns. Create crafting table recipes for base panels and shaft units. Throw the HSLA into the AE system.
4. Place a lever, DC Electric Engine, and autocrafting unit. **If you place the autocrafting unit next to an existing fluix cable, it will not connect.** However, if you place cable down next to the autocrafting unit once it is placed, it will connect.
5. Insert the crafting patterns into the autocrafting unit. Try to request one. Nothing will happen.
6. Return to the AE terminal. **You may see the inventory of the system via the terminal, but it is not accessible.** Trying to remove something from the AE will make this more obvious as the inventory then disappears.
7. Nothing in-world that I've tried will recover the AE system. However, if you Save & Exit, then come back into the world, everything will be fine again until you try to craft something on the autocrafting unit. **The fluix cable may disconnect itself from the Autocrafting Unit upon world reload**.

I can only assume that the cable disconnections from the Autocrafting unit are part of the security API and the autocrafting unit interacting in a successful fashion to prevent the autocrafting unit from being on the network. However, as I pointed out above, you can remove the cable and place it down again, and it will connect, at which point the failure will occur.

Let me know if I can provide any more details.

**Comment by ReikaKalseki** [comment]
I just updated the AE API in my dev environment, and only one code change was required, (a new method in CC's ItemVoidCell), so whatever it is, it is not a version issue.

**Comment by Twitchh** [comment]
tested this myself on version 8d after having the issue on my server. The issue only arrises with the security terminal attached, without the security terminal the autocrafter works as intended. a get around for this is then just use the autocrafter in a sub network.

**Comment by ReikaKalseki** [comment]
I never use security terminals...probably why I could not reproduce it.

**Comment by Optimoos** [comment]
Security terminals are required for any wireless functionality in AE2, so while I don't use them for anything else, I do use them to provide wireless and that's where this issue crops up.

**Comment by ReikaKalseki** [comment]
Looking at the code, there is nothing the Autocrafter does (or even can) specify regarding security. There is a "securityBreak()" method, but that is only called by AE to break the machine, something I just left empty (so a rejected machine remains unbroken).
