### ISSUE TITLE
[Chromaticraft] ConcurrentModificationException on getNearestPylonSpawn()

### ISSUE THREAD

**Issue by Darkos333** [ReikaKalseki/Reika_Mods_Issues#2078]
I wasnt doing anything special, just walking around my base, and got this crash:

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_144]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_144]
	at Reika.ChromatiCraft.World.IWG.PylonGenerator.getNearestPylonSpawn(PylonGenerator.java:298) ~[PylonGenerator.class:?]
	at Reika.ChromatiCraft.Auxiliary.Render.FullScreenOverlayRenderer.renderPylonAura(FullScreenOverlayRenderer.java:132) ~[FullScreenOverlayRenderer.class:?]
	at Reika.ChromatiCraft.Auxiliary.Render.ChromaOverlays.renderHUD(ChromaOverlays.java:182) ~[ChromaOverlays.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1889_ChromaOverlays_renderHUD_Pre.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895) [GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:241) [GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:117) [GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1420) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

[Full log](https://gist.github.com/Darkos333/7ea445936004604d53016dd949f14555)

**Comment by ReikaKalseki** [comment]
This is not a new issue, and is due to interference from some external source, and only affects a tiny fraction of people.

**Comment by Darkos333** [comment]
Ohhh, I just realized something. This gets called to render pylon aura on the screen - but my base is far enough from pylons so I am not under their effect while in base. This is really strange...

**Comment by ReikaKalseki** [comment]
Even when not near a pylon, the render code needs to run to actually *check* that.

**Comment by Darkos333** [comment]
Ah, I see. I kinda assumed render code relies on some sort of observer pattern instead of polling... my bad.

**Comment by ReikaKalseki** [comment]
"observer pattern"?

**Comment by OvermindDL1** [comment]
He probably meant something like a division tree, like an octree or so to test for nearby pylons only instead of needing to iterate an entire list.  The useful thing about those is you only need to test again when your assigned tree node changes, which is super rare and thus very efficient.

**Comment by Darkos333** [comment]
Erm... nope, thats not what I meant.

Instead of polling on every render tick (which isnt very CPU-friendly) you could make the client-side pylon indirectly notify the renderer that it should render the aura effect.

The pylon tracks nearby players anyway, so when Steve is close enough the pylon just sets necessary aura state on some helper object, lets call it PlayerState. Now the Renderer no longer needs to actively search for Pylons every render tick, it dosent even need to know what Pylon is - it just checks the PlayerState.
You could even add some AuraRenderingController which would own and hide both Renderer and PlayerState - making some poor man's MVC out of this :)

**Comment by OvermindDL1** [comment]
As long as it is run client only and access the local player directly for the location information then it wouldn't be too costly, though still less efficient than a division tree.

**Comment by Darkos333** [comment]
Ah, I overlooked that entity tracking is obviously done on server-side. Foolish me. Ultimately the notification could be sent trough network, but that sounds like an overkill.

My point is: polling is bad, especially if the operation you perform is significantly more complex than O(1). And on top of that render ticks have much higher frequency than game ticks, so you end up checking the same thing multiple times before the pylon proximity had even a chance to actually change.

Perhaps we just need a different notification source. If not the client-side pylon, then maybe some event related to player changing its position in the world?

**Comment by ReikaKalseki** [comment]
> He probably meant something like a division tree, like an octree or so to test for nearby pylons only instead of needing to iterate an entire list.

That is how the Crystal Network *already is* implemented. It is sorted on a chunk by chunk set, and a search in radius X only looks in chunks which intersect that radius from the search position.


> Instead of polling on every render tick (which isnt very CPU-friendly) you could make the client-side pylon indirectly notify the renderer that it should render the aura effect.

That requires every pylon do a distance check for the player at all times. I seriously doubt that to be more performant. Additionally, it would open up the possibility of abrupt appearance of the haze if you move rapidly.
