### ISSUE TITLE
Ocean Temple Structure Controller Overwrite

### ISSUE THREAD

**Issue by freyskol** [ReikaKalseki/Reika_Mods_Issues#2086]
something overwrote an ocean temple structure controller thus making it think a player broke it activating a trap, thus playing the sound to a null player and crashing the server

java.lang.NullPointerException: Exception in server tick loop
    at Reika.ChromatiCraft.Registry.ChromaSounds.playSound(ChromaSounds.java:151)
    at Reika.ChromatiCraft.TileEntity.Technical.TileEntityStructControl.triggerOceanTrap(TileEntityStructControl.java:172)
    at Reika.ChromatiCraft.TileEntity.Technical.TileEntityStructControl.breakBlock(TileEntityStructControl.java:604)
    at Reika.ChromatiCraft.Base.BlockChromaTile.func_149749_a(BlockChromaTile.java:635)

**Comment by freyskol** [comment]
https://i.imgur.com/RHtUMCM.png

https://i.imgur.com/YDdSUHr.png

structure controller drops are still there

it's assumed that the server crashed before

a. the mineshaft completed it's generation

b. the structure code finished

**Comment by chotke** [comment]
Welcome to vanilla WorldGen

**Comment by ReikaKalseki** [comment]
Fixed.
