### ISSUE TITLE
[CrC] Payload may not be larger than 32k

### ISSUE THREAD

**Issue by Hiranus** [ReikaKalseki/Reika_Mods_Issues#2101]
I get something like that whenever i try to hold in my hand Elemental Manipulator and server kicks me. The same error also happens sometimes when I look at CrC plants etc. that display this description on right side of screen.

`[08:00:55] [Netty Client IO #1/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32k
	at net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38) ~[iz.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120) ~[FMLProxyPacket.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434) ~[NetworkDispatcher.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at mods.immibis.core.impl.NetworkingManager$FakeSpecialPacketHandler.write(NetworkingManager.java:499) ~[NetworkingManager$FakeSpecialPacketHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]`

**Comment by Hiranus** [comment]
Update:
Removing Morph mod and fixing player data with NBT Editor fixed issue. I think you can add Morph to the list of incompatible mods.

**Comment by ReikaKalseki** [comment]
#1340 #1344 #1369
