### ISSUE TITLE
Minecraft froze near my fission reactor

### ISSUE THREAD

**Issue by Hiranus** [ReikaKalseki/Reika_Mods_Issues#2109]
This happened when i was testing some stuff. I have fission reactor with quite a few of Heat Relays if that makes a difference. You are mentioned at 3rd line from the bottom.

`[11:47:22] [WrUpdateThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalStateException: Already tesselating!
[11:47:22] [WrUpdateThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:394)
[11:47:22] [WrUpdateThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:384)
[11:47:22] [WrUpdateThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at WorldRendererThreaded.preRenderBlocksThreaded(WorldRendererThreaded.java:278)
[11:47:22] [WrUpdateThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at WorldRendererThreaded.updateRenderer(WorldRendererThreaded.java:157)
[11:47:22] [WrUpdateThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at WrUpdateThread.run(WrUpdateThread.java:119)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.callBoolean(Reflector.java:448)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.SpawnerAnimals.func_77190_a(SpawnerAnimals.java:318)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:178)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.u.a(F:289)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.H.aq(F:36)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.RotaryCraft.Base.BlockModelledMultiTE.isSideSolid(BlockModelledMultiTE.java:185)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.block.Block.canCreatureSpawn(Block.java:1533)
[11:47:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more`

When I killed MC and tried launching that save again i got this:

`[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.util.zip.ZipException: Not in GZIP format
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.nbt.CompressedStreamTools.func_152457_a(CompressedStreamTools.java:60)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at latmod.core.NBTHelper.readMap(NBTHelper.java:68)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at latmod.core.NBTHelper.readMap(NBTHelper.java:74)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at latmod.core.mod.LCEventHandler.worldLoaded(LCEventHandler.java:87)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_LCEventHandler_worldLoaded_Load.invoke(.dynamic)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.call(Reflector.java:567)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.postForgeBusEvent(Reflector.java:680)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.postForgeBusEvent(Reflector.java:666)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:83)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[11:58:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

Which probably translates to "corrupted save". Could you fix this thing?

**Comment by ReikaKalseki** [comment]
Your game crashed due to an NPE when calling `Reika.RotaryCraft.Base.BlockModelledMultiTE.isSideSolid(BlockModelledMultiTE.java:185)`, which is almost certainly - as it has always been in the past - a case of being called with invalid parameters. 

The `java.util.zip.ZipException: Not in GZIP format [11:58:37] [Server thread/INFO] [STDERR]: ` is a clear indication of a corrupt and unrecoverable world file, yes. However, it might be only one or a few files; the entire world might not be useless.
