### ISSUE TITLE
Dragon Api crash on world creation and load

### ISSUE THREAD

**Issue by Samrel556** [ReikaKalseki/Reika_Mods_Issues#2132]
[crash-2019-06-23_11.55.36-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3318364/crash-2019-06-23_11.55.36-server.txt)

Minecraft Version: 1.7.10
Forge Version: 10.13.4.1558
Dragon Api version: v22d
Launcher: MultiMC
OS: Linux Mint 19.1
Other mods: None
Description of issue: When attempting to create a new world or enter an existing one the game crashes. It will crash even before you tell the game to create the new world.

**Comment by Samrel556** [comment]
It will even crash if you leave the game open for too long.

**Comment by ReikaKalseki** [comment]
#1799.

**Comment by Samrel556** [comment]
[crash-2019-06-24_16.18.13-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/3322783/crash-2019-06-24_16.18.13-client.txt)
Game still crashes with forge 1614 after being open for a few minutes. Even without loading a world and sitting at the title screen.

**Comment by ReikaKalseki** [comment]
Do you have Streams/Farseek?

**Comment by Samrel556** [comment]
Nope. Same exact environment as last time only with the correct forge

**Comment by ReikaKalseki** [comment]
Your most recent crash is a Java installatin problem and has nothing to do with any mod:

```
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at paulscode.sound.libraries.ChannelLWJGLOpenAL.playing(ChannelLWJGLOpenAL.java:651)
	at paulscode.sound.Source.playing(Source.java:1213)
	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:500)
	at net.minecraft.client.audio.SoundManager.func_148597_a(SoundManager.java:284)
	at net.minecraft.client.audio.SoundHandler.func_147692_c(SourceFile:216)
	at net.minecraft.client.audio.MusicTicker.func_73660_a(SourceFile:33)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2012)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)```

**Comment by Samrel556** [comment]
Is Dragon api incompatible with Java 8? Because the game runs fine without it

**Comment by ReikaKalseki** [comment]
DragonAPI *requires* java 8.

**Comment by Samrel556** [comment]
With out Dragon api I mean. Sorry I worded that poorly.

**Comment by Samrel556** [comment]
I just tested with the Oracle Java and the same crash happened making me think that it is not my java install

**Comment by Samrel556** [comment]
Never mind. Now Oracle's works. Dunno why. Thanks
