### ISSUE TITLE
Harder Underground x DragonAPI crash

### ISSUE THREAD

**Issue by Envy-glitch** [ReikaKalseki/Reika_Mods_Issues#2140]
Crash log: [https://pastebin.com/yPaaKqpv](url)

The game crashes after a short time when the world is loaded and a player enters the world.
Happenes when both DragonAPI and HU (Harder Underground) are installed.
Replicable 100% of the time.
Confirmed that it does happen if only those two mods (and HUs core mod and a required library) are installed.
The issue seems to be related to one of the blocks HU adds, namely it's underground gases.

**Comment by Envy-glitch** [comment]
Replicable 100% of the time.

**Comment by ReikaKalseki** [comment]
My mods do not appear in the stacktrace; why do you think they are involved?

	java.lang.ClassCastException: net.minecraft.block.BlockDynamicLiquid cannot be cast to net.minecraftforge.fluids.BlockFluidBase
    at net.minecraftforge.fluids.BlockFluidFinite.tryToFlowVerticallyInto(BlockFluidFinite.java:297)
    at net.minecraftforge.fluids.BlockFluidFinite.func_149674_a(BlockFluidFinite.java:64)
    at com.draco18s.hazards.block.BlockGas.func_149674_a(BlockGas.java:129)
    at com.draco18s.hazards.block.BlockThinVolatileGas.func_149674_a(BlockThinVolatileGas.java:97)
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)
    at WorldServerOF.func_72835_b(WorldServerOF.java:234)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Envy-glitch** [comment]
It doesn't happen when they aren't present. I found some more information later on the other authors website. It seems to be a known issue, but a one hard to fix. Maybe you can get in contact with him?

**Comment by KILLAKAN10** [comment]
In case this was still a mystery, I came in out of nowhere from making a nostalgia pack to mess around in, to ID this error seemed at first to belong to a specific gas entirely, I was shockingly lucky and just, generated chunks without it and it worked fine, turns out the gas itself is not even an issue... When placed, it's entirely when it's generated where it has a problem. I don't know if that narrows *anything* down, but there it is.

There *is* one definitely constructive thing that I can say, and it's for anyone currently looking this up hoping to find a solution and they come across this github page, this is for you random unfortunate wanderer; A makeshift fix to make this work is easily doable! So you're probably playing HU alongside the custom ore gen mod, since you're also likely using harder ores. Using custom ore gen, you can make for volatile gases to simply not be generated, which seems to atleast fix any crashes to do with that as far as I've seen.

**Comment by ReikaKalseki** [comment]
I am convinced this is not my doing.
