### ISSUE TITLE
ChromatiCraft End Settings Don't Work

### ISSUE THREAD

**Issue by WiduX** [ReikaKalseki/Reika_Mods_Issues#2148]
We are having an issue on a private server, where only the player that deals the final kill to the Ender Dragon appears to get the CC progression. In order for the rest of us to get this, we'd need to be able to each kill the dragon. I looked in the config files, and found the `Always Respawn EnderDragon` option, but it doesn't work on the server, or a test singleplayer world (I checked at coordinates 0,0 where the dragon should have spawned and surroundings, but there simply was no dragon).

Since this failed, I next tried the `Delete End on Unload` option, but this appears to only work if the dimension is unloading because the server is shutting down. This means someone needs to be in the End at shutdown time (because otherwise it unloads before then). If it unloads any other time, this error occurs (I'm assuming because the files are still in use by something):

```
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.IOException: Unable to delete file: C:\Users\[SNIP]\Games\Minecraft\instances\[SNIP]\.minecraft\saves\New World\DIM1\region\r.0.0.mca
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.IO.ReikaFileReader.deleteFolderWithContents(ReikaFileReader.java:559)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.ChromaticEventManager.deleteEnd(ChromaticEventManager.java:1460)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_310_ChromaticEventManager_deleteEnd_Unload.invoke(.dynamic)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:334)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:657)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[17:56:41] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

We're solving the problem by manually deleting the dimension once for each player to be able to get the progression, but this is clearly not an optimal solution. I believe the `Always Respawn EnderDragon` setting may need to be fixed to actually do that.

Two further questions:
- Is there a proper way to respawn the dragon? (The setting hints at _always_ spawning the dragon, this sounds like there is another specific case where it can respawn)
- Why does only the one player get the progression, instead of everyone present for the fight?

Thanks!

**Comment by ReikaKalseki** [comment]
Your `Delete End on Unload` is failing because something else ingame is attaching to the files; the fact it works during shutdown means it has to be another part of the game. My guess is some sort of server management mod or plugin.

I need to look into how `Always Respawn EnderDragon` to determine what is going wrong, if anything.

`Why does only the one player get the progression, instead of everyone present for the fight?`
Because there is no way of knowing that anyone else is involved in the fight; they may well be not paying attention, and busy fighting endermen, mining for ore, or falling into the void.

**Comment by WiduX** [comment]
> it has to be another part of the game. My guess is some sort of server management mod or plugin.

Note that this error was produced on a singleplayer world, I didn't test this on the server (only the respawn option). No weird management going on, not even MystCraft (I can provide a list if it helps, but there's nothing unusual)

> Because there is no way of knowing that anyone else is involved in the fight; they may well be not paying attention, and busy fighting endermen, mining for ore, or falling into the void.

That's fair, maybe have it so any player in a certain range of the killing player gets it? They aren't going to be doing much else nearby during the fight...

**Comment by ReikaKalseki** [comment]
> Note that this error was produced on a singleplayer world, I didn't test this on the server (only the respawn option). No weird management going on, not even MystCraft (I can provide a list if it helps, but there's nothing unusual)

In that case, I have no idea.

> They aren't going to be doing much else nearby during the fight...

They easily could be.

**Comment by ReikaKalseki** [comment]
Also:

		if (evt.world.provider.dimensionId == 1 && !evt.world.isRemote) {
			if (ChromaOptions.REDRAGON.getState()) {
				EntityDragon ed = new EntityDragon(evt.world);
				ed.setLocationAndAngles(0.0D, 128.0D, 0.0D, evt.world.rand.nextFloat() * 360.0F, 0.0F);
				evt.world.spawnEntityInWorld(ed);
			}
		}

So if something is keeping the End loaded - which would also explain the deletion failure - and thus preventing a reload, that would explain why the option seems to do nothing.

**Comment by WiduX** [comment]
The dragon is not respawning regardless of how I load the dimension. Even if I exit the game while in the End then start it back up, which would trigger a dimension load (And I see `[14:22:07] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@32900f35)` in the log), no dragon.

If I exit the end through the portal, I see `[14:25:44] [Server thread/INFO] [FML]: Unloading dimension 1`, and re-entering I see the loading as above, and still no dragon. Without your "delete End" option on, there are no errors or indications of a failed unload.

**Comment by ReikaKalseki** [comment]
OK, that makes no sense. You can see the code is extremely simple, not something which can have weird bugs.

**Comment by WiduX** [comment]
I can see that, if I understood what might be causing it, I would have mentioned so. Is it possible the method is not being called at all for some reason? That's the only thing I can think of...

**Comment by ReikaKalseki** [comment]
The method not being called is equivalent to the event not being fired; it is a standard Forge event subscription, in a class that handles hundreds of such subscriptions without issues.
