### ISSUE TITLE
DragonAPI causes Computronics to crash during init

### ISSUE THREAD

**Issue by thePalindrome** [ReikaKalseki/Reika_Mods_Issues#2195]
https://paste.ee/p/uQxGz

```
Caused by: java.lang.SecurityException: class "cofh.api.tileentity.IEnergyInfo"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
```

( Root error ripped from log for convenience )

All of the other energy using mods (EIO, AE2, etc.) seem to be perfectly okay, and it's *just* computronics. This issue is new with V23a, and isn't present on V22

**Comment by ReikaKalseki** [comment]
Does v22 contain the CoFH API in its jar?

**Comment by thePalindrome** [comment]
Yeah, checking the differences, v22 and v23 have the same cofh api classes *except* v23a contains IReconfigurableFacing.class. I'm... not sure if that's actually related to this error though.

(and, to clarify, by the same cofh classes I mean their CRCs match)

**Comment by ReikaKalseki** [comment]
Odd that that would have changed...I never updated the CoFH API on my end...
