### ISSUE TITLE
VoidMonster v23b ConcurrentModificationException

### ISSUE THREAD

**Issue by Fishy51** [ReikaKalseki/Reika_Mods_Issues#2209]
My world keeps crashing as I'm exploring due to this crash. Twice when in boat and once on foot.

pastebin.com/a0a7rRN4

Sorry if this was posted before.

**Comment by OvermindDL1** [comment]
Why are iterators being used there...  >.>

**Comment by ReikaKalseki** [comment]
There is code to prevent there from ever being more than one void monster in the world.


But seriously, this "Thread safe" set is throwing more CMEs than the old "vanilla" sets did.

**Comment by OvermindDL1** [comment]
> But seriously, this "Thread safe" set is throwing more CMEs than the old "vanilla" sets did.

It's catching more cases where there were previously hidden issues, it's not an immutable collection.

Also, CME's have nothing to do with Threading.  Sure poor Threading can cause CME's but that is not the main cause of CME's, so being thread-safe does not mean no CME's, a CME is always always always caused by using the collection incorrectly, which though in this case is probably threaded related.

So let's look since I have a few minutes free.  The VoidMonster is using your MultiMap at:
https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/Maps/MultiMap.java

Which is backed by, in the voidmonster case, a custom ThreadSafeSet:
https://github.com/ReikaKalseki/DragonAPI/blob/master/Instantiable/Data/Collections/ThreadSafeSet.java

Which it itself is backed by `java.util.HashSet`, hmm, let's find it's code, here we go, the one in Java8 (so the one that is being used here) is at:
http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/HashSet.java

And as we see from the stacktrace:
```java
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
    at java.util.HashSet.<init>(HashSet.java:119)
    at Reika.DragonAPI.Instantiable.Data.Collections.ThreadSafeSet.add(ThreadSafeSet.java:50)
    at Reika.DragonAPI.Instantiable.Data.Maps.MultiMap.addValue(MultiMap.java:113)
    at Reika.DragonAPI.Instantiable.Data.Maps.MultiMap.addValue(MultiMap.java:99)
    at Reika.DragonAPI.Instantiable.Data.Maps.MultiMap.addValue(MultiMap.java:95)
    at Reika.VoidMonster.VoidMonster.registerExistingMonster(VoidMonster.java:244)
```
It's happening on this line in `ThreadSafeSet::add`:
```java
		data = new HashSet(data);
```
And looking a the official Java HashSet constructor that is used there from the above link the code is:
```java
    public HashSet(Collection<? extends E> c) {
        map = new HashMap<>(Math.max((int) (c.size()/.75f) + 1, 16));
        addAll(c);
    }
```
And indeed, it matches the stacktrace, so on the `addAll(c);` line that function is define in the `AbstractCollection` parent class at http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/AbstractCollection.java and it is:
```java
    public boolean addAll(Collection<? extends E> c) {
        boolean modified = false;
        for (E e : c)
            if (add(e))
                modified = true;
        return modified;
    }
```
And we can plainly see it uses an iterator to iterate all of the items then `add` them to the new collection if they don't already exist, however a CME is being through in the `for (E e : c)` line on the iterator `next()` call, which happens when the collection that the iterator is iterating over was edited, so that collection was the one that was passed in at the `ThreadSafeSet::add` call above of:
```java
	public synchronized boolean add(E e) {
		data = new HashSet(data);
		return data.add(e);
	}
```
So the original `data` is being mutated at the same time it is being copied, yet this method is obviously synchronized, thus meaning `data` is somehow leaking out somewhere, let's look in the file:
* `size` returns an integer
* `isEmpty` returns a boolean
* `contains` returns a boolean
* `iterator` returns an iterator, oh dear an iterator 'can' hold a collection and let it leak outside of the synchronization depending on how it is implemented, for an iterator to be save it would have to be synchronized for the entire life of the iterator itself, so let's see how it is implemented:
```java
	public Iterator<E> iterator() {
		return data.iterator();
	}
```
Oh dear, it returns the original iterator of the internal data set itself.  We'll keep that in mind.  A quick look doesn't see it leaking out anywhere else.

So let's look back at the MultiMap that wraps it, let's see where all it touches the iterator, and first of all the VoidMonster class only touches `MultiMap` to construct it, to `addValue`, and to `get`, so let's see `get` first:
```java
	public Collection<V> get(K key) {
		Collection<V> c = data.get(key);
		if (c == null && this.nullEmpty)
			return null;
		return c != null ? (this.modifiable ? c : Collections.unmodifiableCollection(c)) : this.factory.createCollection(); //Internal NPE protection
	}
```
So it does a `get` on it's data, oh wait, I mis-read something, the 
custom `ThreadSafeSet` *is* the value collection, so the above iterator in the VoidMonster class at:
```java
	public static Collection<EntityVoidMonster> getCurrentMonsterList(World world) {
		Iterator<Integer> it = monsterList.get(world.provider.dimensionId).iterator();
		ArrayList<EntityVoidMonster> li = new ArrayList();
		while (it.hasNext()) {
			int id = it.next();
			Entity e = world.getEntityByID(id);
			if (e instanceof EntityVoidMonster)
				li.add((EntityVoidMonster)e);
			else
				it.remove();
		}
		return li;

		/*
		 * for (Entity e : ((List<Entity>)world.loadedEntityList)) {
			if (e instanceof EntityVoidMonster) {
				return false;
			}
		}
		 */
	}
```
Does indeed mutate it.

So if a thread (client or server or network thread or whatever) hits this `getCurrentMonsterList` function and managed to get to `Iterator<Integer> it = monsterList.get(world.provider.dimensionId).iterator();` before another thread hits the `registerExistingMonster` function, then it will start iterating the collection at the time the other function acquired it's lock after the `iterator` call has been returned and unlocked, so the `getCurrentMonsterList` it iterating and happens to either add or remove something to that collection (then returns the collection) at the same time the other thread is copying the collection, then boom, CME, so yes, this one is caused by bad threading.

Yes `ThreadSafeSet` is synchronized properly, no the iterator is not, it would need to remain locked until it is fully consumed to do this style properly.

There are two possible fixes:

1. Use a proper Immutable Collection, this `ThreadSafeSet` is too mutably leaking by letting it's iterator be accessible.

2. Make both `VoidMonster::registerExistingMonster` and `VoidMonster::getCurrentMonsterList` be synchronized as well so only one at a time can be entered.

Remember that synchronization needs to 'bubble' up in the callstack for the lifetime of anything of the internal collection being returned (such as an iterator, thus the entire iterator loop must be synchronized with the access of acquiring the iterator itself).

I.E.  Just a programming error from using the wrong kind of container, this specific case seems to have an easy fix however.

**Comment by OvermindDL1** [comment]
And yes, `registerExistingMonster` *can* be called from multiple threads (client and server) as it is in the entity's `update` function, which is called on both client and server, and since it is a static function accessing static data, then boom (static functions are good, better than member functions, more optimizable, however static data fields is always always always bad unless it is a never-modified data cache of static information).

**Comment by Fishy51** [comment]
It found out I reported it and found its way into the ocean and is coming to get me. D:

![2019-10-30_20 41 56](https://user-images.githubusercontent.com/38511269/67906015-3f57f900-fb56-11e9-8f40-60f59a3094c7.png)
![2019-10-30_20 39 29](https://user-images.githubusercontent.com/38511269/67906083-67dff300-fb56-11e9-873f-1993d3d78f9f.png)

And then it went away?

![2019-10-30_20 51 08](https://user-images.githubusercontent.com/38511269/67906315-1e43d800-fb57-11e9-9c0d-df50575b5e1d.png)

Sorry, was funny when it happened. :P
Is there a despawn mechanic for when it finds a way up top?

**Comment by OvermindDL1** [comment]
That seems slightly terrifying, lol.  ^.^

**Comment by EreticKB** [comment]
Hi. this crash still in VM V24a. :(

**Comment by nicolhaq** [comment]
This seem to still crash in 26a.
crash log: https://paste.ee/p/Mlnvl

**Comment by SilkenStrand** [comment]
Hoping someone can help with what appears to be the same [**crash**](https://gist.github.com/SilkenStrand/50a4f0ce83fd9d61b26aa24af9b5e403#file-crash-2020-11-25_23-12-33-server-txt)? Or maybe give an eta on when help might arrive? Sorry if I'm wasting your time; I suspect another report isn't really useful here, but mainly I wanted to ask for help/info.
...Suppose I can just remove void monster, but I would prefer not to if possible.

**Comment by ReikaKalseki** [comment]
This is still a live issue.

**Comment by ReikaKalseki** [comment]
This miiiiiiiiight be fixed.

![https://i.imgur.com/El0mof1.png](https://i.imgur.com/El0mof1.png)
