### ISSUE TITLE
Logspam from Fans/Sprinklers

### ISSUE THREAD

**Issue by Rewyn** [ReikaKalseki/Reika_Mods_Issues#2220]
https://gist.github.com/Rewyn/10ee4fc8d426be3a8f620d01a6a7e921
Here's a fml log with the error starting at line 40476.
This does happen even by only placing a fan, without actually supplying power as well, but might depend on other factors. For one this happens in SMP, tried to replicate on SSP and couldn't.

**Comment by voidsong-dragonfly** [comment]
The log cuts off at ~6800, and I cannot replicate this _with_ Advanced Rocketry. So it's specific to not having Advanced Rocketry.

**Comment by Rewyn** [comment]
God damnit, it showed up properly when I still had the thing open.
https://paste.ee/p/0yhnr
Let's see if this works.
If not, here's just the part that's getting spammed.
`[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.AtmosphereHandler.getAtmo(AtmosphereHandler.java:30)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.AtmosphereHandler.isNoAtmo(AtmosphereHandler.java:40)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.RotaryCraft.TileEntities.Farming.TileEntityFan.updateEntity(TileEntityFan.java:82)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:510)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[01:17:49] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

**Comment by ReikaKalseki** [comment]
So digging into this, it appears that either the invocation to `getAtmosphereType` is throwing an NPE in AdvR code, or - more likely - that the result from `getOxygenHandler` called a line above is null. This should not happen (I think).

I put some extra logging in, and made it not spit out an entire stacktrace, only one error line.

@zmaster587

**Comment by zmaster587** [comment]
@ReikaKalseki I do believe that `getOxygenHandler` can return null.  Dimensions that are not registered with AR, which should be limited to galacticraft planets if overrideGCAir is false or if O2 handling in AR is outright disabled via the config.

If the player is connecting to a server, then on the client the atmosphere info shouldn't be getting registered.  That might explain why it only occurs in multiplayer.

The rationale behind this is that the client shouldn't need to process atmosphere info, the server takes care of adjusting health and other stats.  The atmosphere the player is in is synced to the client when the client changes the atmosphere they're in on the server.

@ReikaKalseki if you need to do client/visual stuff depending on the atmosphere a block is in, you may need to update the state of the block on the server and sync with the client if that's not already what you're doing.

**Comment by ReikaKalseki** [comment]
The code now actually verifies that a dimension is an AdvR world before calling AdvR code on it, so this should now be fixed.
