### ISSUE TITLE
[Server-Side only][ChromatiCraft][DragonAPI][V8e]No such method error(and that method has @SideOnly(Side.CLIENT)) on server - players get kicked

### ISSUE THREAD

**Issue by Modbder** [ReikaKalseki/Reika_Mods_Issues#225]
I've been testing different features of ChromatiCraft and it worked perfectly fine when I was in single-player. Decided to show the mod to one of my friends - didn't go so well.

What actually happens:
Every time something client-sided(for example, spawning particles) must happen the server would kick every player nearby with the "Internal Server Error" message(no error messages in the Client's console). The server report the following error(here I've used the Crystal Orchestra):

[Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchMethodError: Reika.ChromatiCraft.TileEntity.TileEntityCrystalMusic.doParticles(Lnet/minecraft/world/World;IIILReika/ChromatiCraft/Registry/CrystalElement;)V
        at Reika.ChromatiCraft.ChromatiPackets.handleData(ChromatiPackets.java:506) ~[ChromatiPackets.class:?]
        at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper$PacketObj.handleServer(ReikaPacketHelper.java:1601) ~[ReikaPacketHelper$PacketObj.class:?]
        at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:152) ~[PacketPipeline$InternalHandler.class:?]
        at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:139) ~[PacketPipeline$InternalHandler.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

And continues to work just fine - clients can re-join server. 
This seems to work with every server->packet->client event - I can confirm that it does the same for example with lumen turrents when they are attacking, just the method that was not found is different.

If you need full FML logs - here they are:
Server - [http://pastebin.com/pg4jD8rq](the server does NOT crash after the error, I've just stopped it)
Client - [http://pastebin.com/S9mCH0H5](contains no info whatsoever, but might still be usefull)

**Comment by ReikaKalseki** [comment]
Fixed.
