### ISSUE TITLE
ArchiSections crash

### ISSUE THREAD

**Issue by dalapo** [ReikaKalseki/Reika_Mods_Issues#2251]
I placed a Room Controller inside a water fountain such that on top of it was a water source, on each side was flowing water, and underneath was a solid block. I then placed a block to replace the water source, and it crashed.

`java.lang.NullPointerException: Exception while updating neighbours
    at Reika.ArchiSections.Control.TransparencyRules.isOpaqueForRoom(TransparencyRules.java:208)
    at Reika.ArchiSections.TileRoomController.getDimensions(TileRoomController.java:119)
    at Reika.ArchiSections.TileRoomController.onAdjacentBlockUpdate(TileRoomController.java:49)
    at Reika.DragonAPI.Base.TileEntityBase.onBlockUpdate(TileEntityBase.java:159)
    at Reika.DragonAPI.Base.BlockTEBase.func_149695_a(BlockTEBase.java:53)
    at net.minecraft.world.World.func_147460_e(World.java:697)
    at net.minecraft.world.World.func_147459_d(World.java:650)
    at net.minecraft.world.World.func_147444_c(World.java:613)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:573)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

**Comment by dalapo** [comment]
More information: The same crash happened again when breaking a block directly under the room controller, bordered by air on all other sides.

**Comment by ReikaKalseki** [comment]
This was fixed a long time ago.
