### ISSUE TITLE
Archisections null player lookup or something like that

### ISSUE THREAD

**Issue by Hellexar** [ReikaKalseki/Reika_Mods_Issues#2261]
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at Reika.ArchiSections.RoomTracker.getRoomForEntity(RoomTracker.java:112)
	at Reika.ArchiSections.RoomTracker.cancel(RoomTracker.java:164)
	at Reika.DragonAPI.Extras.ThrottleableEffectRenderer.func_78873_a(ThrottleableEffectRenderer.java:92)
	at biomesoplenty.ClientProxy.spawnParticle(ClientProxy.java:123)
	at biomesoplenty.common.entities.EntityGlob.func_70071_h_(EntityGlob.java:109)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by ninjanomnom** [comment]
I've got this same issue with it crashing on loading the save but a fresh world is fine. Looking at the error logs it seems to be happening with an advanced rocketry observatory.

**Comment by ReikaKalseki** [comment]
Due to rewrites in the relevant code, this might have already been fixed.

**Comment by ninjanomnom** [comment]
When this happened to me I was using 25b, do you mean it's fixed in the next version?

**Comment by ReikaKalseki** [comment]
Yes.

**Comment by ReikaKalseki** [comment]
Is this still actively happening?
