### ISSUE TITLE
EDDB url out of date and CC donator file missing

### ISSUE THREAD

**Issue by HellsingDarge** [ReikaKalseki/Reika_Mods_Issues#2274]
Noticed these errors appear while launching MC

<details>
<summary>donators_chromaticraft.txt</summary>

```
java.io.FileNotFoundException: http://server.techjargaming.com/Reika/Donator/donators_chromaticraft.txt
 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
 	at Reika.DragonAPI.IO.ReikaFileReader.getReader(ReikaFileReader.java:127)
 	at Reika.DragonAPI.IO.ReikaFileReader.getFileAsLines(ReikaFileReader.java:248)
 	at Reika.DragonAPI.IO.ReikaFileReader.getFileAsLines(ReikaFileReader.java:244)
 	at Reika.DragonAPI.Auxiliary.Trackers.DonatorController.registerMod(DonatorController.java:52)
 	at Reika.ChromatiCraft.ChromatiCraft.load(ChromatiCraft.java:644)
```

</details>
<details>
<summary>commodities.json</summary>

```
java.io.FileNotFoundException: https://eddb.io/archive/v5/commodities.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at Reika.DragonAPI.IO.ReikaFileReader.getReader(ReikaFileReader.java:127)
	at Reika.ChromatiCraft.Magic.Artefact.UATrades.<init>(UATrades.java:85)
	at Reika.ChromatiCraft.Magic.Artefact.UATrades.<clinit>(UATrades.java:52)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at Reika.DragonAPI.Libraries.Java.ReikaJavaLibrary.initClass(ReikaJavaLibrary.java:287)
	at Reika.ChromatiCraft.Auxiliary.VillageTradeHandler.<init>(VillageTradeHandler.java:28)
	at Reika.ChromatiCraft.Auxiliary.VillageTradeHandler.<clinit>(VillageTradeHandler.java:25)
	at Reika.ChromatiCraft.ChromatiCraft.load(ChromatiCraft.java:540)
```

</details>

**Comment by ReikaKalseki** [comment]
They work for me and basically everyone else. Is your game able to access the internet at all?

**Comment by HellsingDarge** [comment]
Considering that ChromatiCraft music is downloaded without any issues and other requests are also handled fine (`/Reika/Donator/patreon_Reika.txt`, `/Reika/versions_1-7-10.txt`), I'd say yes

**Comment by OvermindDL1** [comment]
> They work for me and basically everyone else. Is your game able to access the internet at all?

I tried from 2 distinct locations and both had the same results:

* http://server.techjargaming.com/Reika/Donator/donators_chromaticraft.txt just returns a 404 not found with a picture of a van covered in cameras?
* https://eddb.io/archive/v5/commodities.json returns a 404 of "Page not found".

You sure they are working for you?  Perhaps you should do what GT6 does for it's donator lists, which is to both bake in the latest version of it into the mod to use as a fallback when it can't look it up, and to host it in a more reliable location, a github gist would work though is abusing their API, or put it on your own website (or you can put it on the GT6 maven like GT6's lists if you want).

**Comment by Barhandar** [comment]
I do _not_ have filenotfound exception listing those files in my logs. However, they're not accessible through the browser, 404ing, so I might have some config option that allows looking those up off.

**Comment by ReikaKalseki** [comment]
Apparently eddb has very recently (like since Christmas) changed their url to use "v6" instead of "v5".

As for the donators file, it was working on someone else's client just two days ago; they commented on the render.

However, I too have the file not found now, and looking at techjar's server in FileZilla, the file is gone: ![https://i.imgur.com/ZxKbJCq.png](https://i.imgur.com/ZxKbJCq.png)

**Comment by OvermindDL1** [comment]
Do you need a better server to host files on?  ^.^

**Comment by ReikaKalseki** [comment]
The EDDB file is not static; EDDB is a service which dynamically updates various statistics from the game.

**Comment by Shahelion** [comment]
Since it's been a few years, I'd just like to chime in that this is still a thing that's happening.

**Comment by ReikaKalseki** [comment]
It is happening *now* because EDDB has gone down in the intervening years - in the last few months actually. I am aware of this but do not have another site to contact yet.
