### ISSUE TITLE
[ChC v24c] Casting Stand Insertion Focus woes: cannot craft the worst intermediates

### ISSUE THREAD

**Issue by Barhandar** [ReikaKalseki/Reika_Mods_Issues#2276]
~~More specifically, it gets pushed into regardless of ME connection, and it doesn't push items into the ME connected to it by fluix cable, with item storage (ME Drive) on the other end of quantum bridge from it. The system is valid and powered.~~ that's #2256, which I hadn't noticed.

By any reasonable definition, Elemental Core and Crystal Star are intermediates - they're _only_ used for further crafting, and have no use on their own (or their non-crafting use is so arcane and gotcha that it can be disregarded). They're also obnoxious to manually craft, requiring all 16 colors of elemental stone, and all 16 colors of boosted crystal shards, respectively. But the insertion focus cannot craft them.

P.S. Bonus: the focus has been spamming my server log with the following error.
```
[17:31:44] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Casting Sta
nd Insertion Focus @ DIM0: 23906, 78, -23946 [SERVER] is throwing class java.lan
g.NullPointerException on update: null
java.lang.NullPointerException
        at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingInjector.updat
eEntity(TileEntityCastingInjector.java:112)
        at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java
:509)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547)
        at fastcraft.at.a(F:978)
        at fastcraft.H.aq(F:36)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by ReikaKalseki** [comment]
This was done at some point in the past.
