### ISSUE TITLE
Flywheel recursion error, crash

### ISSUE THREAD

**Issue by mpevner** [ReikaKalseki/Reika_Mods_Issues#230]
Java 8
Minecraft 1.7.10
Forge 1448 (Recommended)
DragonAPI V8e
Rotarycraft V8d
Reactorcraft V8d

Attempting to use a flywheel as pictured results in log/chat spam of:

`[17:05:12] [Server thread/INFO] [FML/]: DRAGONAPI: 
[17:05:12] [Client thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Stone Flywheel @ DIM0: -197, 70, -265 is throwing class java.lang.NullPointerException on update: null
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.Instantiable.Data.Immutable.WorldLocation.<init>(WorldLocation.java:68)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveCount(TorqueUsage.java:307)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveCount(TorqueUsage.java:299)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.process(TileEntityFlywheel.java:313)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.updateEntity(TileEntityFlywheel.java:179)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:432)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[17:05:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.EntryPoint.main(EntryPoint.java:54)`

On rotating the flywheel opposite as pictured, the game immediately crashed (normally it will crash after a Great deal of the above spam) though that might have been the error above finally hitting the recursion limit, as the log then spat out this repeatedly:

`java.lang.StackOverflowError: Ticking block entity
    at java.util.HashMap.putVal(Unknown Source)
    at java.util.HashMap.put(Unknown Source)
    at java.util.HashSet.add(Unknown Source)
    at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.getAllOutputs(TileEntityFlywheel.java:527)
    at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveCount(TorqueUsage.java:305)
    at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveCount(TorqueUsage.java:315)
    at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveCount(TorqueUsage.java:315)`

With the recursiveCount bit repeating a Great Deal.
Basic testing shows that the same setup with any flywheel results in the same crash. A friend is reporting the same error even when a load is applied to the setup and that it does not matter in which order the parts are placed.

Full logs, screenshots of setup at:
https://www.dropbox.com/sh/lukadbamv0azcfb/AAALj2cEGZE6F884lLOT_2E6a?dl=0

**Comment by ReikaKalseki** [comment]
Hopefully fixed.

**Comment by KevinNielson** [comment]
Not yet fixed.

**Comment by ReikaKalseki** [comment]
I tested and it is. Use v9b.

**Comment by KevinNielson** [comment]
My mistake; I was basing my conclusion on the google sites page statement that v8g was current.
Thanks for the update.

**Comment by ReikaKalseki** [comment]
Fixed.
