### ISSUE TITLE
[RoC] Broken ZH-CN XML in Rotatry Craft

### ISSUE THREAD

**Issue by Water-Moon** [ReikaKalseki/Reika_Mods_Issues#2328]
When the game language was set to Chinese and get loaded, it crashes at Initialize. In the log, it said the XML is broken due to "incorrect UTF-8 character".
This is probably caused by wrong file encoding or selected wrong encoding when building a jar file.

Problematic XML is Resources/zh_CN/categories.xml, but I doubt that other XML may have encoding problem as well :[

MC 1.7.10
Forge 10.13.4.1614
Dragon API v24c
RoC v24c

`java.lang.ExceptionInInitializerError
        at Reika.RotaryCraft.RotaryCraft.load(RotaryCraft.java:352) ~[RotaryCraft.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:?]
        at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Could not load XML at Resources/zh_CN/categories.xml relative to Reika.RotaryCraft.RotaryCraft
        at Reika.DragonAPI.Instantiable.IO.XMLInterface.init(XMLInterface.java:109) ~[XMLInterface.class:?]
        at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.loadData(RotaryDescriptions.java:116) ~[RotaryDescriptions.class:?]
        at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.<clinit>(RotaryDescriptions.java:103) ~[RotaryDescriptions.class:?]
        ... 37 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 3 字节的 UTF-8 序列的字节 3 无效。
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:435) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_211]
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_211]
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[?:1.8.0_211]
        at Reika.DragonAPI.IO.ReikaXMLBase.getXMLDocument(ReikaXMLBase.java:39) ~[ReikaXMLBase.class:?]
        at Reika.DragonAPI.Instantiable.IO.XMLInterface.init(XMLInterface.java:91) ~[XMLInterface.class:?]
        at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.loadData(RotaryDescriptions.java:116) ~[RotaryDescriptions.class:?]
        at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.<clinit>(RotaryDescriptions.java:103) ~[RotaryDescriptions.class:?]
        ... 37 more`

**Comment by Water-Moon** [comment]
just realize a commandline parameter is required

**Comment by ReikaKalseki** [comment]
#2167 #2233
