### ISSUE TITLE
Chat spam when moving between Suspension Field Controllers at different heights

### ISSUE THREAD

**Issue by Alrena** [ReikaKalseki/Reika_Mods_Issues#2330]
I have a rather large vertical shaft inside a tree that one suspension field controller isn't able to get me to the top of. I started installing a second set of SFC at the top of where the first set could reach, but moving from one to the other absolutely floods my chat, not the server log, with hundreds of error messages.

https://i.imgur.com/lKhIwuZ.png
https://i.imgur.com/neiJW4Y.png
https://i.imgur.com/WC1VXet.png

Based on the latest log it's repeating this:

> [10:10:15] [Client thread/ERROR]: DRAGONAPI ERROR: Tile Entity Suspension Field Controller @ DIM0: 491, 88, 641 [CLIENT] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: null
[10:10:15] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException
[10:10:15] [Client thread/INFO]: DRAGONAPI: 
[10:10:15] [Client thread/INFO]: [CHAT] Tile Entity Suspension Field Controller @ DIM0: 490, 88, 641 [CLIENT] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: null
[10:10:15] [Client thread/INFO]: [CHAT] []
[10:10:15] [Client thread/INFO]: [CHAT] 

and then this one message also comes in after every few dozen of the previous:

> [10:10:17] [Client thread/INFO]: net.minecraft.client.gui.GuiChat

**Comment by OvermindDL1** [comment]
Can you upload the log file that shows that, it should show the full stacktrace to see the precise location of the error.

**Comment by Alrena** [comment]
[latest.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4238843/latest.log)

All of the error messages shown are from me triggering it one time

**Comment by ReikaKalseki** [comment]
```
[21:10:09] [Client thread/INFO]: [CHAT] Tile Entity Suspension Field Controller @ DIM0: 490, 113, 643 [CLIENT] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: 2
[21:10:09] [Client thread/INFO]: [CHAT] [
Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad$ParticleMode.doParticles(TileEntityHoverPad.java:313)
Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad$ParticleMode.access$000(TileEntityHoverPad.java:237)
Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad.spawnParticles(TileEntityHoverPad.java:106)
Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad.updateEntity(TileEntityHoverPad.java:90)
Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:509)
net.minecraft.world.World.func_72939_s(World.java:1939)
net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
net.minecraft.client.main.Main.main(SourceFile:148)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
net.minecraft.launchwrapper.Launch.main(Launch.java:28)
]
[21:10:09] [Client thread/INFO]: [CHAT] 
[21:10:09] [Client thread/ERROR]: DRAGONAPI ERROR: Tile Entity Suspension Field Controller @ DIM0: 490, 113, 643 [CLIENT] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: 2
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 2
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad$ParticleMode.doParticles(TileEntityHoverPad.java:313)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad$ParticleMode.access$000(TileEntityHoverPad.java:237)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad.spawnParticles(TileEntityHoverPad.java:106)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.ChromatiCraft.TileEntity.AOE.TileEntityHoverPad.updateEntity(TileEntityHoverPad.java:90)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:509)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[21:10:09] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)```

**Comment by ReikaKalseki** [comment]
This looks like a serious design error on my part regarding the particle handling. Granted, I did write that code in May 2016...

**Comment by ReikaKalseki** [comment]
Fixed.
