### ISSUE TITLE
Chromaticraft "crystal groups" uncraftable (amongst others)

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#234]
When trying to craft a crystal group (all four colors) the table shows the recipe is correct but clicking the table with the wand gives a null pointer exception to chat (see below) even though the animation plays and the "started crafting" sound can be heared (the "finished" sound is not played). I spawned some crystal groups to test the higher ones. Crafting primary/secondary cluster and crystal core does work fine. Some further testing reveals that the same (or very similar) error happens when trying to create ornamental crystal stone varians (engraved, pillar, etc), though making the stones themselfs does work.

I also tried removing all mods except DragonAPI and Chromaticraft (v8e) which did not solve the issue.

Running: forge-1.7.10-10.13.4.1448-1.7.10-universal, jre1.7.0_80

The exception (apparently github doesn't support attaching the full log...):

[23:33:12] [Client thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Casting Table @ DIM0: -1273, 2, 760 is throwing class java.lang.NullPointerException on update: null
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.craft(TileEntityCastingTable.java:518)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:223)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:133)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:432)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:33:12] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:33:12] [Client thread/INFO] [FML/]: DRAGONAPI: 
![Uploading crystalgrouperror.png…]()

**Comment by ReikaKalseki** [comment]
Update.
