### ISSUE TITLE
[1.7.10] crash of draconic evolution 1.0.2h with dragonApi v25c

### ISSUE THREAD

**Issue by OptimusZeGaming** [ReikaKalseki/Reika_Mods_Issues#2422]
Hello

I have just finished my modspack 1.7.10 but I have a problem with draconic evolution when I create a new map all is well I leave the map but when I come back on it crashes and according to the crash report it comes from draconic evolution I put the complete crash report attached.

thank you for your help.

Base information
Minecraft version: 1.7.10
Mod version: 1.7.10 draconic evolution 1.0.2h and dragon api v25c
Minecraft Forge version: 1614
Mod Pack: (if applicable)
Crash report
CRASH REPORT HERE
Please note assuming the issue is a crash something like this

crash-2020-04-12_21.50.25-server.txt

	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.loadCacheAndUpdate(VersionTransitionTracker.java:52)
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.onWorldLoad(VersionTransitionTracker.java:38)
	at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.checkModChanges(DragonAPIEventWatcher.java:143)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_635_DragonAPIEventWatcher_checkModChanges_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)```

**Comment by ReikaKalseki** [comment]
#2397 #2413 #2420
