### ISSUE TITLE
[CondensedOres] CondensedOres unreliably loads config

### ISSUE THREAD

**Issue by charagarlnad** [ReikaKalseki/Reika_Mods_Issues#2425]
With only DragonAPI and CondensedOres installed, any CondensedOres generation config will have a random amount of entries error out at load time and with the /reloadoreconfig command. 
https://pastebin.com/m2YDSaYY
<details>
<summary> example config: </summary> 

```lua
{
	type = "pack"
	retrogen = false
	sprinkleMix = false
	veinSize = 12
	biomeRules = {
		combination = "or"
		strict = false
	}
	blocks = {
	}
	dimensionRules = {
		combination = "or"
	}
	heightRule = {
		maxHeight = 64
		minHeight = 0
		variation = "linear"
	}
	proximityRules = {
	}
	spawnBlock = {
		{
			block = "minecraft:stone"
		}
	}
	veinFrequency = {
		chunkGenChance = 1
		veinsPerChunk = 6
	}
}
{
	type = "test1"
	inherit = "pack"
	name = "Test 1"
	blocks = {
		"minecraft:dirt"
	}
	heightRule = {
		minHeight = 40
		maxHeight = 75
		variation = "linear"
	}
}
{
	type = "test2"
	inherit = "pack"
	name = "Test 2"
	blocks = {
		"minecraft:dirt"
	}
	heightRule = {
		minHeight = 20
		maxHeight = 55
		variation = "linear"
	}
}
{
	type = "test3"
	inherit = "pack"
	name = "Test 3"
	blocks = {
		"minecraft:dirt"
	}
	heightRule = {
		minHeight = 5
		maxHeight = 30
		variation = "linear"
	}
}
{
	type = "test4"
	inherit = "pack"
	name = "Test 4"
	blocks = {
		"minecraft:dirt"
	}
	heightRule = {
		minHeight = 10
		maxHeight = 35
		variation = "linear"
	}
}
{
	type = "test5"
	inherit = "pack"
	name = "Test 5"
	blocks = {
		"minecraft:dirt"
	}
	heightRule = {
		minHeight = 5
		maxHeight = 20
		variation = "linear"
	}
}
```
</details>

**Comment by ReikaKalseki** [comment]
It looks like you are specifying entries that reference blocks that do not exist.

**Comment by charagarlnad** [comment]
> It looks like you are specifying entries that reference blocks that do not exist.

I'm using dirt as a placeholder so I could boot with the minimum amount of mods required for the error, here's a config with actual ores selected that still causes the same issue. 

<details>
<summary> config: </summary> 

```lua
{
	type = "pack"
	retrogen = false
	sprinkleMix = false
	veinSize = 12
	biomeRules = {
		combination = "or"
		strict = false
	}
	blocks = {
	}
	dimensionRules = {
		combination = "or"
	}
	heightRule = {
		maxHeight = 64
		minHeight = 0
		variation = "linear"
	}
	proximityRules = {
	}
	spawnBlock = {
		{
			block = "minecraft:stone"
		}
	}
	veinFrequency = {
		chunkGenChance = 1
		veinsPerChunk = 6
	}
}
{
	type = "copper"
	inherit = "pack"
	name = "Copper Ore"
	blocks = {
		"ThermalFoundation:Ore:0"
	}
	heightRule = {
		minHeight = 40
		maxHeight = 75
		variation = "linear"
	}
}
{
	type = "tin"
	inherit = "pack"
	name = "Tin Ore"
	blocks = {
		"ThermalFoundation:Ore:1"
	}
	heightRule = {
		minHeight = 20
		maxHeight = 55
		variation = "linear"
	}
}
{
	type = "silver"
	inherit = "pack"
	name = "Silver"
	blocks = {
		"ThermalFoundation:Ore:2"
	}
	heightRule = {
		minHeight = 5
		maxHeight = 30
		variation = "linear"
	}
}
{
	type = "lead"
	inherit = "pack"
	name = "Lead Ore"
	blocks = {
		"ThermalFoundation:Ore:3"
	}
	heightRule = {
		minHeight = 10
		maxHeight = 35
		variation = "linear"
	}
}
{
	type = "ferrous"
	inherit = "pack"
	name = "Ferrous Ore"
	blocks = {
		"ThermalFoundation:Ore:4"
	}
	heightRule = {
		minHeight = 5
		maxHeight = 20
		variation = "linear"
	}
}
```
</details>

![image](https://user-images.githubusercontent.com/27380203/79670574-15d96b00-8192-11ea-9029-64c86e344114.png)

**Comment by ReikaKalseki** [comment]
And what error is getting thrown?

**Comment by charagarlnad** [comment]
This gets thrown for every entry that errors from the log above, there seems to be no pattern to which entry will error:
```
[22:21:13] [Server thread/ERROR] [FML/]: CONDENSED ORES ERROR: Could not parse config section test3:
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.CondensedOres.CondensedOreConfig.parseEntry(CondensedOreConfig.java:184)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.CondensedOres.CondensedOreConfig.parseConfigs(CondensedOreConfig.java:152)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.CondensedOres.CondensedOreConfig.loadConfigs(CondensedOreConfig.java:95)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.CondensedOres.ReloadOreConfigCommand.func_71515_b(ReloadOreConfigCommand.java:23)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[22:21:13] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by ReikaKalseki** [comment]
I added some new debug info.
