### ISSUE TITLE
[DragonAPI] server crash during world load

### ISSUE THREAD

**Issue by gabriel-nsiqueira** [ReikaKalseki/Reika_Mods_Issues#2435]
I typed /stop then changed allow-flight option to true then started the server and this error appeared and the server crashed:
[22:51:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.loadCacheAndUpdate(VersionTransitionTracker.java:52) ~[VersionTransitionTracker.class:?]
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.onWorldLoad(VersionTransitionTracker.java:38) ~[VersionTransitionTracker.class:?]
	at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.checkModChanges(DragonAPIEventWatcher.java:143) ~[DragonAPIEventWatcher.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_317_DragonAPIEventWatcher_checkModChanges_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by ReikaKalseki** [comment]
#2397 #2413 #2420 #2422
