### ISSUE TITLE
Path checking on repeaters causes disconnect with multipart blocks.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#244]
If i right click a crystal repeater which's path is blocked by a multipart block (in my case a forge microblocks sandstone panel), the client will be disconnected with "Internal server error" and the server log shows the below error. The client can reconnect normally afterwards.
The repeater with the microblock on top reports a working path if it has air or the microblock above it, but will be blocked if a full block is put above it.

```
java.lang.ClassCastException: TileMultipart_cmp$$0 cannot be cast to Reika.ChromatiCraft.Magic.Interfaces.CrystalTransmitter
        at Reika.ChromatiCraft.Magic.Network.CrystalPath.stillValid(CrystalPath.java:108) ~[CrystalPath.class:?]
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.checkExistingPaths(PylonFinder.java:140) ~[PylonFinder.class:?]
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylonWith(PylonFinder.java:78) ~[PylonFinder.class:?]
        at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:73) ~[PylonFinder.class:?]
        at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.checkConnectivity(CrystalNetworker.java:173) ~[CrystalNetworker.class:?]
        at Reika.ChromatiCraft.TileEntity.Networking.TileEntityCrystalRepeater.checkConnectivity(TileEntityCrystalRepeater.java:170) ~[TileEntityCrystalRepeater.class:?]
        at Reika.ChromatiCraft.Items.Tools.ItemManipulator.func_77648_a(ItemManipulator.java:205) ~[ItemManipulator.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

A "carpenter's wedge slope" causes the same error.

```
java.lang.ClassCastException: com.carpentersblocks.tileentity.TEBase cannot be cast to Reika.ChromatiCraft.Magic.Interfaces.CrystalTransmitter
```

![pylon_route_small](https://cloud.githubusercontent.com/assets/14168854/9804024/4a131246-5829-11e5-903f-53bdbf5f8a3f.jpg)

**Comment by ReikaKalseki** [comment]
Fixed.
