### ISSUE TITLE
[rotarycraft]crashed with extractor

### ISSUE THREAD

**Issue by syf097** [ReikaKalseki/Reika_Mods_Issues#247]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 15-9-11 下午8:29
Description: Ticking block entity

java.lang.ExceptionInInitializerError
    at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.canProcess(TileEntityExtractor.java:288)
    at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.testIdle(TileEntityExtractor.java:89)
    at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.updateEntity(TileEntityExtractor.java:210)
    at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:432)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.UnsupportedOperationException: This map does not support overwriting values! Item tile.brOre.0:0 already mapped to '1xitem.item.modextracts@40'!
    at Reika.DragonAPI.Instantiable.Data.Maps.ItemHashMap.put(ItemHashMap.java:66)
    at Reika.DragonAPI.Instantiable.Data.Maps.ItemHashMap.put(ItemHashMap.java:82)
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.addRecipe(RecipesExtractor.java:105)
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.addModRecipes(RecipesExtractor.java:75)
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.<init>(RecipesExtractor.java:55)
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.<clinit>(RecipesExtractor.java:32)
    ... 11 more

**Comment by ljfa-ag** [comment]
Can you provide the entire crash report (with something like gist or pastebin), and how to repoduce this?

**Comment by syf097** [comment]
when i put ores into extractor, it crashed.
the entire report is here(Current Language is chinese)
http://pastebin.com/9i1HeDK0

there is another report
http://pastebin.com/7b0BTNT1

**Comment by syf097** [comment]
if you still want to have more info,check it
http://openeye.openmods.info/crashes/d144de8cc0e14887559308f12c2069c7

**Comment by ReikaKalseki** [comment]
This is the AOBD issue. Again.

**Comment by ljfa-ag** [comment]
Ah I didn't recognize that..
