### ISSUE TITLE
ReactorCraft crashes when breaking a Solenoid block

### ISSUE THREAD

**Issue by scrouthtv** [ReikaKalseki/Reika_Mods_Issues#2491]
I was breaking a Ferromagnetic Base Block of the Solonoid magnet:
![image](https://user-images.githubusercontent.com/23227405/81504643-bda60c80-92ea-11ea-9bae-179049d6387f.png)
``` 
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10.05.20 18:16
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Reika/ChromatiCraft/TileEntity/AOE/Defence/TileEntityExplosionShield
	at Reika.DragonAPI.Instantiable.FlyingBlocksExplosion.func_77278_a(FlyingBlocksExplosion.java:72)
	at Reika.DragonAPI.Instantiable.FlyingBlocksExplosion.doExplosion(FlyingBlocksExplosion.java:51)
	at Reika.ReactorCraft.TileEntities.Fusion.TileEntitySolenoidMagnet.fail(TileEntitySolenoidMagnet.java:72)
	at Reika.ReactorCraft.TileEntities.Fusion.TileEntitySolenoidMagnet.testBreakageFailure(TileEntitySolenoidMagnet.java:66)
	at Reika.ReactorCraft.TileEntities.Fusion.TileEntitySolenoidMagnet.setHasMultiBlock(TileEntitySolenoidMagnet.java:60)
	at Reika.ReactorCraft.Blocks.Multi.BlockSolenoidMulti.breakMultiBlock(BlockSolenoidMulti.java:317)
	at Reika.ReactorCraft.Base.BlockMultiBlock.func_149749_a(BlockMultiBlock.java:88)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:240)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:278)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:151)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: Reika.ChromatiCraft.TileEntity.AOE.Defence.TileEntityExplosionShield
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 28 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1013605776 bytes (966 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAAAAAAA	DragonAPI{v25c} [DragonAPI] (DragonAPI+1.7.10+V25c.jar) 
	UCHIJAAAAAAAAA	RotaryCraft{v25b} [RotaryCraft] (RotaryCraft+1.7.10+V25b.jar) 
	UCHIJAAAAAAAAA	ReactorCraft{v25b} [ReactorCraft] (ReactorCraft+1.7.10+V25b.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['ScrouthTV'/6940, l='New World', x=-196,88, y=68,87, z=-760,76]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by ReikaKalseki** [comment]
I assume you do not have CC installed?

**Comment by scrouthtv** [comment]
Negative.

**Comment by ReikaKalseki** [comment]
Fixed.
