### ISSUE TITLE
Leaf Decay Causing Crash

### ISSUE THREAD

**Issue by Zebralear** [ReikaKalseki/Reika_Mods_Issues#2530]
I’m currently using V26a of Chromaticraft and DragonAPI. I am trying to use a multiplayer server, but whenever I get close to land, it crashes. Upon inspection of the log, it says there was an error parsing Reika’s leaf decay. I can’t replicate this in single player, and it’s probably just mod interaction, but I’m posting this on the off chance it’ll help...

**Comment by andrewlear** [comment]
java.lang.NoSuchMethodError: net.minecraft.world.IBlockAccess.func_72807_a(II)Lnet/minecraft/world/biome/BiomeGenBase;
at Reika.ChromatiCraft.ChromaticEventManager.stopBiggerOakDecay(ChromaticEventManager.java:297)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_194_ChromaticEventManager_stopBiggerOakDecay_LeafDecayEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at Reika.DragonAPI.Instantiable.Event.LeafDecayEvent.fire(LeafDecayEvent.java:31)
at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:132)
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Mimic0445** [comment]
I get this crash using only the required mods and Fast Leaf Decay.
Disabling fast leaf decay to an already crashing world does not stop it from crashing.

**Comment by Schadrach** [comment]
Received the same error.  

When I play with the same set of mods in SSP it works fine, but when I run a SMP server it crashes with that error the moment a player joins.  Was using treecapitator (only mod I could think of that would effect leaf decay that was installed), disabling treecapitator makes no difference whether on that world or a completely new one.

**Comment by ReikaKalseki** [comment]
This is already fixed.
