### ISSUE TITLE
[Chromaticraft] Item Duplication Ability on Item Fabricator

### ISSUE THREAD

**Issue by Arcaneless** [ReikaKalseki/Reika_Mods_Issues#2536]
The console throws an exception while the Item duplication (DOUBLECRAFT) ability acts on the Item fabricator:
DRAGONAPI ERROR: Tile Entity Item Fabricator @ DIM0: -91, 68, 212 [SERVER] is throwing class java.lang.ArrayIndexOutOfBoundsException on update: 2
 java.lang.ArrayIndexOutOfBoundsException: 2
 at Reika.DragonAPI.Libraries.ReikaInventoryHelper.addOrSetStack(ReikaInventoryHelper.java:1210)
 at Reika.ChromatiCraft.TileEntity.Acquisition.TileEntityItemFabricator.craft(TileEntityItemFabricator.java:224)
 at Reika.ChromatiCraft.TileEntity.Acquisition.TileEntityItemFabricator.onCraftingTick(TileEntityItemFabricator.java:192)
 at Reika.ChromatiCraft.TileEntity.Acquisition.TileEntityItemFabricator.updateEntity(TileEntityItemFabricator.java:151)
 at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:543)
 at net.minecraft.world.World.func_72939_s(World.java:1939)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
 at fastcraft.u.a(F:289)
 at fastcraft.H.aq(F:36)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Outcome: the item fabricator will not produce any product and will restart the fabricating process over and over.

I believe you may use the addOrSetStack method wrong?

**Comment by OvermindDL1** [comment]
The code was changed recently:
```diff
-                       ReikaInventoryHelper.addOrSetStack(recipe.output.copy(), inv, 1);
+                       int n = 1;
+                       EntityPlayer ep = this.getPlacer();
+                       if (ep != null && !ReikaPlayerAPI.isFake(ep) && Chromabilities.DOUBLECRAFT.enabledOn(ep))
+                               n = 2;
+                       ReikaInventoryHelper.addOrSetStack(recipe.output.copy(), inv, n);
```
The last argument in `ReikaInventoryHelper.addOrSetStack` is the slot number, not a count or so, and slot `2` doesn't exist on this inventory, think the recipe output's copy was meant to be doubled (or `ReikaInventoryHelper.addOrSetStack` called twice?).

**Comment by ReikaKalseki** [comment]
Did I make that mistake in any of the other places I added the doubling?

**Comment by OvermindDL1** [comment]
I haven't looked at the commit log in detail, would be a lot easier to do within your IDE.  :-)

**Comment by ReikaKalseki** [comment]
No, none of the others were inventory code.
