### ISSUE TITLE
Casting delegate error spam

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#256]
When placing a casting delegate in a temple instead of the crafting table it first gives this error

```
[03:46:15] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Item Casting Stand @ DIM0: -1271, 2, 760 is throwing class java.lang.ClassCastException on update: Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingAuto cannot be cast to Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException: Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingAuto cannot be cast to Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityItemStand.updateEntity(TileEntityItemStand.java:57)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:432)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03:46:15] [Client thread/INFO]: [CHAT] Tile Entity Item Casting Stand @ DIM0: -1273, 3, 756 is throwing class java.lang.ClassCastException on update: null
[03:46:15] [Client thread/INFO]: [CHAT] []
[03:46:15] [Client thread/INFO]: [CHAT] 
```

then continues to spam this:

```
[03:46:15] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Item Casting Stand @ DIM0: -1273, 3, 756 is throwing class java.lang.ClassCastException on update: null
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException
[03:46:15] [Client thread/INFO]: [CHAT] Tile Entity Item Casting Stand @ DIM0: -1271, 2, 762 is throwing class java.lang.ClassCastException on update: null
[03:46:15] [Client thread/INFO]: [CHAT] []
```

```
[03:46:15] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Item Casting Stand @ DIM0: -1273, 2, 756 is throwing class java.lang.ClassCastException on update: null
[03:46:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException
[03:46:15] [Client thread/INFO]: [CHAT] Tile Entity Item Casting Stand @ DIM0: -1271, 3, 762 is throwing class java.lang.ClassCastException on update: null
[03:46:15] [Client thread/INFO]: [CHAT] []
```

for more than 500 times per second until destroyed.

PS: I have ofc no clue how to use that thing properly.

**Comment by ReikaKalseki** [comment]
This is not going to break anything. Until then, just do not place it there.
