### ISSUE TITLE
Payload may not be larger than 32K

### ISSUE THREAD

**Issue by helphelphelpplease** [ReikaKalseki/Reika_Mods_Issues#2562]
This is a weird one, as only I have it, and it doesnt appear to be my instance, considering i got the exact same as a friend of mine for whom it works, AND i tried reinstalling cc.
Anyhow folowing is the problem: When i look at the magic colourful trees, or rainbow trees, i will sometimes instantly get a crash. if it doesnt happen instalty it will happen after the block description has foldet out completely and the text appears i get the following error:

20:09:48.937
NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32k
	at net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120)
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
	at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)

both seem to have the same (im not 100% percent sure on this, but in testing couldt get a instant crash anymore, so if i get one again i will update with its report)

we figuered this is like a texture problem with the letters, but wouldn't know how to act on that.

Now this is definetly annoying, but not unplayable. the problem occurs when i try to hold the elemental manipulator in my hand. I get the following crash:

NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32k
	at net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120)
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
	at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)

hope you can help me, its stopping me from enjoying your mod

**Comment by ReikaKalseki** [comment]
That implies your player NBT is massively overloaded. Open it with an NBT editor.

**Comment by helphelphelpplease** [comment]
Hello Reika, i dont know what that means, however here is my player data:
[WinRAR-ZIP-Archiv (neu).zip](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/4765055/WinRAR-ZIP-Archiv.neu.zip)

I hope it helps because i really want to play your mod!

**Comment by ReikaKalseki** [comment]
Open your player data with an NBT editor like NBTExplorer.

**Comment by helphelphelpplease** [comment]
do you want me to send you a screenshot of the opened nbt editor, or look for something specific?

**Comment by ReikaKalseki** [comment]
The latter. Is there a large quantity of data under any particular tags?

**Comment by helphelphelpplease** [comment]
![image](https://user-images.githubusercontent.com/64865907/84579148-f0509280-adcb-11ea-8ecc-39c924e81876.png)
well im sorry, im not really knowledge about that. however i do remember my server technician telling me i had less entries than him or something, its all quite weird really... there should be a screenshot added to this if i didnt fuck it up

**Comment by ReikaKalseki** [comment]
Top-level entry count is not relevant; look into the data and see if any of them are absurdly large.
