### ISSUE TITLE
[ReactorCraft/Electricraft] [v26b] Removing electricraft wire from active reactorcraft multiblock generator, results in an NPE.

### ISSUE THREAD

**Issue by Vectrobe** [ReikaKalseki/Reika_Mods_Issues#2568]
Build multiblock generator, set it to electricraft output, run a simple wire to a motor, power the generator with a turbine, break the wire directly attached to the generator and NPE;

`java.lang.NullPointerException: Exception in server tick loop
	at Reika.ElectriCraft.Network.WirePath.<init>(WirePath.java:53)
	at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:137)
	at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:149)
	at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:149)
	at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:149)
	at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:149)
	at Reika.ElectriCraft.Network.PathCalculator.calculatePaths(PathCalculator.java:83)
	at Reika.ElectriCraft.Network.WireNetwork.recalculatePaths(WireNetwork.java:401)
	at Reika.ElectriCraft.Network.WireNetwork.doRepath(WireNetwork.java:166)
	at Reika.ElectriCraft.Network.WireNetwork.repath(WireNetwork.java:160)
	at Reika.ElectriCraft.ElectriNetworkManager.tick(ElectriNetworkManager.java:58)
	at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.serverTick(TickRegistry.java:89)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_150_TickRegistry_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
`

**Comment by ReikaKalseki** [comment]
Fixed.
