### ISSUE TITLE
Casting delegate client crash.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#257]
Trying to figure out how the casting delegate works... (at least i've figured out where to place it). I tried putting Karmir rune into the upper left slot and the client crashed (for the second time). It crashed before too when i put an ME Assembler. Actually it might be doing the crashing when i left click the slot a second time with the item still "on the cursor". It didn't crash with e.g. a crystal core though.

```
[04:32:30] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392) ~[blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source) ~[?:1.7.0_80]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.7.0_80]
    at Reika.ChromatiCraft.GUI.Tile.GuiCastingAuto.getRecipe(GuiCastingAuto.java:80) ~[GuiCastingAuto.class:?]
    at Reika.ChromatiCraft.GUI.Tile.GuiCastingAuto.func_146979_b(GuiCastingAuto.java:175) ~[GuiCastingAuto.class:?]
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119) ~[bex.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358) ~[blt.class:?]
    ... 9 more
[04:32:30] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 9/14/15 4:32 AM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at Reika.ChromatiCraft.GUI.Tile.GuiCastingAuto.getRecipe(GuiCastingAuto.java:80)
    at Reika.ChromatiCraft.GUI.Tile.GuiCastingAuto.func_146979_b(GuiCastingAuto.java:175)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at Reika.ChromatiCraft.GUI.Tile.GuiCastingAuto.getRecipe(GuiCastingAuto.java:80)
    at Reika.ChromatiCraft.GUI.Tile.GuiCastingAuto.func_146979_b(GuiCastingAuto.java:175)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
```

**Comment by ReikaKalseki** [comment]
What was on the screen before it crashed? Something went very wrong, in the "this should never have happened" category.

**Comment by lossycrypt** [comment]
I'm not sure how you want me to answer that. There were no visual abnormalities. So basically there's the gui of the casting delegate with the casting temple and some walls "on the screen".

Edit:
Reproducing this works (for me) as following: open the gui, "imprint" an item onto the upper left slot (of which the delegate does not know the recipie or that has not been crafted with the table?), put item back in inventory so your mouse is empty. Then click left mouse button on the "imprinted" slot very fast. (Confirmed to be exactly the same error message as above)
I've also made a small video should you need that, doen't show much tho. Contanct me on irc for that.

**Comment by ReikaKalseki** [comment]
What was in the GUI (and did an action of yours trigger it)?

**Comment by lossycrypt** [comment]
Please read the desctiption given in the edit above.
And here is the video: http://www.xup.in/dl,95399278/delegate-lmb-spam-crash.mkv/

**Comment by lossycrypt** [comment]
As you mentioned that above site does not work for you, here's another link:
http://wikisend.com/download/617684/delegate-lmb-spam-crash.mkv

**Comment by ReikaKalseki** [comment]
It does not crash for me. Instead, nothing happens.

EDIT:
OK, it crashes, but not on button click. It crashes on GUI close.

**Comment by ReikaKalseki** [comment]
Fixed.
