### ISSUE TITLE
Chromaticraft crash

### ISSUE THREAD

**Issue by flyingperson23** [ReikaKalseki/Reika_Mods_Issues#2595]
[pastebin](https://pastebin.com/SvTL8VQT)

It's probably something stupid but I can't seem to figure it out

**Comment by lAimBotl** [comment]
did you try launching it again? it always gives me that crash one time when I add/remove a mod.

**Comment by flyingperson23** [comment]
Yep I tried starting it at least 5 times, always gave the same crash

**Comment by lAimBotl** [comment]
maybe #1493 can help

"Go to your config folder, next to AppliedEnergistics2 folder and open CustomRecipes.cfg file and edit the value exportItemNames form true to false. Everything should be working fine now."

**Comment by ReikaKalseki** [comment]
#1732 #1683 #1681 #1493 #1257 #1280 #1238 #2390 #1848 #1985 #2419 #2502

**Comment by flyingperson23** [comment]
I'm by no means an experienced modder but I know you're not opposed to changing other mods, why don't you simply change the ae2 config file on startup to make it work so it stops being reported?

**Comment by ReikaKalseki** [comment]
That is not a reliable fix given the fact a crash is likely to happen before that point, and besides, the issue is trivial enough that it is not worth the effort.

**Comment by ghost** [comment]
Hello Reika.
How are you? I and my friend very like you.
We want play with your mods RoteryCraft and ChromatikCraft.
But we don't start game with this two mods.
We install DragonsAPI.jar ChromatikCraft.jar and RoteryCraft.jar
Wen we run game forge load 1 minutes and crush.
Crush logs

> `---- Minecraft Crash Report ----
// Don't do that.

Time: 26.03.21 11:26
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/Render/ISBRH/CrystalRenderer
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: Reika/ChromatiCraft/Render/ISBRH/CrystalRenderer
	at Reika.ChromatiCraft.ChromaClient.<clinit>(ChromaClient.java:189)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: Reika.ChromatiCraft.Render.ISBRH.CrystalRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: Reika/DragonAPI/Interfaces/ISBRH
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: Reika.DragonAPI.Interfaces.ISBRH
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 203623192 bytes (194 MB) / 503316480 bytes (480 MB) up to 2952790016 bytes (2816 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx2814M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UC	DragonAPI{v29c} [DragonAPI] (DragonAPI+1.7.10+V29c.jar) 
	UE	ChromatiCraft{v26b} [ChromatiCraft] (ChromatiCraft+1.7.10+V26b.jar) 
	UC	RotaryCraft{v29b} [RotaryCraft] (RotaryCraft1.7.10V29b.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4252' Renderer: 'Intel(R) HD Graphics'`

Can you help as?

**Comment by ReikaKalseki** [comment]
One, you are posting about a completely unrelated crash in this issue.
Two, it is crashing because you installed them incorrectly.
Three, those jar names are not what I call them, and if you are transcribing them correctly you are using some third party garbage from who knows what site.
