### ISSUE TITLE
(DragonAPI & RotaryCraft) Not opening together

### ISSUE THREAD

**Issue by FallenKing699** [ReikaKalseki/Reika_Mods_Issues#2650]
Reika.DragonAPI.Exception.IDConflictException: The mods were not installed correctly:
CONFLICT: RotaryCraft - Potion IDs: com.emoniph.witchery.brewing.potions.PotionSpiked@2dfd225c @ ID 35 (PotionSpiked & FreezePotion)
Check your IDs and change them if possible.
This is NOT a mod bug. Do not post it or ask for support or you will look lazy or extremely foolish..
	at Reika.DragonAPI.Auxiliary.Trackers.IDCollisionTracker.check(IDCollisionTracker.java:102)
	at Reika.DragonAPI.DragonAPIInit.postload(DragonAPIInit.java:531)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62

**Comment by ReikaKalseki** [comment]
I suggest you read what you posted.

**Comment by FallenKing699** [comment]
i read it before posting and don't know what to do
