### ISSUE TITLE
Rendering just.. fails?  Rendering error while loading DragonAPI causes nothing to render and for the Minecraft display to jusf\t \

### ISSUE THREAD

**Issue by TsmDan3** [ReikaKalseki/Reika_Mods_Issues#2667]
I have no idea what is hapenning, but here's the error that appears.

`[14:13:13] [Client thread/ERROR]: DRAGONAPI ERROR: Error when handling MODLOCK packet [type STRING; Data: [0, 0, 0, 0, 0, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] from Reika.DragonAPI.APIPacketHandler (ID 0)]: java.lang.ArrayIndexOutOfBoundsException: 1
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 1
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Auxiliary.Trackers.ModLockController.readSync(ModLockController.java:94)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.APIPacketHandler.clientHandle(APIPacketHandler.java:464)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.APIPacketHandler.handleData(APIPacketHandler.java:388)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper$PacketObj.handleClient(ReikaPacketHelper.java:1703)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:157)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.IO.PacketPipeline$InternalHandler.onMessage(PacketPipeline.java:147)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:13:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:13:14] [Client thread/INFO]: DragonAPI: Running patcher TILERENDER [net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher/bmk]
[14:13:14] [Client thread/INFO]: DragonAPI: Successfully applied TILERENDER [net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher/bmk] ASM handler!`

**Comment by thehajo** [comment]
Please either upload the crash report here directly or upload it to https://pastebin.com/ and post the link here.

**Comment by ReikaKalseki** [comment]
That error is entirely unrelated, and is only a packet failing to parse.

If I had to guess as to your issue, it would be these: #2315 #2495 #2260 #2368 #2440 #2460 #2606 #2610 #2516

**Comment by TsmDan3** [comment]
https://pastebin.com/iLq8ERpG

sorry for long response time

**Comment by ReikaKalseki** [comment]
So yes.
