### ISSUE TITLE
Every time I try to create or enter a world with the new version of dragonapi this error appears:    

### ISSUE THREAD

**Issue by brunoquiz2** [ReikaKalseki/Reika_Mods_Issues#2686]
---- Minecraft Crash Report ----
// There are four lights!

Time: 26/12/20 20:30
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/gen/layer/GenLayerAddIsland
	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:40)
	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:48)
	at net.minecraft.world.WorldType.getChunkManager(WorldType.java:143)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:61)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
	at net.minecraft.world.World.<init>(World.java:244)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at WorldServerOF.<init>(WorldServerOF.java:69)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.gen.layer.GenLayerAddIsland
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: Reika.DragonAPI.Exception.ASMException$NoSuchASMMethodException: Error ASMing net/minecraft/world/gen/layer/GenLayerAddIsland:
Method func_75901_a (JLnet/minecraft/world/WorldType;)[Lnet/minecraft/world/gen/layer/GenLayer; not found in class net/minecraft/world/gen/layer/GenLayerAddIsland.
This is a critical ASM error and the class transformer operation cannot proceed. If you are the developer of this mod, check for proper use of SRG/deobf names and/or sideonly elements. If not, report it to the developer.

Additional information:
Identified methods:
	<init> (JLnet/minecraft/world/gen/layer/GenLayer;)V
	func_75904_a (IIII)[I

	at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getMethodByName(ReikaASMHelper.java:161)
	at Reika.DragonAPI.ASM.Patchers.Hooks.Event.World.Gen.BeachGenLayerEvent.apply(BeachGenLayerEvent.java:32)
	at Reika.DragonAPI.ASM.Patchers.Patcher.apply(Patcher.java:81)
	at Reika.DragonAPI.ASM.DragonAPIClassTransformer.transform(DragonAPIClassTransformer.java:98)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 827984720 bytes (789 MB) / 1864908800 bytes (1778 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAA	DragonAPI{v27a} [DragonAPI] (DragonAPI+1.7.10+V27a.jar) 
	UCHIJAA	CaveControl{v27a} [CaveControl] (CaveControl+1.7.10+V27a.jar) 
	UCHIJAA	ChromatiCraft{v27a} [ChromatiCraft] (ChromatiCraft+1.7.10+V27a.jar) 
	UCHIJAA	CondensedOres{v27a} [Condensed Ores] (CondensedOres+1.7.10+V27a.jar) 
	UCHIJAA	CritterPet{v27a} [Critter Pet] (CritterPet+1.7.10+V27a.jar) 
	UCHIJAA	RotaryCraft{v27a} [RotaryCraft] (RotaryCraft+1.7.10+V27a.jar) 
	UCHIJAA	ElectriCraft{v27a} [ElectriCraft] (ElectriCraft+1.7.10+V27a.jar) 
	UCHIJAA	ExpandedRedstone{v27a} [Expanded Redstone] (ExpandedRedstone+1.7.10+V27a.jar) 
	UCHIJAA	GeoStrata{v27a} [GeoStrata] (GeoStrata+1.7.10+V27a.jar) 
	UCHIJAA	LegacyCraft{v27a} [LegacyCraft] (LegacyCraft+1.7.10+V27a.jar) 
	UCHIJAA	LootTweaks{v27a} [LootTweaks] (LootTweaks+1.7.10+V27a.jar) 
	UCHIJAA	MeteorCraft{v27a} [MeteorCraft] (MeteorCraft+1.7.10+V27a.jar) 
	UCHIJAA	ReactorCraft{v27a} [ReactorCraft] (ReactorCraft+1.7.10+V27a.jar) 
	UCHIJAA	TerritoryZone{v27a} [TerritoryZone] (TerritoryZone+1.7.10+V27a.jar) 
	UCHIJAA	TreeClimbing{v@MAJOR_VERSION@@MINOR_VERSION@} [TreeClimbing] (TreeClimbing+1.7.10+V27a.jar) 
	UCHIJAA	UsefulTNT{v27a} [Useful TNT] (UsefulTNT+1.7.10+V27a.jar) 
	UCHIJAA	VoidMonster{v27a} [Void Monster] (VoidMonster+1.7.10+V27a.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D4
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: AMD Radeon(TM) R7 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by ReikaKalseki** [comment]
#2684

**Comment by brunoquiz2** [comment]
how can i fix it ?

**Comment by ReikaKalseki** [comment]
Read it.
