### ISSUE TITLE
[Help][Chromaticraft v27d] Minecraft Server crashing when I try joining it

### ISSUE THREAD

**Issue by Tokopisco** [ReikaKalseki/Reika_Mods_Issues#2706]
My server crash when i try joining it.

java.lang.NoSuchMethodError: net.minecraft.world.IBlockAccess.func_72807_a(II)Lnet/minecraft/world/biome/BiomeGenBase;
	at Reika.DragonAPI.Instantiable.Event.Base.PositionEventBase.getBiome(PositionEventBase.java:35)
	at Reika.ChromatiCraft.ChromaticEventManager.allowCliffGrassCrops(ChromaticEventManager.java:718)

Pastebin : https://pastebin.pl/view/ff10dffb

**Comment by ReikaKalseki** [comment]
#2696 #2699
