### ISSUE TITLE
[Chromaticraft]Mystery Save Damage

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2708]
In a computer failure, the save is damaged for unknown reasons, and it will crash if you enter it again. Can this problem be recovered?

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 21-1-4 下午8:18
Description: Exception getting block type in world

java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at codechicken.chunkloader.ChunkLoaderManager.load(ChunkLoaderManager.java:496)
	at codechicken.chunkloader.ChunkLoaderEventHandler.onChunkDataLoad(ChunkLoaderEventHandler.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_270_ChunkLoaderEventHandler_onChunkDataLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at net.minecraft.server.management.ServerConfigurationManager.func_152596_g(ServerConfigurationManager.java:717)
	at codechicken.core.ServerUtils.isPlayerOP(ServerUtils.java:85)
	at codechicken.chunkloader.ChunkLoaderManager.allowOffline(ChunkLoaderManager.java:582)
	at codechicken.chunkloader.ChunkLoaderManager.loadPlayerChunks(ChunkLoaderManager.java:543)
	at codechicken.chunkloader.ChunkLoaderManager.load(ChunkLoaderManager.java:492)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.chunkloader.ChunkLoaderManager.load(ChunkLoaderManager.java:496)
	at codechicken.chunkloader.ChunkLoaderEventHandler.onChunkDataLoad(ChunkLoaderEventHandler.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_270_ChunkLoaderEventHandler_onChunkDataLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (140,64,248), Chunk: (at 12,4,8 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)

-- Affected level --
Details:
	Level name: test
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 5073047148131647126
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1303479968 bytes (1243 MB) / 2181038080 bytes (2080 MB) up to 4294967296 bytes (4096 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.7.0
	LaunchWrapper: 41 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: Reika.ChromatiCraft.Auxiliary.ChromaASMHandler$ASMExecutor
          - Transformer: Reika.DragonAPI.ASM.InterfaceInjector
          - Transformer: Reika.DragonAPI.ASM.APIStripper
          - Transformer: Reika.DragonAPI.ASM.DragonAPIClassTransformer
          - Transformer: Reika.DragonAPI.ASM.FMLItemBlockPatch
          - Transformer: Reika.DragonAPI.ASM.FluidNamePatch
          - Transformer: Reika.DragonAPI.ASM.DependentMethodStripper
          - Transformer: Reika.DragonAPI.ASM.ClassReparenter
          - Transformer: Reika.DragonAPI.ASM.Profiling.WorldGeneratorProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.Profiling.MapGeneratorProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.Profiling.ChunkInitProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.StructureLootHooks
          - Transformer: Reika.DragonAPI.ASM.SpecialBiomePlacement
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 5, tallocated: 67
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAA	ChickenChunks{1.3.4.16} [ChickenChunks] ([区块载入]ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAA	DragonAPI{v26b} [DragonAPI] (DragonAPI+1.7.10+V26b.jar) 
	UCHIJAA	ChromatiCraft{v26b} [ChromatiCraft] (ChromatiCraft+1.7.10+V26b.jar) 
	UCHIJAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAA	ItemRender{@VERSION@} [Item Render] (ItemRenderRebirth_V1.0.0_MC1.7.10.jar) 
	UCHIJAA	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.7.10-2.1.jar) 
	UCHIJAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins-1.1.0.11.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ReikaKalseki** [comment]
Why are you posting this here and titling it 'ChromatiCraft'? It has nothing to do with me.
