### ISSUE TITLE
dragon api chrashing when I open a new world.

### ISSUE THREAD

**Issue by OG35th123** [ReikaKalseki/Reika_Mods_Issues#2722]
here is my error code.
it is long btw

---- Minecraft Crash Report ----
// My bad.

Time: 1/11/21 5:31 PM
Description: Invalid Biome id

java.lang.NullPointerException: Invalid Biome id
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:76)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:26)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
	at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:58)
	at net.minecraft.world.gen.structure.MapGenScatteredFeature.func_75047_a(SourceFile:63)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_82695_e(ChunkProviderGenerate.java:498)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:76)

-- DownfallBlock --
Details:
	biome id: 128
	downfalls[] size: 256
	x: 192
	z: 80
	w: 16
	h: 16
Stacktrace:
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:76)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:26)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
	at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:58)
	at net.minecraft.world.gen.structure.MapGenScatteredFeature.func_75047_a(SourceFile:63)

-- Feature being prepared --
Details:
	Is feature chunk: ~~ERROR~~ ReportedException: Invalid Biome id
	Chunk location: 12,5
	Chunk pos hash: 21474836492
	Structure type: net.minecraft.world.gen.structure.MapGenScatteredFeature
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_82695_e(ChunkProviderGenerate.java:498)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1996788840 bytes (1904 MB) / 2571108352 bytes (2452 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms2048m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAA	AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJAA	appliedenergistics2{rv0-stable-10} [Applied Energistics 2] (appliedenergistics2-rv0-stable-10.jar) 
	UCHIJAA	DragonAPI{v28a} [DragonAPI] (DragonAPI+1.7.10+V28a.jar) 
	UCHIJAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031.jar) 
	UCHIJAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.7.10-9.1.1.1031.jar) 
	UCHIJAA	stefinusguns{0.3} [New Stefinus Guns] (Stefinus+Guns-0.3.jar) 
	UCHIJAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
	AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:OFF, MJ5:OFF, MJ6:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, Waila:OFF, CLApi:OFF, RB:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, FMP:ON
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by lmentrix2** [comment]
Lo siento si comento en este error en español pero es curioso los mods que requerían Dragon API me servian en versiones anteriores pero actualmente no en Windows ahora tengo también linux lo probé y no me sale el error pero hay texturas de minecraft como dañadas, solo digo algo paso que se modifico el OpenGL que no permita unas funciones

**Comment by ReikaKalseki** [comment]
One, that is not in a language anyone here knows. Two, OpenGL has nothing to do with the issue posted here.

@OG35th123 Does this happen reliably?

**Comment by rogerwim** [comment]
I have the same problem, on the newest version, have only electricraft RotaryCraft and reactorcraft installed

It happens with normal worlds, not superflat, smells like ore gen bug

**Comment by ReikaKalseki** [comment]
The only mod of mine he has is DAPI, which does not even add any ores.

Come to think of it, that also means a lot of potential explanations do not apply.

**Comment by OG35th123** [comment]
@ReikaKalseki it happens every time I make a new world or join one. It is dragon API that is the issue. I can remove all other mods and it still does not work but when I remove dragon API it does work.

**Comment by chulindo** [comment]
@ReikaKalseki same issue here. I'm getting the OpenGL context error every time I open or create a world that isn't superflat. 
When I open a superflat world I get a message in the text box that reads "OpenGL Error: 1282 (Invalid Operation)" It is indeed only being caused by DragonAPI which is really strange

**Comment by ReikaKalseki** [comment]
OpenGL has nothing to do with the issue reported here.
