### ISSUE TITLE
[ChromatiCraft] Lost player progression data (with Advent of Ascension mod)

### ISSUE THREAD

**Issue by ZaadvanSatan** [ReikaKalseki/Reika_Mods_Issues#2735]
I had made my own modpack, but I could unlock the progression again even though I had unlock it already (the blur effect and unlock sound occurred again).
This could cause me lose all my progressions.
Then I found that this could only happen with Advent of Ascension mod in my modpack.
Will this issue be fixed?

Error messages from log is below
> [00:40:27] [Server thread/WARN] [FML]: ****************************************
[00:40:27] [Server thread/WARN] [FML]: * ChromatiCraft: Player [PlayerID] just lost some of their progression!
[00:40:27] [Server thread/WARN] [FML]: *  at Reika.ChromatiCraft.Magic.Progression.ProgressionLoadHandler.updateProgressCache(ProgressionLoadHandler.java:132)
[00:40:27] [Server thread/WARN] [FML]: *  at Reika.ChromatiCraft.Magic.Progression.ProgressionManager.setPlayerDiscoveredColor(ProgressionManager.java:665)
[00:40:27] [Server thread/WARN] [FML]: *  at Reika.ChromatiCraft.Auxiliary.ExplorationMonitor.tick(ExplorationMonitor.java:54)
[00:40:27] [Server thread/WARN] [FML]: *  at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.playerTick(TickRegistry.java:49)
[00:40:27] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.eventhandler.ASMEventHandler_453_TickRegistry_playerTick_PlayerTickEvent.invoke(.dynamic)
[00:40:27] [Server thread/WARN] [FML]: *  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)...
[00:40:27] [Server thread/WARN] [FML]: ****************************************

**Comment by ReikaKalseki** [comment]
#2139 #1852
