### ISSUE TITLE
DragonAPI v.28a Crash

### ISSUE THREAD

**Issue by JustForMinecraft6** [ReikaKalseki/Reika_Mods_Issues#2739]
So lately i went lookin for some minecraft 1..7.10 mods i discovered chromaticraft and fell in love so i found out that i needed DragonAPI For Chromaticraft so i downloaded DragonAPI First to see if it would work
Everything starts up all nice and then when i try to load a new world I get this reinstalling wont work
Restarting wont work
Pls Help
Also here is the crash report i think it isnt too long

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 01.02.21 10:22
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderGenerate.func_147423_a(ChunkProviderGenerate.java:269)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_147424_a(ChunkProviderGenerate.java:110)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:212)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderGenerate.func_147423_a(ChunkProviderGenerate.java:269)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_147424_a(ChunkProviderGenerate.java:110)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:212)

-- Chunk to be generated --
Details:
	Location: 0,0
	Position hash: 0
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)

-- Affected level --
Details:
	Level name: New World----
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: -6397700457039059949
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 283910936 bytes (270 MB) / 469762048 bytes (448 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAA	DragonAPI{v28a} [DragonAPI] (DragonAPI+1.7.10+V28a (1).jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

See not too long

**Comment by ReikaKalseki** [comment]
At no point does that mention my code. Why do you think it is involved?

**Comment by rogerwim** [comment]
You are absolutely correct, please list what mods you are using and why it's related to Reika's mods

**Comment by Acroficer** [comment]
I actually came to post the same error, it occurs when I have only DragonAPI enabled and no other mods, and stops happening as soon as I disable DragonAPI.

**Comment by Acroficer** [comment]
Nevermind, it was an issue on my end. I suspected as much but couldn't track it down before. I upgraded from recommended Forge version 1558 to the newest version 1614.
