### ISSUE TITLE
Server crash DragonAPI 29a

### ISSUE THREAD

**Issue by Star4Fun** [ReikaKalseki/Reika_Mods_Issues#2769]
Server crash on startup. It seems to be a problem with the DragonAPI. Just updated to 29a and now server wont launch.

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 3/23/21 1:38 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/audio/SoundCategory
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/audio/SoundCategory
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at java.lang.Class.getEnumConstantsShared(Class.java:3311)
	at java.lang.Class.getEnumConstants(Class.java:3297)
	at Reika.DragonAPI.Instantiable.IO.SoundLoader.<init>(SoundLoader.java:42)
	at Reika.ExpandedRedstone.CommonProxy.<init>(CommonProxy.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.SoundCategory
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 43 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 5.4.97-gentoo
	Java Version: 1.8.0_272, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 7959941256 bytes (7591 MB) / 8232370176 bytes (7851 MB) up to 8232370176 bytes (7851 MB)
	JVM Flags: 2 total; -Xmx8G -Xms8G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge.jar) 
	UC	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UC	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UC	tickDynamic{0.1.5} [Tick Dynamic] (minecraft.jar) 
	UC	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UC	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UC	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UC	ae2stuff{0.5.1.9} [AE2 Stuff] (ae2stuff-rv3-0.5.1.9-mc1.7.10.jar) 
	UC	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UC	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UC	DragonAPI{v29a} [DragonAPI] (DragonAPI+1.7.10+V29a.jar) 
	UE	ChromatiCraft{v29a} [ChromatiCraft] (ChromatiCraft+1.7.10+V29a.jar) 
	UC	climatecontrol{0.8.1} [Climate Control] (ClimateControl-0.8.2.jar) 
	UC	creativecore{1.3.14} [CreativeCore] (CreativeCore+v1.3.24+mc1.7.10.jar) 
	UC	CritterPet{v29a} [Critter Pet] (CritterPet+1.7.10+V29a.jar) 
	UC	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UC	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UE	RotaryCraft{v29a} [RotaryCraft] (RotaryCraft+1.7.10+V29a.jar) 
	UE	ElectriCraft{v29a} [ElectriCraft] (ElectriCraft+1.7.10+V29a.jar) 
	UE	ExpandedRedstone{v29a} [ExpandedRedstone] (ExpandedRedstone+1.7.10+V29a.jar) 
	UC	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b200.jar) 
	UC	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UC	GeoStrata{v29a} [GeoStrata] (GeoStrata+1.7.10+V29a.jar) 
	UC	LegacyCraft{v29a} [LegacyCraft] (LegacyCraft+1.7.10+V29a.jar) 
	UC	littletiles{1.1.0} [LittleTiles] (LittleTiles+v1.2.0+mc1.7.10.jar) 
	UC	LootTweaks{v29a} [LootTweaks] (LootTweaks+1.7.10+V29a.jar) 
	UC	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UC	examplemod{1.0} [examplemod] (Moneymod-1.8.jar) 
	UC	moneymod{1.1} [Money Mod] (Moneymod-1.8.jar) 
	UC	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UC	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UC	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UC	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UC	OpenPeripheralCore{1.4} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.4.jar) 
	UC	OpenPeripheral{0.6} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.6.jar) 
	UC	OpenPeripheralIntegration{0.6} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.6.jar) 
	UC	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UC	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UC	projectbench{0.5.0} [Project Bench Updated] (ProjectBench-Update-1.7.10-0.5.jar) 
	UE	ReactorCraft{v29a} [ReactorCraft] (ReactorCraft+1.7.10+V29a.jar) 
	UC	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
	UC	TreeClimbing{v@MAJOR_VERSION@@MINOR_VERSION@} [TreeClimbing] (TreeClimbing+1.7.10+V29a.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@40d53ed3) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@6d90ef32) returned non-null result: 0
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by CPSRYAN** [comment]
I've been having the same issue once I updated my modpack. I thought there might have been an issue with interaction between the mods, so I did a fresh install with only Reika's mods, but still had the issue. (I only get a crash report server side, and to test I didn't bother to install a server)

**Comment by ReikaKalseki** [comment]
How did this not crash all the time before?!

**Comment by CPSRYAN** [comment]
Question, how did it get fixed? What is the solution? As far as I can tell there's been no update to the mods and I'm still having the same issue.
