### ISSUE TITLE
Chromaticraft v29c Server Crash

### ISSUE THREAD

**Issue by Star4Fun** [ReikaKalseki/Reika_Mods_Issues#2779]
Now the server starts and runs fine for a moment, but after a few moments it crashed. I think it crashes when the server resets the chroma dimension or something.
```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 3/26/21 9:07 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
	at Reika.ChromatiCraft.ChromaticEventManager.resetDimension(ChromaticEventManager.java:1840)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_138_ChromaticEventManager_resetDimension_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:334)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:657)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 5.4.97-gentoo
	Java Version: 1.8.0_272, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 6376973304 bytes (6081 MB) / 7928807424 bytes (7561 MB) up to 7928807424 bytes (7561 MB)
	JVM Flags: 2 total; -Xmx8G -Xms8G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 17
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	tickDynamic{0.1.5} [Tick Dynamic] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.1.9} [AE2 Stuff] (ae2stuff-rv3-0.5.1.9-mc1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	DragonAPI{v29c} [DragonAPI] (DragonAPI+1.7.10+V29c.jar) 
	UCHIJAAAA	ChromatiCraft{v29c} [ChromatiCraft] (ChromatiCraft+1.7.10+V29c.jar) 
	UCHIJAAAA	climatecontrol{0.8.1} [Climate Control] (ClimateControl-0.8.2.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (CreativeCore+v1.3.24+mc1.7.10.jar) 
	UCHIJAAAA	CritterPet{v29a} [Critter Pet] (CritterPet+1.7.10+V29a.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	RotaryCraft{v29c} [RotaryCraft] (RotaryCraft+1.7.10+V29c.jar) 
	UCHIJAAAA	ElectriCraft{v29a} [ElectriCraft] (ElectriCraft+1.7.10+V29a.jar) 
	UCHIJAAAA	ExpandedRedstone{v29b} [Expanded Redstone] (ExpandedRedstone+1.7.10+V29b.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b200.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	GeoStrata{v29a} [GeoStrata] (GeoStrata+1.7.10+V29a.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	LegacyCraft{v29a} [LegacyCraft] (LegacyCraft+1.7.10+V29a.jar) 
	UCHIJAAAA	littletiles{1.1.0} [LittleTiles] (LittleTiles+v1.2.0+mc1.7.10.jar) 
	UCHIJAAAA	LootTweaks{v29a} [LootTweaks] (LootTweaks+1.7.10+V29a.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (Moneymod-1.8.jar) 
	UCHIJAAAA	moneymod{1.1} [Money Mod] (Moneymod-1.8.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJAAAA	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJAAAA	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenPeripheralCore{1.4} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.4.jar) 
	UCHIJAAAA	OpenPeripheral{0.6} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.6.jar) 
	UCHIJAAAA	OpenPeripheralIntegration{0.6} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.6.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCHIJAAAA	projectbench{0.5.0} [Project Bench Updated] (ProjectBench-Update-1.7.10-0.5.jar) 
	UCHIJAAAA	ReactorCraft{v29c} [ReactorCraft] (ReactorCraft+1.7.10+V29c.jar) 
	UCHIJAAAA	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
	UCHIJAAAA	TreeClimbing{v@MAJOR_VERSION@@MINOR_VERSION@} [TreeClimbing] (TreeClimbing+1.7.10+V29c.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@27f01e07) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@3803178c) returned non-null result: 0
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from DragonAPI+1.7.10+V29c.jar
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
		* CoFHAPI (1.7.10R1.0.2) from DragonAPI+1.7.10+V29c.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from DragonAPI+1.7.10+V29c.jar
		* ComputerCraft|API (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
		* CSLib|API (0.3.0) from Decocraft-2.4.2_1.7.10.jar
		* minechemAPI (1.7.10R1) from DragonAPI+1.7.10+V29c.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0-122.jar
		* OpenPeripheralAddonsApi (1.0) from OpenPeripheralAddons-1.7.10-0.6.jar
		* OpenPeripheralApi (3.4.2) from OpenPeripheralCore-1.7.10-1.4.jar
	AE2 Integration: IC2:OFF, RotaryCraft:ON, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by ReikaKalseki** [comment]
Fixed.
