### ISSUE TITLE
[Chromaticraft v29e] Internal server error with ender bucket

### ISSUE THREAD

**Issue by Star4Fun** [ReikaKalseki/Reika_Mods_Issues#2792]
I don't know if this is a known issue, but if I try to use the ender bucket with any RotaryCraft (v29e) fluid (tried Ethanol, Jet Fuel, Liquid Nitrogen and Lubricant) I lose connection with an internal server error message. 
I tried the quartz tank from extra cells and the reservoir from RotaryCraft.

Let me know if you need any other information.

**Comment by MalTeeez** [comment]
I get this too with other mods, E.g. when clicking on a fresh Tesseract for the first time, I believe I've also had this with some RotaryCraft machines but I can't remember which ones

- Also why did you tag this as ChromatiCraft when it occurs in RotaryCraft?

**Comment by Star4Fun** [comment]
>     * Also why did you tag this as ChromatiCraft when it occurs in RotaryCraft?

The problem is the bucket also doesn't place the liquid and therefore I think it's a problem with the bucket itself.

**Comment by ReikaKalseki** [comment]
I need the error from the serverside log.

**Comment by Star4Fun** [comment]
```
[07:25:42] [Server thread/WARN]: Failed to handle packet for /31.19.30.249:50846
java.lang.NullPointerException
        at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57) ~[apz.class:?]
        at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595) ~[apx.class:?]
        at net.minecraft.world.World.func_147465_d(World.java:451) ~[ahb.class:?]
        at Reika.ChromatiCraft.Items.Tools.ItemEnderBucket$BucketMode.process(ItemEnderBucket.java:199) ~[ItemEnderBucket$BucketMode.class:?]
        at Reika.ChromatiCraft.Items.Tools.ItemEnderBucket.func_77648_a(ItemEnderBucket.java:88) ~[ItemEnderBucket.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
        at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by ReikaKalseki** [comment]
Thaaaaat looks like something wrong in the world data, not a CC error.

**Comment by Star4Fun** [comment]
Uff is there any way to fix it?

**Comment by ReikaKalseki** [comment]
Looking deeper it appears that you likely have `null` as a block somewhere. Someone did something stupid. Try a save editor.

**Comment by Star4Fun** [comment]
> Looking deeper it appears that you likely have `null` as a block somewhere. Someone did something stupid. Try a save editor.

Okay I tried it in a completely new single player world and the whole game crashes.
<a href="https://pastebin.com/LxvFAFqD">Crash report</a>

**Comment by ReikaKalseki** [comment]
What fluid are you trying to place, and what block does it use?

**Comment by Star4Fun** [comment]
In my test it was lubricant with a reservoir, but it happens basically with every liquid from rotarycraft regardless the tank. (in the test that I did).

**Comment by ReikaKalseki** [comment]
Lubricant does not have a block. That explains why it was putting null there. On the bright side the recent ender bucket rewrite fixed that oversight.

**Comment by Star4Fun** [comment]
Okay sounds great. I'm looking forward for the update! :)
