### ISSUE TITLE
Crash when completing monument if void monster not installed

### ISSUE THREAD

**Issue by qwahaha** [ReikaKalseki/Reika_Mods_Issues#2814]
I placed all the stuff needed to complete the monument. When I used the elemental manipulator on the orb in the middle, I got a game crash. The full log is here:

https://gist.github.com/qwahaha/8ad055270232404d94e40c1b75ff4649

But I think this is the part that matters:

[21:33:49] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/9/21 9:33 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: Reika/VoidMonster/Entity/EntityVoidMonster
	at Reika.ChromatiCraft.Auxiliary.Render.WorldRenderIntercept.runIntercept(WorldRenderIntercept.java:55)
	at Reika.ChromatiCraft.Auxiliary.Render.WorldRenderIntercept.callGlLists(WorldRenderIntercept.java:44)
	at net.minecraft.client.renderer.RenderList.func_78419_a(SourceFile:52)
	at net.minecraft.client.renderer.RenderGlobal.func_72733_a(RenderGlobal.java:932)
	at Reika.DragonAPI.ASM.ASMCallsClient.onCallChunkRenderLists(ASMCallsClient.java:51)
	at net.minecraft.client.renderer.RenderGlobal.func_72724_a(RenderGlobal.java:922)
	at net.minecraft.client.renderer.RenderGlobal.func_72719_a(RenderGlobal.java:802)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1211)
	at Reika.DragonAPI.ASM.ASMCallsClient.onRenderWorld(ASMCallsClient.java:55)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: Reika.VoidMonster.Entity.EntityVoidMonster
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 19 more

**Comment by ReikaKalseki** [comment]
Fixed.
