### ISSUE TITLE
[Chromaticraft] [MP] [Client] java.lang.NullPointerException: BlockPistonController

### ISSUE THREAD

**Issue by lAimBotl** [ReikaKalseki/Reika_Mods_Issues#2820]
_java.lang.NullPointerException: Unexpected error
	at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController.func_149673_e(BlockPistonController.java:80)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6011)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at Reika.DragonAPI.Instantiable.Event.Client.RenderBlockAtPosEvent.fire(RenderBlockAtPosEvent.java:57)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at Reika.DragonAPI.ASM.ASMCallsClient.onRenderWorld(ASMCallsClient.java:55)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)_

Happens when I join my server (only crashes client).

**Comment by lAimBotl** [comment]
whoa, never mind, the world is very dead indeed, good thing I have backups . . .
Random blocks replaced a bunch of stuff lol.
