### ISSUE TITLE
[RotaryCraft v30c] Error adding custom recipes to blast furnace

### ISSUE THREAD

**Issue by Sipepper** [ReikaKalseki/Reika_Mods_Issues#2916]
When i tried to add custom recipe it dont work.
[java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesBlastFurnace.addCustomRecipe(RecipesBlastFurnace.java:675)
script 
{
	type = "redstone_alloy"
	primary_input = {
		items = {
			"minecraft:redstone"
		}
		consumption_chance = 90
		number_to_use = 3
	}
	secondary_input = {
		items = {
			"EnderIO:itemMaterial"
		}
		consumption_chance = 60
		number_to_use = 2
	}
	tertiary_input = {
		items = {
			"Mekanism:Salt"
		}
		consumption_chance = 35
		number_to_use = 1
	}
	main_item = {
		"minecraft:gold_ingot"
	}
	required_main_item = 1
	match_number_exactly = false
	has_bonus = false
	xp = 0.3
	temperature = 900
	alloying = false
	output = "EnderIO:itemAlloy:3"
	output_nbt = {
	
	}
},
I`ve also tried the template from 
[https://github.com/ReikaKalseki/RotaryCraft/blob/master/CustomRecipeExamples/test.recipes_blastfurnace](url)
returns same code.
Also tested only with rotarycraft. Recipe template still dont work.

**Comment by ReikaKalseki** [comment]
What is the error it gives you? You cut that part out of what you pasted.

**Comment by Sipepper** [comment]
[12:33:13] [Client thread/ERROR]: ROTARYCRAFT ERROR: Could not load custom recipe 'rabotai' for BLASTFURNACE
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: The top-level LuaBlock must be a map type (root NBTTagCompound)!
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Libraries.ReikaNBTHelper.constructNBT(ReikaNBTHelper.java:503)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.DragonAPI.Instantiable.IO.CustomRecipeList.parseItemString(CustomRecipeList.java:277)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesBlastFurnace.addCustomRecipe(RecipesBlastFurnace.java:675)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipeHandler.loadCustomRecipeFiles(RecipeHandler.java:245)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.RotaryCraft.RotaryRecipes.addPostLoadRecipes(RotaryRecipes.java:232)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:649)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:33:13] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ReikaKalseki** [comment]
` java.lang.IllegalArgumentException: The top-level LuaBlock must be a map type (root NBTTagCompound)!`

Check your formatting.

**Comment by ReikaKalseki** [comment]
Anything?

**Comment by Sipepper** [comment]
Sorry for not responding for so long, i`ve tried to just plug your example of a recipe (because i`m not very good at LUA block system, and dont know exactly which parameters i must use to format my recipe correctly), and it gives me the same error. So please, can you revisit your old folder with custom recipes [https://github.com/ReikaKalseki/RotaryCraft/tree/master/CustomRecipeExamples](url)
or list all mandatory "definitions"(consumption_chance,match_number_exactly etc.)

**Comment by ReikaKalseki** [comment]
The error you are getting suggests the file is just formatted wrongly - did you make copy-paste errors?

**Comment by Sipepper** [comment]
No, i even downloaded example (test.blast_furnace) from [https://github.com/ReikaKalseki/RotaryCraft/blob/master/CustomRecipeExamples/test.recipes_blastfurnace](url)
to my desktop github and copy-pasted it in RotaryCraft_CustomRecipes folder, dont changing anything.
And its still gives me the same error. Same thing happens with chromaticraft casting table recipes example from
[https://github.com/ReikaKalseki/ChromatiCraft/blob/master/CustomRecipeExamples/test.recipes_castingtable](url)

**Comment by Madsoul01** [comment]
Hello,
Has any progress been made to resolve this?I'm getting the same error.

**Comment by voidentente** [comment]
Yes, so, this seems to be a bug in the LuaBlock parser?
I got around it by adding the recipe directly via the respective API:

```
Item canisterItem = GameRegistry.findItem("TConstruct", "heartCanister");
ItemStack canisterItemStack = new ItemStack(canisterItem, 1);
ItemStack canisterHeartItemStack = canisterItemStack.copy();
canisterItemStack.setItemDamage(5); // Green Heart
canisterHeartItemStack.setItemDamage(6); // Green Heart Canister

Item infusedDiamondItem = GameRegistry.findItem("rftools", "infusedDiamondItem");
ItemStack infusedDiamondItemStack = new ItemStack(infusedDiamondItem);

RecipesBlastFurnace.getRecipes().add3x3Crafting(
		canisterHeartItemStack, 
		1500, 
		4, 
		0, 
		"BDB", 
		"THT", 
		"BDB", 
		'B', ItemStacks.bedingot, 
		'D', infusedDiamondItemStack, 
		'T', CraftingItems.CARBIDE.getItem(), 
		'H', canisterItemStack);

System.out.println("Added green heart canister recipe");
```

**Comment by ReikaKalseki** [comment]
I fixed the parsing of empty NBT blocks recently.
