### ISSUE TITLE
[RotaryC v31a] Crash during startup

### ISSUE THREAD

**Issue by chotke** [ReikaKalseki/Reika_Mods_Issues#2948]
It seems that the integration with thaumcraft is broken in particular ItemScrewdriverFocus.

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/RotaryCraft/ModInterface/ItemScrewdriverFocus
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: Reika/RotaryCraft/ModInterface/ItemScrewdriverFocus
	at Reika.RotaryCraft.Registry.ItemRegistry.<clinit>(ItemRegistry.java:212)
	at Reika.RotaryCraft.RotaryCraft.<clinit>(RotaryCraft.java:188)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: Reika.RotaryCraft.ModInterface.ItemScrewdriverFocus
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: Reika/DragonAPI/ModInteract/DeepInteract/ItemCustomFocus
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
Caused by: java.lang.ClassNotFoundException: Reika.DragonAPI.ModInteract.DeepInteract.ItemCustomFocus
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more

**Comment by TheMgfeedthebeast** [comment]
i have the same problem

**Comment by TheMgfeedthebeast** [comment]
[crash-2021-12-19_17.17.06-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/7741270/crash-2021-12-19_17.17.06-client.txt)

**Comment by ReikaKalseki** [comment]
When this was happening with the manipulator focus, it was because of some TC addon including an old copy of the TC API. Given that I have been using the focus for a month without an issue, I expect that to be the case here.

Try removing mods, especially TC addons.

**Comment by TheMgfeedthebeast** [comment]
it works now thanks

**Comment by TheMgfeedthebeast** [comment]
also i have a nother problem when i lode my world
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/20/21 4:11 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Reika.ReactorCraft.Blocks.BlockDuct.func_149668_a(BlockDuct.java:72)
	at portablejim.bbw.core.WandWorker.getBlockPositionList(WandWorker.java:126)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:49)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_200_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at Reika.DragonAPI.ASM.ASMCallsClient.onRenderWorld(ASMCallsClient.java:86)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.ReactorCraft.Blocks.BlockDuct.func_149668_a(BlockDuct.java:72)
	at portablejim.bbw.core.WandWorker.getBlockPositionList(WandWorker.java:126)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:49)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_200_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at Reika.DragonAPI.ASM.ASMCallsClient.onRenderWorld(ASMCallsClient.java:86)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Mgfeedthebeast'/17801, l='MpServer', x=-774.04, y=18.92, z=-523.65]]
	Chunk stats: MultiplayerChunkCache: 5, 5
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-823,4,-244), Chunk: (at 9,0,12 in -52,-16; contains blocks -832,0,-256 to -817,255,-241), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 351669 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityItem['item.item.projectred.transmission.wire|0'/17954, l='MpServer', x=-791.13, y=4.13, z=-521.13], EntityBat['Bat'/17955, l='MpServer', x=-779.28, y=28.09, z=-529.84], EntityBat['Bat'/17956, l='MpServer', x=-779.44, y=28.09, z=-532.47], EntityBat['Bat'/17957, l='MpServer', x=-770.38, y=28.09, z=-531.41], EntityBat['Bat'/17958, l='MpServer', x=-775.09, y=28.09, z=-505.25], EntityBat['Bat'/17959, l='MpServer', x=-773.25, y=28.09, z=-505.28], EntityBat['Bat'/17960, l='MpServer', x=-783.25, y=28.09, z=-499.25], EntityClientPlayerMP['Mgfeedthebeast'/17801, l='MpServer', x=-774.04, y=18.92, z=-523.65], EntityRadiation['entity.ReactorCraft.Radiation.name'/17962, l='MpServer', x=-792.50, y=30.50, z=-510.50], EntityRadiation['entity.ReactorCraft.Radiation.name'/17963, l='MpServer', x=-790.50, y=31.50, z=-508.50], EntityRadiation['entity.ReactorCraft.Radiation.name'/17964, l='MpServer', x=-790.50, y=30.50, z=-510.50], EntityBat['Bat'/17965, l='MpServer', x=-796.25, y=28.09, z=-510.75], EntityBat['Bat'/17966, l='MpServer', x=-799.75, y=28.09, z=-499.28], EntityBat['Bat'/17967, l='MpServer', x=-795.56, y=28.09, z=-503.50], EntityBat['Bat'/17968, l='MpServer', x=-799.50, y=28.09, z=-507.44], EntityBat['Bat'/17969, l='MpServer', x=-786.34, y=28.09, z=-498.31], EntityRadiation['entity.ReactorCraft.Radiation.name'/17970, l='MpServer', x=-791.50, y=30.50, z=-533.50], EntityBat['Bat'/17971, l='MpServer', x=-794.69, y=28.09, z=-540.22], EntityBat['Bat'/17972, l='MpServer', x=-794.69, y=28.09, z=-537.63], EntityRadiation['entity.ReactorCraft.Radiation.name'/17973, l='MpServer', x=-789.50, y=32.50, z=-532.50], EntityRadiation['entity.ReactorCraft.Radiation.name'/17974, l='MpServer', x=-802.50, y=30.50, z=-521.50], EntityBat['Bat'/17975, l='MpServer', x=-809.34, y=28.09, z=-526.38], EntityBat['Bat'/17976, l='MpServer', x=-800.25, y=28.09, z=-512.75], EntityRadiation['entity.ReactorCraft.Radiation.name'/17977, l='MpServer', x=-802.50, y=32.50, z=-521.50], EntityBat['Bat'/17978, l='MpServer', x=-802.28, y=28.09, z=-500.53], EntityBat['Bat'/17979, l='MpServer', x=-801.63, y=28.09, z=-541.38], EntityItem['item.item.rottenFlesh'/17980, l='MpServer', x=-818.03, y=4.13, z=-540.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1576257512 bytes (1503 MB) / 3179806720 bytes (3032 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.24} [BuildCraft] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.24} [BC Builders] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.24} [BC Robotics] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.24} [BC Silicon] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.24} [BC Energy] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.24} [BC Transport] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.24} [BC Factory] (buildcraft-7.1.24.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.2 - MC 1.7.10.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	DragonAPI{v31a} [DragonAPI] (DragonAPI 1.7.10 V31a.jar) 
	UCHIJAAAA	Eln{@VERSION@} [Electrical Age] (ElectricalAge-1.17.0.jar) 
	UCHIJAAAA	RotaryCraft{v31a} [RotaryCraft] (RotaryCraft 1.7.10 V31a.jar) 
	UCHIJAAAA	ElectriCraft{v31a} [ElectriCraft] (ElectriCraft 1.7.10 V31a.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ReactorCraft{v31a} [ReactorCraft] (ReactorCraft 1.7.10 V31a.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	XaeroMinimap{21.10.15} [Xaero's Minimap] (Xaeros_Minimap_21.10.15_Forge_1.7.10.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 496.74' Renderer: 'NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2'
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13B1 from extrautilities-1.2.12.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (@aeversion@ from DragonAPI 1.7.10 V31a.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 496.74, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ReikaKalseki** [comment]
This is an entirely unrelated issue. Move it to a new one.

**Comment by chotke** [comment]
Okay, I still have some problems. What TC means? TinkersConstruct or Thaumcraft? I spent a couple of hours to find what crashes my minecraft, so i need some hint how I can fix it (if I can).

What I found so far:
dragonApi+RotC+ReacC+industrialCraft+TConstruct+Gravisuite =Ok (crash with ElectriCraft mod) [1]
dragonApi+RotC+ReacC+industrialCraft+TConstruct+Gravisuite+another_40_mods =Ok (crash with ElectriCraft mod) [1]
[1] -> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: gravisuite/ItemGraviTool

Same problem with CoFHCore:
dragonApi+TConstruct+CoFHCore =Ok (crash with RotC) [2]
dragonApi+bunch_of_40_mods+TConstruct+CoFHCore =Ok (crash with RotC) [2]
[2] -> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/RotaryCraft/ModInterface/ItemScrewdriverFocus

Can I somehow fix it? I Still can play without Gravisuite, but I would like to keep CoFH mods ( Thermal Dynamics/Expansion/Foundation). Waiting for any of your reply.
Thanks.

**Comment by ReikaKalseki** [comment]
TC is ThaumCraft. TiC is tinkers.

@TheMgfeedthebeast what mod did you remove to make it work?

**Comment by chotke** [comment]
Okay, i can do it for him @ReikaKalseki 
CoFHCore-[1.7.10]3.1.4-329.jar
ThermalFoundation-[1.7.10]1.2.6-118.jar
ThermalExpansion-[1.7.10]4.1.5-248.jar
ThermalDynamics-[1.7.10]1.2.1-172.jar

**Comment by TheMgfeedthebeast** [comment]
i removed cofhcore and  thermalfoundation

**Comment by voidentente** [comment]
CoFH Lib does not seem to be affected, you may try to use it instead of CoFH Core

**Comment by chotke** [comment]
Mods requires core not lib:
CoFHCore : [1.7.10R3.1.4,1.7.10R3.2.0)

**Comment by ReikaKalseki** [comment]
I use CoFHCore and it works fine.

**Comment by chotke** [comment]
Please share which version you are using

**Comment by TheMgfeedthebeast** [comment]
i used CoFHCore-[1.7.10]3.1.4-329.jar
ThermalFoundation-[1.7.10]1.2.6-118.jar
ThermalExpansion-[1.7.10]4.1.5-248.jar
ThermalDynamics-[1.7.10]1.2.1-172.jar

**Comment by chotke** [comment]
I have the same versions of mods. But I have to use old version of dragonApi (V30d). Duplicating issue threads suggests that the problem is still in new version api
#2558
#2974
and others

**Comment by lee321987** [comment]
I got this crash (ItemScrewdriverFocus) to stop by installing Railcraft.

I don't know enough modder-language to know why that made a difference (I just read https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2974#issuecomment-1030598025).

I don't have Thaumcraft.

All these were installed when the crash started (along with a lot of other mods, and they are all still installed):
Chisel-2.9.5.11.jar
CoFHCore-[1.7.10]3.1.4-329.jar
ThermalFoundation-[1.7.10]1.2.6-118.jar
ThermalExpansion-[1.7.10]4.1.5-248.jar
ThermalDynamics-[1.7.10]1.2.1-172.jar

**Comment by chotke** [comment]
@lee321987 yeah, thanks for the "fix". Railcraft+Chisel works for me. After a half year idk if i would able to load old world and remember what to do next 😄

**Comment by gameskip** [comment]
Now idk whether this fits here, but I also don't have TC or stuff like that.
I seem to have this same problem, I have the latest versions, and the only mods I have here that are mentioned are CoFHCore+Lib and Chisel, yet still the problem continues

[crash-2022-06-02_15.23.20-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/8823810/crash-2022-06-02_15.23.20-client.txt)
.
