### ISSUE TITLE
[ReC v31a] (DUPLICATION GLITCH) Kicked from server every time I place a block trying to build HP turbine.

### ISSUE THREAD

**Issue by Credit-Score** [ReikaKalseki/Reika_Mods_Issues#2949]
Below is what the server logs when I'm kicked. If the block isn't one that will fully complete that layer of the HP turbine multiblock, it will kick you with "Internal server error"

This only happens if you have placed the HP turbine block itself where it will go, then try to build around it. If you build the layer, then place HP turbine block, then break/replace a block in that layer, it will work correctly.

There is steam in the line, if that matters.

```
[14:56:54] [Server thread/WARN]: Failed to handle packet for /[IP REDACTED]
java.lang.NullPointerException
        at Reika.DragonAPI.Instantiable.Data.BlockStruct.SlicedBlockBlueprint.checkAgainst(SlicedBlockBlueprint.java:236) ~[SlicedBlockBlueprint.class:?]
        at Reika.ReactorCraft.Blocks.Multi.BlockTurbineMulti.checkForShape(BlockTurbineMulti.java:231) ~[BlockTurbineMulti.class:?]
        at Reika.ReactorCraft.Blocks.Multi.BlockTurbineMulti.checkForFullMultiBlock(BlockTurbineMulti.java:194) ~[BlockTurbineMulti.class:?]
        at Reika.ReactorCraft.Blocks.Multi.BlockTurbineMulti.checkForFullMultiBlock(BlockTurbineMulti.java:32) ~[BlockTurbineMulti.class:?]
        at Reika.DragonAPI.Base.BlockMultiBlock.func_149689_a(BlockMultiBlock.java:74) ~[BlockMultiBlock.class:?]
        at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213) ~[abh.class:?]
        at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
        at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by Credit-Score** [comment]
2 more things

1. This happens with Turbine Generators when placing rotor cores.

2. This duplicates whatever block you place, since it stays in your hand but is also placed in the world.

**Comment by ReikaKalseki** [comment]
Fixed.
