### ISSUE TITLE
[SatisForestry] Strange crash

### ISSUE THREAD

**Issue by cyb3rm4n** [ReikaKalseki/Reika_Mods_Issues#2953]
When you're travelling on the world, you can get the next error in logs and crash:

java.lang.RuntimeException: Biome [Pink Birch Forest] threw an error while populating chunk.
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_73153_a(ChunkProviderMyst.java:165)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy$ChunkProviderServerDummy.originalLoadChunk(WorldProviderMystDummy.java:62)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:217)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:343)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:180)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_961_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at Reika.DragonAPI.Libraries.Java.ReikaRandomHelper.getRandomBetween(ReikaRandomHelper.java:150)
	at Reika.Satisforestry.Biome.Generator.WorldGenCaveFlora.generate(WorldGenCaveFlora.java:24)
	at Reika.Satisforestry.Biome.DecoratorPinkForest.func_150513_a(DecoratorPinkForest.java:179)
	at Reika.DragonAPI.Instantiable.Worldgen.StackableBiomeDecorator.func_150512_a(StackableBiomeDecorator.java:29)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_73153_a(ChunkProviderMyst.java:163)
	... 17 more

**Comment by ReikaKalseki** [comment]
Was this a void world or otherwise unusual?

**Comment by ReikaKalseki** [comment]
If so, this should be fixed.
