### ISSUE TITLE
Colour Tape Puzzle Crashes Server

### ISSUE THREAD

**Issue by CaiB** [ReikaKalseki/Reika_Mods_Issues#2994]
(ChromatiCraft puzzle spoilers)

I was working on solving the ChromatiCraft colour tape puzzle in Proxima, and everything was going fine. I was able to send bursts, advance the tape, and do playback several times. Then all of a sudden when I asked it to send a single burst, right-clicking the block to do that immediately kicked my client from the server with "Internal Server Error" (with no useful errors in the logs on either client or server). Luckily I was expecting issues, so had put down a persistence crystal. Logged back in, put down another one, right-clicked the single burst button again, same thing. Logged back in, put another one down, then clicked the full playback button, and that completely crashed the server with:

```
Description: Ticking block entity
 
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to net.minecraft.block.BlockPistonBase
	at Reika.DragonAPI.Libraries.World.ReikaBlockHelper.extendPiston(ReikaBlockHelper.java:501)
	at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.PistonTapeSlice.cycle(PistonTapeSlice.java:94)
	at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.PistonTapeLoop.cycle(PistonTapeLoop.java:67)
	at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.TapeStage.cycle(TapeStage.java:146)
	at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController$TilePistonPlayback.func_145845_h(BlockPistonController.java:125)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Stacktrace:
	at Reika.DragonAPI.Libraries.World.ReikaBlockHelper.extendPiston(ReikaBlockHelper.java:501)
	at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.PistonTapeSlice.cycle(PistonTapeSlice.java:94)
	at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.PistonTapeLoop.cycle(PistonTapeLoop.java:67)
	at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.TapeStage.cycle(TapeStage.java:146)
	at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController$TilePistonPlayback.func_145845_h(BlockPistonController.java:125)
 
-- Block entity being ticked --
Details:
	Name: CCTilePistonPlayback // Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController.TilePistonPlayback
	Block type: ID #1193 (tile.chroma.pistoncontrol // Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1819,73,-819), Chunk: (at 11,4,13 in 113,-52; contains blocks 1808,0,-832 to 1823,255,-817), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)
	Actual block type: ID #1193 (tile.chroma.pistoncontrol // Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
```

**Comment by ReikaKalseki** [comment]
#2569

**Comment by CaiB** [comment]
Not sure how that's related. I did not attempt to break anything, especially the piston. Also, the **server** crashes, not the client.

**Comment by ReikaKalseki** [comment]
The issue is the same - air where a piston is supposed to be.
