### ISSUE TITLE
[Chroma] Minor: Creative Elemental Lock bypass causes instance crash upon atempt

### ISSUE THREAD

**Issue by Shibva** [ReikaKalseki/Reika_Mods_Issues#3054]
To reporduce: 
1, Locate or Generate a BiomeFrag structure
2. go down to the elemental locks
3. while in creative sneak and Rlcick with an empty hand
4. crash

report generated

```
Time: 7/19/22 3:17 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at Reika.ChromatiCraft.Block.Dimension.Structure.Locks.BlockColoredLock.func_149734_b(BlockColoredLock.java:88)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:354)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2048)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Reika.ChromatiCraft.Block.Dimension.Structure.Locks.BlockColoredLock.func_149734_b(BlockColoredLock.java:88)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:354)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2048)
```

**Comment by Shibva** [comment]
@ReikaKalseki looking back at this now I'm not exactly sure if this is a valid issue… I mean I'm not exactly sure how I'm supposed to do it correctly so you tell me I guess (i'm fine with learning how to get through it. I'm just saying this in case spoilers are going to be an issue)

**Comment by ReikaKalseki** [comment]
This is not happening for me. Maybe it got fixed in v32, or maybe you had something invalid.

EDIT:
And as soon as I say that it crashes with this exact error, not when right clicking, but when logging out of a world.

**Comment by Shibva** [comment]
Don't you hate it when that happens?
