### ISSUE TITLE
Flywheel transmitting to empty splitter causes exception

### ISSUE THREAD

**Issue by kfastov** [ReikaKalseki/Reika_Mods_Issues#308]
Steps to reproduce:
1) Place a flywheel
2) Spin it with some motor powerful enough
3) Connect shaft junction to flywheel's output
4) Change junction mode to splitter

Error log:
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.Instantiable.Data.Immutable.WorldLocation.<init>(WorldLocation.java:64)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.Instantiable.Data.Maps.TileEntityCache.containsKey(TileEntityCache.java:76)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveFind(TorqueUsage.java:95)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.RotaryCraft.Auxiliary.TorqueUsage.getTorque(TorqueUsage.java:58)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.process(TileEntityFlywheel.java:316)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.updateEntity(TileEntityFlywheel.java:179)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[15:00:34] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Possible reason: variable `read` not being checked for null on https://github.com/ReikaKalseki/RotaryCraft/blob/3bc85e848d95e47b2c27c6f8ec1de4ffc8477871/Auxiliary/TorqueUsage.java#L75

![2015-10-04_14 55 56](https://cloud.githubusercontent.com/assets/1312744/10267734/3be91cc8-6aa9-11e5-8b3a-2ad9b5c824a3.png)

**Comment by ljfa-ag** [comment]
Hum, we recently had reports about the flywheel with #230 and #294 
Maybe something broke from fixing these?

**Comment by ReikaKalseki** [comment]
Can someone try in v9a to see if v9b's fix is the issue?

**Comment by ljfa-ag** [comment]
Hum, in v9a when the junction is in merging mode (and its output faces into the flywheel's output) I get a StackOverflowError like in #294.
In splitting mode it works fine.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by kevenduchesneau** [comment]
Without opening a new issue, can I post that I had a similar one happening? Or should I open a new issue ?
AC Motor > Iron flywheel > Steel 8:1 Gearbox > Bevel, it threw the error as soon as I reversed the gearbox speed/torque.

Each time I placed a new Gearbox and corrected the orientation, it threw the same error.

```
[17:42:37] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Iron Flywheel @ DIM0: 1309, 66, 4376 is throwing class java.lang.NullPointerException on update: null
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.DragonAPI.Instantiable.Data.Immutable.WorldLocation.<init>(WorldLocation.java:64)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.DragonAPI.Instantiable.Data.Maps.TileEntityCache.containsKey(TileEntityCache.java:76)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.RotaryCraft.Auxiliary.TorqueUsage.recursiveFind(TorqueUsage.java:116)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.RotaryCraft.Auxiliary.TorqueUsage.getTorque(TorqueUsage.java:58)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.process(TileEntityFlywheel.java:385)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.updateEntity(TileEntityFlywheel.java:179)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.World.func_72939_s(World.java:1939)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[17:42:37] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by ReikaKalseki** [comment]
Does this still happen?

**Comment by Innsewerants** [comment]
[quote][03:04:39] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_73]
    at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_73]
    at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source) ~[?:1.8.0_73]
    at Reika.DragonAPI.Instantiable.Data.Maps.TileEntityCache.invert(TileEntityCache.java:177) ~[TileEntityCache.class:?]
    at Reika.DragonAPI.Instantiable.Data.Maps.TileEntityCache.invert(TileEntityCache.java:184) ~[TileEntityCache.class:?]
    at Reika.RotaryCraft.Auxiliary.TorqueUsage.getTorque(TorqueUsage.java:56) ~[TorqueUsage.class:?]
    at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.process(TileEntityFlywheel.java:316) ~[TileEntityFlywheel.class:?]
    at Reika.RotaryCraft.TileEntities.Transmission.TileEntityFlywheel.updateEntity(TileEntityFlywheel.java:179) ~[TileEntityFlywheel.class:?]
    at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:465) ~[TileEntityBase.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
    ... 4 more
[03:04:40] [Server thread/ERROR]: This crash report has been saved to: C:\MultiMC\instances\DiscCraftPack\minecraft\crash-reports\crash-2016-04-06_03.04.39-server.txt
[03:04:40] [Server thread/INFO]: Stopping server[/quote]

I think it's this error, happened on a 2 week old server which was running quite well aside from a disappointing host. I was tinkering with my extractor setup when I decided to try a flywheel to stabilize the output of my ac into a multidirectional junction for driving the different stages.
Server went bust the second I turned it on. Can't launch the server anymore, it goes through this, says it will close the server but just gets stuck at 100% cpu load.
Same in SSP after cloning the world, same on a second test server.

Mods:
  Biomes O Plenty-2.1.0.1889
  BuildCraft-7.1.16
  BuildCraft Compat-7.1.4
  ChickenChunks-1.3.4.19
  CodeChickenCore-1.0.7.47
  DragonAPI-v12e
  ElectriCraft-v12c
  EnderStorage-1.4.7.38
  Et Futurum-1.5.5
  Forestry-4.2.11
  Fossils and Archaeology Revival-7.2.1
  iChunUtil-4.2.2
  Inventory Tweaks-1.59 dev 152
  IronChest-6.0.62.742
  Jabba-1.2.1a
  JourneyMap-5.1.4
  Logistics Pipes-0.9.3.114
  Not Enough Items-1.0.5.120
  OpenBlocks-1.5.1
  OpenComputers-1.5.22.46
  OpenModsLib-0.9.1
  Origin-8.0.3.334
  Parzis Star Wars Mod-1.2.11
  Portal Gun-4.0.0 beta 6
  PortalGunSounds
  ProjectRed Compat-4.7.0pre12.95
  ProjectRed Base-4.7.0pre12.95
  ProjectRed World-4.7.0pre12.95
  ProjectRed Lighting-4.7.0pre12.95
  ProjectRed Integration-4.7.0pre12.95
  Railcraft-9.10.0.0
  ReactorCraft-v12d
  RotaryCraft-v12e
  SimplySit-1.1.0
  WeepingAngels-4.0.2.113
  Witchery-0.24.1
  WRCBE-1.4.1.9

Forge: 7.99.40.1614
Java 1.8.0_73 x64

**Comment by ReikaKalseki** [comment]
That is an entirely different error.

**Comment by ReikaKalseki** [comment]
Given the recent fixes to the shaft junction and the current more severe issue with flywheels, this issue is entirely eclipsed.
