### ISSUE TITLE
[Chromaticraft] Networking a Thaumcraft Aura Node with an Aura Locus nearby crashes

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#3095]
Stack trace:
```
[Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@681c139c:
java.lang.UnsupportedOperationException: This set does not support natural iteration! Use .iterate()!
	at Reika.DragonAPI.Instantiable.Data.Collections.ThreadSafeSet.iterator(ThreadSafeSet.java:111) ~[ThreadSafeSet.class:?]
	at java.util.Collections$UnmodifiableCollection$1.<init>(Unknown Source) ~[?:1.8.0_341]
	at java.util.Collections$UnmodifiableCollection.iterator(Unknown Source) ~[?:1.8.0_341]
	at Reika.ChromatiCraft.TileEntity.AOE.TileEntityAuraPoint.getPoints(TileEntityAuraPoint.java:495) ~[TileEntityAuraPoint.class:?]
	at Reika.ChromatiCraft.ModInterface.ThaumCraft.NodeReceiverWrapper.tick(NodeReceiverWrapper.java:274) ~[NodeReceiverWrapper.class:?]
	at Reika.ChromatiCraft.ModInterface.ThaumCraft.NodeRecharger.tick(NodeRecharger.java:120) ~[NodeRecharger.class:?]
	at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.worldTick(TickRegistry.java:80) ~[TickRegistry.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_498_TickRegistry_worldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
I've managed to trigger the same crash 3 different ways:
- Right-clicking an aura node with a manipulator to network it (while in range of an Aura Locus/TileEntityAuraPoint)
- Jarring an already-networked aura node (while in range of an Aura Locus)
- Placing an Aura Locus within range of a networked aura node

**Comment by ReikaKalseki** [comment]
This was fixed in v32.
