### ISSUE TITLE
[Chromaticraft] Crystal Bees crash in Alveary without owner NBT; also, Construction Star fails to set Alveary owner tag

### ISSUE THREAD

**Issue by EyeDeck** [ReikaKalseki/Reika_Mods_Issues#3096]
```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at Reika.ChromatiCraft.ModInterface.Bees.ProductChecks$ProgressionCheck.check(ProductChecks.java:246)
	at Reika.ChromatiCraft.ModInterface.Bees.FlowerAlleles$ConditionalProductFlowerProvider.affectProducts(FlowerAlleles.java:384)
	at forestry.apiculture.genetics.Bee.produceStacks(Bee.java:531)
	at forestry.apiculture.BeekeepingLogic.doProduction(BeekeepingLogic.java:261)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:241)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:224)
	at forestry.apiculture.multiblock.AlvearyController.updateServer(AlvearyController.java:233)
	at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:423)
	at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:82)
	at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:29)
	at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1222_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
The crashing line: https://github.com/ReikaKalseki/ChromatiCraft/blob/4f3680382bb81109e462b9c1def5a16022c23ccf/ModInterface/Bees/ProductChecks.java#L246

I correctly guessed that the specific NPE was the `ibh.getOwner()` part of that line; a crystal bee, when trying to produce certain products in an alveary with no `owner` NBT set, will try to get the UUID of nothing and crash.

Alveary tiles placed with a ChC Construction Star:
![image](https://user-images.githubusercontent.com/2722970/200231290-732e8ce0-72f4-47c1-9ea7-f93bb6101f41.png)

Alveary tiles placed by hand, or using an ExU Builder's Wand:
![image](https://user-images.githubusercontent.com/2722970/200231260-d8fd4812-d808-4a4b-ae70-aafba38aa828.png)

I usually use an ExU Builder's Wand for Alvearies, because it's quicker to "extrude" out a cuboid when placing those 3^3s (about 7 clicks, vs 27 placing by hand). This time a Construction Star was handier, which of course does nearly the same thing, so I used it instead, and stumbled on this issue.

**Comment by ReikaKalseki** [comment]
I fixed the crash and hopefully fixed the builder wand setting the data.
