### ISSUE TITLE
Mob Spawn Controls 2 crashes with Chromaticraft

### ISSUE THREAD

**Issue by brandyyn** [ReikaKalseki/Reika_Mods_Issues#3127]
Crash on startup with MSC2 after adding solely Chromaticraft (v31b) to the instance, everything works fine before adding chromaticraft and after removing chromaticraft.

>java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.util.List
	at com.mcf.davidee.msc.reflect.BiomeReflector.reflectList(BiomeReflector.java:26)
	at com.mcf.davidee.msc.spawning.MobHelper.populateDefaultMap(MobHelper.java:32)
	at com.mcf.davidee.msc.MobSpawnControls.modsLoaded(MobSpawnControls.java:95)

[crash-2022-12-29_16.28.00-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10320482/crash-2022-12-29_16.28.00-client.txt)

[2022-12-29-7.log](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/10320487/2022-12-29-7.log)

**Comment by ReikaKalseki** [comment]
Not my code.

**Comment by brandyyn** [comment]
and yet it only crashes when i add chromaticraft...
