### ISSUE TITLE
[ChromatiCraft v31b] ItemBlock@4fceb2b8, id 92, is missing or uses the non-matching id -1.

### ISSUE THREAD

**Issue by Dimagican** [ReikaKalseki/Reika_Mods_Issues#3149]
Hello! In my modpack I got issue that crashes Minecraft
When I delete ChromatiCraft it resolves, but I don't know how to fix it by any other way

[crash-2023-03-25_16.23.11-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/11069535/crash-2023-03-25_16.23.11-client.txt)

**Comment by Dimagican** [comment]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 25.03.23 16:23
Description: Initializing game

java.lang.IllegalStateException: Registry entry for ItemBlock net.minecraft.item.ItemBlock@4fceb2b8, id 92, is missing or uses the non-matching id -1.
	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.validateContent(FMLControlledNamespacedRegistry.java:90)
	at cpw.mods.fml.common.registry.GameData.testConsistency(GameData.java:1005)
	at cpw.mods.fml.common.registry.GameData.freezeData(GameData.java:724)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:746)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.validateContent(FMLControlledNamespacedRegistry.java:90)
	at cpw.mods.fml.common.registry.GameData.testConsistency(GameData.java:1005)
	at cpw.mods.fml.common.registry.GameData.freezeData(GameData.java:724)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:746)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4504981968 bytes (4296 MB) / 7751073792 bytes (7392 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	smoothfontcore{1.7.10-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJA	smoothfont{1.7.10-1.15.3} [Smooth Font] (SmoothFont-1.7.10-1.15.3.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJA	aether_legacy{v1.1.2.2} [The Aether] (aether-1.7.10-v1.1.2.2.jar) 
	UCHIJA	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
	UCHIJA	aquacreeper{1.0.1} [Aqua Creeper] (AquaCreepers-1.0.1.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	AromaBackup{0.1.0.0} [AromaBackup] (AromaBackup-1.7.10-0.1.0.0.jar) 
	UCHIJA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.1.0.0.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJA	hud{1.3.5} [Better HUD] (Better+HUD+by+NukeDuck+[1.7.10][1.3.5].jar) 
	UCHIJA	betterloadingscreen{1.3.10} [Better Loading Screen] (BetterLoadingScreen-1.3.10.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJA	blur{MC1.7.10-1.0.1-2} [Blur] (blur-mc1.7.10-1.0.1-2.jar) 
	UCHIJA	DragonAPI{v31b} [DragonAPI] (DragonAPI+1.7.10+V31b.jar) 
	UCHIJA	ChromatiCraft{v31b} [ChromatiCraft] (ChromatiCraft+1.7.10+V31b.jar) 
	UCHIJA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJA	DummyCore{2.0.1710.0.A} [DummyCore] (dummycore-2.0.1710.0a.jar) 
	UCHIJA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJA	EMT{1.2.6.2} [Electro-Magic Tools] (ElectroMagicTools-1.2.6.2[1.7.10].jar) 
	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (forbidden-magic-1.7.10-0.575.jar) 
	UCHIJA	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCHIJA	got{23.02.14} [Game of Thrones] (Game of Thrones v23.03.25.jar) 
	UCHIJA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion++MC-1.7.10++v1.8.6.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152-1.7.10.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJA	joetater{1.4} [Joetater: Region Saver] (joetater-1.4.jar) 
	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJA	mdeco{0.3.5} [Magical Decorations] (MagicalDecorations-0.3.5.jar) 
	UCHIJA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJA	mjutils{1.6.1} [MJUtils] (mjutils-1.6.1.jar) 
	UCHIJA	naturescompass{1.3.1} [Nature's Compass] (naturescompass-1.7.10-1.3.1.jar) 
	UCHIJA	reccomplex{0.9.7.1.1} [Recurrent Complex] (RecurrentComplex-0.9.7.1.1.jar) 
	UCHIJA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike_1.7.10_1.5.0b.jar) 
	UCHIJA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJA	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (rwg-alpha-1.3.2.jar) 
	UCHIJA	SimpleAchievements{MC1.7.10-1.1.0-21} [Simple Achievements] (SimpleAchievements-MC1.7.10-1.1.0-21.jar) 
	UCHIJA	SpecialMobs{3.2.2} [Special Mobs] (SpecialMobs-1.7.10-3.2.2.jar) 
	UCHIJA	spongemixins{1.2.0} [SpongeMixins Loader] (SpongeMixins-1.2.0.jar) 
	UCHIJA	TaintedMagic{8.1.1} [Tainted Magic] (Tainted-Magic-1.7.10-8.1.1.jar) 
	UCHIJA	tchelper{1.7.10-1.4} [TC Research-Helper] (tchelper-1.7.10-1.4.jar) 
	UCHIJA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJA	TextureGeneratorLib{0.2} [TextureGeneratorLib] (TextureGeneratorLib-1.7.10_vBeta2.jar) 
	UCHIJA	benway_knowledge{0.1.5.1} [Thaumaturgical Knowledge] (Thaumaturgical+Knowledge-0.1.5.2+-+1.7.10.jar) 
	UCHIJA	ThaumcraftLocalizationOptimizer{1.0.3} [Thaumcraft Localization Optimizer] (ThaumcraftLocalizationOptimizer-1.0.4.jar) 
	UCHIJA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJA	thaumicdyes{1.10.5} [Thaumic Dyes] (thaumic-dyes-1.7.101.10.5-0.jar) 
	UCHIJA	thaumicbases{1.3.1710.2} [Thaumic Bases] (thaumic_bases_1.7.10.jar) 
	UCHIJA	ThaumicExpanse{1.7.10-1.1.1} [Thaumic Expanse] (ThaumicExpanse-1.7.10-1.1.1.jar) 
	UCHIJA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJA	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJA	thaumrev{1.2.2} [Thaumic Revelations] (ThaumicRevelations-1.2.2.jar) 
	UCHIJA	thaumores{1.6.0} [ThaumOres] (thaumores-1.6.0.jar) 
	UCHIJA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJA	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	WarpTheory{1.7.10R1.0} [WarpTheory] (WarpTheory-1.7-1.0-24.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	WitchingGadgets{1.1.10} [Witching Gadgets] (witchinggadgets-1.7.10-1.1.10 (1).jar) 
	UCHIJA	WTFCore{1.7} [WhiskyTangoFox's Core] (WTFCore_1.7.10_v1.7.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	[DummyCore]: 'Special case ASM modification mods: ''Note, that this mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore''DragonAPI''CodeChickenCore'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.51, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

**Comment by ReikaKalseki** [comment]
That exception is entirely referencing vanilla code and vanilla items. Also, I have never seen it before and have no idea what it means.
