### ISSUE TITLE
[RotaryCraft 31b] Grinder NEI crash

### ISSUE THREAD

**Issue by chotke** [ReikaKalseki/Reika_Mods_Issues#3168]
An attempt to look at the available recipes leads to crash in 31b version. No problems is V30c which I tested last.

Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.getGrindingResult(RecipesGrinder.java:282)
	at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler$GrinderRecipe.<init>(GrinderHandler.java:50)
	at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler$GrinderRecipe.<init>(GrinderHandler.java:45)
	at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler$GrinderRecipe.<init>(GrinderHandler.java:39)
	at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:145)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
	at codechicken.nei.recipe.TemplateRecipeHandler.transferRect(TemplateRecipeHandler.java:574)
	at codechicken.nei.recipe.TemplateRecipeHandler.access$000(TemplateRecipeHandler.java:34)
	at codechicken.nei.recipe.TemplateRecipeHandler$RecipeTransferRectHandler.transferRect(TemplateRecipeHandler.java:234)
	at codechicken.nei.recipe.TemplateRecipeHandler$RecipeTransferRectHandler.mouseClicked(TemplateRecipeHandler.java:225)
	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by svipthedrunk** [comment]
I experienced the same crash in version 31b.
Some additional informations:

Applied Energistics 2 or EnderIO needs to be installed for this crash to occurr.

I found two ways to trigger the crash reliable:
Option 1 (with ae2 or enderio installed): in the grinder GUI click on the process arrow to view the grinder recipes -> crash
Option 2 (with ae2 installed): in NEI trying to view the recipes from "Ender Dust" (rightclick) -> crash

Crashlog with ae2 installed via Grinder GUI
[https://gist.github.com/svipthedrunk/dc5aefcd94262396413746e538d41276](url)

Crashlog with ae2 installed via ender dust
[https://gist.github.com/svipthedrunk/54e3ee1ca701fa9914aa9a45d5844ded](url)

**Comment by ReikaKalseki** [comment]
Fixed in v32.
