### ISSUE TITLE
Mineral Extractor observations.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#320]
Premise:
Was toying around with a mineral extractor with all 3 upgrades and a 256x accelerator.

1) After the MiEx "finished" mining the area the gui still shows about 1 of every block type left. Though doing another scan confirms that there are no minerals left.

2) The MiEx only mined 4 "Rocky Hive" which seems unrealistically low for an area of that size and i also can see a Rocky Hive in an adjacent cave that was not mined.

3) Putting a second 256x accelerator on the MiEx makes it stop working until the accelerator is removed and the MiEx is broken and replaced. (i think)

4) Afterwards i noticed the server console was spammed with 2663 instances of OOB over 45 seconds, this might have been caused by 3).

```
[16:35:05] [Server thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Mineral Extractor @ DIM6: -1303, 33, 793 is throwing class java.lang.IndexOutOfBoundsException on update: Index: 311916, Size: 202470
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IndexOutOfBoundsException: Index: 311916, Size: 202470
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.ArrayList.rangeCheck(Unknown Source)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.util.ArrayList.get(Unknown Source)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.ChromatiCraft.TileEntity.Acquisition.TileEntityMiner.updateEntity(TileEntityMiner.java:140)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.ChromatiCraft.TileEntity.AOE.TileEntityAccelerator.updateEntity(TileEntityAccelerator.java:142)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[16:35:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by ReikaKalseki** [comment]
These may all be related.

**Comment by Reignofmagic** [comment]
As an additional random thing with the mineral extractor, Dense ores from the Dense Ores Mod: http://www.curse.com/mc-mods/minecraft/224942-dense-ores, will not be found by the mineral extractor. Not exactly a big issue just wonder why they were not found during the scan or the extraction process.

**Comment by ReikaKalseki** [comment]
They are not recognized as ore by DragonAPI.

**Comment by ReikaKalseki** [comment]
I am just going to blacklist the accelerators on the Mineral Extractor.
