### ISSUE TITLE
[Dragon Realm Modpack v32a] world gene crash in climateControl.customGenLayer

### ISSUE THREAD

**Issue by Mgctz** [ReikaKalseki/Reika_Mods_Issues#3215]
Description: Exception preparing structure feature

java.lang.RuntimeException
	at climateControl.customGenLayer.GenLayerLowlandRiverMix.func_75904_a(GenLayerLowlandRiverMix.java:98)
	at climateControl.customGenLayer.GenLayerRiverMixWrapper.func_75904_a(GenLayerRiverMixWrapper.java:66)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:23)
	at net.minecraft.world.biome.WorldChunkManager.func_76931_a(WorldChunkManager.java:163)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
	at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:58)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:160)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
	at net.minecraft.world.World.func_72807_a(World.java:130)
	at Reika.CaveControl.CaveLoader.getEffectiveBiome(CaveLoader.java:196)
	at Reika.CaveControl.CaveLoader.getDefinition(CaveLoader.java:189)
	at Reika.CaveControl.Generators.ControllableMineshaftGen.getConfig(ControllableMineshaftGen.java:45)
	at Reika.CaveControl.Generators.ControllableMineshaftGen.func_75047_a(ControllableMineshaftGen.java:41)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_82695_e(ChunkProviderGenerate.java:495)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at Reika.DragonAPI.Instantiable.Data.Immutable.Coordinate.getBlockKey(Coordinate.java:303)
	at Reika.ChromatiCraft.TileEntity.Networking.TileEntityCrystalPylon.updateEntity(TileEntityCrystalPylon.java:385)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:562)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at climateControl.customGenLayer.GenLayerLowlandRiverMix.func_75904_a(GenLayerLowlandRiverMix.java:98)
	at climateControl.customGenLayer.GenLayerRiverMixWrapper.func_75904_a(GenLayerRiverMixWrapper.java:66)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:23)
	at net.minecraft.world.biome.WorldChunkManager.func_76931_a(WorldChunkManager.java:163)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
	at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:58)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:160)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
	at net.minecraft.world.World.func_72807_a(World.java:130)
	at Reika.CaveControl.CaveLoader.getEffectiveBiome(CaveLoader.java:196)
	at Reika.CaveControl.CaveLoader.getDefinition(CaveLoader.java:189)
	at Reika.CaveControl.Generators.ControllableMineshaftGen.getConfig(ControllableMineshaftGen.java:45)
	at Reika.CaveControl.Generators.ControllableMineshaftGen.func_75047_a(ControllableMineshaftGen.java:41)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)

-- Feature being prepared --
Details:
	Is feature chunk: False
	Chunk location: -28,59
	Chunk pos hash: 257698037732
	Structure type: Reika.CaveControl.Generators.ControllableMineshaftGen
Stacktrace:
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_82695_e(ChunkProviderGenerate.java:495)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-384,74,858), Chunk: (at 0,4,10 in -24,53; contains blocks -384,0,848 to -369,255,863), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Stacktrace:
	at Reika.DragonAPI.Instantiable.Data.Immutable.Coordinate.getBlockKey(Coordinate.java:303)
	at Reika.ChromatiCraft.TileEntity.Networking.TileEntityCrystalPylon.updateEntity(TileEntityCrystalPylon.java:385)
	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:562)
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
	Name: CCchroma.pylon // Reika.ChromatiCraft.TileEntity.Networking.TileEntityCrystalPylon
	Block type: ID #1809 (tile.crystal.pylon // Reika.ChromatiCraft.Block.BlockCrystalPylon)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-385,78,858), Chunk: (at 15,4,10 in -25,53; contains blocks -400,0,848 to -385,255,863), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Actual block type: ID #1809 (tile.crystal.pylon // Reika.ChromatiCraft.Block.BlockCrystalPylon)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Mgctz'/401, l='New World', x=-1140.00, y=70.00, z=1599.12]]
	Chunk stats: ServerChunkCache: 1341 Drop: 456
	Level seed: -6673442162575459660
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-623,70,-323), Chunk: (at 1,4,13 in -39,-21; contains blocks -624,0,-336 to -609,255,-321), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 205889 game time, 306343 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 64398 (now: false), thunder time: 72757 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Mgctz** [comment]
**fixed by changing the latest version of climatecontrol mod**

**Comment by ReikaKalseki** [comment]
Updating *to* or not using the latest version? Updating the version on your own could very easily break the pack.
