### ISSUE TITLE
Client disconnect when right clicking some CC/RoC items while holding TiCo tools. 

### ISSUE THREAD

**Issue by vintagepc** [ReikaKalseki/Reika_Mods_Issues#3230]
I have noticed I sometimes get client disconnects when I right click on machines or items from CC or RoC while holding a Tinker's Construct tool in my active slot. 

Client message is "Connection Lost: Internal Server Error", but the server remains up and I can reconnect immediately. 

I noticed it early on when I was playing these mods (as in several years ago, v21 era - at the time I just dealt with it) and I've recently picked them up again and occasionally forget about this.  Annoyingly, it is a heisenbug and doesn't happen reliably - sometimes I can go right clicking things all around my base without issue. I just reproduced it twice in a row with the casting table and when I tried a third time to reproduce it with RoC machines it started working fine. Not sure what else to make of it so I'm reporting it in the hope there might be something informative here. I have no expectations of a fix anytime soon since it seems to be one of _those_ bugs. 

Here is the NBT data for the tool in question: 
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/53943260/61a9b32b-b4b6-4a38-8203-a32457c4585c)

Client side log isn't very useful:

```
[21:00:43] [Client thread/INFO]: DRAGONAPI: Pipelining texture from Reika.ChromatiCraft.ChromatiCraft to Textures/Particle/64x.png
[21:00:45] [Client thread/INFO]: Reika.ChromatiCraft.GUI.Tile.Inventory.GuiCastingTable
[21:00:45] [Client thread/INFO]: Reika.ChromatiCraft.Container.ContainerCastingTable
[21:00:45] [Netty Client IO #3/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -30
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -20
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -21
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -15
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -22
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -29
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -13
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -18
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -19
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -16
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -17
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -14
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -37
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -35
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -34
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -38
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -31
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -28
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -33
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -39
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -40
[21:00:45] [Netty Client IO #3/INFO]: Unregistered Dimension: -36
[21:00:45] [Netty Client IO #3/INFO]: Disconnect from server: Unregistering RFTools dimensions
[21:00:45] [Client thread/INFO]: Applying holder lookups
[21:00:45] [Client thread/INFO]: Holder lookups applied
[21:00:46] [Client thread/INFO]: Mw.close: closing...
[21:00:46] [Client thread/INFO]: waiting for 123 tasks to finish...
[21:00:46] [Client thread/INFO]: done
```

Server side log reports the following:

```

[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for ExpandedRedstone. Hash: 69BD4C17AE648B09AF07FE1D49C6983A44824561606C43F7FE4D80CEBB2B1E8E
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for GeoStrata. Hash: F2520EC10ECBF196C711B257E26AA0D42DF5BE44780BC4DC2C7AED414D7910D2
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for ElectriCraft. Hash: 6D3E81B80084DCC7E8F710937BD2E11C523721B7CC749C40F22B3B15E6ACC18D
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for DragonAPI. Hash: 170E57B7BCCB24FBF143CF795873AC646042C2CE79A875FA6205D011C308F132
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for ReactorCraft. Hash: 74D5A950CE3FB705067756F4F38FA8F11E1593434D7CCA42A1C39324E71C76FC
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for ChromatiCraft. Hash: 1657F67E9A205502071D9BF62FF7F9B47A7E93792FB559F2027079DFFB79578D
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for CondensedOres. Hash: 1B087D5976A1019F19F47A8C1056F7B1BA96B43C654576A2F3C0BE65F6C02D87
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for RotaryCraft. Hash: 6754AD22D6A8E8A3D0AF3A9667D4B0703ABFC6C1D4F83DFBE49A6AFCD1BDD8DB
[01:00:28] [Server thread/INFO]: DRAGONAPI: Player VintagePC passed hash check for TerritoryZone. Hash: 077D468623A5C3AA3865EB384F3DFEFA99A280A20ACCD1166D8F32BCEB7D0294
[01:00:45] [Server thread/WARN]: Failed to handle packet for /[My IP]:55700
java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[01:00:45] [Server thread/INFO]: VintagePC lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

```

Apologies if there is an existing issue, I tried to do my due diligence by searching for "Tinkers Construct" and "Client Crash"/"Connection Lost" and did not see anything relevant.

**Comment by ReikaKalseki** [comment]
> Apologies if there is an existing issue, I tried to do my due diligence by searching for "Tinkers Construct" and "Client Crash"/"Connection Lost" and did not see anything relevant.

Your searching was...ineffective.

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1423, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/652, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/590, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/855, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/161, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1358, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1474, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1488, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1565, https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1871
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2194
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2665
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/3101

**Comment by ReikaKalseki** [comment]
@OvermindDL1 if you want to write your thing about this being a vanilla race condition again, feel free.

**Comment by vintagepc** [comment]
alrighty then. Sorry for the time-waste, I'll crawl back under my rock now :wink:

**Comment by vintagepc** [comment]
Related question(s), because I just got super frustrated having had this happen repeatedly with the Piston Tape puzzle (with empty hands) on the control blocks, losing progress each time because the dimension resets.

1. I take it this sort of disconnect isn't detectable by CC as it's all inside MC code and therefore the persistence crystals don't have their usual effect? 

2.  ~~Given I'm currently unable to complete those puzzles (and I have finished the mod before) I ended up using chromaprog to mark the structures (Kitrino/Zambaru), as complete. (after completing the remaining puzzle normally I do have `ALLCORES` progress flag and got the pop-up(s).  However, the monument is refusing to complete (I placed all the mineral blocks and chroma buckets, the core beams/music play but I just get the error sound when hitting the center orb).  I'm guessing this is because I had to magic in those two dimension cores via Creative GUI. If that's the case, is there something else I can do to enable me to get those final two cores "properly" enough to reach endgame, or am I stuck? Alas the bypass passwords I saved from my previous playthough are no longer valid; (it's the same world instance/seed but from a backup that was taken before I completed the last playthrough)~~ Edit: My portal tuning was... ineffective. (But I wouldn't have put it past you :grinning: ) Completion sequence is pretty epic btw, nice work! Last time around, it wasn't as elaborate)

**Comment by ReikaKalseki** [comment]
If you are playing SSP the entire server shuts down when you log out, and that means there is nothing to keep loaded.

**Comment by vintagepc** [comment]
This is a dedicated server instance (definitely understandable if it was SSP though)

**Comment by ReikaKalseki** [comment]
OK, in that case they *should* work, as their only other condition is that they do not help when intentionally logging out, which this does not count as.

**Comment by vintagepc** [comment]
Hmm... ok. Currently off in the far regions (trying to locate a Radiant Fissures biome :grinning: ) but I'll set up to repro and watch the log live serverside in the next few days to see if there's anything interesting that might explain why it's not persisting. Should be a nearly-stock config, the only changes I recall making were resolving some biome ID collisions.

**Comment by vintagepc** [comment]
Just my luck...  I spend a good chunk of time yesterday wandering and today I connect and find said biome in about 5 minutes. >_<

Anyway, I headed back to the main area and here's the server side log -  looks like it might actually be a different error (not NPE, it's index-out-of-bounds). And you can see about 1 second after I get dropped it resets the dimension and it's gone when I reconnect about 8 seconds later... most likely because it thinks I voluntarily left: `[Server thread/INFO]: ?f[ops]?r ?c[OP] ?rVintagePC left the game` even though I was actually "violently ejected" :wink: 

Seems like this was reported once before in #2734 but dismissed due to world corruption issues.  (Haven't seen any sign of that myself (no misaligned chunks, partial resets) while touring the dimension)

```
[22:10:03] [Server thread/WARN]: Failed to handle packet for /[My IP]:40126
java.lang.ArrayIndexOutOfBoundsException: 10
        at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.TapeStage.fireEmitters(TapeStage.java:130) ~[TapeStage.class:?]
        at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController$TilePistonController.fire(BlockPistonController.java:352) ~[BlockPistonC
ontroller$TilePistonController.class:?]
        at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController$TilePistonTrigger.onRightClick(BlockPistonController.java:222) ~[BlockPi
stonController$TilePistonTrigger.class:?]
        at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController.onRightClicked(BlockPistonController.java:99) ~[BlockPistonController.cl
ass:?]
        at Reika.ChromatiCraft.Base.BlockDimensionStructureTile.func_149727_a(BlockDimensionStructureTile.java:41) ~[BlockDimensionStructureTile.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[22:10:03] [Server thread/INFO]: VintagePC lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold
=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[22:10:03] [Server thread/INFO]: ?f[ops]?r ?c[OP] ?rVintagePC left the game
[22:10:03] [Server thread/INFO]: CHROMATICRAFT: Checking dimension for unload - player entities: [EntityPlayerMP['VintagePC'/37352199, l='world', x=73.52, y=90.00
, z=-4243.36]][EntityPlayerMP['VintagePC'/37352199, l='world', x=73.52, y=90.00
, z=-4243.36]]
[22:10:04] [Server thread/INFO]: CHROMATICRAFT: Resetting dimension of age 11725; Server shutdown? false
[22:10:04] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Initializing Dimension Structure generation thread...
[22:10:04] [ChromatiCraft Dimension Biome/INFO]: CHROMATICRAFT: Initializing Dimension Biome generation thread...
[22:10:04] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a BROWN TDMAZE
[22:10:04] [ChromatiCraft Dimension Region/INFO]: CHROMATICRAFT: Initializing Dimension Region generation thread...
[22:10:04] [ChromatiCraft Dimension Skyriver/INFO]: CHROMATICRAFT: Initializing Dimension Skyriver generation thread...
[22:10:04] [Server thread/INFO]: CHROMATICRAFT: Resetting dimension of age 11725; Server shutdown? false
[22:10:04] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Initializing Dimension Structure generation thread...
[22:10:04] [ChromatiCraft Dimension Biome/INFO]: CHROMATICRAFT: Initializing Dimension Biome generation thread...
[22:10:04] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a BROWN TDMAZE
[22:10:04] [ChromatiCraft Dimension Region/INFO]: CHROMATICRAFT: Initializing Dimension Region generation thread...
[22:10:04] [ChromatiCraft Dimension Skyriver/INFO]: CHROMATICRAFT: Initializing Dimension Skyriver generation thread...
[22:10:07] [ChromatiCraft Dimension Region/INFO]: CHROMATICRAFT: Dimension Region generation thread complete; Elapsed time: 3.323s. Central region created; 15943.
732010341246 +/- 650.0
[22:10:07] [Server thread/INFO]: Unloading dimension 60
[22:10:07] [ChromatiCraft Dimension Fissurepatterns/INFO]: CHROMATICRAFT: Initializing Dimension Fissurepatterns generation thread...
[22:10:07] [ChromatiCraft Dimension Skyriver/INFO]: CHROMATICRAFT: Dimension Skyriver generation thread complete; Elapsed time: 3.328s. Generated sky rivers, with
 32 rays and 33188 points.
[22:10:07] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3902ms behind, skipping 78 tick(s)
[22:10:07] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 3505 ms
[22:10:07] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a ORANGE TDMAZE
[22:10:07] [ChromatiCraft Dimension Fissurepatterns/INFO]: CHROMATICRAFT: Dimension Fissurepatterns generation thread complete; Elapsed time: 0.146s. 500 fissure 
layouts calculated.
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 135 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a PINK SHIFTMAZE
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 15 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a RED LOCKS
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 6 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a GREEN MUSIC
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 1 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a BLACK NONEUCLID
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 1 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a GRAY GOL
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 1 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a LIME LASER
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 119 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a LIGHTBLUE LASER
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 15 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a BLUE WATER
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 22 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a LIGHTGRAY LIGHTPANEL
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 2 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a MAGENTA LIGHTPANEL
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 3 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a PURPLE PISTONTAPE
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 2 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a YELLOW PISTONTAPE
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 2 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a CYAN RAYBLEND
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 262 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Calculating a WHITE RAYBLEND
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Done in 331 ms
[22:10:08] [ChromatiCraft Dimension Structure/INFO]: CHROMATICRAFT: Dimension Structure generation thread complete; Elapsed time: 4.428s. 16 structures generated.
[22:10:09] [User Authenticator #71/INFO]: UUID of player VintagePC is e472e09a-75ed-428d-9c32-f9f6ba5587a2
[22:10:09] [Netty IO #1/INFO]: Client protocol version 2

```

These are from over the weekend where I lost my progress, same issue/trace:

```
2023-07-09-1.log:[13:46:51] [Server thread/WARN]: Failed to handle packet for /[IP]:53178
2023-07-09-1.log-java.lang.ArrayIndexOutOfBoundsException: 58
2023-07-09-1.log-       at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.TapeStage.fireEmitters(TapeStage.java:130) ~[TapeStage.class:?]
2023-07-09-1.log-       at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController$TilePistonController.fire(BlockPistonController.java:352) ~[BlockPistonController$TilePistonController.class:?]
--
2023-07-09-1.log:[14:30:35] [Server thread/WARN]: Failed to handle packet for /[IP]:58644
2023-07-09-1.log-java.lang.ArrayIndexOutOfBoundsException: 28
2023-07-09-1.log-       at Reika.ChromatiCraft.World.Dimension.Structure.PistonTape.TapeStage.fireEmitters(TapeStage.java:130) ~[TapeStage.class:?]
2023-07-09-1.log-       at Reika.ChromatiCraft.Block.Dimension.Structure.PistonTape.BlockPistonController$TilePistonController.fire(BlockPistonController.java:352) ~[BlockPistonController$TilePistonController.class:?]
```

Hope that is interesting/useful, if not don't hesitate to let me know what else I can provide.  DragonAPI isn't telling me any of your other mods are out of date, and CC is v31b.

**Comment by ReikaKalseki** [comment]
This is fixed in v33.
