### ISSUE TITLE
Crash with Disabled TiCon Tools

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#326]
Recently, due to TiCon's decision to drop support for all but critical issues on the 1.7.10 version of their mod, I've been trying to remove its features from my modpack, without dropping it altogether (Iguana Tinker Tweaks is still the only way to change tool mining levels to keep up my intended progression).

To this end, I have disabled all TiCon features from the TinkersModules.cfg file.

However, the game crashes with the following error:

```
[09:50:00] [Client thread/ERROR]: The following problems were captured during this phase
[09:50:00] [Client thread/ERROR]: Caught exception from RotaryCraft
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.toString(Unknown Source) ~[add.class:?]
    at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_60]
    at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_60]
    at Reika.DragonAPI.ModInteract.RecipeHandlers.SmelteryRecipeHandler.addCasting(SmelteryRecipeHandler.java:100) ~[SmelteryRecipeHandler.class:?]
    at Reika.DragonAPI.ModInteract.RecipeHandlers.SmelteryRecipeHandler.addCasting(SmelteryRecipeHandler.java:89) ~[SmelteryRecipeHandler.class:?]
    at Reika.DragonAPI.ModInteract.RecipeHandlers.SmelteryRecipeHandler.addCasting(SmelteryRecipeHandler.java:85) ~[SmelteryRecipeHandler.class:?]
    at Reika.DragonAPI.ModInteract.RecipeHandlers.SmelteryRecipeHandler.addReversibleCasting(SmelteryRecipeHandler.java:111) ~[SmelteryRecipeHandler.class:?]
    at Reika.DragonAPI.ModInteract.DeepInteract.TinkerMaterialHelper$CustomTinkerMaterial.registerSmelteryCasting(TinkerMaterialHelper.java:437) ~[TinkerMaterialHelper$CustomTinkerMaterial.class:?]
    at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:559) ~[RotaryCraft.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[09:50:00] [Client thread/ERROR]: Caught exception from ExtraTiC
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(Unknown Source) ~[add.class:?]
    at tconstruct.library.crafting.CastingRecipe.matches(CastingRecipe.java:28) ~[CastingRecipe.class:?]
    at tconstruct.library.crafting.LiquidCasting.contains(LiquidCasting.java:18) ~[LiquidCasting.class:?]
    at tconstruct.library.crafting.LiquidCasting.addCastingRecipe(LiquidCasting.java:44) ~[LiquidCasting.class:?]
    at tconstruct.library.crafting.LiquidCasting.addCastingRecipe(LiquidCasting.java:103) ~[LiquidCasting.class:?]
    at glassmaker.extratic.common.RecipeHandler._addItemStackCasting(RecipeHandler.java:640) ~[RecipeHandler.class:?]
    at glassmaker.extratic.common.RecipeHandler._addToolsCasting(RecipeHandler.java:673) ~[RecipeHandler.class:?]
    at glassmaker.extratic.common.RecipeHandler._addM3BaseRecipes(RecipeHandler.java:942) ~[RecipeHandler.class:?]
    at glassmaker.extratic.common.RecipeHandler.addPartsRecipes(RecipeHandler.java:187) ~[RecipeHandler.class:?]
    at glassmaker.extratic.common.RecipeHandler.addRecipes(RecipeHandler.java:171) ~[RecipeHandler.class:?]
    at glassmaker.extratic.ExtraTiC.postInit(ExtraTiC.java:67) ~[ExtraTiC.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1492-1.7.10-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[09:50:01] [Client thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145) ~[k.class:?]
    at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:333) ~[b.class:?]
    at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:303) ~[b.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) ~[Main.class:?]
    ... 14 more
[09:50:01] [Client thread/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:497)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:971)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 8 more
[09:50:01] [Client thread/INFO]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 5
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:971)
[09:50:01] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "SAPUpdateThread" Exception in thread "Client thread" 
Game was killed by user.
```

If I'm reading this right, It seems that RotaryCraft is attempting to add casts and parts regardless of their active status in TiC.  Is there an option that can disable RoC casting support?

**Comment by ReikaKalseki** [comment]
This is actually in the tools, not the casts, though those probably should be disabled if the casting system is totally disabled.

I can probably hook into his config.

**Comment by ghost** [comment]
Thanks.  If you need more information, let me know.

**Comment by ReikaKalseki** [comment]
OK...after digging through TiC and Mantle code, he uses a dedicated [pulsar](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/TConstruct.java#L143) system. Looking into it, it has [nothing for me to hook into](https://github.com/SlimeKnights/Mantle/blob/master/src/mantle/pulsar/control/PulseManager.java#L91)...

Well...it _does_ have [this](https://github.com/SlimeKnights/Mantle/blob/master/src/mantle/pulsar/control/PulseManager.java#L258), but I really do not want to keep reflectively calling a list iteration...

**Comment by ghost** [comment]
And I take it there's no way to read the "TinkersModules.cfg" config file directly, and just check at startup the status of the tinker's weaponry module?

**Comment by ReikaKalseki** [comment]
Correct. I used to try that, and it broke everything.

That said, I have an idea.

**Comment by ghost** [comment]
Alright, thanks for trying, at least.

**Comment by ReikaKalseki** [comment]
I think I pulled it off.

**Comment by ghost** [comment]
Ah, then I look forward to v10.  Thanks! :)
