### ISSUE TITLE
[DragonAPI v32c][DragonRealm] DragonAPI_Retrogen cache file writing causes server to freeze periodically in large worlds

### ISSUE THREAD

**Issue by defaultuser1** [ReikaKalseki/Reika_Mods_Issues#3277]
There are two cache files that are written to every time there is a world save event:
- world\DragonAPI_Retrogen\DIM0\CondensedOresPrototype_Cinnabar.dat"
- world\DragonAPI_Retrogen\DIM0\CondensedOresPrototype_Emerald.dat"

As these files get larger, every time a world save occurs (every 30 seconds or so) the server will freeze because it takes several seconds to write out these files. 

I believe the culprit is the writeLinesToFile here: https://github.com/ReikaKalseki/DragonAPI/blob/c29c4fcc2d3a65566783a4a163d8e682116e868c/Auxiliary/Trackers/RetroGenController.java#L175.

Because these files are just text and being written to disk one line at a time, it is slow which becomes an issue the bigger these files get. I have a procmon log showing the files being written several bytes at a time over a period of 5 or so seconds but the log is 600+MB so I have just attached a screenshot showing the start.
![procmon_log](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/5995551/88c4ce81-4928-4b33-bbb2-c640de4c6814)

If I dump the stacks while the server is frozen, this trace occurs:

"Server thread" #75 prio=5 os_prio=0 tid=0x000001c4fedb6000 nid=0x7114 runnable [0x0000007b453fe000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at org.apache.commons.io.IOUtils.writeLines(IOUtils.java:1667)
	at Reika.DragonAPI.IO.ReikaFileReader.writeLinesToFile(ReikaFileReader.java:262)
	at Reika.DragonAPI.Auxiliary.Trackers.RetroGenController.updateFile(RetroGenController.java:175)
	at Reika.DragonAPI.Auxiliary.Trackers.RetroGenController.onWorldSave(RetroGenController.java:84)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_957_RetroGenController_onWorldSave_Save.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:810)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I also tried deleting the cache files and restarting the server which resolved the issue so I'm pretty confident this is the cause.

I didn't dig into what the cache is for but if the cache data is only ever appended to, then a potential fix could be to track changes to the cache data in memory and only append anything to the files that has changed since the last write.

**Comment by defaultuser1** [comment]
I decided to try patching the function to test out a potential fix by changing the last part of RetroGenController:updateFile to just write the whole file at once. It's still probably unnecessarily writing out the whole file each world save but it's a quick easy fix.
Been running with this for a while now and it seems to work no issues and is about 8000 times faster.

I'm still curious as to whether other people are encountering this issue or not. Particularly on DragonRealm where exploration is a key focus, it doesn't take long for the freezes to start becoming noticeable as the world gets larger.

```
private void updateFile(World world, GeneratorEntry e)
{
        DataCache cache = this.getOrCreateCache(world);
        if (cache == null) {
            return;
        }
        File f = this.getFile(world, e);
        if (f == null) {
            return;
        }
        try {
            f.delete();
            f.getParentFile().mkdirs();
            f.createNewFile();
        }
        catch (IOException ex) {
            ex.printStackTrace();
        }
        ArrayList<String> ex = new ArrayList<String>();
        for (ChunkCoordIntPair p : cache.generatedChunks.get(e.id)) {
            ex.add(this.toString(p));
        }
        // ReikaFileReader.writeLinesToFile(f, li, true, Charsets.UTF_8);
        String listString = String.join((CharSequence)"\r\n", ex);
        FileOutputStream fout = new FileOutputStream(f);
        fout.write(listString.getBytes());
        fout.flush();
        ((OutputStream)fout).close();
    }
```
![image](https://github.com/ReikaKalseki/Reika_Mods_Issues/assets/5995551/26e89e7d-17d2-4b1f-8e3a-b3a4c864c519)
