### ISSUE TITLE
[Chromaticraft (DragonRealm)] Attempting first craft with Pylon Energy causes crash 

### ISSUE THREAD

**Issue by metnavman** [ReikaKalseki/Reika_Mods_Issues#3357]
Time: 3/29/24 8:59 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Tried to access energization manager from client!
	at Reika.DragonRealmCore.Energizer.EnergizationManager.getEnergizationLevel(EnergizationManager.java:40)
	at Reika.DragonRealmCore.Util.DragonRealmHooks.updateCCNetFlowThrottle(DragonRealmHooks.java:1304)
	at Reika.ChromatiCraft.Magic.Network.CrystalFlow.drain(CrystalFlow.java)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.tick(CrystalNetworker.java:322)
	at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.serverTick(TickRegistry.java:89)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_441_TickRegistry_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

The "Enable Atmospheric Permeability Mediation" config line is set to "false"

**Comment by metnavman** [comment]
And this is after changing that config line to "true" and attempting again:

Time: 3/30/24 7:43 AM
Description: Exception in server tick loop

java.lang.IllegalStateException: Tried to access energization manager from client!
	at Reika.DragonRealmCore.Energizer.EnergizationManager.getEnergizationLevel(EnergizationManager.java:40)
	at Reika.DragonRealmCore.Util.DragonRealmHooks.updateCCNetFlowThrottle(DragonRealmHooks.java:1304)
	at Reika.ChromatiCraft.Magic.Network.CrystalFlow.drain(CrystalFlow.java)
	at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.tick(CrystalNetworker.java:322)
	at Reika.DragonAPI.Auxiliary.Trackers.TickRegistry.serverTick(TickRegistry.java:89)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_443_TickRegistry_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
