### ISSUE TITLE
[GeoStrata] Crash upon loading/creating new world

### ISSUE THREAD

**Issue by Jonius7** [ReikaKalseki/Reika_Mods_Issues#3386]
I have narrowed it down by including as few mods as possible. The source of the crash is between Geostrata and AdditionalBuildcraftObjects' ScaryGen. If ABO is disabled, the world will load with Geostrata.
Related to #3295 

```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 18/06/24 7:51 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at da3dsoul.scaryGen.generate.GeostrataGen.Ore.COFH.WorldGenMinableClusterOverride.generateBlock(WorldGenMinableClusterOverride.java:173)
	at da3dsoul.scaryGen.generate.GeostrataGen.Ore.COFH.WorldGenMinableClusterOverride.generateBlock(WorldGenMinableClusterOverride.java:159)
	at da3dsoul.scaryGen.generate.GeostrataGen.Ore.COFH.WorldGenMinableClusterOverride.func_76484_a(WorldGenMinableClusterOverride.java:114)
	at cofh.lib.world.feature.FeatureGenUniform.generateFeature(FeatureGenUniform.java:39)
	at cofh.lib.world.feature.FeatureBase.generateFeature(FeatureBase.java:116)
	at cofh.core.world.WorldHandler.generateWorld(WorldHandler.java:270)
	at cofh.core.world.WorldHandler.generate(WorldHandler.java:233)
	at Reika.DragonAPI.Auxiliary.WorldGenInterceptionRegistry.interceptIWG(WorldGenInterceptionRegistry.java:213)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at Reika.DragonAPI.Auxiliary.WorldGenInterceptionRegistry.interceptChunkPopulation(WorldGenInterceptionRegistry.java:186)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2002501216 bytes (1909 MB) / 2819096576 bytes (2688 MB) up to 5779226624 bytes (5511 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6200m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	Sanity Checker Notification: The DragonAPI environment sanity checker is disabled. Note that the mod showing up in the stacktrace may not be the cause, especially if the crash involves general-use registries like recipes or biomes.
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
	UCHIJAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAA	CodeChickenCore{1.2.1} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{2.6.7-GTNH-pre} [NotEnoughItems] (NotEnoughItems-2.6.7-GTNH-pre.jar) 
	UCHIJAA	sdnf{1.0} [Storage Drawers NEI Fix] (minecraft.jar) 
	UCHIJAA	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	unimixins{0.1.17} [UniMixins] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	unimixins-compat{0.1.17} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	mixinextras{0.1.17} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.17-fastutil.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAA	BuildCraft|Core{7.1.25} [BuildCraft] (buildcraft-7.1.25.jar) 
	UCHIJAA	BuildCraft|Builders{7.1.25} [BC Builders] (buildcraft-7.1.25.jar) 
	UCHIJAA	BuildCraft|Robotics{7.1.25} [BC Robotics] (buildcraft-7.1.25.jar) 
	UCHIJAA	BuildCraft|Silicon{7.1.25} [BC Silicon] (buildcraft-7.1.25.jar) 
	UCHIJAA	BuildCraft|Energy{7.1.25} [BC Energy] (buildcraft-7.1.25.jar) 
	UCHIJAA	BuildCraft|Transport{7.1.25} [BC Transport] (buildcraft-7.1.25.jar) 
	UCHIJAA	BuildCraft|Factory{7.1.25} [BC Factory] (buildcraft-7.1.25.jar) 
	UCHIJAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
	UCHIJAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAA	DragonAPI{v33b} [DragonAPI] (DragonAPI 1.7.10 V33b.jar) 
	UCHIJAA	GeoStrata{v33a} [GeoStrata] (GeoStrata 1.7.10 V33a.jar) 
	UCHIJAA	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.13} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.13.jar) 
	UCHIJAA	ActuallyAdditions{1.7.10-r21} [Actually Additions] (ActuallyAdditions-1.7.10-r21.jar) 
	UCHIJAA	LogisticsPipes{1.2.15-GTNH} [Logistics Pipes] (logisticspipes-1.2.15-GTNH.jar) 
	UCHIJAA	additionalpipes{4.7.7} [Additional Pipes] (additionalpipes-4.7.7.jar) 
	UCHIJAA	ae2fc{g92699c9} [AE2 Fluid Crafting] (ae2fc-1.7.10-g92699c9.jar) 
	UCHIJAA	bdlib{1.9.5.1} [BD Lib] (bdlib-1.9.5.1-mc1.7.10.jar) 
	UCHIJAA	ae2stuff{0.5.1.61} [AE2 Stuff] (ae2stuff-0.5.1.61-mc1.7.10.jar) 
	UCHIJAA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJAA	Avaritia{1.13} [Avaritia] (Avaritia-1.13.jar) 
	UCHIJAA	wanionlib{1.7.10-1.8} [WanionLib] (WanionLib-1.7.10-1.8.jar) 
	UCHIJAA	avaritiaddons{1.4b} [Avaritiaddons] (Avaritiaddons-1.4b.jar) 
	UCHIJAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAA	BuildCraft|Compat{7.1.8} [BuildCraft Compat] (buildcraft-compat-7.1.8.jar) 
	UCHIJAA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJAA	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UCHIJAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAA	endercore{1.7.10-0.2.0.40_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.40_beta.jar) 
	UCHIJAA	EnderIO{1.7.10-2.3.0.430_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.430_beta.jar) 
	UCHIJAA	enderioaddons{0.10.13} [Ender IO Addons] (EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta.jar) 
	UCHIJAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAA	EnderTech{1.7.10-0.3.2.405} [EnderTech] (EnderTech-1.7.10-0.3.2.405.jar) 
	UCHIJAA	ExpandedRedstone{v33a} [Expanded Redstone] (ExpandedRedstone 1.7.10 V33a.jar) 
	UCHIJAA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCHIJAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAA	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAA	p455w0rdslib{1.0.4} [p455w0rd's Library] (p455w0rdslib-1.7.10-1.0.4.jar) 
	UCHIJAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCHIJAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAA	StorageDrawersBop{1.7.10-1.1.1} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar) 
	UCHIJAA	StorageDrawersForestry{1.7.10-1.1.2} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.2.jar) 
	UCHIJAA	StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.1.2.jar) 
	UCHIJAA	StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
	UCHIJAA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJAA	thaumcraftneiplugin{1.7.10-1.7a} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAA	tcneiadditions{1.3.6} [Thaumcraft NEI Additions] (tcneiadditions-1.3.6.jar) 
	UCHIJAA	thaumicenergistics{1.1.3.0} [Thaumic Energistics] (thaumicenergistics-1.1.3.0.jar) 
	UCHIJAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAA	ThermalSmeltery{1.0} [Thermal Smeltery] (ThermalSmeltery-1.3.1.4.jar) 
	UCHIJAA	UsefulTNT{v33a} [Useful TNT] (UsefulTNT 1.7.10 V33a.jar) 
	UCHIJAA	ae2wct{1.7.10-rv3-1.8.7.9b} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b.jar) 
	UCHIJAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAA	redgear_core{2.2.2} [Red Gear Core] (RedGearCore-1.7.10-2.2.2.jar) 
	UCHIJAA	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
	UCHIJAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.2.1-172
	List of loaded APIs: 
		* ActuallyAdditionsAPI (3) from ActuallyAdditions-1.7.10-r21.jar
		* ae2wct|API (1.7.10-rv3-1.8.6b) from WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b.jar
		* AgriCraftAPI (1.0) from DragonAPI 1.7.10 V33b.jar
		* apAPI (2) from additionalpipes-4.7.7.jar
		* appliedenergistics2|API (@aeversion@) from DragonAPI 1.7.10 V33b.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* bcadditionsAPI (2.1.1) from BuildcraftAdditions-1.7.10-2.2.5.jar
		* BotaniaAPI (61) from Avaritia-1.13.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.25.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|core (2.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.25.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.25.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.25.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.25.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.25.jar
		* BuildCraftAPI|recipes (3.1) from buildcraft-7.1.25.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.25.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.25.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.1.25.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.25.jar
		* CoFHAPI (1.7.10R1.0.2) from ActuallyAdditions-1.7.10-r21.jar
		* CoFHAPI|block (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|core (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from p455w0rdslib-1.7.10-1.0.4.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.1.8.jar
		* CoFHAPI|item (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|modhelpers (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|transport (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|world (1.7.10R1.1.0) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui|container (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|slot (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render|particle (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|helpers (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|util|position (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world|feature (1.7.10R1.0.4B1) from EnderTech-1.7.10-0.3.2.405.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.430_beta.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V33b.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.9.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
		* thaumicenergistics|API (1.1) from thaumicenergistics-1.1.3.0.jar
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from p455w0rdslib-1.7.10-1.0.4.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (@aeversion@ from DragonAPI 1.7.10 V33b.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Jonius7** [comment]
I have downgraded Reika mods to v32, no issues.
