### ISSUE TITLE
crash with ae2

### ISSUE THREAD

**Issue by Kenshij** [ReikaKalseki/Reika_Mods_Issues#367]
reported to ae2 https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1975

ae2 have implemented in r3-alpha-9 an item exporter or something, which runs in chromatiichraft in an nullPointer Exception. After this chromaticraft crashes in pre mod loading phase with NoClassDefFound

reduced log: http://pastebin.com/VhNAfRrw

clean install with only dragon/chroma and ae2 : 

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/29/15 11:24 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
    at Reika.ChromatiCraft.Registry.ChromaResearch.<clinit>(ChromaResearch.java:76)
    at Reika.ChromatiCraft.ChromaRecipes.addRecipes(ChromaRecipes.java:61)
    at Reika.ChromatiCraft.ChromatiCraft.load(ChromatiCraft.java:383)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 18 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1423237208 bytes (1357 MB) / 2765094912 bytes (2637 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHI    Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHI    appliedenergistics2-core{rv3-alpha-9} [Applied Energistics 2 Core](minecraft.jar) 
    UCHI    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHI    appliedenergistics2{rv3-alpha-9} [Applied Energistics 2](appliedenergistics2-rv3-alpha-9.jar) 
    UCHI    DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V9b.jar) 
    UCHE    ChromatiCraft{1.0} [ChromatiCraft](ChromatiCraft 1.7.10 V9b.jar) 
    UCHI    GeoStrata{1.0} [GeoStrata](GeoStrata 1.7.10 V9a.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3496' Renderer: 'Intel(R) HD Graphics 4400'
    AE2 Version: alpha rv3-alpha-9 for Forge 10.13.4.1448

**Comment by ReikaKalseki** [comment]
The log makes no mention of AE, and the crash provides little insight...

**Comment by 1skandar** [comment]
At a guess the AE API has changed, probably significantly, between RV2 and RV3. This really shouldn't be surprising, all things considered.

As is almost always the case, whenever a mod goes through a major revision like this any other mod that uses its API will need to update to support it. Because RV3 is still in alpha this hasn't happened for most mods. As such, you'll need to check each mod that offers AE2 compatibility and see if they support RV3. If they don't you can't use them together, simple as that.

**Comment by Kenshij** [comment]
you know the error is thrown from cromaticraft in the pre init phase, that it can't find some of its owne classes

**Comment by ReikaKalseki** [comment]
Yes, but since that class exists, it means initializing it failed. And since that class is a registry class, and _internal to a bigger registry class_, it means any one of the fragments failed to initialize.

**Comment by wormzjl** [comment]
I'm getting the same problem, how did you solve this finally?

**Comment by 1skandar** [comment]
If you are using AE2 rv3 alpha you'll need to downgrade to rv2

**Comment by ReikaKalseki** [comment]
So...AE has broken its API yet again? With now nine breaking changes in six months, I am starting to get very exasperated.

**Comment by 1skandar** [comment]
From the rv3 download page: Alpha builds are not compatible with any AE2 addons, 

I'd say to not worry about updating to rv3 until it is at least in beta unless you can support rv2 AND rv3 at the same time because of this line, also from the download page: These builds are considered unstable, they may contain item dupes, deletions or other world ending bugs these builds are for TESTING ONLY. 

Which pretty much people using these builds in real worlds are asking for trouble anyway.

**Comment by Kenshij** [comment]
@wormzjl you don't need to downgrade ... disable in CustomRecipes.cfg all and it is working

@1skandar please, what you say is not true ... thaumicenergistics-0.9.0.0 is only with rev3-alpha compatible, so there are AE2 addons which are compatible...

**Comment by wormzjl** [comment]
Strange, it only crashes on first launch but afterwards worked fine, this is too weird

**Comment by 1skandar** [comment]
@Kenshij I only quoted from the download page. And the fact remains playing with an alpha version is not recommended for exactly this kind of reason.

**Comment by philmalv129** [comment]
> playing with an alpha version is not recommended for exactly this kind of reason

You mean that modders can't get off their lazy asses and work together for once? Why does it always have to be the players who take the brunt of this kind of thing?

**Comment by 1skandar** [comment]
Because being an alpha means the code is under heavy development and may change significantly from version to version. As such, compatibility may break from version to version. Which makes targeting that code for add ons difficult at best. 

Your attitude is poor, and you come off as an entitled dickhead, FYI. Modders do this for free and as a hobby.

**Comment by TimWaterham** [comment]
Well, i still saw some posts leading to this one even if this one is about a year ago, figured id add my own experience with this, no intention for necroing a post, but as its still a thing thats present, i thought maybe it helps, maybe not. : 

![6b5d2243db60f02df4ab52e6fa8b52e4](https://cloud.githubusercontent.com/assets/21358525/20277576/696c1644-aaa1-11e6-8768-4b3538ee4a00.png)

After messing around a bit, and finding some things on the web everywhere (And wondering why it would work for the Revolution 3 Pack but not when i did it myself, i went fiddiling with the config) 

Found out that like stated on some other posts :   

B:"Use HashMap for Sound Categories - Only use if necessary"=true

Will somehow fix it, i don't know what for reason is behind it, but apparently it fixes it for the Revolution 3 Pack, and as well for my own private custom modpack.

I doubt if this is fixable by Reika.

**Comment by Builderb0y** [comment]
That's NOT the cause of the issue. The only reason it "fixes" it is because as wormzjl put it:

> Strange, it only crashes on first launch but afterwards worked fine

From a technical perspective, there are 4 things happening here:

1: AE2 rv3+ dumps the names of all items in the game to a file on game launch (though this is a config option)
2: AE caches which items do and don't exist and only re-dumps them if that cache does not match the real item list.
3: Some items in chromaticraft check the progression of the player when fetching their name. If the player does not have the required progression, the name shows up as garbled text.
4: At the time AE dumps item names, some parts of chromaticraft's research/progression code have not been initialized yet, which means that attempting to figure out if the item even needs to check player progression or not fails, which crashes the game.

Changing the hash map sound categories config option does NOT change which items get added, so AE's cache will still match up with the current item list. Therefore, it won't attempt to dump item names again, and the game doesn't crash.

**Comment by TimWaterham** [comment]
So just starting it twice would work then as well i guess, alright.. just found it to be working after i changed it...  (Thought that doesnt deny that i had to boot it twice)

Oh well.. just around trying to help ya know :P
