### ISSUE TITLE
Server crash when placing bluestone next to Computercraft Computer.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#389]
```
java.lang.ArrayIndexOutOfBoundsException: 5
    at dan200.computercraft.shared.common.BlockGeneric.canConnectRedstone(BlockGeneric.java:277)
    at Reika.ExpandedRedstone.ItemBlocks.BlockExpandedWire.isConnectedTo(BlockExpandedWire.java:672)
    at Reika.ExpandedRedstone.ItemBlocks.BlockExpandedWire.func_149709_b(BlockExpandedWire.java:481)
    at dan200.computercraft.shared.util.RedstoneUtil.getRedstoneOutput(RedstoneUtil.java:41)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:326)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.onNeighbourChange(TileComputerBase.java:193)
    at dan200.computercraft.shared.common.BlockGeneric.func_149695_a(BlockGeneric.java:172)
    at net.minecraft.world.World.func_147460_e(World.java:697)
    at net.minecraft.world.World.func_147459_d(World.java:649)
    at Reika.ExpandedRedstone.ItemBlocks.BlockExpandedWire.updateAndPropagateCurrentStrength(BlockExpandedWire.java:142)
    at Reika.ExpandedRedstone.ItemBlocks.BlockExpandedWire.func_149695_a(BlockExpandedWire.java:427)
    at net.minecraft.world.World.func_147460_e(World.java:697)
    at dan200.computercraft.shared.util.RedstoneUtil.propogateRedstoneOutput(RedstoneUtil.java:85)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateOutput(TileComputerBase.java:343)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145845_h(TileComputerBase.java:212)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

After placing: [Full Log 1](https://gist.github.com/lossycrypt/a93a2b6999e6c4d951d0)
When trying to restart server crashes again: [Full Log 2](https://gist.github.com/lossycrypt/c1025d77e3df57d02d5f)

Picture with Redstone instead:
![2015-11-10_07 00 03](https://cloud.githubusercontent.com/assets/14168854/11055568/b8ff1a82-8778-11e5-841d-5e80cfa97b77.jpg)

Fixed by MCEditing out the bluestone.
Is this on your side or his?

**Comment by ReikaKalseki** [comment]
A very similar crash was seen with OpenComputers. That time I thought it was on OC's end, since the sided logic they were using was both unseen anywhere else as well as looking very broken. Now...

**Comment by lossycrypt** [comment]
What kind of Info do you require then?

**Comment by lossycrypt** [comment]
So i tried reproducing this in Singleplayer. First placing lapis wire adjacent to a computer didn't cause a crash (the computer wasn't doing anything yet). Then i tried running a simple 1second clock on the computer which caused the above crash. After restarting MC i made a new world and tried again and there it crashed instantly when placing the lapis wire even without the computer doing anything.
