### ISSUE TITLE
Centrifugal Fluid Extractor + World Rift cause log spam

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#431]
Centrifugal Fluid Extractor + World Rift cause Log Spam

While restructuring my base i tried to connect a Centrifugal Extractor via world rift. Placing the rift directly beneath the Extractor caused (client side only) logspam several times per second:

```
[14:18:07] [Client thread/INFO] [FML]: DRAGONAPI: 
[14:18:07] [Client thread/INFO]: [CHAT] Tile Entity Centrifugal Fluid Extractor @ DIM0: 5332, 12, 4836 is throwing class java.lang.NullPointerException on update: null
[14:18:07] [Client thread/INFO]: [CHAT] [Reika.RotaryCraft.API.Power.PowerTransferHelper.checkPowerFrom(PowerTransferHelper.java:23), Reika.RotaryCraft.API.Power.PowerTransferHelper.checkPowerFrom(PowerTransferHelper.java:34), Reika.ReactorCraft.TileEntities.TileEntityHeavyPump.updateEntity(TileEntityHeavyPump.java:120), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source), java.lang.reflect.Method.invoke(Unknown Source), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[14:18:07] [Client thread/INFO]: [CHAT] 
[14:18:07] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Centrifugal Fluid Extractor @ DIM0: 5332, 12, 4836 is throwing class java.lang.NullPointerException on update: null
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.API.Power.PowerTransferHelper.checkPowerFrom(PowerTransferHelper.java:23)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.API.Power.PowerTransferHelper.checkPowerFrom(PowerTransferHelper.java:34)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ReactorCraft.TileEntities.TileEntityHeavyPump.updateEntity(TileEntityHeavyPump.java:120)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.client.main.Main.main(SourceFile:148)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:18:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

After connecting an unpowered induction motor to the other side of the rift the logspam changed (notice there's no stacktrace displayed anymore):

```
[14:19:07] [Client thread/INFO] [FML]: DRAGONAPI: 
[14:19:07] [Client thread/INFO]: [CHAT] Tile Entity Centrifugal Fluid Extractor @ DIM0: 5332, 12, 4836 is throwing class java.lang.NullPointerException on update: null
[14:19:07] [Client thread/INFO]: [CHAT] []
[14:19:07] [Client thread/INFO]: [CHAT] 
[14:19:07] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Centrifugal Fluid Extractor @ DIM0: 5332, 12, 4836 is throwing class java.lang.NullPointerException on update: null
[14:19:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
```

Breaking+replacing the whole thing now always gives the second logspam (without stacktrace). Putting a shaft between the worldrift and extractor causes no logspam. This reproduces every time on my survival server world but i haven't managed to reproduce it in my singleplayer test world yet.

![2015-12-01_14 55 28](https://cloud.githubusercontent.com/assets/14168854/11502562/d8f265c8-983b-11e5-837f-89f7bf116623.jpg)

**Comment by lossycrypt** [comment]
Small update:
Supplying power to the other end of the rift works fine and the extractor starts working. But the logspam stays.

**Comment by ReikaKalseki** [comment]
The stacktrace removal after an error prints enough is an automatic Java "feature" that can be disabled with arguments.

**Comment by ReikaKalseki** [comment]
Fixed.
