### ISSUE TITLE
Crash with GeoStrata

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#464]
http://pastebin.com/AFuhmX2K

With both mods installed, receive a crash during world generation. Removing GeoStrata removes the issue. Cross posting to both issue trackers.

Team-RTG/Realistic-Terrain-Generation#343

**Comment by TomeWyrm** [comment]
I noticed that you additionally have HarderOres by draco18s (which also requires CoG), Farseek (I assume for streams), and fastcraft. Is the bug reproduceable with only RTG, Geostrata, and dependencies?

**Comment by Haggle1996** [comment]
Here's one without RTG. 

https://gist.github.com/Haggle1996/03169fb4751a257f5e42

Looks like it's barfing in the Custom Ore Gen Revival stuff. I'll poke over there as well as harder ores.

**Comment by Haggle1996** [comment]
Narrowed it down to an interaction with Logistics Pipes.

**Comment by Haggle1996** [comment]
Narrowed this down to an interaction with Logistics Pipes. Here's a snippet.

java.lang.StackOverflowError: Exception getting block type in world
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:834)
    at net.minecraft.world.World.func_147438_o(World.java:2540)
    at logisticspipes.utils.tuples.LPPosition.getTileEntity(LPPosition.java:71)
    at logisticspipes.routing.pathfinder.changedetection.TEControl.handleBlockUpdate(TEControl.java:151)
    at logisticspipes.routing.pathfinder.changedetection.LPWorldAccess.func_147586_a(LPWorldAccess.java:22)
    at net.minecraft.world.World.func_147471_g(World.java:607)
    at Reika.GeoStrata.Blocks.BlockVent$TileEntityVent.activate(BlockVent.java:173)
    at Reika.GeoStrata.Blocks.BlockVent$TileEntityVent.access$000(BlockVent.java:163)
    at Reika.GeoStrata.Blocks.BlockVent.func_149674_a(BlockVent.java:125)
    at net.minecraft.world.WorldServer.func_147454_a(WorldServer.java:432)
    at net.minecraft.world.WorldServer.func_147464_a(WorldServer.java:409)
    at Reika.GeoStrata.Blocks.BlockVent.func_149674_a(BlockVent.java:126)
    at net.minecraft.world.WorldServer.func_147454_a(WorldServer.java:432)
    at net.minecraft.world.WorldServer.func_147464_a(WorldServer.java:409)
    at Reika.GeoStrata.Blocks.BlockVent.func_149674_a(BlockVent.java:126)
    at net.minecraft.world.WorldServer.func_147454_a(WorldServer.java:432)
    at net.minecraft.world.WorldServer.func_147464_a(WorldServer.java:409)
    at Reika.GeoStrata.Blocks.BlockVent.func_149674_a(BlockVent.java:126)

I pulled Logistics Pipes from my pack and have happily pregenerated tens of thousands of chunks without issue.

**Comment by Haggle1996** [comment]
After removing Logistics Pipes, I had pregenerated several worlds without the error, so assumed it was an issue with that mod. Just pregenerated another world and the error cropped up again. Looks similar to these issues with Custom Ore Generation:

lawremi/CustomOreGen#62
lawremi/CustomOreGen#120

Closing this issue as I no longer believe it's related to GeoStrata.

**Comment by Haggle1996** [comment]
Reopening this issue: it reoccurs in previously generated chunks. I've tried without COG, RTG, and Harder Ores. It is completely random. Sometimes it occurs multiple times within seconds, and others I can go an hour or more without a crash. For kicks and giggles, I tried setting D:"Vent Density"=0.0, and while I don't see any vents generated, I still get the crash.

Edit: I still see vents getting generated, even with Vent Density at 0.
Edit 2: Different error without COG installed. Narrowed it down to just having COG installed. Error occurs when COG attempts to place a block that affects a vent.

**Comment by Haggle1996** [comment]
Updated my development server with the latest and getting a slightly different error. http://pastebin.com/scLjpNT9

**Comment by Haggle1996** [comment]
@ReikaKalseki 

https://github.com/ReikaKalseki/GeoStrata/blob/master/Blocks/BlockVent.java#L124-L126

Should line 126 only be called if line 125 is executed? Seems 125/126 should be enclosed in braces.

**Comment by ReikaKalseki** [comment]
No, that is the random timing algorithm. If the update schedule was in the bracket, if they ever were unable to fire, they would never fire again.

**Comment by ReikaKalseki** [comment]
This crash is extremely sporadic, and I have only ever seen it a few times, never repeatably.

**Comment by wormzjl** [comment]
I think I got something similar
http://pastebin.com/MmezGdjQ

**Comment by jamesb6626** [comment]
@ReikaKalseki 
I see [here](https://github.com/ReikaKalseki/GeoStrata/blob/5efeaacbab974fe13264b73d5ed57c8dbc4fb3aa/Registry/GeoOptions.java#L125-L127) that the vent density seems to be clamped between 0.25 and 4, before being multiplied by 60 and used to give the number of placement attempts per chunk [here](https://github.com/ReikaKalseki/GeoStrata/blob/5efeaacbab974fe13264b73d5ed57c8dbc4fb3aa/World/VentGenerator.java#L29-L37), so I assume that is why vents could not be dissabled by @Haggle1996 above.
Is it possible for this to be changed, or some other option to be added that allows completely removing vent generation? This mod has many other great features, but I can't really use it because of this bug, as the crashes are very annoying.
I understand if there is a reason why this can't be/isn't done, but if it isn't too hard it would help a lot.

**Comment by ReikaKalseki** [comment]
A crash that happens once every six months is of no concern.
