### ISSUE TITLE
RotaryCraft v10a crashing with GalactiCraft on dedicated server only

### ISSUE THREAD

**Issue by spamenigma** [ReikaKalseki/Reika_Mods_Issues#484]
Tested with a couple of versions of GalactiCraft (1.7-3.0.12.406) and (1.7-3.0.12.369)

Worked OK with client test, but with dedicated server getting the following crash:

http://pastebin.com/QMUsn033

java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.getDeclaredMethod(Class.java:2128)
    at micdoodle8.mods.galacticraft.api.world.OxygenHooks.noAtmosphericCombustion(OxygenHooks.java:41)
    at Reika.RotaryCraft.Base.TileEntity.TileEntityEngine.hasAir(TileEntityEngine.java:154)
    at Reika.RotaryCraft.Base.TileEntity.TileEntityEngine.initialize(TileEntityEngine.java:250)
    at Reika.RotaryCraft.Base.TileEntity.TileEntityEngine.updateEntity(TileEntityEngine.java:340)

**Comment by ljfa-ag** [comment]
I belive this is on Galacticraft's side: The whole OxygenUtil class is dependent on GuiScreen just because one method has it as a parameter.

I reported that to Galacticraft.

**Comment by spamenigma** [comment]
Awesome, thanks! fingers crossed its a quick fix :)

**Comment by radfast** [comment]
For anyone who comes across this, this was a Galacticraft issue fixed on January 03, 2016 on Galacticraft's side.

**Comment by ReikaKalseki** [comment]
I know a good way to deal with that.... ;)
