### ISSUE TITLE
Updated to v10b and now RotaryCraft and/or ExpandedRedstone? server crash.

### ISSUE THREAD

**Issue by spamenigma** [ReikaKalseki/Reika_Mods_Issues#487]
Got my server running with 10a after temporarily disabling galacticraft/pneumaticcraft 
Updated to 10b just and getting this crash now.

http://pastebin.com/i6Dk50Gi

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Reika/RotaryCraft/API/BlockColorInterface
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: Reika/RotaryCraft/API/BlockColorInterface
    at Reika.ExpandedRedstone.ExpandedRedstone.postload(ExpandedRedstone.java:119)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by ghost** [comment]
I have the same error: http://pastebin.com/NALFkdXn

**Comment by ReikaKalseki** [comment]
Already fixed. Redownload the mod when it is approved by Curse.

**Comment by spamenigma** [comment]
Great work! thanks Reika!!

**Comment by BakermanLP** [comment]
Sorry to ask that ... is this the new correct md5sum?
86c9aee96f86e8c60db01008f33307c1  RotaryCraft 1.7.10 V10b.jar
Or does the Curse Network need that much time?

**Comment by ReikaKalseki** [comment]
I have no idea what the correct hashes are. But Curse is taking stupidly long.
