### ISSUE TITLE
GPR color configuration causes Minecraft to crash on launch.

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#494]
I tried to make a [configuration](https://gist.github.com/reteo/98991a10d2768c0c5b99) to assign colors to all the ores in my modpack for the Ground Penetrating Radar, but the game [crashes](https://gist.github.com/reteo/b205af0d8cf23de9834d) at the 6th stage of startup (after postinit).

**Comment by ReikaKalseki** [comment]
Redownload RC.

**Comment by ghost** [comment]
Re-downloaded all your mods and updated DragonAPI.  Looks like the issue is still [persisting](https://gist.github.com/reteo/ef26b5e01a0b1f8efb00).

**Comment by ReikaKalseki** [comment]
OK, I misread. Your crash is not the normal GPR crash being reported every ten minutes - it is because the line parsing is failing, because you are using namespaces and not numerical IDs:

> java.lang.NumberFormatException: For input string: "minecraft"
>     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_66]
>     at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_66]
>     at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_66]
>     at Reika.RotaryCraft.Auxiliary.BlockColorMapper.parseLine(BlockColorMapper.java:558) ~[BlockColorMapper.class:?]
>     at Reika.RotaryCraft.Auxiliary.BlockColorMapper.loadFromConfig(BlockColorMapper.java:537) ~[BlockColorMapper.class:?]
>     at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:500) ~[RotaryCraft.class:?]

**Comment by ghost** [comment]
I see.

I don't know if that will be feasible for the pack, since I can't predict whether or not players will enable or disable certain mods in the launcher to avoid certain features or just reduce the memory footprint, and if I recall correctly, the numeric IDs are always assigned on the first launch; if the mods enabled differ from the baseline, there is a good chance that the ore ID numbers will be different from the baseline.  From what I understand, that was the reason namespaces became a thing in the first place.

**Comment by ReikaKalseki** [comment]
Yes, but while namespacing support is planned, it is not yet implemented.

**Comment by ghost** [comment]
Fair enough.  Judging from some of the other issues in the tracker, this one can wait, although I am relieved to know namespaces are planned.

**Comment by pablode** [comment]
I've stumbled across the same issue.
It can be easily fixed by replacing [these 4 lines](https://github.com/ReikaKalseki/RotaryCraft/blob/b8203ebfc4727306cf300c56336050d2afa56389/Auxiliary/BlockColorMapper.java#L580-L583) with the following:
```
ItemStack itemStack = ReikaItemHelper.lookupItem(key);
Item item = itemStack.getItem();
Block block = Block.getBlockFromItem(item);
```

**Comment by ReikaKalseki** [comment]
At the time this issue was originally reported, and that code was written, the `lookupItem` function did not exist, nor did the internal systems which enable it to work.

**Comment by pablode** [comment]
This might be true, but the issue still exists.
Would love to see this fixed! The solution is already there.
