### ISSUE TITLE
Right-clicking on an empty Item Casting Stand with an empty hand crashes client

### ISSUE THREAD

**Issue by pjolin** [ReikaKalseki/Reika_Mods_Issues#513]
This is new to v10 I believe. 

Clicking on an empty Item Casting Stand, while holding nothing, crashes. It happens to me when I double-click on a stand that has items to pick them up (first click pops it, second crashes). 

Happens systematically (did it 5 times in a row between 2 people), on multiple altars, and removing / replacing the Item Casting Stands did not help. 

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/26/15 8:07 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityItemStand.onRightClickWith(TileEntityItemStand.java:145)
    at Reika.ChromatiCraft.Base.BlockChromaTile.func_149727_a(BlockChromaTile.java:230)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TomeWyrm** [comment]
Please pastebin the full crash log.

**Comment by pjolin** [comment]
http://pastebin.com/9wRXftLm

**Comment by ReikaKalseki** [comment]
Fixed.
