### ISSUE TITLE
Chromaticraft Dimension: harvesting a dimensional core crashes server

### ISSUE THREAD

**Issue by pjolin** [ReikaKalseki/Reika_Mods_Issues#527]
Seems to be an error that happens when granting player progression for completing one of the dimension dungeons - had that crash twice, completing two different dungeons (the 3d maze and the keys puzzle one). 

java.lang.NoSuchMethodError: Reika.ChromatiCraft.Registry.ChromaResearchManager$ProgressElement.getTitle()Ljava/lang/String;
    at Reika.ChromatiCraft.Auxiliary.ChromaAux.notifyServerPlayersExcept(ChromaAux.java:250)
    at Reika.ChromatiCraft.Registry.ChromaResearchManager.notifyPlayerOfProgression(ChromaResearchManager.java:354)
    at Reika.ChromatiCraft.Auxiliary.ProgressionManager.markPlayerCompletedStructureColor(ProgressionManager.java:745)
    at Reika.ChromatiCraft.TileEntity.TileEntityDimensionCore.breakByPlayer(TileEntityDimensionCore.java:444)
    at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.trackBrokenBlocks(DragonAPIEventWatcher.java:29)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_188_DragonAPIEventWatcher_trackBrokenBlocks_BreakEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259)
    at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Complete error log: 

http://pastebin.com/Y2JiHjrR

**Comment by zemerick** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/520
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/526
