### ISSUE TITLE
ChromatiCraft v10d Crash

### ISSUE THREAD

**Issue by SonarBeserk** [ReikaKalseki/Reika_Mods_Issues#528]
I get the following error when looking at some things. For example I looked at a crystal and disconnected from the server.

These crashes seem to only be serverside and not all crash the game.

```
[23:10:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: Reika.ChromatiCraft.Registry.ChromaResearchManager$ProgressElement.getTitle()Ljava/lang/String;
    at Reika.ChromatiCraft.Auxiliary.ChromaAux.notifyServerPlayersExcept(ChromaAux.java:250) ~[ChromaAux.class:?]
    at Reika.ChromatiCraft.Registry.ChromaResearchManager.notifyPlayerOfProgression(ChromaResearchManager.java:354) ~[ChromaResearchManager.class:?]
    at Reika.ChromatiCraft.Auxiliary.ProgressionManager.setPlayerStage(ProgressionManager.java:477) ~[ProgressionManager.class:?]
    at Reika.ChromatiCraft.Auxiliary.ProgressionManager.setPlayerStage(ProgressionManager.java:441) ~[ProgressionManager.class:?]
    at Reika.ChromatiCraft.Auxiliary.ProgressionManager.stepPlayerTo(ProgressionManager.java:374) ~[ProgressionManager.class:?]
    at Reika.ChromatiCraft.Auxiliary.ProgressionManager.access$000(ProgressionManager.java:62) ~[ProgressionManager.class:?]
    at Reika.ChromatiCraft.Auxiliary.ProgressionManager$ProgressStage.stepPlayerTo(ProgressionManager.java:144) ~[ProgressionManager$ProgressStage.class:?]
    at Reika.ChromatiCraft.ChromaticEventManager.triggerBossProgress(ChromaticEventManager.java:868) ~[ChromaticEventManager.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_190_ChromaticEventManager_triggerBossProgress_LivingDeathEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891) ~[sv.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) ~[sv.class:?]
    at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54) ~[yg.class:?]
    at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:222) ~[yq.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232) ~[yz.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821) ~[nh.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by zemerick** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/520
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/526
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/527
