### ISSUE TITLE
AutoCrafting Unit completely disables ME networks until server restart

### ISSUE THREAD

**Issue by pjolin** [ReikaKalseki/Reika_Mods_Issues#533]
Reproduced this a few times. 

I placed AutoCrafting unit down, connected to ME directly (smart cable hooked to top, device using channel). 

Changed its mode to Sustain. 

Added 12 patterns to it (shafts, gears, etc.) and configured the quantities to sustain. 

Connected a DC engine to it, turned it on - ME network stopped working instantly: Items were still showing in terminal / wireless terminal, but I couldn't take items in / out of the network, export busses stopped exporting, etc. 

In fact, ALL ME networks on the server got locked up in the same way - they all stopped working at once. 

Removing the AutoCrafting Unit, removing the ME controllers and installing them again (i.e. making a new network), both didn't restore ME functionnality. 

ME Networks only started working again after restarting the server (without having the AutoCrafting Unit connected). 

The following is printed at the server console the instant I give power to the AutoCrafting Unit: 

[03:42:22] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity AutoCrafting Unit @ DIM6: -4992, 75, -304 [SERVER] is throwing class java.lang.ClassCastException on update: Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader$ActionSource cannot be cast to appeng.api.networking.security.MachineSource
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException: Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader$ActionSource cannot be cast to appeng.api.networking.security.MachineSource
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.me.storage.NetworkInventoryHandler.testPermssion(NetworkInventoryHandler.java:155)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.me.storage.NetworkInventoryHandler.extractItems(NetworkInventoryHandler.java:210)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.api.storage.MEMonitorHandler.extractItems(MEMonitorHandler.java:149)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader.removeItem(MESystemReader.java:127)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.ModInteract.DeepInteract.MESystemReader.getItemCount(MESystemReader.java:167)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.craftMissingItems(TileEntityAutoCrafter.java:188)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.access$500(TileEntityAutoCrafter.java:57)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter$CraftingMode.tick(TileEntityAutoCrafter.java:154)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter$CraftingMode.access$700(TileEntityAutoCrafter.java:118)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.RotaryCraft.TileEntities.Processing.TileEntityAutoCrafter.updateEntity(TileEntityAutoCrafter.java:244)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[03:42:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[03:42:22] [Server thread/INFO] [FML]: DRAGONAPI:
[03:42:23] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@1fc595c6 to craft 1024xitem.item.placer@17 returned a null link!
[03:42:23] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@457ff73c to craft 64xitem.item.shaftcraft@3 returned a null link!
[03:42:23] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@31109734 to craft 4096xitem.item.shaftcraft@2 returned a null link!
[03:42:23] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@1a83c633 to craft 4096xitem.item.shaftcraft@0 returned a null link!
[03:42:23] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@295b1b00 to craft 1024xitem.item.borecraft@10 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@1327cf00 to craft 128xitem.item.enginecraft@1 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@263b4367 to craft 1024xitem.item.misccraft@5 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@220dabcd to craft 128xitem.item.enginecraft@0 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@17609a to craft 64xitem.item.enginecraft@14 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@9340725 to craft 64xitem.item.enginecraft@8 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@375591dd to craft 64xitem.item.misccraft@8 returned a null link!
[03:42:24] [Server thread/ERROR] [FML]: DRAGONAPI ERROR: appeng.crafting.CraftingJob@7d386997 to craft 64xitem.item.enginecraft@2 returned a null link!

The server itself keeps working - it's not a full blown crash, but it does break ME networks completely. 

This is with v10d, AE2 rv2 stable, forge 1558.

**Comment by ghost** [comment]
I experienced this too with the Casting Delegate from ChC. I think it has something to do with the security station. Try removing it and doing it again. This made the ME system not die per say when it was used as the cable got moved so it couldn't connect or something.

**Comment by pjolin** [comment]
As a follow up, I took a wild guess and hit the A.C.U. with a biometric card. Client got disconnected, server had this in its output: 

[09:00:34] [Server thread/WARN]: Failed to handle packet for /10.10.0.10:64851
java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[09:00:34] [Server thread/INFO]: pjolin lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[09:00:34] [Server thread/INFO]: pjolin left the game

**Comment by ReikaKalseki** [comment]
Unrelated and vanilla code.

**Comment by Builderb0y** [comment]
ActionSource in MESystemReader should extend MachineSource or PlayerSource instead of BaseActionSource. Most declarations of machine source in vanilla AE simply provide "this" for their IActionHost (they all extend something that implements IActionHost), but PlayerSource can, (according to [a single class somewhere in AE](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/items/tools/powered/ToolMassCannon.java#L153)), take null for its IActionHost argument.

Additionally, IActionHost and all IGrid-related classes are in the API, so they should be safe to extend.

**Comment by ReikaKalseki** [comment]
Done.
