### ISSUE TITLE
Can't craft Chromaticraft items using Casting Table

### ISSUE THREAD

**Issue by theron61** [ReikaKalseki/Reika_Mods_Issues#538]
With v10d - this is logged in the chat when I try to use the casting table:

[19:14:58] [Client thread/ERROR] [FML]: CHROMATICRAFT ERROR: Tried to give progress 'CASTING' to null player???
[19:14:58] [Client thread/INFO]: [CHAT] Tile Entity Casting Table @ DIM0: -198, 64, 370 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[19:14:58] [Client thread/INFO]: [CHAT] []
[19:14:58] [Client thread/INFO]: [CHAT] 
[19:14:58] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Casting Table @ DIM0: -198, 64, 370 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[19:14:58] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[19:14:58] [Client thread/INFO] [FML]: DRAGONAPI:

**Comment by theron61** [comment]
I added the CASTING research with the chromaresearch command and now get the following:

[19:38:51] [Client thread/INFO]: [CHAT] 
[19:38:51] [Client thread/ERROR] [FML]: DRAGONAPI ERROR: Tile Entity Casting Table @ DIM0: -198, 64, 370 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.DragonAPI.Libraries.ReikaPlayerAPI.getDeathPersistentNBT(ReikaPlayerAPI.java:270)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.Registry.ChromaResearchManager.getNBT(ChromaResearchManager.java:340)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.Registry.ChromaResearchManager.getNBTRecipes(ChromaResearchManager.java:385)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.Registry.ChromaResearchManager.getPlayerRecipes(ChromaResearchManager.java:375)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.Registry.ChromaResearchManager.playerHasUsedRecipe(ChromaResearchManager.java:360)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.Registry.ChromaResearchManager.givePlayerRecipe(ChromaResearchManager.java:364)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.onCrafted(CastingRecipe.java:193)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.craft(TileEntityCastingTable.java:578)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:230)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:140)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[19:38:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.EntryPoint.main(EntryPoint.java:54)
[19:38:51] [Client thread/INFO] [FML]: DRAGONAPI:

**Comment by theron61** [comment]
I didn't realize that some sneaky sob put a chest by my casting table taking my crafted elements.  I was figuring this warning/error and the lack of an output item were related.

Retribution has been exacted.  Thanks and sorry for the false description.

**Comment by Turmfalke2** [comment]
I can reproduce it this 100% of the time even when starting in a new world.
installed mods:
Chisel2-2.5.1.44.jar
DragonAPI 1.7.10 V10d.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
ReactorCraft 1.7.10 V10d.jar
StorageDrawers-1.7.10-1.7.5.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
ChromatiCraft 1.7.10 V10d.jar
ElectriCraft 1.7.10 V10b.jar
InventoryTweaks-1.59-dev-152.jar
VoidMonster 1.7.10 V10a.jar
fastcraft-1.21.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
ExpandedRedstone 1.7.10 V10b.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
RotaryCraft 1.7.10 V10d.jar
Waila-1.5.10_1.7.10.jar

and forge-1.7.10-10.13.3.1403-1.7.10-universal.jar with java 8 (with the required GC setting)

**Comment by Turmfalke2** [comment]
I don't get it, after staring at the code for well over an hour I have no still no idea why craftingPlayer should be null.
Currently my theories are a) java8 broke the short circuit evaluation in trigger() b) JIT did stupid stuff trying to optimize c) a rogue thread is messing with it d) getPlacer() from DragonAPI somehow can return null if called twice in a row.

It is just so confusing, craftingPlayer gets set in triggerCrafting - since I can craft with the casting table it is safe to assume that the method really gets called. In trigger() it is checked that the placer is not null. In theory the placer could be a fakeplayer, but even in that case it wouldn't be null.

**Comment by ReikaKalseki** [comment]
Now you know my problem.

**Comment by Turmfalke2** [comment]
Just to rule out other mods doing stupid things, I can reproduce it with just forge,dragonAPI and chromaticraft.

e: updated to jdk 8u66, still the same

**Comment by Turmfalke2** [comment]
Ok still trying to figure this one out. I have tried creating a heap dump, but apparently jhat runs out of memory trying to read the 1.5G dump.
I found that dragonapi has a config option for showing a tile entity's nbt data when holding tab. With that I could confirm that placer for my empty casting table is indeed "Turmfalke_".  I have tried to do that same with a casting table that has currently a valid recipe, but when I did so minecraft froze.

The next idea was to get both dragonapi and chromticraft to run in a gradle environment, but already dragonapi alone is making this things difficult.
During startup it claims to have successfully patched world.World with ICECANCEL and MOBTARGETEVENT, but directly after that it crashs because world.World is malformed. Am I being stupid? I don't understand enough ASM to figure out what is going wrong there, so any help from you would be appreciated.
log:  http://paste2.org/gk10XOpz

**Comment by ReikaKalseki** [comment]
>  have tried to do that same with a casting table that has currently a valid recipe, but when I did so minecraft froze.

Tables have a **huge** amount of NBT data, and rendering that is likely too expensive.

> During startup it claims to have successfully patched world.World with ICECANCEL and MOBTARGETEVENT, but directly after that it crashs because world.World is malformed. Am I being stupid? I don't understand enough ASM to figure out what is going wrong there, so any help from you would be appreciated.

Are you using KCauldron?

**Comment by Turmfalke2** [comment]
No, just normal forge gradle with the eclipse workspace. I usually don't use eclipse, but for minecraft modding it is seems be the preferred ide.

**Comment by ReikaKalseki** [comment]
I have never seen that error before. It might be an ASM conflict, but with what?

**Comment by Turmfalke2** [comment]
@ReikaKalseki I don't think it is a conflict, I only have NEI there and it even happens without. I think it is something about detecting the deobfuscated environment and not adopting accordingly? I noticed your code is quite environment sensitive and given that isReikasComputer() exists, maybe it never happens on your computer?

**Comment by ReikaKalseki** [comment]
`isReikasComputer()` only controls debugging features. Also, all the ASM is developed in the dev environment, so it is far more likely to fail in the _compiled_ game than outside it.

**Comment by Turmfalke2** [comment]
Something that I should have thought about earlier, given that it worked fine in the past I think commit Update 441 - v10 / 5768b35 to TileEntityCastingTable broke it. I still don't see quite why, but could we try reverting that change? Except for ProgressStage.CASTING.stepPlayerTo(craftingPlayer); I don't think the changes should do anything to the intended behaviour. 

E:
I made  a mistake earlier, I assumed crafting was always triggered by calling trigger(), but triggerCrafting is public and called from the ItemManipulator. So everything I said earlier about checking that it isn't null does not apply.

**Comment by Turmfalke2** [comment]
Ok, turns out it changes nothing, for activeRecipe.canRunRecipe and isOwnedByPlayer is apparently not null. After that in my tests craftingTick gets set to 20 and craftingPlayer gets set to ep and 20 calls of updateentity and onCraftingTick later craft gets called and for ProgressStage.CASTING.stepPlayerTo(craftingPlayer) craftingPlayer is suddenly null.  
Is it save to assume that updateentity is called from the same thread as triggerCrafting? And that updateentity isn't getting called 20 times between the duration being set and craftingPlayer getting set?

E: I understand that the changes from 5768b35 are to ensure that crafting gets tracked the for the player who triggered it and not the player who placed the casting table, but something isn't quite working with that.

**Comment by ReikaKalseki** [comment]
> Is it save to assume that updateentity is called from the same thread as triggerCrafting?

Yes.

**Comment by Keyarose** [comment]
A related side note to this issue, due to it not finding the player NBT when crafting using a casting temple the castingprog is never set for temple.  This makes it impossible to progress to multicraft.

**Comment by ReikaKalseki** [comment]
It does not fail to find player NBT - it fails to find the player itself.

**Comment by Keyarose** [comment]
Well yes same result, I crafted a number of different casting temple recipes without it setting the NBT flag.

**Comment by Aivech** [comment]
I am getting this same thing in a test world after using the commands to give myself all research and progression, namely, on completion of a recipe in a casting table, I get a "java.lang.NullPointerException" along with some other text, a name that identifies it as a casting table, and coordinates. It happens on completion of a valid recipie, e.g. when you are able to take the result item out of the slot.

**Comment by webbster64** [comment]
got the same problem, so looks like i have to remove all of ReikaKalseki's mods considering im going choose thermos over DragonAPI RotaryCraft ReactorCraft ElectriCraft GeoStrata, i want to give my players a stable and fun server running at 20-19tps over a server with 5 extra mods thats running at 5tps
