### ISSUE TITLE
Custom Extracts for Metallurgy ore does not process

### ISSUE THREAD

**Issue by wedge9s** [ReikaKalseki/Reika_Mods_Issues#561]
I am sure that I am using the CustomExtracts file correctly but I cannot get any Metallurgy ores processed when using the following CustomExtracts config-
Prometheum, SCARCE, INGOT, ingotPrometheum, 1, 0xffffff, 0x73cc12, null, orePrometheum

I originally had AOBD installed but encountered the same issue (I assumed it was an issue with AOBD), so I have disabled it and I still cannot put the Prometheum ore in the Extractor using the CustomExtracts recipe. I was under the impression that using a CustomExtract file I could in theory use the Extractor for any ore dictionary registered ore, I am using RotaryCraft 1.7.10 V9b and DragonAPI 1.7.10 V9b.

The ore just fails to load into the Extractor.

**Comment by ReikaKalseki** [comment]
Check your logs for relevant errors.

**Comment by wedge9s** [comment]
OK, so looking at the log there are the following lines related to Prometheum:

```
[20:57:11] [Client thread/INFO] [FML]: ROTARYCRAFT: Loading custom extract config.
[20:57:11] [Client thread/INFO] [FML]: ROTARYCRAFT: Added extract entry Prometheum to ingotPrometheum with rarity SCARCE (1 ores found from [orePrometheum])
...
Jan 12, 2016 8:57:16 PM exter.fodc.registry.OreNameRegistry RegisterOreName
INFO: registered ore name: dustPrometheum
Jan 12, 2016 8:57:16 PM exter.fodc.registry.OreNameRegistry RegisterOreName
INFO: registered ore name: ingotPrometheum
Jan 12, 2016 8:57:16 PM exter.fodc.registry.OreNameRegistry RegisterOreName
INFO: registered ore name: orePrometheum
Jan 12, 2016 8:57:16 PM exter.fodc.registry.OreNameRegistry RegisterOreName
INFO: registered ore name: blockPrometheum
...
[20:56:35] [Client thread/INFO] [FML]: DRAGONAPI: Logged OreDict registration of 1xitem.metal.item.fantasy.dust@0 as 'dustPrometheum'.
[20:56:35] [Client thread/WARN] [FML]: ****************************************
[20:56:35] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name ingotPrometheum has occurred. It adds an item (type: class com.teammetallurgy.metallurgy.metals.MetalItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Metallurgy 4 report it to them!
[20:56:35] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[20:56:35] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[20:56:35] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.metals.MetalSet.load(MetalSet.java:380)
[20:56:35] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.BlockList.injectMetalSet(BlockList.java:201)
[20:56:35] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.BlockList.initMetalSets(BlockList.java:163)
[20:56:35] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.BlockList.init(BlockList.java:91)...
[20:56:35] [Client thread/WARN] [FML]: ****************************************
[20:56:35] [Client thread/INFO] [FML]: DRAGONAPI: Logged OreDict registration of 1xitem.metal.item.Prometheum.ingot@0 as 'ingotPrometheum'.
[20:56:35] [Client thread/INFO] [FML]: DRAGONAPI: Logged OreDict registration of 1xtile.metal.block.fantasy.ore@0 as 'orePrometheum'.
[20:56:35] [Client thread/INFO] [FML]: DRAGONAPI: Logged OreDict registration of 1xtile.metal.block.fantasy.block@0 as 'blockPrometheum'.
[20:56:35] [Client thread/INFO] [FML]: DRAGONAPI: Logged OreDict registration of 1xtile.metal.block.fantasy.brick@0 as 'brickPrometheum'.
```

Is this issue caused by the registration of the orePrometheum or ingotPrometheum from Metallurgy 4?

**Comment by ReikaKalseki** [comment]
That big error is a Forge one, not mine. It appears that Metallurgy is seriously broken, because this config is not even loaded until postInit.

**Comment by wedge9s** [comment]
That explains why the ore wont even load in the Extractor, I take it the reason why the Ore works in the Grinder (with AOBD) is because AOBD is doing something after the config is loaded to add the recipe to the Grinder?

Here's an odd question, could I code a tiny mod which registers the initial OreDict entries for Metallurgy ores at the correct time, I don't fancy recoding all of Metallurgy to fix this issue. From what you are saying if the OreDict entries are registered properly then in theory both AOBD and using a CustomExtract should work correctly.

**Comment by ReikaKalseki** [comment]
Such a thing is possible, but it would need large amounts of reflection or possibly even ASM.
