### ISSUE TITLE
Updating screen events  java.lang.ExceptionInInitializerError (Version 10d)

### ISSUE THREAD

**Issue by darkman1984** [ReikaKalseki/Reika_Mods_Issues#564]
The new Version of Reactorcraft and Rotarycraft got the following issue:

Reading the Handbook or clicking on the Questionmark on a machine will crash minecraft totally

Description: Updating screen events

java.lang.ExceptionInInitializerError
    at Reika.RotaryCraft.Registry.HandbookRegistry.getEntry(HandbookRegistry.java:632)
    at Reika.RotaryCraft.GUIs.GuiHandbook.getEntry(GuiHandbook.java:666)
    at Reika.RotaryCraft.GUIs.GuiHandbook.func_73866_w_(GuiHandbook.java:136)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
    at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:472)
    at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:303)
    at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:94)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
    at Reika.RotaryCraft.Base.GuiMachine.func_146284_a(GuiMachine.java:86)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(TimSort.java:773)
    at java.util.TimSort.mergeAt(TimSort.java:510)
    at java.util.TimSort.mergeCollapse(TimSort.java:435)
    at java.util.TimSort.sort(TimSort.java:241)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1454)
    at java.util.Collections.sort(Collections.java:175)
    at Reika.DragonAPI.Libraries.Registry.ReikaItemHelper.sortItems(ReikaItemHelper.java:403)
    at Reika.DragonAPI.Instantiable.Data.Maps.ItemHashMap.updateKeysets(ItemHashMap.java:56)
    at Reika.DragonAPI.Instantiable.Data.Maps.ItemHashMap.keySet(ItemHashMap.java:139)
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.MulchMaterials.getAllValidPlants(MulchMaterials.java:97)
    at Reika.RotaryCraft.Auxiliary.HandbookAuxData.addPlants(HandbookAuxData.java:214)
    at Reika.RotaryCraft.Auxiliary.HandbookAuxData.load(HandbookAuxData.java:102)
    at Reika.RotaryCraft.Auxiliary.HandbookAuxData.<clinit>(HandbookAuxData.java:94)

**Comment by ReikaKalseki** [comment]
#550, #544, #540, #534, #522, #515, #488
