### ISSUE TITLE
DragonAPI & Reactorcraft NullPointerException

### ISSUE THREAD

**Issue by darkman1984** [ReikaKalseki/Reika_Mods_Issues#565]
After placing the Central Control Unit i got the following issue:

[03:03:21] [Client thread/INFO]: [CHAT] Tile Entity Central Control @ DIM0: 1124, 29, 757 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[03:03:21] [Client thread/INFO]: [CHAT] [Reika.ReactorCraft.Auxiliary.ReactorControlLayout.SCRAM(ReactorControlLayout.java:158), Reika.ReactorCraft.TileEntities.Fission.TileEntityCPU.SCRAM(TileEntityCPU.java:113), Reika.ReactorCraft.TileEntities.Fission.TileEntityCPU.updateEntity(TileEntityCPU.java:92), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:483), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[03:03:21] [Client thread/INFO]: [CHAT] 
[03:03:21] [Client thread/ERROR](DRAGONAPI:): DRAGONAPI ERROR: Tile Entity Central Control @ DIM0: 1124, 29, 757 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ReactorCraft.Auxiliary.ReactorControlLayout.SCRAM(ReactorControlLayout.java:158)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ReactorCraft.TileEntities.Fission.TileEntityCPU.SCRAM(TileEntityCPU.java:113)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ReactorCraft.TileEntities.Fission.TileEntityCPU.updateEntity(TileEntityCPU.java:92)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:483)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[03:03:21] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

By the way:
The Steam Boiler has a Texture Failure (Top and Bottom Texture is missing (Purple Black Texture). The sides of the boiler are fully normal

**Comment by darkman1984** [comment]
If the Central Control Unit got energy the spam stops
Same if you click everytime on retract or insert rods

**Comment by ReikaKalseki** [comment]
Fixed.
