### ISSUE TITLE
Crash on Guide Information

### ISSUE THREAD

**Issue by agowa** [ReikaKalseki/Reika_Mods_Issues#588]
Hello I have a strange problem, when I klick the "?" in any RotaryCraft Machine or open the Book my game crashes. I tried to find the conflict but it seams to be something more complicated then only two mods. I wasn't able to find the conflicting ones (by disabling and carefully re-enabling).

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 18.01.16 21:33
Description: Updating screen events

java.lang.ExceptionInInitializerError
    at Reika.RotaryCraft.Registry.HandbookRegistry.getEntry(HandbookRegistry.java:632)
    at Reika.RotaryCraft.GUIs.GuiHandbook.getEntry(GuiHandbook.java:666)
    at Reika.RotaryCraft.GUIs.GuiHandbook.func_73866_w_(GuiHandbook.java:136)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)

More: http://pastebin.com/gSpsHGYF

**Comment by Builderb0y** [comment]
#587, #582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488

Also, don't paste the entire log here, use a paste service instead.
