### ISSUE TITLE
Crash when requesting NEI to show gravel recipes (Rotarycraft grinder)

### ISSUE THREAD

**Issue by th4umiel** [ReikaKalseki/Reika_Mods_Issues#626]
Hi, here's the crash report:
(If there's already a solution I apologize)

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 17/02/16 8.59
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.getSources(RecipesGrinder.java:188)
    at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:163)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
    at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:146)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.mouseClicked(RecipeItemInputHandler.java:36)
    at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
    at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:102)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.getSources(RecipesGrinder.java:188)
    at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:163)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
    at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:146)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.mouseClicked(RecipeItemInputHandler.java:36)
    at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:329)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
    at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:102)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: codechicken.nei.recipe.GuiUsageRecipe

**Comment by ReikaKalseki** [comment]
Something invalid was registered as stone or cobblestone. Try removing mods.

**Comment by th4umiel** [comment]
First of all, thank you for your quick response. 
I've found the problem, caused by the Avaritia mod. In my ignorance, I can't understand precisely the problem, so I will report it quoting you, if you don't mind.
Thanks again! :)

**Comment by th4umiel** [comment]
Sorry to re-open it, but it crashed again when i requested the recipe for clay and for sludge bucket (MFR). For any further clarification, if you want, I will send you the new crash reports.

**Comment by ReikaKalseki** [comment]
The exact same crash?

**Comment by th4umiel** [comment]
The first crash, no. The second, yes.
In the first it says java.lang.IllegalArgumentException: Comparison method violates its general contract!
In the second again is java.lang.NullPointerException: Updating screen events

edit: I was thinking... maybe do an update of forge?

**Comment by ReikaKalseki** [comment]
No, that issue is fixed in v11 and a duplicate of over 30 others.

**Comment by th4umiel** [comment]
Mmm... Obviously I can't test every recipe in NEI to see if it makes the game crash, I will try to overhaul my mod list in order to avoid strange interactions. I think it's the only thing to do and hope for the best, unless you have any other idea in mind.

**Comment by ReikaKalseki** [comment]
There is nothing you can do to fix that crash.

**Comment by th4umiel** [comment]
okok, thanks anyway
