### ISSUE TITLE
Chromaticraft casting -- null errors??

### ISSUE THREAD

**Issue by Vornad** [ReikaKalseki/Reika_Mods_Issues#629]
Heya,

I sure hope one of you brilliant guys can figure out what's going on here. I'm really intrigued by Chromaticraft and would like to continue playing it to the end, but some issues are preventing my progress.

I started a single player world with a popular modpack that included all of Reika's mods. I encountered the first hiccup with Chromaticraft when I used the basic casting table. It gave a chat warning of:

[11:47:55] [Client thread/INFO]: [CHAT] Tile Entity Casting Table @ DIM0: 169, 73, 54 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[11:47:55] [Client thread/INFO]: [CHAT] [Reika.DragonAPI.Libraries.ReikaPlayerAPI.getDeathPersistentNBT(ReikaPlayerAPI.java:270), Reika.ChromatiCraft.Registry.ChromaResearchManager.getNBT(ChromaResearchManager.java:340), Reika.ChromatiCraft.Registry.ChromaResearchManager.getNBTRecipes(ChromaResearchManager.java:385), Reika.ChromatiCraft.Registry.ChromaResearchManager.getPlayerRecipes(ChromaResearchManager.java:375), Reika.ChromatiCraft.Registry.ChromaResearchManager.playerHasUsedRecipe(ChromaResearchManager.java:360), Reika.ChromatiCraft.Registry.ChromaResearchManager.givePlayerRecipe(ChromaResearchManager.java:364), Reika.ChromatiCraft.Auxiliary.RecipeManagers.CastingRecipe.onCrafted(CastingRecipe.java:193), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.craft(TileEntityCastingTable.java:578), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:230), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:140), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source), java.lang.reflect.Method.invoke(Unknown Source), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[11:47:55] [Client thread/INFO]: [CHAT] 

But, I received my crystalline stone as output, so it just seemed like a weird spam. I ignored it and continued with the game.

Later, when I upgraded tiers and placed items into casting stands, I got this message:

[11:36:11] [Client thread/INFO]: [CHAT] Tile Entity Item Casting Stand @ DIM0: 167, 73, 52 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[11:36:11] [Client thread/INFO]: [CHAT] [net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217), net.minecraft.item.crafting.FurnaceRecipes.func_151397_a(FurnaceRecipes.java:100), net.minecraft.item.crafting.FurnaceRecipes.func_151395_a(FurnaceRecipes.java:93), Reika.ChromatiCraft.Registry.ItemElementCalculator.getFromVanillaSmelting(ItemElementCalculator.java:136), Reika.ChromatiCraft.Registry.ItemElementCalculator.calculateTag(ItemElementCalculator.java:414), Reika.ChromatiCraft.Registry.ItemElementCalculator.getValueForItem(ItemElementCalculator.java:112), Reika.ChromatiCraft.Registry.ItemElementCalculator.getIRecipeTotal(ItemElementCalculator.java:460), Reika.ChromatiCraft.Registry.ItemElementCalculator.getFromVanillaCrafting(ItemElementCalculator.java:127), Reika.ChromatiCraft.Registry.ItemElementCalculator.calculateTag(ItemElementCalculator.java:413), Reika.ChromatiCraft.Registry.ItemElementCalculator.getValueForItem(ItemElementCalculator.java:112), Reika.ChromatiCraft.Registry.ItemElementCalculator.getTagForItemOrList(ItemElementCalculator.java:495), Reika.ChromatiCraft.Registry.ItemElementCalculator.getIRecipeTotal(ItemElementCalculator.java:468), Reika.ChromatiCraft.Registry.ItemElementCalculator.getFromVanillaCrafting(ItemElementCalculator.java:127), Reika.ChromatiCraft.Registry.ItemElementCalculator.calculateTag(ItemElementCalculator.java:413), Reika.ChromatiCraft.Registry.ItemElementCalculator.getValueForItem(ItemElementCalculator.java:112), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityItemStand.spawnItemParticles(TileEntityItemStand.java:79), Reika.ChromatiCraft.TileEntity.Recipe.TileEntityItemStand.updateEntity(TileEntityItemStand.java:64), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source), java.lang.reflect.Method.invoke(Unknown Source), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[11:36:11] [Client thread/INFO]: [CHAT] 

But once again, I received the completed recipe items, so I proceeded.

When I finally upgraded to the top-tier, I got the lumen network set up and decided to craft potion crystals as my first recipe. I got to watch a pretty light show for about 90 seconds before crashing to the 'shutting down internal server' screen. The log displays this message:

[11:51:01] [Server thread/INFO]: Saving and pausing game...
[11:51:01] [Server thread/INFO]: Saving chunks for level 'Starter'/Overworld [...]
[11:57:21] [Server thread/INFO]: Stopping server
[11:57:21] [Server thread/INFO]: Saving players
[11:57:21] [Server thread/INFO]: Saving worlds [...]
[11:57:26] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.world.World.func_72939_s(World.java:1954) ~[ahb.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_66]
    at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_66]
    at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source) ~[?:1.8.0_66]
    at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.getTransmittersTo(CrystalNetworker.java:452) ~[CrystalNetworker.class:?]
    at Reika.ChromatiCraft.Magic.Network.PylonFinder.findFrom(PylonFinder.java:259) ~[PylonFinder.class:?]
    at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:115) ~[PylonFinder.class:?]
    at Reika.ChromatiCraft.Magic.Network.PylonFinder.findPylon(PylonFinder.java:105) ~[PylonFinder.class:?]
    at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:221) ~[CrystalNetworker.class:?]
    at Reika.ChromatiCraft.Magic.Network.CrystalNetworker.makeRequest(CrystalNetworker.java:208) ~[CrystalNetworker.class:?]
    at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:78) ~[CrystalReceiverBase.class:?]
    at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergy(CrystalReceiverBase.java:86) ~[CrystalReceiverBase.class:?]
    at Reika.ChromatiCraft.Base.TileEntity.CrystalReceiverBase.requestEnergyDifference(CrystalReceiverBase.java:93) ~[CrystalReceiverBase.class:?]
    at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.onCraftingTick(TileEntityCastingTable.java:223) ~[TileEntityCastingTable.class:?]
    at Reika.ChromatiCraft.TileEntity.Recipe.TileEntityCastingTable.updateEntity(TileEntityCastingTable.java:140) ~[TileEntityCastingTable.class:?]
    at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:454) ~[TileEntityBase.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
    ... 10 more

I'm playing with one of the major mod-packs through the AT Launcher, and guessed that it could be any one of the 157 loaded mods conflicting. The best course of action would be to eliminate all those variables, so I installed a clean version of the plain, vanilla Minecraft, then only installed Forge10.13.4.1614, DragonAPI v10d and Chromaticraft v10d.

After starting a new game and getting initial progression to the casting table, I received the same first chat error message when I made the crystalline stone.

Well, the only other variable I could think of was Java, so I changed from 
Java 8.0_66 (arguments -XX:+UseG1GC -Xmx6G -XX:-UseAdaptiveSizePolicy -Xmn3G) 
to Java 7 (arguments -Xmx4G -XX:-UseAdaptiveSizePolicy -Xmn1G)

Inside the jittery environment, I made some more crystalline stone, only to receive the same chat message.

Which could only mean that its something in my system. I'm running a desktop with Win7 Ultimate (Version 6.1.7601 Service Pack 1 Build 7601), Z97X-Gaming motherboard in x64 mode with 16G ram and a 4-core I5 cpu @ 3.00GHz.

I'm hoping that i'm missing something obvious and there's a fix for this problem.

Thank you for your attention.

**Comment by TomeWyrm** [comment]
The first two are harmless (if spammy) errors. We're still getting them occasionally on the Dev Server. Or at least I heard about the first one again a day or two ago from someone that hadn't done chromaticraft yet.

The third one? The code that manages Pylons got rewritten in this current dev cycle for a reason.
