### ISSUE TITLE
Mystcraft fluid integration needs review

### ISSUE THREAD

**Issue by keybounce** [ReikaKalseki/Reika_Mods_Issues#63]
This is with 0.11.7, and may be another example of updated API.

The good news: Xcw is now using a versioned API, so you won't have to worry about a changing API moving forward, unless an incompatible change shows up.

```
[20:55:32] [Client thread/TRACE] [FML/]: Attempting to deliver 6 IMC messages to mod Mystcraft
[20:55:32] [Client thread/TRACE] [Mystcraft/Mystcraft]: Sending event IMCEvent to mod Mystcraft
[20:55:32] [Client thread/ERROR] [Mystcraft/Mystcraft]: IMC message 'fluidsymbol' from [RotaryCraft] unrecognized
[20:55:32] [Client thread/ERROR] [Mystcraft/Mystcraft]: Failed to process IMC message 'fluidsymbol' from [RotaryCraft]
[20:55:32] [Client thread/INFO] [STDERR/Mystcraft]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[20:55:32] [Client thread/INFO] [STDERR/Mystcraft]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at com.xcompwiz.mystcraft.imc.IMCHandler.process(IMCHandler.java:40)
[20:55:32] [Client thread/INFO] [STDERR/Mystcraft]: [java.lang.Throwable$WrappedPrintStream:println:748]:       at com.xcompwiz.mystcraft.Mystcraft.handleIMC(Mystcraft.java:302)
```

**Comment by ReikaKalseki** [comment]
His [site](http://binarymage.com/wiki/doku.php?id=mods:api:imc) is out of date....

**Comment by ReikaKalseki** [comment]
OK, having decompiled his source, I think I fixed it.

**Comment by keybounce** [comment]
Good. Can you update that part of the wiki?

If not, I'll ask someone else to.

**Comment by ReikaKalseki** [comment]
?

**Comment by keybounce** [comment]
Your link was to a section of the mystcraft wiki on the API.

You determined that it was out of date.

I was asking if you can update that section. If you can't, I'll ask on the mystcraft forums if someone else can bring it up to date.

**Comment by ReikaKalseki** [comment]
That was his website, not a wiki.

**Comment by keybounce** [comment]
The link you gave goes to http://binarymage.com/wiki/doku.php?id=mods:api:imc ,which is a wiki.

**Comment by ReikaKalseki** [comment]
I do not have the power to edit it.

**Comment by keybounce** [comment]
Ahh ...
Alright, I'll see if I can get someone else to edit it then.

**Comment by XCompWiz** [comment]
That isn't even my wiki.  I host it, but the data is community made.
The API documentation is on the forum. ;)

The IMC messages have their own topic.

Keybounce, (and I'll bring this up in the forums), I'd rather you took the API doc off of the Wiki. It doesn't belong there.
