### ISSUE TITLE
RotaryCraft crashed when I start the client

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#655]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ExceptionInInitializerError
    at Reika.RotaryCraft.RotaryCraft.load(RotaryCraft.java:348)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: XML file at Resources/zh_CN/trans.xml relative to Reika.RotaryCraft.RotaryCraft failed to load!
    at Reika.DragonAPI.Instantiable.IO.XMLInterface.<init>(XMLInterface.java:48)
    at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.<clinit>(RotaryDescriptions.java:97)
    ... 38 more
Caused by: java.lang.RuntimeException: XML file at Resources/zh_CN/trans.xml relative to Reika.RotaryCraft.RotaryCraft failed to load!
    at Reika.DragonAPI.IO.ReikaXMLBase.getXMLDocument(ReikaXMLBase.java:46)
    at Reika.DragonAPI.Instantiable.IO.XMLInterface.<init>(XMLInterface.java:44)
    ... 39 more

I don't know what should I do, but I find this:

```
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: XML file at Resources/zh_CN/trans.xml relative to Reika.RotaryCraft.RotaryCraft failed to load!
    at Reika.DragonAPI.Instantiable.IO.XMLInterface.<init>(XMLInterface.java:48)
    at Reika.RotaryCraft.Auxiliary.RotaryDescriptions.<clinit>(RotaryDescriptions.java:97)
    ... 38 more
Caused by: java.lang.RuntimeException: XML file at Resources/zh_CN/trans.xml relative to Reika.RotaryCraft.RotaryCraft failed to load!
    at Reika.DragonAPI.IO.ReikaXMLBase.getXMLDocument(ReikaXMLBase.java:46)
    at Reika.DragonAPI.Instantiable.IO.XMLInterface.<init>(XMLInterface.java:44)
    ... 39 more
```

So, `Resources/zh_CN/trans.xml`, what... :(

**Comment by ghost** [comment]
#654 Oh this issues is same like me! No! Exactly the same mistake!

**Comment by ReikaKalseki** [comment]
Same title too. Had this been all the same user I would have looked into blocking them.
