### ISSUE TITLE
Server Crashed.

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#657]
When I backup and update to V11a, there is so many problem.
I installed Reika's 5 mods:

```
DragonAPI
RotaryCraft
ReactorCraft
ElectriCraft
GeoStrata
```

And there is report log:

```
---- Minecraft Crash Report ----
// My bad.

Time: 16-2-28 上午11:29
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/WorldServer.func_147454_a(IIILnet/minecraft/block/Block;II)V @100: getfield
  Reason:
    Type 'net/minecraft/block/Block' (current frame, stack[1]) is not assignable to 'net/minecraft/world/NextTickListEntry'
  Current Frame:
    bci: @100
    flags: { }
    locals: { 'net/minecraft/world/WorldServer', integer, integer, integer, 'net/minecraft/block/Block', integer, integer, 'net/minecraft/block/Block' }
    stack: { 'net/minecraft/world/WorldServer', 'net/minecraft/block/Block' }
  Bytecode:
    0x0000000: 2ab4 03b4 9900 7c19 04b6 03b8 b203 bea5
    0x0000010: 0071 1904 b603 c199 0066 2a1b 1008 641c
    0x0000020: 1008 641d 1008 641b 1008 601c 1008 601d
    0x0000030: 1008 60b6 03c5 9900 462a 1b1c 1db6 0331
    0x0000040: 3a07 1907 b603 b8b2 03be a500 3219 0719
    0x0000050: 04a6 002b 1907 2a1b 1c1d 2ab4 0225 b603
    0x0000060: 592a 1907 b403 ca19 07b4 03cd 1907 b403
    0x0000070: d019 09b2 03d3 b403 62b8 0368 b104 3605
    0x0000080: 2a1b 077a 1d07 7ab6 03d6 c600 1d2a b400
    0x0000090: 901b 1c1d 1506 1505 852a b401 4fb6 0168
    0x00000a0: 6119 04b6 03da 57b1                    
  Stackmap Table:
    same_frame_extended(@124)
    same_frame(@125)
    same_frame(@128)
    same_frame(@167)

    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/WorldServer.func_147454_a(IIILnet/minecraft/block/Block;II)V @100: getfield
  Reason:
    Type 'net/minecraft/block/Block' (current frame, stack[1]) is not assignable to 'net/minecraft/world/NextTickListEntry'
  Current Frame:
    bci: @100
    flags: { }
    locals: { 'net/minecraft/world/WorldServer', integer, integer, integer, 'net/minecraft/block/Block', integer, integer, 'net/minecraft/block/Block' }
    stack: { 'net/minecraft/world/WorldServer', 'net/minecraft/block/Block' }
  Bytecode:
    0x0000000: 2ab4 03b4 9900 7c19 04b6 03b8 b203 bea5
    0x0000010: 0071 1904 b603 c199 0066 2a1b 1008 641c
    0x0000020: 1008 641d 1008 641b 1008 601c 1008 601d
    0x0000030: 1008 60b6 03c5 9900 462a 1b1c 1db6 0331
    0x0000040: 3a07 1907 b603 b8b2 03be a500 3219 0719
    0x0000050: 04a6 002b 1907 2a1b 1c1d 2ab4 0225 b603
    0x0000060: 592a 1907 b403 ca19 07b4 03cd 1907 b403
    0x0000070: d019 09b2 03d3 b403 62b8 0368 b104 3605
    0x0000080: 2a1b 077a 1d07 7ab6 03d6 c600 1d2a b400
    0x0000090: 901b 1c1d 1506 1505 852a b401 4fb6 0168
    0x00000a0: 6119 04b6 03da 57b1                    
  Stackmap Table:
    same_frame_extended(@124)
    same_frame(@125)
    same_frame(@128)
    same_frame(@167)

    at net.minecraftforge.common.ChestGenHooks.init(ChestGenHooks.java:59)
    at net.minecraftforge.common.ChestGenHooks.<clinit>(ChestGenHooks.java:39)
    at mods.railcraft.common.plugins.forge.LootPlugin.addLoot(LootPlugin.java:54)
    at mods.railcraft.common.plugins.forge.LootPlugin.addLoot(LootPlugin.java:49)
    at mods.railcraft.common.plugins.forge.LootPlugin.addLootRailway(LootPlugin.java:69)
    at mods.railcraft.common.fluids.FluidContainers.getCreosoteOilBottle(FluidContainers.java:66)
    at mods.railcraft.common.fluids.FluidContainers.getCreosoteOilBottle(FluidContainers.java:54)
    at mods.railcraft.common.fluids.RailcraftFluids$1.defineContainers(RailcraftFluids.java:36)
    at mods.railcraft.common.fluids.RailcraftFluids.init(RailcraftFluids.java:94)
    at mods.railcraft.common.fluids.RailcraftFluids.preInitFluids(RailcraftFluids.java:75)
    at mods.railcraft.common.modules.ModuleCore.preInit(ModuleCore.java:135)
    at mods.railcraft.common.modules.ModuleManager.preInit(ModuleManager.java:237)
    at mods.railcraft.common.modules.ModuleManager.preInit(ModuleManager.java:169)
    at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1614.200 Official
    Plugins: ~~ERROR~~ NullPointerException: null
    Disabled Plugins: ~~ERROR~~ NullPointerException: null
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 171420904 bytes (163 MB) / 522715136 bytes (498 MB) up to 934281216 bytes (891 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 45 mods loaded, 45 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.200.jar) 
    UCH Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.200.jar) 
    UCH kimagine{0.2} [KImagine] (minecraft.jar) 
    UCH InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
    UCE IC2{2.2.815-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.815-experimental.jar) 
    UCE AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCH aiimprovements{0.0.1.19} [AI Improvements] (AIImprovements-1.7.10-0.0.1b19-dev.jar) 
    UCH BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCH BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
    UCH BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
    UCH BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
    UCH BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
    UCH BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
    UCH BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
    UCH BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
    UCH BuildMod{v1.0} [Build Mod] (coroutil.jar) 
    UCH CoroPets{v1.0} [CoroPets] (coroutil.jar) 
    UCH CoroAI{v1.0} [CoroAI] (coroutil.jar) 
    UCH ExtendedRenderer{v1.0} [Extended Renderer] (coroutil.jar) 
    UCH ConfigMod{v1.0} [Extended Mod Config] (coroutil.jar) 
    UCH creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.23 mc1.7.10.jar) 
    UCH Forestry{4.2.9.57} [Forestry for Minecraft] (forestry_1.7.10-4.2.9.57.jar) 
    UCH ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCH ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCH DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V11a.jar) 
    UCH RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V11a.jar) 
    UCH ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V11a.jar) 
    UCH GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V11a.jar) 
    UCE IC2NuclearControl{2.3.4a} [Nuclear Control 2] (IC2NuclearControl-2.3.4a.jar) 
    UCH ingameconfigmanager{0.1} [InGameConfigManager] (InGameConfigManager Alpha v0.1.12 mc1.7.10.zip) 
    UCH IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCH LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10 v7.jar) 
    UCH malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
    UCH malisisdoors{1.7.10-1.13.1} [Malisis' Doors] (malisisdoors-1.7.10-1.13.1.jar) 
    UCH me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UCH AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
    UCH cfm{3.4.8} [?9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
    UCE Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
    UCH ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V11a.jar) 
    UCH RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) 
    UCH ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness.jar) 
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)
```

I don't know what happend, I have not seen such a mistake, but if I delete all Reika's Mod, there is no any error, so these errors must be Reika's Mod generated.

And then, I try only use Reika's Mod without any other mod, and start the server, crashed.

Server version: KCauldron 1.7.10 - 200 - 1614.
Java version: 8

**Comment by ReikaKalseki** [comment]
KCauldron.

**Comment by ghost** [comment]
But if this problem is KCauldron's, why I use V10 version is OK?

**Comment by ReikaKalseki** [comment]
I doubt V10 was working, as I have not added any WorldServer ASM in v11.

**Comment by webbster64** [comment]
got the same problem, so looks like i have to remove all of ReikaKalseki's mods considering im going choose thermos over DragonAPI RotaryCraft ReactorCraft ElectriCraft GeoStrata, i want to give my players a stable and fun server running at 20-19tps over a server with 5 extra mods thats running at 5tps
