### ISSUE TITLE
Chromaticraft STILL Crashing

### ISSUE THREAD

**Issue by echthesia** [ReikaKalseki/Reika_Mods_Issues#663]
[crash-2016-02-28_18.59.02-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/151999/crash-2016-02-28_18.59.02-client.txt)

This is a continuation of #659 , because the suggestion of the issue I was inadvertently duplicating (oops) did not work. I was already on AE2-rv2, and had the corresponding Thaumic Energistics installed, when the original crash occurred. In addition, my error occurred later in the loading phase and with a different message (no, not the witty one, the one after the java explanation of the error). Please don't tell me there was a way to reuse the existing issue, because that would make me look like a fool. I'm new. Thanks!

**Comment by ReikaKalseki** [comment]
Not even my crash.

java.lang.NullPointerException: Unexpected error
    at com.mumfrey.liteloader.util.Input.onTick(Input.java:205)
    at com.mumfrey.liteloader.core.event.HandlerList$TickObserver4.onTick(HandlerList$TickObserver4.java:102)
    at com.mumfrey.liteloader.core.LiteLoader.onTick(LiteLoader.java:988)
    at com.mumfrey.liteloader.core.Events.onTick(Events.java:241)
    at com.mumfrey.liteloader.client.ClientEvents.onTick(ClientEvents.java:407)
    at com.mumfrey.liteloader.client.CallbackProxyClient.onTick(CallbackProxyClient.java:63)
    at com.mumfrey.liteloader.core.event.EventProxy.$event00005(EventProxy.java:216)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by echthesia** [comment]
Thanks for the hyperspeed response, and what's funny is that it only occurs with your mod present. Oh well, guess I'll go bother the LiteLoader section now.
