### ISSUE TITLE
Rotarycraft issue

### ISSUE THREAD

**Issue by xXxANOxXx** [ReikaKalseki/Reika_Mods_Issues#670]
The Version i used :
Rotarycraft V11b
Reactorcraft V11b
DragonAPI V11b

I want to make a server for me and my friend with Rotarycraft and Reactorcraft but every time when i try to start the server i get this error (thanks for help)  :

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/4/16 3:22 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at cpw.mods.fml.common.eventhandler.EventBus.unregister(EventBus.java:124)
    at Reika.DragonAPI.Base.DragonAPIMod.basicSetup(DragonAPIMod.java:124)
    at Reika.RotaryCraft.RotaryCraft.preload(RotaryCraft.java:320)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 2.6.32-5-amd64
    Java Version: 1.7.0_72, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 470965536 bytes (449 MB) / 816054272 bytes (778 MB) up to 817102848 bytes (779 MB)
    JVM Flags: 4 total; -XX:+UseConcMarkSweepGC -XX:MaxPermSize=168M -Xmx805M -Xms805M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 51 mods loaded, 51 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](bhserver.jar) 
    UCH Forge{10.13.4.1448} [Minecraft Forge](bhserver.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCH zeldaswordskills{1.7.10-2.4} [Zelda Sword Skills](1.7.10-zeldaswordskills-2.4.jar) 
    UCH divinerpg{1.4.1.3} [DivineRPG]([1.7.10][SMP]DivineRPG-1.4.1.3.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH Backpack{2.0.1} [Backpack](backpack1.7.x.jar) 
    UCH BattleTowers{1.5.2} [Battle Towers](BattleTowers-1.7.10.jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCH BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCH BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCH ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UCH chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UCH Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCH ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCH TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V11b.jar) 
    UCH CritterPet{1.0} [Critter Pet](CritterPet 1.7.10 V11b.jar) 
    UCH dimdoors{2.2.5-test9} [Dimensional Doors](DimensionalDoors-2.2.5-test9.jar) 
    UCH dldungeonsjdg{1.8.8} [Doomlike Dungeons](DoomlikeDungeons-1.8.8-MC1.7.10.jar) 
    UCH eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCH GraveStone{2.16.0} [GraveStone](GraveStone-2.16.0.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCH IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCH ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCH Mekanism{8.1.9} [Mekanism](Mekanism-1.7.10-8.1.9.264.jar) 
    UCH MekanismGenerators{8.1.9} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.9.264.jar) 
    UCH MekanismTools{8.1.9} [MekanismTools](MekanismTools-1.7.10-8.1.9.264.jar) 
    UCH minegicka3{1.0.0} [Minegicka 3](Minegicka-3-Mod-1.7.10.jar) 
    UCH MobAmputation{4.0.1} [MobAmputation](MobAmputation-4.0.1.jar) 
    UCH PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
    UCE RotaryCraft{1.0} [RotaryCraft](RotaryCraft 1.7.10 V11b.jar) 
    UCE ReactorCraft{1.0} [ReactorCraft](ReactorCraft 1.7.10 V11b.jar) 
    UCH rftl{1.7.10} [Rotten Flesh to Leather](Rotten-Flesh-to-Leather-Mod-1.7.10.jar) 
    UCH Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCH AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UCH warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.36.jar) 
    UCH McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCH ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Sarioah** [comment]
You need to be on Forge 1558 at least. Try that version and see if it still crashes.

**Comment by ReikaKalseki** [comment]
Try updating Forge, but that crash is all in internal code from me; it should be invariant.

**Comment by xXxANOxXx** [comment]
okay i have get it now with a the newst Forge version but now i dont see the iteams in creative mode

**Comment by ReikaKalseki** [comment]
Any information?
