### ISSUE TITLE
NPE in ElectriCraft.Network.PathCalculator.recursiveCalculate

### ISSUE THREAD

**Issue by cypren** [ReikaKalseki/Reika_Mods_Issues#71]
I've got an interesting problem running ElectriCraft power through world rifts in my main SMP world. I've tested this in a creative world with Reika mods only, so I know that this works correctly in a clean environment; something about the modpack or world state of my main gameworld is causing a failure that I'd like to try to understand.

When I try to connect EC power directly to a world rift, placing the connecting cable on the other end generates the following exception:

```
[19:15:33] [Server thread/INFO] [FML]: Tile Entity electri.wire @ DIM12: -3, 66, -4 is throwing class java.lang.NullPointerException on update: null
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:115)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:149)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:134)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.PathCalculator.calculatePaths(PathCalculator.java:79)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.WireNetwork.recalculatePaths(WireNetwork.java:279)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.WireNetwork.updateWires(WireNetwork.java:266)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.WireNetwork.addElement(WireNetwork.java:262)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Base.NetworkTileEntity.setNetwork(NetworkTileEntity.java:81)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Network.WireNetwork.merge(WireNetwork.java:186)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Base.NetworkTileEntity.linkTile(NetworkTileEntity.java:54)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Base.NetworkTileEntity.findAndJoinNetwork(NetworkTileEntity.java:40)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.Base.NetworkTileEntity.updateEntity(NetworkTileEntity.java:28)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.ElectriCraft.TileEntities.TileEntityWire.updateEntity(TileEntityWire.java:40)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:392)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.World.func_72939_s(World.java:1939)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[19:15:33] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Passing RotaryCraft power through the rift works just fine; the problems seem to be limited only to ElC network calculation. From a cursory inspection, something is apparently causing recursiveCalculate to get called on a location that doesn't contain a TileEntity.

I've verified that this happens even when the rifts and the involved networks are completely broken and replaced. It also happens regardless of which side pairs are used to connect the wires through the rift.

I realize this is kind of thin for a bug report; if you'd like to investigate this and would like me to provide world saves or debugging assistance, please let me know.

**Comment by ReikaKalseki** [comment]
You say "directly". Do you mean a generator directly into a world rift, or is there wire on both sides?

**Comment by ReikaKalseki** [comment]
OK, I cannot reproduce this. The following setup works perfectly.

![](http://i.imgur.com/ABNMeIV.png)

**Comment by cypren** [comment]
The specific setup is battery -> superconductor -> world rift -> world rift -> superconductor -> 4 inductive motors. 

As I mentioned in the initial post, I wasn't able to reproduce this problem in a clean test world (using only your mods and NEI), either. I also can't reproduce it in a clean test world using my server's mod setup (which is basically FTB Infinity 1.5.1 + your mods + Mekanism) when I make a setup like the one you did above.

_But._

These tests are single-dimension. As soon as I create a Mystcraft dimension and put the corresponding world rift on the other end, then connect up my electric cables...

```
[23:41:59] [Server thread/INFO] [FML/]: Tile Entity machine.electribattery @ DIM0: -876, 4, -709 is throwing class java.lang.NullPointerException on update: null
[23:41:59] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[23:41:59] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:115)
...
```

Armed with this knowledge, I went back into my Reika Test World mini-mod-pack and added one new mod: ChickenChunks. I dropped a chunkloader in the overworld and one in the nether, connected up a battery on one side to a motor on the other, and... we have a winner.

```
[23:52:06] [Server thread/INFO] [FML]: Tile Entity Induction Motor @ DIM0: -544, 4, 1385 is throwing class java.lang.NullPointerException on update: null
[23:52:06] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[23:52:06] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at Reika.ElectriCraft.Network.PathCalculator.recursiveCalculate(PathCalculator.java:115)
...
```

So it looks like this bug happens specifically when you attempt to connect ElectriCraft wires through an _interdimensional_ world rift only.

**Comment by ReikaKalseki** [comment]
OK, I found the problem; ElC networks were never designed for multi-world applications, and carry the first world object through all the calculations...

**Comment by ReikaKalseki** [comment]
Well, the good news is that it works now. The bad news is that leaving the "other side" in the other world unloaded causes it to completely freak out and remap the network every tick.

**Comment by ReikaKalseki** [comment]
OK, I think I fixed this too.
