### ISSUE TITLE
AE2 and ChromatiCraft research levels crash

### ISSUE THREAD

**Issue by chrisk123999** [ReikaKalseki/Reika_Mods_Issues#710]
A strange crash occurs only the first time the game is loaded.  It looks to be related to AE2.  After it crashes the first time, it won't happen again unless mods are changed around.
Relevant part of the crash log:

```
[20:54:44] [AE2 CSV Export/INFO]: New mod configuration was found. Commencing exporting.
[20:54:44] [AE2 CSV Export/INFO]: Item Exporting ( started )
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ExceptionInInitializerError
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Registry.ChromaResearchManager.<init>(ChromaResearchManager.java:77)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Registry.ChromaResearchManager.<clinit>(ChromaResearchManager.java:66)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Auxiliary.ProgressionManager$ProgressStage.<init>(ProgressionManager.java:154)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Auxiliary.ProgressionManager$ProgressStage.<clinit>(ProgressionManager.java:91)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Block.Worldgen.BlockTieredPlant$TieredPlants.<clinit>(BlockTieredPlant.java:71)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Block.Worldgen.BlockTieredPlant.func_149666_a(BlockTieredPlant.java:293)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.services.export.MinecraftItemCSVExporter$ItemRowExtractFunction.apply(MinecraftItemCSVExporter.java:243)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.services.export.MinecraftItemCSVExporter$ItemRowExtractFunction.apply(MinecraftItemCSVExporter.java:193)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.base.Joiner$2.appendTo(Joiner.java:253)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.base.Joiner.appendTo(Joiner.java:152)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.base.Joiner.join(Joiner.java:193)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.base.Joiner.join(Joiner.java:183)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.services.export.MinecraftItemCSVExporter.export(MinecraftItemCSVExporter.java:99)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.services.export.ExportProcess.run(ExportProcess.java:126)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Thread.run(Unknown Source)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel.<init>(ChromaResearchManager.java:438)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel.<clinit>(ChromaResearchManager.java:423)
[20:54:45] [AE2 CSV Export/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  ... 18 more
```

Full crash log: https://dl.dropboxusercontent.com/u/1455347/2016-03-30-6.log
(I know a lot of mods, but I can provide another one with just the mods that cause the crash if needed)

Tested with the latest versions of your mods (v12c) and AE2 v3 (rv3.beta build 5).

**Comment by chrisk123999** [comment]
Crash log with just the 3 mods: https://paste.ee/p/6Lu6A
Game log after loading up the 2nd time (no crash): https://paste.ee/p/zLjDF

**Comment by ReikaKalseki** [comment]
Use rv2.
