### ISSUE TITLE
Could not add sound category CHROMA!

### ISSUE THREAD

**Issue by aetherstrata** [ReikaKalseki/Reika_Mods_Issues#863]
### Using  MultiMC

Forge version = 10.13.4.1614
Java version = 1.8.0_91 64-bit
OS version = Win 10 64-bit (version 1151, build 10586.318)
- [**complete log**](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/282591/latest.txt)
- [**crash**](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/282597/crash-2016-05-25_20.00.30-client.txt)
- [**modlist**](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/282605/modlist.txt)

```
Reika.DragonAPI.Exception.InstallationException:
    at Reika.DragonAPI.Libraries.ReikaRegistryHelper.addSoundCategory(ReikaRegistryHelper.java:334)
    at Reika.ChromatiCraft.ChromaClient.registerSounds(ChromaClient.java:162)
    at Reika.ChromatiCraft.ChromatiCraft.preload(ChromatiCraft.java:305)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

EDIT: Added online versions

> [complete log](https://paste.ee/p/P8ipZ)
> [crash](https://paste.ee/p/FgulT)
> [modlist](https://paste.ee/p/0GWZp)

**Comment by ReikaKalseki** [comment]
Read the log, including the part about not posting it that you removed to post it here.

**Comment by aetherstrata** [comment]
Sorry, I thought that part was superfluous.

**Comment by ReikaKalseki** [comment]
I do not exactly believe you.

**Comment by TomeWyrm** [comment]
"Could not add sound category CHROMA! Use the Sound HashMap config!"

It's right there, seriously.

**Comment by ReikaKalseki** [comment]
Notice they removed it from the log to post (claiming it was "superfluous").

**Comment by aetherstrata** [comment]
Did u see the 

### [complete log](https://paste.ee/p/P8ipZ)

button...

**Comment by redelman** [comment]
No, I do not see the "complete log" button. Is this a new button on Github somewhere? I do see a "complete log" link in the original report, however.

**Comment by ReikaKalseki** [comment]
Which were not there before.

**Comment by TomeWyrm** [comment]
It was when I looked. In any case, the answer was in the crash. Which is what you and I said
