### ISSUE TITLE
java.lang.NoClassDefFoundError when approaching some structures in dimension

### ISSUE THREAD

**Issue by therodet** [ReikaKalseki/Reika_Mods_Issues#874]
Server-only crash when approaching some structures

java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
    at Reika.ChromatiCraft.Block.Dimension.Structure.BlockLaserEffector.func_149915_a(BlockLaserEffector.java:71)
    at net.minecraft.block.Block.createTileEntity(Block.java:1446)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at Reika.DragonAPI.Instantiable.Worldgen.ChunkSplicedGenerationCache$SetBlock.place(ChunkSplicedGenerationCache.java:189)
    at Reika.DragonAPI.Instantiable.Worldgen.ChunkSplicedGenerationCache$TileSet.place(ChunkSplicedGenerationCache.java:219)
    at Reika.DragonAPI.Instantiable.Worldgen.ChunkSplicedGenerationCache.doGenerate(ChunkSplicedGenerationCache.java:128)
    at Reika.DragonAPI.Instantiable.Worldgen.ChunkSplicedGenerationCache.generate(ChunkSplicedGenerationCache.java:108)
    at Reika.ChromatiCraft.Base.DimensionStructureGenerator.generateChunk(DimensionStructureGenerator.java:128)
    at Reika.ChromatiCraft.World.Dimension.ChunkProviderChroma.onPopulationHook(ChunkProviderChroma.java:788)
    at Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
    at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
    at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:174)
    at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
    at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by ReikaKalseki** [comment]
Already fixed.
