### ISSUE TITLE
[ChromatiCraft] NPE with Crystal Wand and Inventory Simulator

### ISSUE THREAD

**Issue by jeremiahwinsley** [ReikaKalseki/Reika_Mods_Issues#969]
I'm using v14d in SMP. When I place a crystal wand into a chunkloaded Inventory Simulator and then log off, the server console is spammed with this exception. 

```
[01:44:07] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
java.lang.NullPointerException
        at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
        at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) [SimpleNetworkWrapper.class:?]
        at Reika.DragonAPI.Instantiable.IO.PacketPipeline.sendToPlayer(PacketPipeline.java:83) [PacketPipeline.class:?]
        at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper.sendDataPacket(ReikaPacketHelper.java:250) [ReikaPacketHelper.class:?]
        at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper.sendDataPacket(ReikaPacketHelper.java:210) [ReikaPacketHelper.class:?]
        at Reika.ChromatiCraft.ModInterface.CrystalWand$WandUpdater.onUpdate(CrystalWand.java:94) [CrystalWand$WandUpdater.class:?]
        at thaumcraft.common.items.wands.ItemWandCasting.func_77663_a(ItemWandCasting.java:355) [ItemWandCasting.class:?]
        at Reika.ChromatiCraft.TileEntity.Processing.TileEntityInventoryTicker.updateItems(TileEntityInventoryTicker.java:80) [TileEntityInventoryTicker.class:?]
        at Reika.ChromatiCraft.TileEntity.Processing.TileEntityInventoryTicker.updateEntity(TileEntityInventoryTicker.java:70) [TileEntityInventoryTicker.class:?]
        at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:464) [TileEntityBase.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

```

**Comment by ReikaKalseki** [comment]
This is deep in network code. Are you sure this is on my end?

**Comment by jeremiahwinsley** [comment]
At a quick glance, it looks like [`onUpdate`](https://github.com/ReikaKalseki/ChromatiCraft/blob/fcd1f3d17b6ea680b2a436672b956cfbad693788/ModInterface/CrystalWand.java#L66) is receiving a `FakePlayer` which does extend `EntityPlayerMP` but is apparently not valid for receiving client packets. So it passes the `instanceof` on L88, but throws an exception on L94 because of it.

**Comment by ReikaKalseki** [comment]
Ah, and since the wand actually sends packets periodically...

Though I can fix this particular case, there is a high likelihood that there are many more such unstable items, and which I can do nothing about.

**Comment by ReikaKalseki** [comment]
I make the wand itself not update with fake players, and I put a try-catch around the tile's update loop to prevent spam, though it will still be unperformant. This is the best I can do.
