### ISSUE TITLE
[ChromatiCraft] Place a item causes the server to crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#971]
I'm sorry to disturb you, but I find a problem.
When I place **Wireless Lumen Distributor** in server world, server will crash.

```
[16:13:15] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
    at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_92]
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_92]
    at Reika.ChromatiCraft.Registry.ChromaTiles.createTEFromIDAndMetadata(ChromaTiles.java:357) ~[ChromaTiles.class:?]
    at Reika.ChromatiCraft.Base.BlockChromaTile.createTileEntity(BlockChromaTile.java:141) ~[BlockChromaTile.class:?]
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:957) ~[apx.class:?]
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:715) ~[apx.class:?]
    at net.minecraft.world.World.func_147465_d(World.java:860) ~[ahb.class:?]
    at Reika.ChromatiCraft.Items.ItemChromaPlacer.func_77648_a(ItemChromaPlacer.java:152) ~[ItemChromaPlacer.class:?]
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535) ~[ForgeHooks.class:1.7.10-1614.57]
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:164) ~[add.class:?]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:498) ~[mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) ~[nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
    ... 23 more
[16:13:15] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_92]
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_92]
    at Reika.ChromatiCraft.Registry.ChromaTiles.createTEFromIDAndMetadata(ChromaTiles.java:357) ~[ChromaTiles.class:?]
    at Reika.ChromatiCraft.Base.BlockChromaTile.createTileEntity(BlockChromaTile.java:141) ~[BlockChromaTile.class:?]
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:957) ~[apx.class:?]
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:715) ~[apx.class:?]
    at net.minecraft.world.World.func_147465_d(World.java:860) ~[ahb.class:?]
    at Reika.ChromatiCraft.Items.ItemChromaPlacer.func_77648_a(ItemChromaPlacer.java:152) ~[ItemChromaPlacer.class:?]
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:535) ~[ForgeHooks.class:1.7.10-1614.57]
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:164) ~[add.class:?]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:498) ~[mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) ~[nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
[16:13:15] [Server thread/ERROR]: This crash report has been saved to: F:\Minecraft_Server\Minecraft_Server\.\crash-reports\crash-2016-06-16_16.13.15-server.txt
[16:13:15] [Server thread/INFO]: Stopping server
```

Client version: Minecraft 1.7.10 - Forge 1614
Server version: Thermos 1.7.10 - Forge 1614 - 57
**Single-player games do not have this problem.**
So I think this is a BUG for server.
Thank you very much!

(\* The log file is too long, I can't upload it... Sorry...)

**Comment by ReikaKalseki** [comment]
Already fixed.

**Comment by ghost** [comment]
@ReikaKalseki Thanks very much, I almost ruined my main server world ......

**Comment by LukaPix** [comment]
still happens to my server on startup (newest version)

**Comment by ReikaKalseki** [comment]
Tell me exactly what version you are using.

**Comment by LukaPix** [comment]
V16d
i try to link to the log later on (im on my phone)

**Comment by Aivech** [comment]
Does it work on a server that isn't running Thermos?
