### ISSUE TITLE
After 14d update, it's unable to launch

### ISSUE THREAD

**Issue by ixkdc** [ReikaKalseki/Reika_Mods_Issues#989]
[19:04:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:04:39] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[19:04:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[19:04:39] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[19:04:39] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_66, running on Windows Vista:x86:6.0, installed at C:\Program Files\Java\jre1.8.0_66
[19:04:39] [main/INFO] [FML]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.0.1.jar
[19:04:39] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:04:41] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:04:41] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:04:41] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:04:41] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:04:41] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_C1.jar
[19:04:42] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:04:42] [main/INFO] [LaunchWrapper]: Loading tweak class name me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[19:04:42] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:04:42] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:04:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:04:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:04:42] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[19:04:42] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[19:04:42] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[19:04:42] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[19:04:42] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Kuba/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_U_C1.jar
[19:04:42] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@9cd3b1
[19:04:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:45] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:04:46] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:46] [main/INFO] [IC2-core]: Loaded library EJML-core-0.26.jar.
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[19:04:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[19:04:47] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:48] [main/INFO] [FML]: Java Version: [8, 0, 66]
[19:04:48] [main/INFO] [FML]: Heap memory allocation: 1100000000
[19:04:48] [main/INFO] [FML]: 4 Java arguments present: [-Xmx1100M, -Xms128M, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Djava.library.path=C:\Users\Kuba\AppData\Roaming.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10-natives-35583823485387]
[19:04:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:04:48] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[19:04:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[19:04:48] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[19:04:48] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:04:48] [main/INFO] [me.guichaguri.betterfps.transformers.EventTransformer]: Patching Game Start...
[19:04:48] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.client.Minecraft
[19:04:48] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied MUSICTYPEEVENT ASM handler!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.entity.Entity
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied PUSHENTITYOUT ASM handler!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.entity.player.EntityPlayer
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied GUIEVENT ASM handler 1!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied GUIEVENT ASM handler 2!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.entity.player.EntityPlayer
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied PLAYERRENDERPASS ASM handler!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.entity.player.EntityPlayer
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied KEEPINVEVENT ASM handler 1!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied KEEPINVEVENT ASM handler 2!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.client.gui.inventory.GuiContainer
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied ITEMRENDEREVENT ASM handler!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.client.gui.inventory.GuiContainer
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied HOTBARKEYEVENT ASM handler!
[19:04:49] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Patching class net.minecraft.world.World
[19:04:49] [main/INFO] [FML]: DRAGONAPI: LiteLoader not detected.
[19:04:49] [main/INFO] [FML]: DRAGONAPI: Optifine detected. Loading compatibility features.
[19:04:49] [main/INFO] [FML]: DRAGONAPI:        Note that some parts of the game, especially rendering and textures, may error out.
[19:04:49] [main/INFO] [FML]: DRAGONAPI: FastCraft not detected.
[19:04:49] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: Reika.DragonAPI.Exception.ASMException$NoSuchASMMethodInstructionException: Error ASMing method func_147465_d (IIILnet/minecraft/block/Block;II)Z in net/minecraft/world/World:
Could not find an instruction for a method call to net/minecraft/world/World's func_147451_t (III)Z:

```
at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getNthMethodCall(ReikaASMHelper.java:556) ~[DragonAPI%201.7.10%20V14d.jar:?]
at Reika.DragonAPI.Libraries.Java.ReikaASMHelper.getFirstMethodCall(ReikaASMHelper.java:540) ~[DragonAPI%201.7.10%20V14d.jar:?]
at Reika.DragonAPI.ASM.DragonAPIClassTransformer$ClassPatch.apply(DragonAPIClassTransformer.java:1806) ~[DragonAPI%201.7.10%20V14d.jar:?]
at Reika.DragonAPI.ASM.DragonAPIClassTransformer.transform(DragonAPIClassTransformer.java:1952) ~[DragonAPI%201.7.10%20V14d.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
... 6 more
```

Exception in thread "main" [19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.SecurityManager.checkExit(Unknown Source)
[19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Runtime.exit(Unknown Source)
[19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.System.exit(Unknown Source)
[19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:04:49] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by redelman** [comment]
I am almost positive this is a duplicate, but you don't provide the full log or a mod list, so it's hard to tell. And next time, don't paste the log directly into the comment. Use gist or something.

**Comment by ReikaKalseki** [comment]
It is.
