### ISSUE TITLE
Crash if I plays 2 world rifts

### ISSUE THREAD

**Issue by Ryius** [ReikaKalseki/Reika_Mods_Issues#992]
Just placed to world rifts down but i think the mod who is causing this is Opencomputer ?

java.lang.NullPointerException: Unexpected error
    at li.cil.oc.server.network.Network.contains(Network.scala:212)
    at li.cil.oc.server.network.Network.connect(Network.scala:79)
    at li.cil.oc.server.network.Network$Wrapper.connect(Network.scala:749)
    at li.cil.oc.server.network.Node$class.connect(Node.scala:38)
    at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.connect(Network.scala:599)
    at Reika.ChromatiCraft.TileEntity.Transport.TileEntityRift.onLinkTo(TileEntityRift.java:221)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:61)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:93)
    at Reika.ChromatiCraft.Items.ItemLinkedTilePlacer.func_77648_a(ItemLinkedTilePlacer.java:88)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ReikaKalseki** [comment]
Not my code, and works for me.

**Comment by ghost** [comment]
Happens in the Rev|2 modpack. Probably mod interaction.

**Comment by ReikaKalseki** [comment]
@Haggle1996?

**Comment by Haggle1996** [comment]
Besides being a duplicate of #987, it could be a problem with OpenComputers. I'll strip some mods out and see if I can replicate.

**Comment by Ryius** [comment]
what version you run on open computers Reika

**Comment by Ryius** [comment]
Hm okey i now have only your mods and opencomputers in 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 23.06.16 14:58
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at li.cil.oc.server.network.Network.contains(Network.scala:212)
    at li.cil.oc.server.network.Network.connect(Network.scala:79)
    at li.cil.oc.server.network.Network$Wrapper.connect(Network.scala:749)
    at li.cil.oc.server.network.Node$class.connect(Node.scala:38)
    at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.connect(Network.scala:599)
    at Reika.ChromatiCraft.TileEntity.Transport.TileEntityRift.onLinkTo(TileEntityRift.java:221)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:61)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:93)
    at Reika.ChromatiCraft.Items.ItemLinkedTilePlacer.func_77648_a(ItemLinkedTilePlacer.java:88)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at li.cil.oc.server.network.Network.contains(Network.scala:212)
    at li.cil.oc.server.network.Network.connect(Network.scala:79)
    at li.cil.oc.server.network.Network$Wrapper.connect(Network.scala:749)
    at li.cil.oc.server.network.Node$class.connect(Node.scala:38)
    at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.connect(Network.scala:599)
    at Reika.ChromatiCraft.TileEntity.Transport.TileEntityRift.onLinkTo(TileEntityRift.java:221)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:61)
    at Reika.ChromatiCraft.Base.TileEntity.LinkedTile.linkTo(LinkedTile.java:93)
    at Reika.ChromatiCraft.Items.ItemLinkedTilePlacer.func_77648_a(ItemLinkedTilePlacer.java:88)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [EntityClientPlayerMP['Ryius'/179, l='MpServer', x=314,95, y=70,62, z=-190,85], MCH_ViewEntityDummy['McHeliDummyEntity'/204, l='MpServer', x=0,00, y=-4,00, z=0,00]]
    Chunk stats: MultiplayerChunkCache: 765, 765
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (296,64,-213), Chunk: (at 8,4,11 in 18,-14; contains blocks 288,0,-224 to 303,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 666 game time, 666 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false

```
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
```

Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1553919624 bytes (1481 MB) / 2833489920 bytes (2702 MB) up to 15998779392 bytes (15257 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 12 mods loaded, 12 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   OpenComputers|Core{1.6.0.5-beta.3} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHIJAAAA   mcheli{1.0.2} [MC Helicopter](mcheli) 
    UCHIJAAAA   DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V15a.jar) 
    UCHIJAAAA   ChromatiCraft{1.0} [ChromatiCraft](ChromatiCraft 1.7.10 V15a.jar) 
    UCHIJAAAA   RotaryCraft{1.0} [RotaryCraft](RotaryCraft 1.7.10 V15a.jar) 
    UCHIJAAAA   ElectriCraft{1.0} [ElectriCraft](ElectriCraft 1.7.10 V15a.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.5-beta.3} [OpenComputers](OpenComputers-MC1.7.10-1.6.0.5-beta.3-universal.jar) 
    UCHIJAAAA   ReactorCraft{1.0} [ReactorCraft](ReactorCraft 1.7.10 V15a.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [faithful32packOptiFine (1).zip]
Current Language: English (UK)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Haggle1996** [comment]
Just to update this thread with info from the others; I can replicate this problem with just Forge (1614), DragonAPI, ChromatiCraft (v15 for both), and OpenComputers (1.6.0.5 beta 3). Removing OpenComputers allows you to place multiple World Rifts; however, that doesn't necessarily mean it's at fault

**Comment by ReikaKalseki** [comment]
I changed some World Rift code in v15, but nothing to do with OC.

**Comment by Haggle1996** [comment]
This was happening in v14 too; just tested with v15 to rule out 'not latest'

**Comment by Builderb0y** [comment]
Try downgrading open computers to 1.5.22.43, as that's the version we're using on our dev server. If I recall correctly, there were API issues when we updated support for OC that required updating to the 1.6 branch, so we reverted those changes simply because the last time we updated OC on the server many things broke.

**Comment by Haggle1996** [comment]
Tried 1.5.22.43 (which is no longer available from the curseforge site) and 1.5.22.46. Both crash, same error.

**Comment by Haggle1996** [comment]
Here's a crashlog with v13 (tried backdating that) and 1.5.22.43 and nothing else
https://gist.github.com/Haggle1996/61dc36ababc9897e1b54d1a00b25c27b

**Comment by Haggle1996** [comment]
Okay, I've tested v15 (DragonAPI and ChromatiCraft) with the following versions of OpenComputers, and no other mods; all receive the crash. Note, deleted my OC, DragonAPI, and CrC config files each time so they would regenerate fresh. Removing OpenComputers prevents the crash.

OpenComputers 1.6.0.5 beta3 (latest)
OC 1.6.0.4 beta2
OC 1.6.0.2 rc1
OC 1.5.22.46 (last 1.5 version released Feb 7th, 2016)
OC 1.5.22.43 (version recommended by @Builderb0y -- not available on OC's CurseForge [page](http://minecraft.curseforge.com/projects/opencomputers/files?filter-game-version=2020709689%3A4449)) 
OC 1.5.21.41 December 29th, 2015
OC 1.5.21.39
OC 1.5.21.38 Released November 21, 2015

At this point, I'm looking at @ReikaKalseki. Since OC 1.5.22.43 is not available for download, perhaps he has a special version that no one else does? I had a copy in my cache, so I assume it was available at some point but pulled.

**Comment by ReikaKalseki** [comment]
@Sangar: If that version it is not available, may I provide it? Also, any idea on what the problem might be?

**Comment by fnuecke** [comment]
It's probably just on Jenkins, I don't push every build to Curse; sure, feel free to.

As for the crash... the only thing the could be null there is the node being connected to, which on the one hand isn't surprising, because OC nodes don't exist on the client side, but what's odd is that it didn't NPE _before_ that in [onLinkTo](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Transport/TileEntityRift.java#L221). I'd almost guess that at construction time the side check in the node creation code fails, and erroneously returns something instead of null, but that does seem a bit unlikely. Sortakinda doesn't matter though, since there should be a side check in [this line](https://github.com/ReikaKalseki/ChromatiCraft/blob/master/TileEntity/Transport/TileEntityRift.java#L219) I'd say, so that you only run the connect code when on the server.
(Alternatively, to be extra sure, add a null check to ensure both the first and second node are not null before trying to connect them).

**Comment by ReikaKalseki** [comment]
I added the side and `!= null` checks, but that still does not explain why it does not crash for me (including last night).

Here is the version of OC we are using:

http://expirebox.com/download/957fdc08c340b058a2d05ce30f3975b6.html

@Haggle1996 That link will expire after 48 hours.

**Comment by Haggle1996** [comment]
@ReikaKalseki downloaded; testing now.

**Comment by Haggle1996** [comment]
Sorry, Reika. Still crashes with your version. Just your DragonAPI/CrC (v15) and the OpenComputers you provided: https://gist.github.com/Haggle1996/f8dc4ff65315af73a93961f9d223720b

**Comment by ReikaKalseki** [comment]
WTF?!!?

Are you on Forge 1614 (though that should not matter)?

**Comment by Haggle1996** [comment]
Yes, as noted in the crash report, I am on Forge 1614

**Comment by ReikaKalseki** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAGH

Just to prove it works for us:
![](http://i.imgur.com/v8JFOcM.jpg)

**Comment by Haggle1996** [comment]
Well, you are running Windows 7 -- everything works better in Windows 7. :P

**Comment by TomeWyrm** [comment]
What OS are you running? ... why am I asking, it should be in the report!

Well at least you're running latest J8. WindeX though, Ugh. I can't stand Win10.

Can we get OS reports for the other people reporting this error?

**Comment by 1Matthias** [comment]
Ubuntu 14.04, 16GB RAM, AMD FX 8350, GT 640, Java 1.8.0 91, place 2 world
rifts, instant crash.

http://pastebin.com/AcgJTExN

**Comment by 1Matthias** [comment]
Repost because I am a derp: Ubuntu 14.04, 16GB RAM, AMD FX 8350, GT 640, Java 1.8.0 91, place 2 world rifts, instant crash.

http://pastebin.com/AcgJTExN

**Comment by 1Matthias** [comment]
Odd side note: After this crash, the world rifts work perfectly and will actually transmit OC power/data just fine.

**Comment by Ryius** [comment]
I know

**Comment by Ryius** [comment]
it's not fixed now but when you play on windows seven it will work for you :p
